USE AB_DDA
GO
---------------------------------------------------
--ÍNDICES BAIXAS_OPERACIONAIS
DROP INDEX IDX_BAIXAS_OPERACIONAIS_CANALPAGTO ON [DBO].[BAIXAS_OPERACIONAIS]
GO
----
DROP INDEX IDX_BAIXAS_OPERACOES_NUMIDENTCDDA ON [DBO].[BAIXAS_OPERACIONAIS]
GO
----
DROP INDEX IDX_BAIXAS_OPERACIONAIS_NUMIDENTCBAIXAOPERAC ON [DBO].[BAIXAS_OPERACIONAIS]
GO
---------------------------------------------------
--ÍNDICES TITULOS
DROP INDEX IDX_TITULOS_DATAPAGTOBAIXA ON [DBO].[TITULOS]
GO
----
DROP INDEX IDX_TITULOS_TIPOBAIXA ON [DBO].[TITULOS]
GO
---------------------------------------------------
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'APOIO_WS_BAIXAOPERACIONAL') BEGIN ALTER TABLE APOIO_WS_BAIXAOPERACIONAL ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'BAIXAS_EFETIVAS') BEGIN ALTER TABLE BAIXAS_EFETIVAS ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'BAIXAS_EFETIVAS_PASS_OLD') BEGIN ALTER TABLE BAIXAS_EFETIVAS_PASS_OLD ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'BAIXAS_OPERACIONAIS') BEGIN ALTER TABLE BAIXAS_OPERACIONAIS ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'BAIXAS_OPERACIONAIS_PASS_OLD') BEGIN ALTER TABLE BAIXAS_OPERACIONAIS_PASS_OLD ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'CUSTOMERSBACKUP2017') BEGIN ALTER TABLE CUSTOMERSBACKUP2017 ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXAEFETIVA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'CUSTOMERSBACKUP2017') BEGIN ALTER TABLE CUSTOMERSBACKUP2017 ALTER COLUMN TIPOBAIXAEFETIVA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXAOPERACIONAL%' AND C.MAX_LENGTH = 1 AND T.NAME = 'CUSTOMERSBACKUP2017') BEGIN ALTER TABLE CUSTOMERSBACKUP2017 ALTER COLUMN TIPOBAIXAOPERACIONAL VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'MANUT_TITULOS') BEGIN ALTER TABLE MANUT_TITULOS ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'MANUT_TITULOS_PASS_OLD') BEGIN ALTER TABLE MANUT_TITULOS_PASS_OLD ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_ADDA101_RET_RECUSADOS') BEGIN ALTER TABLE RECEBE_ADDA101_RET_RECUSADOS ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_ADDA101_RET_RECUSADOS_PASS_OLD') BEGIN ALTER TABLE RECEBE_ADDA101_RET_RECUSADOS_PASS_OLD ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXATIT%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_ADDA108_RET_RECUSADOS') BEGIN ALTER TABLE RECEBE_ADDA108_RET_RECUSADOS ALTER COLUMN TIPOBAIXATIT VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXATIT%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_ADDA108_RR2') BEGIN ALTER TABLE RECEBE_ADDA108_RR2 ALTER COLUMN TIPOBAIXATIT VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXATIT%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_ADDA108_RR2_PASS_OLD') BEGIN ALTER TABLE RECEBE_ADDA108_RR2_PASS_OLD ALTER COLUMN TIPOBAIXATIT VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXATIT%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_ADDA114_RET_RECUSADOS') BEGIN ALTER TABLE RECEBE_ADDA114_RET_RECUSADOS ALTER COLUMN TIPOBAIXATIT VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXATIT%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_ADDA114_RR2') BEGIN ALTER TABLE RECEBE_ADDA114_RR2 ALTER COLUMN TIPOBAIXATIT VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_AVISOTIT') BEGIN ALTER TABLE RECEBE_AVISOTIT ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_BAIXAS_EFETIVAS_ADDA121_RR3') BEGIN ALTER TABLE RECEBE_BAIXAS_EFETIVAS_ADDA121_RR3 ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_BAIXAS_EFETIVAS_ADDA127') BEGIN ALTER TABLE RECEBE_BAIXAS_EFETIVAS_ADDA127 ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_BAIXAS_EFETIVAS_DDA0106R1_ADDA106') BEGIN ALTER TABLE RECEBE_BAIXAS_EFETIVAS_DDA0106R1_ADDA106 ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_BAIXAS_OPERACIONAIS_ADDA121_RR3') BEGIN ALTER TABLE RECEBE_BAIXAS_OPERACIONAIS_ADDA121_RR3 ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_BAIXAS_OPERACIONAIS_ADDA127') BEGIN ALTER TABLE RECEBE_BAIXAS_OPERACIONAIS_ADDA127 ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_BAIXAS_OPERACIONAIS_DDA0106R1_ADDA106') BEGIN ALTER TABLE RECEBE_BAIXAS_OPERACIONAIS_DDA0106R1_ADDA106 ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_DDA0103_ADDA103') BEGIN ALTER TABLE RECEBE_DDA0103_ADDA103 ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_DDA0118_ADDA118_RECUSADOS') BEGIN ALTER TABLE RECEBE_DDA0118_ADDA118_RECUSADOS ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_DDA0118_ADDA118_RECUSADOS_BKP') BEGIN ALTER TABLE RECEBE_DDA0118_ADDA118_RECUSADOS_BKP ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_DDA0118_ADDA118_RECUSADOS_PASS_OLD') BEGIN ALTER TABLE RECEBE_DDA0118_ADDA118_RECUSADOS_PASS_OLD ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'RECEBE_DDA0118R2_ADDA118RR2') BEGIN ALTER TABLE RECEBE_DDA0118R2_ADDA118RR2 ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'TEMP_TITULOS_FILTRO_AUX') BEGIN ALTER TABLE TEMP_TITULOS_FILTRO_AUX ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXAEFETIVA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'TEMP_TITULOS_FILTRO_AUX') BEGIN ALTER TABLE TEMP_TITULOS_FILTRO_AUX ALTER COLUMN TIPOBAIXAEFETIVA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXAOPERACIONAL%' AND C.MAX_LENGTH = 1 AND T.NAME = 'TEMP_TITULOS_FILTRO_AUX') BEGIN ALTER TABLE TEMP_TITULOS_FILTRO_AUX ALTER COLUMN TIPOBAIXAOPERACIONAL VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'TITULOS') BEGIN ALTER TABLE TITULOS ALTER COLUMN TIPOBAIXA VARCHAR(2) END
IF EXISTS (SELECT 1 FROM SYS.COLUMNS C JOIN SYS.TABLES T ON (C.OBJECT_ID = T.OBJECT_ID) WHERE C.NAME LIKE '%TIPOBAIXA%' AND C.MAX_LENGTH = 1 AND T.NAME = 'TITULOS_PASS_OLD') BEGIN ALTER TABLE TITULOS_PASS_OLD ALTER COLUMN TIPOBAIXA VARCHAR(2) END
GO
---------------------------------------------------
--ÍNDICES BAIXAS_OPERACIONAIS
CREATE NONCLUSTERED INDEX [IDX_BAIXAS_OPERACIONAIS_CANALPAGTO] ON [DBO].[BAIXAS_OPERACIONAIS]
(
	[CANALPAGTO] ASC
)
INCLUDE ( 	[NUMIDENTCDDA],
	[MEIOPAGTO]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
----
CREATE NONCLUSTERED INDEX [IDX_BAIXAS_OPERACOES_NUMIDENTCDDA] ON [DBO].[BAIXAS_OPERACIONAIS]
(
	[NUMIDENTCDDA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
----
CREATE NONCLUSTERED INDEX [IDX_BAIXAS_OPERACIONAIS_NUMIDENTCBAIXAOPERAC] ON [DBO].[BAIXAS_OPERACIONAIS]
(
	[NUMIDENTCBAIXAOPERAC] ASC
)
INCLUDE ( 	[NUMIDENTCDDA]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
---------------------------------------------------
--ÍNDICES TITULOS
CREATE NONCLUSTERED INDEX [IDX_TITULOS_DATAPAGTOBAIXA] ON [dbo].[TITULOS]
(
	[NUMIDENTCDDA] ASC
)
INCLUDE ( 	[SITPAGAMENTO],
	[DATAPAGTOBAIXA],
	[TIPOBAIXA],
	[CODSITUACAO]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
----
CREATE NONCLUSTERED INDEX [IDX_TITULOS_TIPOBAIXA] ON [dbo].[TITULOS]
(
	[TIPOBAIXA] ASC,
	[SITPAGAMENTO] ASC
)
INCLUDE ( 	[NUMIDENTCDDA],
	[CODIFSACADA],
	[CODIFCEDENTE],
	[TIPOPESCEDENTE],
	[CNPJ_CPF_CEDENTE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
---------------------------------------------------
INSERT INTO VERSAO_SISTEMA (
	[VERSAO],
	[NOMESCRIPT],
	[CODUSUARIO],
	[DATAATU])
SELECT 
	'V15_01_1_01Bz', 
	'da_atu_V15_01_1_01Bzb_tables', 
	SYSTEM_USER, 
	GETDATE() 
GO