USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'P_PESQUISA_TITULO_POR_SACADO')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.P_PESQUISA_TITULO_POR_SACADO AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE dbo.P_PESQUISA_TITULO_POR_SACADO (
			@P_CNPJ_CPF_SACADO VARCHAR(15) = NULL, 
			@P_NUMIDENTCDDA NUMERIC(19,0) = NULL,
			@P_TIPOPESQUISA VARCHAR(10) = 'SACADO', 
			@P_ORDEM VARCHAR(3) = 'D',
			@P_CODCONDICAO VARCHAR(30) = NULL, 
			@P_TIPOPESCEDENTE VARCHAR(3) = NULL, 
			@P_CNPJ_CPF_CEDENTE VARCHAR(15) = NULL, 
			@P_DATAVENCIMENTOINI DATETIME = NULL, 
			@P_DATAVENCIMENTOFIM DATETIME = NULL,  
			@P_CODSISLEGADO VARCHAR(15) = NULL,
			@P_TIPOPESQUISAACEITE VARCHAR(2) = NULL
)
AS
	/*
		29/04/2019 - eliane   - Mudando as regras de seleção de títulos que não são cartão e para títulos de cartão
		
		19/06/2019 - eduardok - (PERFORMANCE) remover OR do select - alterado para UNION ALL / alterar para padrão ANSI(INNER JOIN) / alterar os comandos com SELECT *
		
		10/10/2019 - eduardok/banco inter - alteração/criação #titulos, ajuste para o filtro de agregados
		
		22/01/2020 - rfaquini - Alteração para que o serviço possa retornar listagem de acordo com filto de ACEITE.
								Sol 65574 BRP - Disponibilização de WebServices Aceite.
		
		31/01/2020 - rfaquini - Alteração para que o serviço possa retornar título e seu status.
								Sol 65574 BRP - Disponibilização de WebServices Aceite.  
		
		14/02/2020 - rfaquini - Alteração para que o serviço possa retornar títulos e seus status.
								Sol 65574 BRP - Disponibilização de WebServices Aceite.			
		
		12/03/2020 - rfaquini - Alteração para que o serviço possa retornar título e seu status.
								Sol 65574 BRP - Disponibilização de WebServices Aceite.									
		
		13/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOMEPORTADOR E DATAHORARECBTTITULO (CATÁLOGO 5.03 E 5.04)
		
		28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)	
		
		29/03/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
								
		Domínios 
			@P_TIPOPESQUISAACEITE
				'' ou NULL	- Todos
				'B'	- Aceite = '' ou NULL
				'S'	- Aceite = 'S'
				'N' - Aceite = 'N'
				'NN'- Aceite = '' ou NULL ou 'S'
				'X'	- Aceite = 'X' - valor fora do domínio
	*/

BEGIN

	set nocount on

	IF (SELECT OBJECT_ID('TEMPDB..#TEMP_TITULOS_FILTRO')) IS NOT NULL 
		DROP TABLE #TEMP_TITULOS_FILTRO
	IF (SELECT OBJECT_ID('TEMPDB..#TITULOS')) IS NOT NULL 
		DROP TABLE #TITULOS
	IF (SELECT OBJECT_ID('TEMPDB..#TEMP_TITULOS_FILTRO_AUX')) IS NOT NULL 
		DROP TABLE #TEMP_TITULOS_FILTRO_AUX

	DECLARE	@CNPJ_CPF_SACADO VARCHAR(15), 
			@NUMIDENTCDDA NUMERIC(19,0),
			@TIPOPESQUISA VARCHAR(10),
			@CODCONDICAO VARCHAR(30), 
			@TIPOPESCEDENTE VARCHAR(3), 
			@CNPJ_CPF_CEDENTE VARCHAR(15),
			@DATAVENCIMENTOINI DATETIME,
			@DATAVENCIMENTOFIM DATETIME,
			@CODSISLEGADO VARCHAR(15)

	SELECT  @P_CNPJ_CPF_SACADO = CASE WHEN @P_CNPJ_CPF_SACADO = '' THEN NULL ELSE @P_CNPJ_CPF_SACADO END,
			@P_TIPOPESQUISA = CASE WHEN @P_TIPOPESQUISA = '' THEN NULL ELSE @P_TIPOPESQUISA END,
			@P_CODCONDICAO = CASE WHEN @P_CODCONDICAO = '' THEN NULL ELSE @P_CODCONDICAO END,
			@P_TIPOPESCEDENTE = CASE WHEN @P_TIPOPESCEDENTE = '' THEN NULL ELSE @P_TIPOPESCEDENTE END,
			@P_CNPJ_CPF_CEDENTE = CASE WHEN @P_CNPJ_CPF_CEDENTE = '' THEN NULL ELSE @P_CNPJ_CPF_CEDENTE END,
			@P_CODSISLEGADO = CASE WHEN @P_CODSISLEGADO = '' THEN NULL ELSE @P_CODSISLEGADO END

	SELECT  @CNPJ_CPF_SACADO = RTRIM (@P_CNPJ_CPF_SACADO),
			@NUMIDENTCDDA = @P_NUMIDENTCDDA,
			@TIPOPESQUISA = @P_TIPOPESQUISA,
			@CODCONDICAO = RTRIM (@P_CODCONDICAO), 
			@TIPOPESCEDENTE = RTRIM (@P_TIPOPESCEDENTE), 
			@CNPJ_CPF_CEDENTE = RTRIM (@P_CNPJ_CPF_CEDENTE),
			@DATAVENCIMENTOINI = @P_DATAVENCIMENTOINI,
			@DATAVENCIMENTOFIM = @P_DATAVENCIMENTOFIM,
			@CODSISLEGADO = RTRIM (@P_CODSISLEGADO)
--------------------------------------------------------------------------------------------------------
	SELECT 99 	TIPOREGISTRO,
	CONVERT(numeric(19,0), NULL) NUMIDENTCDDA, 
	CONVERT (char(3), NULL) CODIFSACADA, 
	CONVERT (char(3), NULL) CODIFCEDENTE, 
	CONVERT (char(1), NULL) TIPOPESCEDENTE, 
	CONVERT (varchar(14), NULL) CNPJ_CPF_CEDENTE, 
	CONVERT (varchar(50), NULL) NOMECEDENTE, 
	CONVERT (char(1), NULL) TIPOPESCEDENTEORI, 
	CONVERT (varchar(14), NULL) CNPJ_CPF_CEDENTEORI, 
	CONVERT (varchar(50), NULL) NOMECEDENTEORI, 
	CONVERT (varchar(50), NULL) ENDCEDENTEORI, 
	CONVERT (varchar(50), NULL) CIDCEDENTEORI, 
	CONVERT (char(2), NULL) UFCEDENTEORI, 
	CONVERT (char(8), NULL) CEPCEDENTEORI, 
	CONVERT (char(1), NULL) TIPOPESSACADO, 
	CONVERT (varchar(14), NULL) CNPJ_CPF_SACADO, 
	CONVERT (varchar(50), NULL) NOMESACADO, 
	CONVERT (varchar(50), NULL) ENDSACADO, 
	CONVERT (varchar(50), NULL) CIDSACADO,
	CONVERT (char(2), NULL) UFSACADO, 
	CONVERT (char(8), NULL) CEPSACADO, 
	CONVERT (char(1), NULL) TIPOPESSACADOR, 
	CONVERT (varchar(14), NULL) CNPJ_CPF_SACADOR, 
	CONVERT (varchar(50), NULL) NOMESACADOR,
	CONVERT (char(1), NULL) CODCARTEIRA, 
	CONVERT (char(2), NULL) CODMOEDACNAB, 
	CONVERT (varchar(20), NULL) IDENTNOSSONUMERO, 
	CONVERT (varchar(47), NULL) LINHADIGITAVEL, 
	CONVERT (datetime, NULL) DATAVENCIMENTO, 
	CONVERT (numeric(19, 5), NULL) VLRTITULO,
	CONVERT (varchar(15), NULL) SEUNUMERO,
	CONVERT (char(2), NULL) CODESPECIEDOC,
	CONVERT (datetime, NULL) DATAEMISSAO,
	CONVERT (int, NULL) QTDEDIASPROTESTO, 
	CONVERT (datetime, NULL) DATALIMPAGTO,
	CONVERT (int, NULL) TIPOPAGTO,
	CONVERT (char(1), NULL) INDTITULONEGOCIADO,
	CONVERT (numeric(19, 5), NULL) VLRABATIMENTO,
	CONVERT (char(1), NULL) CODMORA,
	CONVERT (datetime, NULL) DATAMORA,
	CONVERT (numeric(19, 5), NULL) VLRPERCMORA, 
	CONVERT (char(1), NULL) CODMULTA,
	CONVERT (datetime, NULL) DATAMULTA,
	CONVERT (numeric(19, 5), NULL) VLRPERCMULTA,
	CONVERT (char(1), NULL) CODDESCONTO01,
	CONVERT (datetime, NULL) DATADESCONTO01,
	CONVERT (numeric(19, 5), NULL) VLRPERCDESCONTO01, 
	CONVERT (char(1), NULL) CODDESCONTO02,
	CONVERT (datetime, NULL) DATADESCONTO02,
	CONVERT (numeric(19, 5), NULL) VLRPERCDESCONTO02,
	CONVERT (char(1), NULL) CODDESCONTO03,
	CONVERT (datetime, NULL) DATADESCONTO03, 
	CONVERT (numeric(19, 5), NULL) VLRPERCDESCONTO03,
	CONVERT (char(1), NULL) ACEITE,
	CONVERT (datetime, NULL) DATAACEITE,
	CONVERT (char(2), NULL) CODSITUACAO,
	--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)	
	CONVERT (varchar(2), NULL) TIPOBAIXA,
	CONVERT (char(1), NULL) SITPAGAMENTO,
	CONVERT (numeric(19, 5), NULL) VLRMINTITULO, 
	CONVERT (numeric(19, 5), NULL) VLRMAXTITULO, 
	CONVERT (char(1), NULL) TIPOPESTERCEIRO,
	CONVERT (varchar(14), NULL) CNPJ_CPF_TERCEIRO,
	CONVERT (varchar(10), NULL) CODSISLEGADO,
	CONVERT (datetime, NULL) DTHRSITTITULO,
	CONVERT (char(1), NULL) INDALTERAVALOR,
	CONVERT (char(2), NULL) TIPOCALCULO,
	CONVERT (varchar(80), NULL) NOMEFANTASIACEDENTE,
	CONVERT (varchar(80), NULL) NOMEFANTASIACEDENTEORI,
	CONVERT (varchar(80), NULL) NOMEFANTASIASACADO,
	CONVERT (varchar(44), NULL) NUMCODBARRAS,
	CONVERT (int, NULL) NUMPARCELA,
	CONVERT (int, NULL) QTDPARCELA,
	CONVERT (char(1), NULL) INDBLOQUEIO,
	CONVERT (char(1), NULL) INDPARCIAL,
	CONVERT (int, NULL)  QTDPAGTO,
	CONVERT (char(1), NULL) INDVALORPERC_MIN,
	CONVERT (char(1), NULL) INDVALORPERC_MAX,
	CONVERT (varchar(8), NULL) ISPBCEDENTE,
	CONVERT (char(1), NULL) TIPOAUTRECDIVERGENTE,
	CONVERT (varchar(8), NULL) ISPBSACADA,
	CONVERT (char(1), NULL) CANALPAGTO,
	CONVERT (char(1), NULL) MEIOPAGTO,
	CONVERT (char(2), NULL) SITPAGAMENTOCIP,
	CONVERT (numeric(19, 0), NULL) ULTNUMREFCADTIT,
	CONVERT (numeric(19, 0), NULL) ULTNUMSEQCADTIT,
	CONVERT (numeric(19, 0), NULL) ULTNUMREFBAIXAOPERAC,
	CONVERT (numeric(19, 0), NULL) ULTNUMSEQBAIXAOPERAC,
	CONVERT (numeric(19, 0), NULL) ULTNUMREFBAIXAEFET,
	CONVERT (numeric(19, 0), NULL) ULTNUMSEQBAIXAEFET,
	CONVERT (numeric(19, 0), NULL) ULTNUMREFACEITE,
	CONVERT (numeric(19, 0), NULL) ULTNUMSEQACEITE,
	CONVERT (numeric(19, 0), NULL) ULTNUMREFTERC,
	CONVERT (numeric(19, 0), NULL) ULTNUMSEQTERC,
	-- MENSAGENS
	CONVERT (integer, NULL) SEQMENSAGEM,
	CONVERT (varchar(100), NULL) TEXTO,
	-- ANEXO FATURA
	CONVERT (numeric(17, 0), NULL) SEQFATURA,
	CONVERT (integer, NULL) CODMODELO,
	CONVERT (numeric(17, 0), NULL) SEQDETANTES,
	CONVERT (numeric(17, 0), NULL) SEQDETDEPOIS,
	CONVERT (varchar(255), NULL) CABECALHO,
	CONVERT (varchar(2), NULL) TPDADOS,
	CONVERT (numeric(17, 0), NULL) SEQMODELO,
	-- NOTAS FISCAIS
	CONVERT (varchar(15), NULL) NUMNOTAFISCAL,
	CONVERT (numeric(19, 5), NULL) VLRNOTAFISCAL,
	CONVERT (datetime, NULL) DATAEMISSAONOTA,
	-- BAIXAS OPERACIONAIS
	CONVERT(numeric(19,0), NULL) NUMIDENTCBAIXAOPERAC,
	CONVERT(numeric(19,0), NULL) NUMREFBAIXAOPERAC,
	--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)	
	CONVERT(varchar(2), NULL) TIPOBAIXAOPERACIONAL, 
	CONVERT(datetime, NULL) DATABAIXAOPERACIONAL,
	CONVERT(numeric(19,5), NULL) VLRBAIXAOPERACIONAL,
	CONVERT(char(1), NULL) TIPOPESPORTADOR,
	CONVERT(varchar(14), NULL) CNPJ_CPF_PORTADOR,
	--13/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOMEPORTADOR E DATAHORARECBTTITULO (CATÁLOGO 5.03 E 5.04)
	CONVERT(VARCHAR(80), NULL) NOME_PORTADOR, 
	--29/03/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
	CONVERT(CHAR(1), NULL) TIPOPESAGREGADOR,
	CONVERT(VARCHAR(14), NULL) CNPJ_CPF_AGREGADOR,
	CONVERT(VARCHAR(50), NULL) NOMEAGREGADOR,
	CONVERT(VARCHAR(8), NULL) ISPBINICIADORPAGTO,
	CONVERT(VARCHAR(4), NULL) AGENCIARECEBEDORA,
	CONVERT(VARCHAR(3), NULL) CODMOTIVO,
	CONVERT(DATETIME, NULL) DATAHORARECBTTITULO, 
	CONVERT(datetime, NULL) DATAHORACANCEL,
	CONVERT(char(1), NULL) INDCONTINGENCIA,
	CONVERT(char(1), NULL) ORIGEMCANCELAMENTO,
	-- BAIXAS EFETIVAS
	CONVERT(numeric(19,0), NULL) NUMIDENTCBAIXAEFET,
	CONVERT(numeric(19,0), NULL) NUMREFBAIXAEFET,
	CONVERT(datetime, NULL) DATABAIXAEFETIVA,
	CONVERT(numeric(19,5), NULL) VLRBAIXAEFETIVA,
	--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)	
	CONVERT(varchar(2), NULL) TIPOBAIXAEFETIVA,
	-- CALCULOS
	CONVERT(datetime, NULL) DATACALCULO,
	CONVERT(numeric(19,5), NULL) VLRMORA,
	CONVERT(numeric(19,5), NULL) VLRMULTA,
	CONVERT(numeric(19,5), NULL) VLRDESCONTO,
	CONVERT(numeric(19,5), NULL) VLRCOBRAR,
	-- TERCEIROS
	CONVERT(char(1), NULL) TIPOPESTERC,
	CONVERT(varchar(14), NULL) CNPJ_CPF_TERC,
	CONVERT(numeric(19,0), NULL) NUMIDENTCTERC,
	CONVERT(numeric(19,0), NULL) NUMREFTERC,
	CONVERT(char(1), NULL) TIPOPESAUTORIZADOR,
	CONVERT(varchar(14), NULL) CNPJ_CPF_AUTORIZADOR,		
	--ACEITE-SITUACAOPEDIDO E CODRETORNO
	CONVERT(char(1), NULL) situacaopedido,
	CONVERT(char(1), NULL) codretorno,
	CONVERT(numeric(17,0), NULL) SEQINCLUSAO
		INTO #TEMP_TITULOS_FILTRO FROM TITULOS WHERE 1=2
--------------------------------------------------------------------------------------------------------	
	--14/02/2020 - rfaquini - Alteração para que o serviço possa retornar título e seu status.
	SELECT 99 	TIPOREGISTRO,
	CONVERT(numeric(19,0), NULL) NUMIDENTCDDA, 
	CONVERT (char(3), NULL) CODIFSACADA, 
	CONVERT (char(3), NULL) CODIFCEDENTE, 
	CONVERT (char(1), NULL) TIPOPESCEDENTE, 
	CONVERT (varchar(14), NULL) CNPJ_CPF_CEDENTE, 
	CONVERT (varchar(50), NULL) NOMECEDENTE, 
	CONVERT (char(1), NULL) TIPOPESCEDENTEORI, 
	CONVERT (varchar(14), NULL) CNPJ_CPF_CEDENTEORI, 
	CONVERT (varchar(50), NULL) NOMECEDENTEORI, 
	CONVERT (varchar(50), NULL) ENDCEDENTEORI, 
	CONVERT (varchar(50), NULL) CIDCEDENTEORI, 
	CONVERT (char(2), NULL) UFCEDENTEORI, 
	CONVERT (char(8), NULL) CEPCEDENTEORI, 
	CONVERT (char(1), NULL) TIPOPESSACADO, 
	CONVERT (varchar(14), NULL) CNPJ_CPF_SACADO, 
	CONVERT (varchar(50), NULL) NOMESACADO, 
	CONVERT (varchar(50), NULL) ENDSACADO, 
	CONVERT (varchar(50), NULL) CIDSACADO,
	CONVERT (char(2), NULL) UFSACADO, 
	CONVERT (char(8), NULL) CEPSACADO, 
	CONVERT (char(1), NULL) TIPOPESSACADOR, 
	CONVERT (varchar(14), NULL) CNPJ_CPF_SACADOR, 
	CONVERT (varchar(50), NULL) NOMESACADOR,
	CONVERT (char(1), NULL) CODCARTEIRA, 
	CONVERT (char(2), NULL) CODMOEDACNAB, 
	CONVERT (varchar(20), NULL) IDENTNOSSONUMERO, 
	CONVERT (varchar(47), NULL) LINHADIGITAVEL, 
	CONVERT (datetime, NULL) DATAVENCIMENTO, 
	CONVERT (numeric(19, 5), NULL) VLRTITULO,
	CONVERT (varchar(15), NULL) SEUNUMERO,
	CONVERT (char(2), NULL) CODESPECIEDOC,
	CONVERT (datetime, NULL) DATAEMISSAO,
	CONVERT (int, NULL) QTDEDIASPROTESTO, 
	CONVERT (datetime, NULL) DATALIMPAGTO,
	CONVERT (int, NULL) TIPOPAGTO,
	CONVERT (char(1), NULL) INDTITULONEGOCIADO,
	CONVERT (numeric(19, 5), NULL) VLRABATIMENTO,
	CONVERT (char(1), NULL) CODMORA,
	CONVERT (datetime, NULL) DATAMORA,
	CONVERT (numeric(19, 5), NULL) VLRPERCMORA, 
	CONVERT (char(1), NULL) CODMULTA,
	CONVERT (datetime, NULL) DATAMULTA,
	CONVERT (numeric(19, 5), NULL) VLRPERCMULTA,
	CONVERT (char(1), NULL) CODDESCONTO01,
	CONVERT (datetime, NULL) DATADESCONTO01,
	CONVERT (numeric(19, 5), NULL) VLRPERCDESCONTO01, 
	CONVERT (char(1), NULL) CODDESCONTO02,
	CONVERT (datetime, NULL) DATADESCONTO02,
	CONVERT (numeric(19, 5), NULL) VLRPERCDESCONTO02,
	CONVERT (char(1), NULL) CODDESCONTO03,
	CONVERT (datetime, NULL) DATADESCONTO03, 
	CONVERT (numeric(19, 5), NULL) VLRPERCDESCONTO03,
	CONVERT (char(1), NULL) ACEITE,
	CONVERT (datetime, NULL) DATAACEITE,
	CONVERT (char(2), NULL) CODSITUACAO,
	--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)	
	CONVERT (varchar(2), NULL) TIPOBAIXA,
	CONVERT (char(1), NULL) SITPAGAMENTO,
	CONVERT (numeric(19, 5), NULL) VLRMINTITULO, 
	CONVERT (numeric(19, 5), NULL) VLRMAXTITULO, 
	CONVERT (char(1), NULL) TIPOPESTERCEIRO,
	CONVERT (varchar(14), NULL) CNPJ_CPF_TERCEIRO,
	CONVERT (varchar(10), NULL) CODSISLEGADO,
	CONVERT (datetime, NULL) DTHRSITTITULO,
	CONVERT (char(1), NULL) INDALTERAVALOR,
	CONVERT (char(2), NULL) TIPOCALCULO,
	CONVERT (varchar(80), NULL) NOMEFANTASIACEDENTE,
	CONVERT (varchar(80), NULL) NOMEFANTASIACEDENTEORI,
	CONVERT (varchar(80), NULL) NOMEFANTASIASACADO,
	CONVERT (varchar(44), NULL) NUMCODBARRAS,
	CONVERT (int, NULL) NUMPARCELA,
	CONVERT (int, NULL) QTDPARCELA,
	CONVERT (char(1), NULL) INDBLOQUEIO,
	CONVERT (char(1), NULL) INDPARCIAL,
	CONVERT (int, NULL)  QTDPAGTO,
	CONVERT (char(1), NULL) INDVALORPERC_MIN,
	CONVERT (char(1), NULL) INDVALORPERC_MAX,
	CONVERT (varchar(8), NULL) ISPBCEDENTE,
	CONVERT (char(1), NULL) TIPOAUTRECDIVERGENTE,
	CONVERT (varchar(8), NULL) ISPBSACADA,
	CONVERT (char(1), NULL) CANALPAGTO,
	CONVERT (char(1), NULL) MEIOPAGTO,
	CONVERT (char(2), NULL) SITPAGAMENTOCIP,
	CONVERT (numeric(19, 0), NULL) ULTNUMREFCADTIT,
	CONVERT (numeric(19, 0), NULL) ULTNUMSEQCADTIT,
	CONVERT (numeric(19, 0), NULL) ULTNUMREFBAIXAOPERAC,
	CONVERT (numeric(19, 0), NULL) ULTNUMSEQBAIXAOPERAC,
	CONVERT (numeric(19, 0), NULL) ULTNUMREFBAIXAEFET,
	CONVERT (numeric(19, 0), NULL) ULTNUMSEQBAIXAEFET,
	CONVERT (numeric(19, 0), NULL) ULTNUMREFACEITE,
	CONVERT (numeric(19, 0), NULL) ULTNUMSEQACEITE,
	CONVERT (numeric(19, 0), NULL) ULTNUMREFTERC,
	CONVERT (numeric(19, 0), NULL) ULTNUMSEQTERC,
	-- MENSAGENS
	CONVERT (integer, NULL) SEQMENSAGEM,
	CONVERT (varchar(100), NULL) TEXTO,
	-- ANEXO FATURA
	CONVERT (numeric(17, 0), NULL) SEQFATURA,
	CONVERT (integer, NULL) CODMODELO,
	CONVERT (numeric(17, 0), NULL) SEQDETANTES,
	CONVERT (numeric(17, 0), NULL) SEQDETDEPOIS,
	CONVERT (varchar(255), NULL) CABECALHO,
	CONVERT (varchar(2), NULL) TPDADOS,
	CONVERT (numeric(17, 0), NULL) SEQMODELO,
	-- NOTAS FISCAIS
	CONVERT (varchar(15), NULL) NUMNOTAFISCAL,
	CONVERT (numeric(19, 5), NULL) VLRNOTAFISCAL,
	CONVERT (datetime, NULL) DATAEMISSAONOTA,
	-- BAIXAS OPERACIONAIS
	CONVERT(numeric(19,0), NULL) NUMIDENTCBAIXAOPERAC,
	CONVERT(numeric(19,0), NULL) NUMREFBAIXAOPERAC,
	--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)	
	CONVERT(varchar(2), NULL) TIPOBAIXAOPERACIONAL, 
	CONVERT(datetime, NULL) DATABAIXAOPERACIONAL,
	CONVERT(numeric(19,5), NULL) VLRBAIXAOPERACIONAL,
	CONVERT(char(1), NULL) TIPOPESPORTADOR,
	--13/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOMEPORTADOR E DATAHORARECBTTITULO (CATÁLOGO 5.03 E 5.04)
	CONVERT(VARCHAR(80), NULL) NOME_PORTADOR, 
	--29/03/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
	CONVERT(CHAR(1), NULL) TIPOPESAGREGADOR,
	CONVERT(VARCHAR(14), NULL) CNPJ_CPF_AGREGADOR,
	CONVERT(VARCHAR(50), NULL) NOMEAGREGADOR,
	CONVERT(VARCHAR(8), NULL) ISPBINICIADORPAGTO,
	CONVERT(VARCHAR(4), NULL) AGENCIARECEBEDORA,
	CONVERT(VARCHAR(3), NULL) CODMOTIVO,
	CONVERT(DATETIME, NULL) DATAHORARECBTTITULO,
	CONVERT(datetime, NULL) DATAHORACANCEL,
	CONVERT(char(1), NULL) INDCONTINGENCIA,
	CONVERT(char(1), NULL) ORIGEMCANCELAMENTO,
	-- BAIXAS EFETIVAS
	CONVERT(numeric(19,0), NULL) NUMIDENTCBAIXAEFET,
	CONVERT(numeric(19,0), NULL) NUMREFBAIXAEFET,
	CONVERT(datetime, NULL) DATABAIXAEFETIVA,
	CONVERT(numeric(19,5), NULL) VLRBAIXAEFETIVA,
	--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)	
	CONVERT(varchar(1), NULL) TIPOBAIXAEFETIVA,
	-- CALCULOS
	CONVERT(datetime, NULL) DATACALCULO,
	CONVERT(numeric(19,5), NULL) VLRMORA,
	CONVERT(numeric(19,5), NULL) VLRMULTA,
	CONVERT(numeric(19,5), NULL) VLRDESCONTO,
	CONVERT(numeric(19,5), NULL) VLRCOBRAR,
	-- TERCEIROS
	CONVERT(char(1), NULL) TIPOPESTERC,
	CONVERT(varchar(14), NULL) CNPJ_CPF_TERC,
	CONVERT(numeric(19,0), NULL) NUMIDENTCTERC,
	CONVERT(numeric(19,0), NULL) NUMREFTERC,
	CONVERT(char(1), NULL) TIPOPESAUTORIZADOR,
	CONVERT(varchar(14), NULL) CNPJ_CPF_AUTORIZADOR,		
	--ACEITE-SITUACAOPEDIDO E CODRETORNO
	CONVERT(char(1), NULL) situacaopedido,
	CONVERT(char(1), NULL) codretorno,
	CONVERT(numeric(17,0), NULL) SEQINCLUSAO
		INTO #TEMP_TITULOS_FILTRO_AUX FROM TITULOS WHERE 1=2
--------------------------------------------------------------------------------------------------------	
	CREATE TABLE #TITULOS (
		NUMIDENTCDDA	NUMERIC (19,0)
	)
	CREATE NONCLUSTERED INDEX IDX_TEMP_TITULOS ON #TITULOS (NUMIDENTCDDA)

	INSERT INTO #TITULOS (NUMIDENTCDDA)
	SELECT NUMIDENTCDDA
	  FROM TITULOS WITH(NOLOCK)
	 WHERE CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO
	 UNION 
	SELECT NUMIDENTCDDA
	  FROM TITULOS WITH(NOLOCK)
	 WHERE CNPJ_CPF_TERCEIRO = @CNPJ_CPF_SACADO
	 UNION 
	SELECT NUMIDENTCDDA
	  FROM TITULOS WITH(NOLOCK)
	 WHERE CNPJ_CPF_SACADO IN (SELECT S.CNPJ_CPF_SACADO 
								FROM SACELETRONICO S 
								WHERE S.CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO 
								AND S.SITUACAOSACADO = 1)
	 UNION 
	SELECT NUMIDENTCDDA
	  FROM TITULOS WITH(NOLOCK)
	 WHERE CNPJ_CPF_SACADO IN (SELECT A.CNPJ_CPF_AGREGADO 
								FROM AGREGADOS A 
								WHERE A.CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO 
								AND A.SITUACAOAGREGADO = 1)  
--------------------------------------------------------------------------------------------------------
	--14/02/2020 - rfaquini - Alteração para que o serviço possa retornar título e seu status.
	--CUIDADO AO MODIFICAR A FORMATAÇÃO!!!
	--ATENTAR-SE A QUANTIDADE MÁXIMA DE 4000 CARACTERES
	
	declare @insert nvarchar(4000),
			--QUERY ORIGINAL
			@campos_insert nvarchar(4000),
			@select_insert nvarchar(4000),
			@select_insert_max nvarchar(4000),
			@from_insert nvarchar(4000),
			@where_insert nvarchar(4000),
			@groupby_insert nvarchar(4000),
			--ACEITE
			@flag_aceite int,
			@campos_insert_aceite nvarchar(4000),
			@select_insert_aceite nvarchar(4000),
			@select_insert_aceite_tipopesquisaaceite_null nvarchar(4000),
			@select_insert_max_aceite nvarchar(4000),
			@from_insert_aceite nvarchar(4000),			
			--@where_insert_aceite nvarchar(4000),
			@groupby_insert_aceite nvarchar(4000),
			
			@PARAMETROS NVARCHAR(4000),
			
			@debugging tinyint
			
	/*
	DEBUGGING
		0 - NÃO
		1 - SIM
	*/
	set @debugging = 0

	--QUERY ORIGINAL
	set @campos_insert = ' 
INSERT INTO #TEMP_TITULOS_FILTRO (TIPOREGISTRO,NUMIDENTCDDA,CODIFSACADA,CODIFCEDENTE,TIPOPESCEDENTE,CNPJ_CPF_CEDENTE,NOMECEDENTE,TIPOPESCEDENTEORI,CNPJ_CPF_CEDENTEORI,
NOMECEDENTEORI,ENDCEDENTEORI,CIDCEDENTEORI,UFCEDENTEORI,CEPCEDENTEORI,TIPOPESSACADO,CNPJ_CPF_SACADO,NOMESACADO,ENDSACADO,CIDSACADO,UFSACADO,CEPSACADO,TIPOPESSACADOR,
CNPJ_CPF_SACADOR,
NOMESACADOR,CODCARTEIRA,CODMOEDACNAB,IDENTNOSSONUMERO,LINHADIGITAVEL,DATAVENCIMENTO,VLRTITULO,SEUNUMERO,CODESPECIEDOC,DATAEMISSAO,QTDEDIASPROTESTO,
DATALIMPAGTO,TIPOPAGTO,INDTITULONEGOCIADO,VLRABATIMENTO,CODMORA,DATAMORA,VLRPERCMORA,CODMULTA,DATAMULTA,VLRPERCMULTA,CODDESCONTO01,DATADESCONTO01,VLRPERCDESCONTO01,
CODDESCONTO02,DATADESCONTO02,VLRPERCDESCONTO02,CODDESCONTO03,DATADESCONTO03,VLRPERCDESCONTO03,ACEITE,DATAACEITE,CODSITUACAO,TIPOBAIXA,SITPAGAMENTO,VLRMINTITULO,
VLRMAXTITULO,TIPOPESTERCEIRO,CNPJ_CPF_TERCEIRO,CODSISLEGADO,DTHRSITTITULO,DATACALCULO,INDALTERAVALOR,TIPOCALCULO,NOMEFANTASIACEDENTE,NOMEFANTASIACEDENTEORI,NOMEFANTASIASACADO,NUMCODBARRAS,NUMPARCELA,
QTDPARCELA,INDBLOQUEIO,INDPARCIAL,QTDPAGTO,INDVALORPERC_MIN,INDVALORPERC_MAX,ISPBCEDENTE,TIPOAUTRECDIVERGENTE,ISPBSACADA,CANALPAGTO,MEIOPAGTO,SITPAGAMENTOCIP,ULTNUMREFCADTIT,ULTNUMSEQCADTIT,ULTNUMREFBAIXAOPERAC,
ULTNUMSEQBAIXAOPERAC,ULTNUMREFBAIXAEFET,ULTNUMSEQBAIXAEFET,ULTNUMREFACEITE,ULTNUMSEQACEITE,ULTNUMREFTERC,ULTNUMSEQTERC,
situacaopedido,codretorno,SEQINCLUSAO) '
	
	set @select_insert_max = ' 
select 1,T.NUMIDENTCDDA,T.CODIFSACADA,T.CODIFCEDENTE,T.TIPOPESCEDENTE,T.CNPJ_CPF_CEDENTE,T.NOMECEDENTE,T.TIPOPESCEDENTEORI,T.CNPJ_CPF_CEDENTEORI,
T.NOMECEDENTEORI,T.ENDCEDENTEORI,T.CIDCEDENTEORI,T.UFCEDENTEORI,T.CEPCEDENTEORI,T.TIPOPESSACADO,T.CNPJ_CPF_SACADO,T.NOMESACADO,T.ENDSACADO,T.CIDSACADO,T.UFSACADO,T.CEPSACADO,T.TIPOPESSACADOR,
CASE
WHEN LEN(T.CNPJ_CPF_SACADOR)>14
	THEN SUBSTRING(T.CNPJ_CPF_SACADOR,2,14)
	ELSE T.CNPJ_CPF_SACADOR
END,
T.NOMESACADOR,T.CODCARTEIRA,T.CODMOEDACNAB,T.IDENTNOSSONUMERO,T.LINHADIGITAVEL,T.DATAVENCIMENTO,T.VLRTITULO,T.SEUNUMERO,T.CODESPECIEDOC,T.DATAEMISSAO,T.QTDEDIASPROTESTO,
T.DATALIMPAGTO,T.TIPOPAGTO,T.INDTITULONEGOCIADO,T.VLRABATIMENTO,T.CODMORA,T.DATAMORA,T.VLRPERCMORA,T.CODMULTA,T.DATAMULTA,T.VLRPERCMULTA,T.CODDESCONTO01,T.DATADESCONTO01,T.VLRPERCDESCONTO01,
T.CODDESCONTO02,T.DATADESCONTO02,T.VLRPERCDESCONTO02,T.CODDESCONTO03,T.DATADESCONTO03,T.VLRPERCDESCONTO03,T.ACEITE,T.DATAACEITE,T.CODSITUACAO,T.TIPOBAIXA,T.SITPAGAMENTO,T.VLRMINTITULO,
T.VLRMAXTITULO,T.TIPOPESTERCEIRO,T.CNPJ_CPF_TERCEIRO,T.CODSISLEGADO,T.DTHRSITTITULO,T.DATACALCULO,T.INDALTERAVALOR,T.TIPOCALCULO,T.NOMEFANTASIACEDENTE,T.NOMEFANTASIACEDENTEORI,T.NOMEFANTASIASACADO,T.NUMCODBARRAS,T.NUMPARCELA,
T.QTDPARCELA,T.INDBLOQUEIO,T.INDPARCIAL,T.QTDPAGTO,T.INDVALORPERC_MIN,T.INDVALORPERC_MAX,T.ISPBCEDENTE,T.TIPOAUTRECDIVERGENTE,T.ISPBSACADA,T.CANALPAGTO,T.MEIOPAGTO,T.SITPAGAMENTOCIP,T.ULTNUMREFCADTIT,T.ULTNUMSEQCADTIT,T.ULTNUMREFBAIXAOPERAC,
T.ULTNUMSEQBAIXAOPERAC,T.ULTNUMREFBAIXAEFET,T.ULTNUMSEQBAIXAEFET,T.ULTNUMREFACEITE,T.ULTNUMSEQACEITE,T.ULTNUMREFTERC,T.ULTNUMSEQTERC '
	
	set @select_insert = ' 
select 1,T.NUMIDENTCDDA,T.CODIFSACADA,T.CODIFCEDENTE,T.TIPOPESCEDENTE,T.CNPJ_CPF_CEDENTE,T.NOMECEDENTE,T.TIPOPESCEDENTEORI,T.CNPJ_CPF_CEDENTEORI,
T.NOMECEDENTEORI,T.ENDCEDENTEORI,T.CIDCEDENTEORI,T.UFCEDENTEORI,T.CEPCEDENTEORI,T.TIPOPESSACADO,T.CNPJ_CPF_SACADO,T.NOMESACADO,T.ENDSACADO,T.CIDSACADO,T.UFSACADO,T.CEPSACADO,T.TIPOPESSACADOR,
CASE
WHEN LEN(T.CNPJ_CPF_SACADOR)>14
	THEN SUBSTRING(T.CNPJ_CPF_SACADOR,2,14)
	ELSE T.CNPJ_CPF_SACADOR
END,
T.NOMESACADOR,T.CODCARTEIRA,T.CODMOEDACNAB,T.IDENTNOSSONUMERO,T.LINHADIGITAVEL,T.DATAVENCIMENTO,T.VLRTITULO,T.SEUNUMERO,T.CODESPECIEDOC,T.DATAEMISSAO,T.QTDEDIASPROTESTO,
T.DATALIMPAGTO,T.TIPOPAGTO,T.INDTITULONEGOCIADO,T.VLRABATIMENTO,T.CODMORA,T.DATAMORA,T.VLRPERCMORA,T.CODMULTA,T.DATAMULTA,T.VLRPERCMULTA,T.CODDESCONTO01,T.DATADESCONTO01,T.VLRPERCDESCONTO01,
T.CODDESCONTO02,T.DATADESCONTO02,T.VLRPERCDESCONTO02,T.CODDESCONTO03,T.DATADESCONTO03,T.VLRPERCDESCONTO03,T.ACEITE,T.DATAACEITE,T.CODSITUACAO,T.TIPOBAIXA,T.SITPAGAMENTO,T.VLRMINTITULO,
T.VLRMAXTITULO,T.TIPOPESTERCEIRO,T.CNPJ_CPF_TERCEIRO,T.CODSISLEGADO,T.DTHRSITTITULO,T.DATACALCULO,T.INDALTERAVALOR,T.TIPOCALCULO,T.NOMEFANTASIACEDENTE,T.NOMEFANTASIACEDENTEORI,T.NOMEFANTASIASACADO,T.NUMCODBARRAS,T.NUMPARCELA,
T.QTDPARCELA,T.INDBLOQUEIO,T.INDPARCIAL,T.QTDPAGTO,T.INDVALORPERC_MIN,T.INDVALORPERC_MAX,T.ISPBCEDENTE,T.TIPOAUTRECDIVERGENTE,T.ISPBSACADA,T.CANALPAGTO,T.MEIOPAGTO,T.SITPAGAMENTOCIP,T.ULTNUMREFCADTIT,T.ULTNUMSEQCADTIT,T.ULTNUMREFBAIXAOPERAC,
T.ULTNUMSEQBAIXAOPERAC,T.ULTNUMREFBAIXAEFET,T.ULTNUMSEQBAIXAEFET,T.ULTNUMREFACEITE,T.ULTNUMSEQACEITE,T.ULTNUMREFTERC,T.ULTNUMSEQTERC '
	
	set @from_insert = ''
	
	set @where_insert = ''
	
	set @groupby_insert = ''
	
	--ACEITE
	/*
	@FLAG_ACEITE
		0 - NÃO
		1 - SIM
	*/
	set @FLAG_ACEITE = 0
	if @P_TIPOPESQUISAACEITE <> '' and @P_TIPOPESQUISAACEITE is not null
		set @FLAG_ACEITE = 1
	
	/*set @campos_insert_aceite = ' 
INSERT INTO #TEMP_TITULOS_FILTRO (TIPOREGISTRO,NUMIDENTCDDA,CODIFSACADA,CODIFCEDENTE,TIPOPESCEDENTE,CNPJ_CPF_CEDENTE,NOMECEDENTE,TIPOPESCEDENTEORI,CNPJ_CPF_CEDENTEORI,
NOMECEDENTEORI,ENDCEDENTEORI,CIDCEDENTEORI,UFCEDENTEORI,CEPCEDENTEORI,TIPOPESSACADO,CNPJ_CPF_SACADO,NOMESACADO,ENDSACADO,CIDSACADO,UFSACADO,CEPSACADO,TIPOPESSACADOR,
CNPJ_CPF_SACADOR,
NOMESACADOR,CODCARTEIRA,CODMOEDACNAB,IDENTNOSSONUMERO,LINHADIGITAVEL,DATAVENCIMENTO,VLRTITULO,SEUNUMERO,CODESPECIEDOC,DATAEMISSAO,QTDEDIASPROTESTO,
DATALIMPAGTO,TIPOPAGTO,INDTITULONEGOCIADO,VLRABATIMENTO,CODMORA,DATAMORA,VLRPERCMORA,CODMULTA,DATAMULTA,VLRPERCMULTA,CODDESCONTO01,DATADESCONTO01,VLRPERCDESCONTO01,
CODDESCONTO02,DATADESCONTO02,VLRPERCDESCONTO02,CODDESCONTO03,DATADESCONTO03,VLRPERCDESCONTO03,ACEITE,DATAACEITE,CODSITUACAO,TIPOBAIXA,SITPAGAMENTO,VLRMINTITULO,
VLRMAXTITULO,TIPOPESTERCEIRO,CNPJ_CPF_TERCEIRO,CODSISLEGADO,DTHRSITTITULO,DATACALCULO,INDALTERAVALOR,TIPOCALCULO,NOMEFANTASIACEDENTE,NOMEFANTASIACEDENTEORI,NOMEFANTASIASACADO,NUMCODBARRAS,NUMPARCELA,
QTDPARCELA,INDBLOQUEIO,INDPARCIAL,QTDPAGTO,INDVALORPERC_MIN,INDVALORPERC_MAX,ISPBCEDENTE,TIPOAUTRECDIVERGENTE,ISPBSACADA,CANALPAGTO,MEIOPAGTO,SITPAGAMENTOCIP,ULTNUMREFCADTIT,ULTNUMSEQCADTIT,ULTNUMREFBAIXAOPERAC,
ULTNUMSEQBAIXAOPERAC,ULTNUMREFBAIXAEFET,ULTNUMSEQBAIXAEFET,ULTNUMREFACEITE,ULTNUMSEQACEITE,ULTNUMREFTERC,ULTNUMSEQTERC,
situacaopedido,codretorno,SEQINCLUSAO) '*/
		
	set @select_insert_max_aceite = ',
	mt.situacaopedido,mt.codretorno,max(mt.SEQINCLUSAO) '
	
	set @select_insert_aceite = ', 
	mt.situacaopedido,mt.codretorno,mt.SEQINCLUSAO '
	
	set @select_insert_aceite_tipopesquisaaceite_null = ', 
	null,null,null '
	
	set @from_insert_aceite = ' 
left join manut_titulos mt
	on(t.numidentcdda=mt.numidentcdda
		and mt.codevento=''8104''
		and mt.SEQINCLUSAO=(select max(mt2.SEQINCLUSAO)
			from MANUT_TITULOS mt2
			where mt2.codevento=''8104''
			and mt.NUMIDENTCDDA=mt2.NUMIDENTCDDA)) '
		
	/*set @where_insert_aceite = '
	and mt.codevento=''8104''
	and isnull(mt.SEQINCLUSAO,'''')=(select isnull(max(mt2.SEQINCLUSAO),'''')
		from MANUT_TITULOS mt2
		where mt2.codevento=''8104''
		and mt.NUMIDENTCDDA=mt2.NUMIDENTCDDA) '*/
	
	/*set @where_insert_aceite = '
	and mt.codevento=''8104''
	and mt.SEQINCLUSAO=(select max(mt2.SEQINCLUSAO)
		from MANUT_TITULOS mt2
		where mt2.codevento=''8104''
		and mt.NUMIDENTCDDA=mt2.NUMIDENTCDDA) '*/
		
	set @groupby_insert_aceite = ',
	mt.situacaopedido,mt.codretorno '
	
	--colocar um a um
	set @parametros = 
	' @CNPJ_CPF_SACADO VARCHAR(15), 
	@NUMIDENTCDDA NUMERIC(19,0),
	@TIPOPESQUISA VARCHAR(10),
	@CODCONDICAO VARCHAR(30), 
	@TIPOPESCEDENTE VARCHAR(3), 
	@CNPJ_CPF_CEDENTE VARCHAR(15),
	@DATAVENCIMENTOINI DATETIME,
	@DATAVENCIMENTOFIM DATETIME,
	@CODSISLEGADO VARCHAR(15),
	@P_TIPOPESQUISAACEITE VARCHAR(2) '
--------------------------------------------------------------------------------------------------------
	IF (@TIPOPESQUISA = 'TITULO') 	
	begin
	
	INSERT INTO #TEMP_TITULOS_FILTRO (TIPOREGISTRO,NUMIDENTCDDA,CODIFSACADA,CODIFCEDENTE,TIPOPESCEDENTE,CNPJ_CPF_CEDENTE,NOMECEDENTE,TIPOPESCEDENTEORI,CNPJ_CPF_CEDENTEORI,
	NOMECEDENTEORI,ENDCEDENTEORI,CIDCEDENTEORI,UFCEDENTEORI,CEPCEDENTEORI,TIPOPESSACADO,CNPJ_CPF_SACADO,NOMESACADO,ENDSACADO,CIDSACADO,UFSACADO,CEPSACADO,TIPOPESSACADOR,
	CNPJ_CPF_SACADOR,
	NOMESACADOR,CODCARTEIRA,CODMOEDACNAB,IDENTNOSSONUMERO,LINHADIGITAVEL,DATAVENCIMENTO,VLRTITULO,SEUNUMERO,CODESPECIEDOC,DATAEMISSAO,QTDEDIASPROTESTO,
	DATALIMPAGTO,TIPOPAGTO,INDTITULONEGOCIADO,VLRABATIMENTO,CODMORA,DATAMORA,VLRPERCMORA,CODMULTA,DATAMULTA,VLRPERCMULTA,CODDESCONTO01,DATADESCONTO01,VLRPERCDESCONTO01,
	CODDESCONTO02,DATADESCONTO02,VLRPERCDESCONTO02,CODDESCONTO03,DATADESCONTO03,VLRPERCDESCONTO03,ACEITE,DATAACEITE,CODSITUACAO,TIPOBAIXA,SITPAGAMENTO,VLRMINTITULO,
	VLRMAXTITULO,TIPOPESTERCEIRO,CNPJ_CPF_TERCEIRO,CODSISLEGADO,DTHRSITTITULO,DATACALCULO,INDALTERAVALOR,TIPOCALCULO,NOMEFANTASIACEDENTE,NOMEFANTASIACEDENTEORI,NOMEFANTASIASACADO,NUMCODBARRAS,NUMPARCELA,
	QTDPARCELA,INDBLOQUEIO,INDPARCIAL,QTDPAGTO,INDVALORPERC_MIN,INDVALORPERC_MAX,ISPBCEDENTE,TIPOAUTRECDIVERGENTE,ISPBSACADA,CANALPAGTO,MEIOPAGTO,SITPAGAMENTOCIP,ULTNUMREFCADTIT,ULTNUMSEQCADTIT,ULTNUMREFBAIXAOPERAC,
	ULTNUMSEQBAIXAOPERAC,ULTNUMREFBAIXAEFET,ULTNUMSEQBAIXAEFET,ULTNUMREFACEITE,ULTNUMSEQACEITE,ULTNUMREFTERC,ULTNUMSEQTERC,
	situacaopedido,codretorno,SEQINCLUSAO)
	
	select 1,T.NUMIDENTCDDA,T.CODIFSACADA,T.CODIFCEDENTE,T.TIPOPESCEDENTE,T.CNPJ_CPF_CEDENTE,T.NOMECEDENTE,T.TIPOPESCEDENTEORI,T.CNPJ_CPF_CEDENTEORI,
	T.NOMECEDENTEORI,T.ENDCEDENTEORI,T.CIDCEDENTEORI,T.UFCEDENTEORI,T.CEPCEDENTEORI,T.TIPOPESSACADO,T.CNPJ_CPF_SACADO,T.NOMESACADO,T.ENDSACADO,T.CIDSACADO,T.UFSACADO,T.CEPSACADO,T.TIPOPESSACADOR,
	CASE
	WHEN LEN(T.CNPJ_CPF_SACADOR)>14
		THEN SUBSTRING(T.CNPJ_CPF_SACADOR,2,14)
		ELSE T.CNPJ_CPF_SACADOR
	END,
	T.NOMESACADOR,T.CODCARTEIRA,T.CODMOEDACNAB,T.IDENTNOSSONUMERO,T.LINHADIGITAVEL,T.DATAVENCIMENTO,T.VLRTITULO,T.SEUNUMERO,T.CODESPECIEDOC,T.DATAEMISSAO,T.QTDEDIASPROTESTO,
	T.DATALIMPAGTO,T.TIPOPAGTO,T.INDTITULONEGOCIADO,T.VLRABATIMENTO,T.CODMORA,T.DATAMORA,T.VLRPERCMORA,T.CODMULTA,T.DATAMULTA,T.VLRPERCMULTA,T.CODDESCONTO01,T.DATADESCONTO01,T.VLRPERCDESCONTO01,
	T.CODDESCONTO02,T.DATADESCONTO02,T.VLRPERCDESCONTO02,T.CODDESCONTO03,T.DATADESCONTO03,T.VLRPERCDESCONTO03,T.ACEITE,T.DATAACEITE,T.CODSITUACAO,T.TIPOBAIXA,T.SITPAGAMENTO,T.VLRMINTITULO,
	T.VLRMAXTITULO,T.TIPOPESTERCEIRO,T.CNPJ_CPF_TERCEIRO,T.CODSISLEGADO,T.DTHRSITTITULO,T.DATACALCULO,T.INDALTERAVALOR,T.TIPOCALCULO,T.NOMEFANTASIACEDENTE,T.NOMEFANTASIACEDENTEORI,T.NOMEFANTASIASACADO,T.NUMCODBARRAS,T.NUMPARCELA,
	T.QTDPARCELA,T.INDBLOQUEIO,T.INDPARCIAL,T.QTDPAGTO,T.INDVALORPERC_MIN,T.INDVALORPERC_MAX,T.ISPBCEDENTE,T.TIPOAUTRECDIVERGENTE,T.ISPBSACADA,T.CANALPAGTO,T.MEIOPAGTO,T.SITPAGAMENTOCIP,T.ULTNUMREFCADTIT,T.ULTNUMSEQCADTIT,T.ULTNUMREFBAIXAOPERAC,
	T.ULTNUMSEQBAIXAOPERAC,T.ULTNUMREFBAIXAEFET,T.ULTNUMSEQBAIXAEFET,T.ULTNUMREFACEITE,T.ULTNUMSEQACEITE,T.ULTNUMREFTERC,T.ULTNUMSEQTERC,

	mt.situacaopedido,mt.codretorno,max(mt.SEQINCLUSAO)
	
	FROM TITULOS T 
	
	left join manut_titulos mt
	on(t.numidentcdda=mt.numidentcdda
		and mt.codevento='8104'
		and mt.SEQINCLUSAO=(select max(mt2.SEQINCLUSAO)
			from MANUT_TITULOS mt2
			where mt2.codevento='8104'
			and mt.NUMIDENTCDDA=mt2.NUMIDENTCDDA))
	
	WHERE T.NUMIDENTCDDA=@NUMIDENTCDDA 
	
	group by T.NUMIDENTCDDA,T.CODIFSACADA,T.CODIFCEDENTE,T.TIPOPESCEDENTE,T.CNPJ_CPF_CEDENTE,T.NOMECEDENTE,T.TIPOPESCEDENTEORI,T.CNPJ_CPF_CEDENTEORI,
	T.NOMECEDENTEORI,T.ENDCEDENTEORI,T.CIDCEDENTEORI,T.UFCEDENTEORI,T.CEPCEDENTEORI,T.TIPOPESSACADO,T.CNPJ_CPF_SACADO,T.NOMESACADO,T.ENDSACADO,T.CIDSACADO,T.UFSACADO,T.CEPSACADO,T.TIPOPESSACADOR,
	CASE
	WHEN LEN(T.CNPJ_CPF_SACADOR)>14
		THEN SUBSTRING(T.CNPJ_CPF_SACADOR,2,14)
		ELSE T.CNPJ_CPF_SACADOR
	END,
	T.NOMESACADOR,T.CODCARTEIRA,T.CODMOEDACNAB,T.IDENTNOSSONUMERO,T.LINHADIGITAVEL,T.DATAVENCIMENTO,T.VLRTITULO,T.SEUNUMERO,T.CODESPECIEDOC,T.DATAEMISSAO,T.QTDEDIASPROTESTO,
	T.DATALIMPAGTO,T.TIPOPAGTO,T.INDTITULONEGOCIADO,T.VLRABATIMENTO,T.CODMORA,T.DATAMORA,T.VLRPERCMORA,T.CODMULTA,T.DATAMULTA,T.VLRPERCMULTA,T.CODDESCONTO01,T.DATADESCONTO01,T.VLRPERCDESCONTO01,
	T.CODDESCONTO02,T.DATADESCONTO02,T.VLRPERCDESCONTO02,T.CODDESCONTO03,T.DATADESCONTO03,T.VLRPERCDESCONTO03,T.ACEITE,T.DATAACEITE,T.CODSITUACAO,T.TIPOBAIXA,T.SITPAGAMENTO,T.VLRMINTITULO,
	T.VLRMAXTITULO,T.TIPOPESTERCEIRO,T.CNPJ_CPF_TERCEIRO,T.CODSISLEGADO,T.DTHRSITTITULO,T.DATACALCULO,T.INDALTERAVALOR,T.TIPOCALCULO,T.NOMEFANTASIACEDENTE,T.NOMEFANTASIACEDENTEORI,T.NOMEFANTASIASACADO,T.NUMCODBARRAS,T.NUMPARCELA,
	T.QTDPARCELA,T.INDBLOQUEIO,T.INDPARCIAL,T.QTDPAGTO,T.INDVALORPERC_MIN,T.INDVALORPERC_MAX,T.ISPBCEDENTE,T.TIPOAUTRECDIVERGENTE,T.ISPBSACADA,T.CANALPAGTO,T.MEIOPAGTO,T.SITPAGAMENTOCIP,T.ULTNUMREFCADTIT,T.ULTNUMSEQCADTIT,T.ULTNUMREFBAIXAOPERAC,
	T.ULTNUMSEQBAIXAOPERAC,T.ULTNUMREFBAIXAEFET,T.ULTNUMSEQBAIXAEFET,T.ULTNUMREFACEITE,T.ULTNUMSEQACEITE,T.ULTNUMREFTERC,T.ULTNUMSEQTERC,

	mt.situacaopedido,mt.codretorno  
	
	
		/*set @from_insert = '
	FROM TITULOS T '
	
		set @where_insert =	'
	WHERE T.NUMIDENTCDDA=@NUMIDENTCDDA '

	
		set @groupby_insert = ' 
group by T.NUMIDENTCDDA,T.CODIFSACADA,T.CODIFCEDENTE,T.TIPOPESCEDENTE,T.CNPJ_CPF_CEDENTE,T.NOMECEDENTE,T.TIPOPESCEDENTEORI,T.CNPJ_CPF_CEDENTEORI,
T.NOMECEDENTEORI,T.ENDCEDENTEORI,T.CIDCEDENTEORI,T.UFCEDENTEORI,T.CEPCEDENTEORI,T.TIPOPESSACADO,T.CNPJ_CPF_SACADO,T.NOMESACADO,T.ENDSACADO,T.CIDSACADO,T.UFSACADO,T.CEPSACADO,T.TIPOPESSACADOR,
CASE
WHEN LEN(T.CNPJ_CPF_SACADOR)>14
	THEN SUBSTRING(T.CNPJ_CPF_SACADOR,2,14)
	ELSE T.CNPJ_CPF_SACADOR
END,
T.NOMESACADOR,T.CODCARTEIRA,T.CODMOEDACNAB,T.IDENTNOSSONUMERO,T.LINHADIGITAVEL,T.DATAVENCIMENTO,T.VLRTITULO,T.SEUNUMERO,T.CODESPECIEDOC,T.DATAEMISSAO,T.QTDEDIASPROTESTO,
T.DATALIMPAGTO,T.TIPOPAGTO,T.INDTITULONEGOCIADO,T.VLRABATIMENTO,T.CODMORA,T.DATAMORA,T.VLRPERCMORA,T.CODMULTA,T.DATAMULTA,T.VLRPERCMULTA,T.CODDESCONTO01,T.DATADESCONTO01,T.VLRPERCDESCONTO01,
T.CODDESCONTO02,T.DATADESCONTO02,T.VLRPERCDESCONTO02,T.CODDESCONTO03,T.DATADESCONTO03,T.VLRPERCDESCONTO03,T.ACEITE,T.DATAACEITE,T.CODSITUACAO,T.TIPOBAIXA,T.SITPAGAMENTO,T.VLRMINTITULO,
T.VLRMAXTITULO,T.TIPOPESTERCEIRO,T.CNPJ_CPF_TERCEIRO,T.CODSISLEGADO,T.DTHRSITTITULO,T.DATACALCULO,T.INDALTERAVALOR,T.TIPOCALCULO,T.NOMEFANTASIACEDENTE,T.NOMEFANTASIACEDENTEORI,T.NOMEFANTASIASACADO,T.NUMCODBARRAS,T.NUMPARCELA,
T.QTDPARCELA,T.INDBLOQUEIO,T.INDPARCIAL,T.QTDPAGTO,T.INDVALORPERC_MIN,T.INDVALORPERC_MAX,T.ISPBCEDENTE,T.TIPOAUTRECDIVERGENTE,T.ISPBSACADA,T.CANALPAGTO,T.MEIOPAGTO,T.SITPAGAMENTOCIP,T.ULTNUMREFCADTIT,T.ULTNUMSEQCADTIT,T.ULTNUMREFBAIXAOPERAC,
T.ULTNUMSEQBAIXAOPERAC,T.ULTNUMREFBAIXAEFET,T.ULTNUMSEQBAIXAEFET,T.ULTNUMREFACEITE,T.ULTNUMSEQACEITE,T.ULTNUMREFTERC,T.ULTNUMSEQTERC '
	
		if @FLAG_ACEITE = 1
		begin
			--set @campos_insert = @campos_insert_aceite
			set @select_insert_max = @select_insert_max_aceite
			set @FROM_insert = @FROM_insert + @FROM_insert_aceite
			--set @where_insert = @where_insert + @where_insert_aceite
			set @groupby_insert = @groupby_insert + @groupby_insert_aceite
		end
	
		set @insert = 
			@campos_insert + 
			@select_insert_max + 
			@from_insert + 
			@where_insert + 
			@groupby_insert
		select @insert	
		EXECUTE SP_EXECUTESQL @insert, 
			@PARAMETROS,
				@CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO, 
				@NUMIDENTCDDA = @NUMIDENTCDDA,
				@TIPOPESQUISA = @TIPOPESQUISA,
				@CODCONDICAO = @CODCONDICAO, 
				@TIPOPESCEDENTE = @TIPOPESCEDENTE, 
				@CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE,
				@DATAVENCIMENTOINI = @DATAVENCIMENTOINI,
				@DATAVENCIMENTOFIM = @DATAVENCIMENTOFIM,
				@CODSISLEGADO = @CODSISLEGADO,
				@P_TIPOPESQUISAACEITE = @P_TIPOPESQUISAACEITE*/
	
	end
	--------------------------------------------------------------------------------------------------------
	ELSE IF (@CODCONDICAO IS NULL )
	begin
	
		set @from_insert = ' 
	TITULOS T WITH (NOLOCK)
	inner join #TITULOS TEMP_T 
		on(T.NUMIDENTCDDA=TEMP_T.NUMIDENTCDDA) '
		
		set @where_insert = '
	WHERE T.CNPJ_CPF_SACADO IN(
		SELECT S.CNPJ_CPF_SACADO 
		FROM SACELETRONICO S 
		WHERE S.CNPJ_CPF_SACADO=@CNPJ_CPF_SACADO 
		AND S.SITUACAOSACADO=1)
	AND(@TIPOPESCEDENTE IS NULL OR T.TIPOPESCEDENTE=@TIPOPESCEDENTE) 
	AND(@CNPJ_CPF_CEDENTE IS NULL OR T.CNPJ_CPF_CEDENTE=@CNPJ_CPF_CEDENTE)
	AND(@DATAVENCIMENTOINI IS NULL OR T.DATAVENCIMENTO>=@DATAVENCIMENTOINI)
	AND(@DATAVENCIMENTOFIM IS NULL OR T.DATAVENCIMENTO<=@DATAVENCIMENTOFIM) '
	
		if @FLAG_ACEITE = 1
		begin
			--set @campos_insert = @campos_insert_aceite
			set @select_insert = @select_insert + @select_insert_aceite
			set @FROM_insert = @FROM_insert + @FROM_insert_aceite
			--set @where_insert = @where_insert + @where_insert_aceite
		end
		else 
		begin
			set @select_insert = @select_insert + @select_insert_aceite_tipopesquisaaceite_null
		end
		
		set @insert = 
			@campos_insert + 
			@select_insert + 
			@from_insert + 
			@where_insert
			
		if @debugging = 1 
			select @insert		
			
		EXECUTE SP_EXECUTESQL @insert, 
			@PARAMETROS,
				@CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO, 
				@NUMIDENTCDDA = @NUMIDENTCDDA,
				@TIPOPESQUISA = @TIPOPESQUISA,
				@CODCONDICAO = @CODCONDICAO, 
				@TIPOPESCEDENTE = @TIPOPESCEDENTE, 
				@CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE,
				@DATAVENCIMENTOINI = @DATAVENCIMENTOINI,
				@DATAVENCIMENTOFIM = @DATAVENCIMENTOFIM,
				@CODSISLEGADO = @CODSISLEGADO,
				@P_TIPOPESQUISAACEITE = @P_TIPOPESQUISAACEITE
			
		--UNION ALL
		--NÃO PODE SER USADO A TEMP #TITULOS POIS A TEMP NÃO POSSUI TITULOS DO AGREGADO!
		set @from_insert = ' 
	TITULOS T WITH (NOLOCK) '
	
		--A CONDIÇÃO DE BUSCA POR AGREGADOS NÃO PERMITE UTILIZAR A TEMP!
		set @where_insert = ' 
	WHERE T.CNPJ_CPF_SACADO IN(
		SELECT S.CNPJ_CPF_SACADO 
		FROM SACELETRONICO S 
		WHERE S.CNPJ_CPF_SACADO=@CNPJ_CPF_SACADO 
		AND S.SITUACAOSACADO=1)
	AND(@TIPOPESCEDENTE IS NULL OR T.TIPOPESCEDENTE=@TIPOPESCEDENTE) 
	AND(@CNPJ_CPF_CEDENTE IS NULL OR T.CNPJ_CPF_CEDENTE=@CNPJ_CPF_CEDENTE)
	AND(@DATAVENCIMENTOINI IS NULL OR T.DATAVENCIMENTO>=@DATAVENCIMENTOINI)
	AND(@DATAVENCIMENTOFIM IS NULL OR T.DATAVENCIMENTO<=@DATAVENCIMENTOFIM) '
		
		set @insert = 
			@campos_insert + 
			@select_insert + 
			@from_insert + 
			@where_insert
		
	if @debugging = 1 
			select @insert		
			
		EXECUTE SP_EXECUTESQL @insert, 
			@PARAMETROS,
				@CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO, 
				@NUMIDENTCDDA = @NUMIDENTCDDA,
				@TIPOPESQUISA = @TIPOPESQUISA,
				@CODCONDICAO = @CODCONDICAO, 
				@TIPOPESCEDENTE = @TIPOPESCEDENTE, 
				@CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE,
				@DATAVENCIMENTOINI = @DATAVENCIMENTOINI,
				@DATAVENCIMENTOFIM = @DATAVENCIMENTOFIM,
				@CODSISLEGADO = @CODSISLEGADO,
				@P_TIPOPESQUISAACEITE = @P_TIPOPESQUISAACEITE
	
		--UNION ALL
		set @from_insert = ' 
	FROM TITULOS T WITH (NOLOCK)
	inner join TITULOS TEMP_T
		on(T.NUMIDENTCDDA=TEMP_T.NUMIDENTCDDA) '
	
		set @where_insert = ' 
	WHERE T.CNPJ_CPF_TERCEIRO = @CNPJ_CPF_SACADO
	AND(@TIPOPESCEDENTE IS NULL OR T.TIPOPESCEDENTE=@TIPOPESCEDENTE) 
	AND(@CNPJ_CPF_CEDENTE IS NULL OR T.CNPJ_CPF_CEDENTE=@CNPJ_CPF_CEDENTE)
	AND(@DATAVENCIMENTOINI IS NULL OR T.DATAVENCIMENTO>=@DATAVENCIMENTOINI)
	AND(@DATAVENCIMENTOFIM IS NULL OR T.DATAVENCIMENTO<=@DATAVENCIMENTOFIM) '
		
		set @insert = 
			@campos_insert + 
			@select_insert + 
			@from_insert + 
			@where_insert
		
		if @debugging = 1 
			select @insert		
			
		EXECUTE SP_EXECUTESQL @insert, 
			@PARAMETROS,
				@CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO, 
				@NUMIDENTCDDA = @NUMIDENTCDDA,
				@TIPOPESQUISA = @TIPOPESQUISA,
				@CODCONDICAO = @CODCONDICAO, 
				@TIPOPESCEDENTE = @TIPOPESCEDENTE, 
				@CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE,
				@DATAVENCIMENTOINI = @DATAVENCIMENTOINI,
				@DATAVENCIMENTOFIM = @DATAVENCIMENTOFIM,
				@CODSISLEGADO = @CODSISLEGADO,
				@P_TIPOPESQUISAACEITE = @P_TIPOPESQUISAACEITE
			
	end
	--------------------------------------------------------------------------------------------------------
	ELSE IF @CODCONDICAO IN ('Aberto', '1')
	begin			
	/*---------------------------------------------*/
	/* Pegar títulos em aberto e cartões em aberto */	
	/*---------------------------------------------*/
		
		set @FROM_insert = ' 
	FROM TITULOS T WITH (NOLOCK)
	inner join #TITULOS TEMP_TIT
		on(T.NUMIDENTCDDA=TEMP_TIT.NUMIDENTCDDA)'
	
	--retirar comentarios da query	
		set @where_insert = '
	WHERE(@TIPOPESCEDENTE IS NULL OR T.TIPOPESCEDENTE=@TIPOPESCEDENTE)
	AND(@CNPJ_CPF_CEDENTE IS NULL OR T.CNPJ_CPF_CEDENTE=@CNPJ_CPF_CEDENTE)
	AND(@DATAVENCIMENTOINI IS NULL OR T.DATAVENCIMENTO>=@DATAVENCIMENTOINI)
	AND(@DATAVENCIMENTOFIM IS NULL OR T.DATAVENCIMENTO<=@DATAVENCIMENTOFIM)
	AND ' +
	/*-----------------------------------------------------------------------------------------------------------*/
	/* 29/04/2019 - Eliane - Mudando as regras de seleção de títulos que não são cartão e para títulos de cartão */
	/*-----------------------------------------------------------------------------------------------------------*/
	'((T.CODESPECIEDOC<>''31'' AND T.CODSITUACAO=''1'' AND T.SITPAGAMENTO IS NULL AND T.TIPOBAIXA IS NULL) OR ' + /*TITULO_SIT_ABERTO*/
	'(T.CODESPECIEDOC<>''31'' AND T.CODSITUACAO=''1'' AND T.SITPAGAMENTO=''3'' AND T.TIPOBAIXA IS NULL) OR ' + /*TITULO_SIT_ABERTO*/
	'(T.CODESPECIEDOC=''31'' AND T.CODSITUACAO=''1'')) ' /*CARTÃO DE CREDITO - TITULO_SIT_ABERTO*/ 
	/*-----------------------------------------------------------------------------------------------------------*/
	/* 29/04/2019 - Eliane - Mudando as regras de seleção de títulos que não são cartão e para títulos de cartão */
	/*-----------------------------------------------------------------------------------------------------------*/
		if @FLAG_ACEITE = 1
		begin
			--set @campos_insert = @campos_insert_aceite
			set @select_insert = @select_insert + @select_insert_aceite
			set @FROM_insert = @FROM_insert + @FROM_insert_aceite
			--set @where_insert = @where_insert + @where_insert_aceite
		end
		else 
		begin
			set @select_insert = @select_insert + @select_insert_aceite_tipopesquisaaceite_null
		end
		
		set @insert = 
			@campos_insert + 
			@select_insert + 
			@from_insert + 
			@where_insert
		
		if @debugging = 1 
			select @insert	as 'ELSE IF @CODCONDICAO IN (''Aberto'', ''1'')'	
			
		EXECUTE SP_EXECUTESQL @insert, 
			@PARAMETROS,
				@CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO, 
				@NUMIDENTCDDA = @NUMIDENTCDDA,
				@TIPOPESQUISA = @TIPOPESQUISA,
				@CODCONDICAO = @CODCONDICAO, 
				@TIPOPESCEDENTE = @TIPOPESCEDENTE, 
				@CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE,
				@DATAVENCIMENTOINI = @DATAVENCIMENTOINI,
				@DATAVENCIMENTOFIM = @DATAVENCIMENTOFIM,
				@CODSISLEGADO = @CODSISLEGADO,
				@P_TIPOPESQUISAACEITE = @P_TIPOPESQUISAACEITE
	
	end
	--------------------------------------------------------------------------------------------------------
	ELSE IF @CODCONDICAO IN ('Bloqueado para Pagamento' , '3')
	begin
		
		set @from_insert = ' 
	FROM TITULOS T WITH (NOLOCK)
	inner join #TITULOS TEMP_TIT
		on(T.NUMIDENTCDDA=TEMP_TIT.NUMIDENTCDDA) '
	
		set @where_insert = ' 
	WHERE(@TIPOPESCEDENTE IS NULL OR T.TIPOPESCEDENTE=@TIPOPESCEDENTE) 
	AND(@CNPJ_CPF_CEDENTE IS NULL OR T.CNPJ_CPF_CEDENTE=@CNPJ_CPF_CEDENTE)
	AND(@DATAVENCIMENTOINI IS NULL OR T.DATAVENCIMENTO>=@DATAVENCIMENTOINI)
	AND(@DATAVENCIMENTOFIM IS NULL OR T.DATAVENCIMENTO<=@DATAVENCIMENTOFIM)
	AND T.CODSITUACAO=1 
	AND T.SITPAGAMENTO=1 
	AND T.TIPOBAIXA IS NULL 
	AND T.CODSISLEGADO=@CODSISLEGADO '/*TITULO_SIT_BLOQUEADO*/ 
		
		if @FLAG_ACEITE = 1
		begin
			--set @campos_insert = @campos_insert_aceite
			set @select_insert = @select_insert + @select_insert_aceite
			set @FROM_insert = @FROM_insert + @FROM_insert_aceite
			--set @where_insert = @where_insert + @where_insert_aceite
		end
		else 
		begin
			set @select_insert = @select_insert + @select_insert_aceite_tipopesquisaaceite_null
		end
		
		set @insert = 
			@campos_insert + 
			@select_insert + 
			@from_insert + 
			@where_insert
		
		if @debugging = 1 
			select @insert		
			
		EXECUTE SP_EXECUTESQL @insert, 
			@PARAMETROS,
				@CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO, 
				@NUMIDENTCDDA = @NUMIDENTCDDA,
				@TIPOPESQUISA = @TIPOPESQUISA,
				@CODCONDICAO = @CODCONDICAO, 
				@TIPOPESCEDENTE = @TIPOPESCEDENTE, 
				@CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE,
				@DATAVENCIMENTOINI = @DATAVENCIMENTOINI,
				@DATAVENCIMENTOFIM = @DATAVENCIMENTOFIM,
				@CODSISLEGADO = @CODSISLEGADO,
				@P_TIPOPESQUISAACEITE = @P_TIPOPESQUISAACEITE
	end
	--------------------------------------------------------------------------------------------------------
	ELSE IF @CODCONDICAO IN ('Baixado', '2')
	begin
	
		set @FROM_insert = ' 
	TITULOS T WITH (NOLOCK)
	inner join #TITULOS TEMP_TIT
		on(T.NUMIDENTCDDA=TEMP_TIT.NUMIDENTCDDA) '
	
		set @WHERE_insert = ' 
	WHERE(@TIPOPESCEDENTE IS NULL OR T.TIPOPESCEDENTE=@TIPOPESCEDENTE) 
	AND(@CNPJ_CPF_CEDENTE IS NULL OR T.CNPJ_CPF_CEDENTE=@CNPJ_CPF_CEDENTE)
	AND(@DATAVENCIMENTOINI IS NULL OR T.DATAVENCIMENTO>=@DATAVENCIMENTOINI)
	AND(@DATAVENCIMENTOFIM IS NULL OR T.DATAVENCIMENTO<=@DATAVENCIMENTOFIM)
	AND T.CODSITUACAO<>1 
	AND T.TIPOBAIXA IS NOT NULL ' /* TITULO_SIT_BAIXADO */
		
		if @FLAG_ACEITE = 1
		begin
			--set @campos_insert = @campos_insert_aceite
			set @select_insert = @select_insert + @select_insert_aceite
			set @FROM_insert = @FROM_insert + @FROM_insert_aceite
			--set @where_insert = @where_insert + @where_insert_aceite
		end
		else 
		begin
			set @select_insert = @select_insert + @select_insert_aceite_tipopesquisaaceite_null
		end
		
		set @insert = 
			@campos_insert + 
			@select_insert + 
			@from_insert + 
			@where_insert
		
		if @debugging = 1 
			select @insert		
			
		EXECUTE SP_EXECUTESQL @insert, 
			@PARAMETROS,
				@CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO, 
				@NUMIDENTCDDA = @NUMIDENTCDDA,
				@TIPOPESQUISA = @TIPOPESQUISA,
				@CODCONDICAO = @CODCONDICAO, 
				@TIPOPESCEDENTE = @TIPOPESCEDENTE, 
				@CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE,
				@DATAVENCIMENTOINI = @DATAVENCIMENTOINI,
				@DATAVENCIMENTOFIM = @DATAVENCIMENTOFIM,
				@CODSISLEGADO = @CODSISLEGADO,
				@P_TIPOPESQUISAACEITE = @P_TIPOPESQUISAACEITE
			
	end	
	--------------------------------------------------------------------------------------------------------
	ELSE
	begin
	
		set @from_insert = ' 
	FROM TITULOS T WITH (NOLOCK)
	inner join #TITULOS TEMP_TIT
		on(T.NUMIDENTCDDA=TEMP_TIT.NUMIDENTCDDA) '
	
		set @where_insert = ' 
	WHERE(@TIPOPESCEDENTE IS NULL OR T.TIPOPESCEDENTE=@TIPOPESCEDENTE)
	AND(@CNPJ_CPF_CEDENTE IS NULL OR T.CNPJ_CPF_CEDENTE=@CNPJ_CPF_CEDENTE)
	AND(@DATAVENCIMENTOINI IS NULL OR T.DATAVENCIMENTO>=@DATAVENCIMENTOINI)
	AND(@DATAVENCIMENTOFIM IS NULL OR T.DATAVENCIMENTO<=@DATAVENCIMENTOFIM)
	AND(T.SITPAGAMENTO IS NULL OR (T.SITPAGAMENTO IS NOT NULL 
		AND T.CODSISLEGADO=@CODSISLEGADO)) '
		
		if @FLAG_ACEITE = 1
		begin
			--set @campos_insert = @campos_insert_aceite
			set @select_insert = @select_insert + @select_insert_aceite
			set @FROM_insert = @FROM_insert + @FROM_insert_aceite
			--set @where_insert = @where_insert + @where_insert_aceite
		end
		else 
		begin
			set @select_insert = @select_insert + @select_insert_aceite_tipopesquisaaceite_null
		end
		
		set @insert = 
			@campos_insert + 
			@select_insert + 
			@from_insert + 
			@where_insert + 
			@groupby_insert
		
		if @debugging = 1 
			select @insert		
			
		EXECUTE SP_EXECUTESQL @insert, 
			@PARAMETROS,
				@CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO, 
				@NUMIDENTCDDA = @NUMIDENTCDDA,
				@TIPOPESQUISA = @TIPOPESQUISA,
				@CODCONDICAO = @CODCONDICAO, 
				@TIPOPESCEDENTE = @TIPOPESCEDENTE, 
				@CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE,
				@DATAVENCIMENTOINI = @DATAVENCIMENTOINI,
				@DATAVENCIMENTOFIM = @DATAVENCIMENTOFIM,
				@CODSISLEGADO = @CODSISLEGADO,
				@P_TIPOPESQUISAACEITE = @P_TIPOPESQUISAACEITE
			
	end
--------------------------------------------------------------------------------------------------------	
	CREATE NONCLUSTERED INDEX IX_01 ON #TEMP_TITULOS_FILTRO ( TIPOREGISTRO ) INCLUDE ( NUMIDENTCDDA, CNPJ_CPF_SACADO, SEQFATURA )

	if @debugging = 1 
		select @insert		

	-- MENSAGEM
	INSERT INTO #TEMP_TITULOS_FILTRO (NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO,
			SEQMENSAGEM, TEXTO)
	SELECT T.NUMIDENTCDDA, 2, T.CNPJ_CPF_SACADO, 
		   M.SEQMENSAGEM, M.TEXTO
	  FROM #TEMP_TITULOS_FILTRO T INNER JOIN MENSAGENS M (NOLOCK)
		ON (T.NUMIDENTCDDA = M.NUMIDENTCDDA)
	 WHERE T.TIPOREGISTRO = 1

	-- NOTA FISCAL
	INSERT INTO #TEMP_TITULOS_FILTRO (NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO,
		   NUMNOTAFISCAL, DATAEMISSAONOTA, VLRNOTAFISCAL)
	SELECT T.NUMIDENTCDDA, 4, T.CNPJ_CPF_SACADO,
		   N.NUMNOTAFISCAL, N.DATAEMISSAO, N.VLRNOTAFISCAL
	  FROM #TEMP_TITULOS_FILTRO T 
	  INNER JOIN  NOTAS_FISCAIS N (NOLOCK)
		ON (T.NUMIDENTCDDA = N.NUMIDENTCDDA)
	 WHERE T.TIPOREGISTRO = 1
		
	-- ANEXO FATURA
	INSERT INTO #TEMP_TITULOS_FILTRO (NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO,
		   SEQFATURA, CODMODELO)
	SELECT T.NUMIDENTCDDA, 5, T.CNPJ_CPF_SACADO,
		   A.SEQFATURA, A.CODMODELO
	  FROM #TEMP_TITULOS_FILTRO T 
	  INNER JOIN  ANEXO_FATURA A (NOLOCK)
		ON (T.NUMIDENTCDDA = A.NUMIDENTCDDA)
	 WHERE T.TIPOREGISTRO = 1
		
	-- MODELO (ANEXO FATURA)
	INSERT INTO #TEMP_TITULOS_FILTRO (NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO,
		   SEQFATURA, SEQMODELO, CABECALHO, TPDADOS)
	SELECT T.NUMIDENTCDDA, 6, T.CNPJ_CPF_SACADO,
		   M.SEQFATURA, M.SEQMODELO, M.CABECALHO, M.TPDADOS
	  FROM #TEMP_TITULOS_FILTRO T 
	  INNER JOIN  MODELO M (NOLOCK)
		ON ( T.NUMIDENTCDDA = M.NUMIDENTCDDA
			AND T.SEQFATURA = M.SEQFATURA)
	 WHERE T.TIPOREGISTRO = 5
		
	-- DETALHE ANTES DO CABECALHO (ANEXO FATURA)
	INSERT INTO #TEMP_TITULOS_FILTRO (NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		   SEQFATURA, SEQDETANTES, TEXTO)
	SELECT T.NUMIDENTCDDA, 7, T.CNPJ_CPF_SACADO,
		   D.SEQFATURA, D.SEQDETANTES, D.TEXTO
	  FROM #TEMP_TITULOS_FILTRO T 
	  INNER JOIN DET_ANTES_CABEC D (NOLOCK)
		ON (T.NUMIDENTCDDA = D.NUMIDENTCDDA
			AND T.SEQFATURA = D.SEQFATURA)
	 WHERE T.TIPOREGISTRO = 5

	-- DETALHE APOS CABECALHO (ANEXO FATURA)
	INSERT INTO #TEMP_TITULOS_FILTRO (NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO,
		   SEQFATURA, SEQDETDEPOIS, TEXTO)
	SELECT T.NUMIDENTCDDA, 8, T.CNPJ_CPF_SACADO, 
		   D.SEQFATURA, D.SEQDETAPOS, D.TEXTO
	  FROM #TEMP_TITULOS_FILTRO T 
	  INNER JOIN DET_APOS_CABEC D (NOLOCK)
		ON (T.NUMIDENTCDDA = D.NUMIDENTCDDA
			AND T.SEQFATURA = D.SEQFATURA)
	 WHERE T.TIPOREGISTRO = 5

	-- BAIXA OPERACIONAL
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO,
		NUMIDENTCBAIXAOPERAC, NUMREFBAIXAOPERAC, TIPOBAIXAOPERACIONAL, DATABAIXAOPERACIONAL, 
		--13/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOMEPORTADOR E DATAHORARECBTTITULO (CATÁLOGO 5.03 E 5.04)
		VLRBAIXAOPERACIONAL, TIPOPESPORTADOR, CNPJ_CPF_PORTADOR, NOME_PORTADOR,
		--29/03/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
		TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO,
		AGENCIARECEBEDORA, DATAHORARECBTTITULO, DATAHORACANCEL, INDCONTINGENCIA, 
		ORIGEMCANCELAMENTO
		)
	SELECT 
		#TEMP_TITULOS_FILTRO.NUMIDENTCDDA, 9, #TEMP_TITULOS_FILTRO.CNPJ_CPF_SACADO,
		BAIXAS_OPERACIONAIS.NUMIDENTCBAIXAOPERAC, BAIXAS_OPERACIONAIS.NUMREFBAIXAOPERAC, BAIXAS_OPERACIONAIS.TIPOBAIXA, BAIXAS_OPERACIONAIS.DATABAIXA, 
		--13/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOMEPORTADOR E DATAHORARECBTTITULO (CATÁLOGO 5.03 E 5.04)
		BAIXAS_OPERACIONAIS.VLRBAIXA, BAIXAS_OPERACIONAIS.TIPOPESPORTADOR, BAIXAS_OPERACIONAIS.CNPJ_CPF_PORTADOR, BAIXAS_OPERACIONAIS.NOME_PORTADOR,
		--29/03/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
		BAIXAS_OPERACIONAIS.TIPOPESAGREGADOR, BAIXAS_OPERACIONAIS.CNPJ_CPF_AGREGADOR, BAIXAS_OPERACIONAIS.NOMEAGREGADOR, BAIXAS_OPERACIONAIS.ISPBINICIADORPAGTO,
		BAIXAS_OPERACIONAIS.AGENCIARECEBEDORA, BAIXAS_OPERACIONAIS.DATAHORARECBTTITULO, BAIXAS_OPERACIONAIS.DATAHORACANCEL, BAIXAS_OPERACIONAIS.INDCONTINGENCIA, 
		BAIXAS_OPERACIONAIS.ORIGEMCANCELAMENTO
	  FROM #TEMP_TITULOS_FILTRO  
	  INNER JOIN BAIXAS_OPERACIONAIS (NOLOCK)
		ON (#TEMP_TITULOS_FILTRO.NUMIDENTCDDA = BAIXAS_OPERACIONAIS.NUMIDENTCDDA)
	 WHERE #TEMP_TITULOS_FILTRO.TIPOREGISTRO = 1

	-- BAIXA EFETIVA
	INSERT INTO #TEMP_TITULOS_FILTRO (NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO,
		   NUMIDENTCBAIXAEFET, NUMREFBAIXAEFET, DATABAIXAEFETIVA, VLRBAIXAEFETIVA, TIPOBAIXAEFETIVA)
	SELECT T.NUMIDENTCDDA, 10, T.CNPJ_CPF_SACADO,
		   BAIXAS.NUMIDENTCBAIXAEFET, BAIXAS.NUMREFBAIXAEFET, BAIXAS.DATABAIXA, BAIXAS.VLRBAIXA, BAIXAS.TIPOBAIXA
	  FROM #TEMP_TITULOS_FILTRO T 
	  INNER JOIN BAIXAS_EFETIVAS BAIXAS (NOLOCK)
		ON (T.NUMIDENTCDDA = BAIXAS.NUMIDENTCDDA)
	 WHERE T.TIPOREGISTRO = 1

	-- CALCULOS
	INSERT INTO #TEMP_TITULOS_FILTRO (NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		   DATACALCULO, VLRMORA, VLRMULTA, VLRDESCONTO, VLRCOBRAR)
	SELECT T.NUMIDENTCDDA, 11, T.CNPJ_CPF_SACADO,
			CALCULOS.DATACALCULO, CALCULOS.VLRMORA, CALCULOS.VLRMULTA, CALCULOS.VLRDESCONTO, CALCULOS.VLRCOBRAR
	  FROM #TEMP_TITULOS_FILTRO T 
	  INNER JOIN CALCULOS (NOLOCK)
		ON(T.NUMIDENTCDDA = CALCULOS.NUMIDENTCDDA)
	 WHERE T.TIPOREGISTRO = 1
		
	-- TERCEIROS
	INSERT INTO #TEMP_TITULOS_FILTRO (NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		   TIPOPESTERC, CNPJ_CPF_TERC, NUMIDENTCTERC, NUMREFTERC, 
		   TIPOPESAUTORIZADOR, CNPJ_CPF_AUTORIZADOR)
	SELECT T.NUMIDENTCDDA, 12, T.CNPJ_CPF_SACADO,
		   TERCEIROS.TIPOPESTERC, TERCEIROS.CNPJ_CPF_TERC, TERCEIROS.NUMIDENTCTERC, TERCEIROS.NUMREFTERC, 
		   TERCEIROS.TIPOPESAUTORIZADOR, TERCEIROS.CNPJ_CPF_AUTORIZADOR
	  FROM #TEMP_TITULOS_FILTRO T 
	  INNER JOIN TERCEIROS (NOLOCK)
		ON (T.NUMIDENTCDDA = TERCEIROS.NUMIDENTCDDA)
	 WHERE T.TIPOREGISTRO = 1
--------------------------------------------------------------------------------------------------------
	--22/01/2020 - rfaquini - Alteração para que o serviço possa retornar listagem de acordo com filto de ACEITE.
	--14/02/2020 - rfaquini - Alteração para que o serviço possa retornar título e seu status.
	declare @COMANDO NVARCHAR(4000),
			@COMANDO_AUX NVARCHAR(4000),
			@COMANDO_AUX_INSERT NVARCHAR(4000),
			@COMANDO_AUX_SELECT NVARCHAR(4000),
			@COMANDO_AUX_ACEITE NVARCHAR(4000),
			@COMANDO_AUX_ACEITE_tipopesquisaaceite_null NVARCHAR(4000),
			@FROM NVARCHAR(4000),
			--@PARAMETROS NVARCHAR(4000),
			@DROP NVARCHAR(4000)

	--CUIDADO AO MODIFICAR A FORMATAÇÃO!!!
	--ATENTAR-SE A QUANTIDADE MÁXIMA DE 4000 CARACTERES
	
	SET @COMANDO_AUX = 
	' TIPOREGISTRO,NUMIDENTCDDA,CODIFSACADA,CODIFCEDENTE,TIPOPESCEDENTE,CNPJ_CPF_CEDENTE,NOMECEDENTE,TIPOPESCEDENTEORI,
	CNPJ_CPF_CEDENTEORI,NOMECEDENTEORI,ENDCEDENTEORI,CIDCEDENTEORI,UFCEDENTEORI,CEPCEDENTEORI,TIPOPESSACADO,CNPJ_CPF_SACADO,
	NOMESACADO,ENDSACADO,CIDSACADO,UFSACADO,CEPSACADO,TIPOPESSACADOR,CNPJ_CPF_SACADOR,NOMESACADOR,CODCARTEIRA,CODMOEDACNAB,
	IDENTNOSSONUMERO,LINHADIGITAVEL,DATAVENCIMENTO,VLRTITULO,SEUNUMERO,CODESPECIEDOC,DATAEMISSAO,QTDEDIASPROTESTO,DATALIMPAGTO,
	TIPOPAGTO,INDTITULONEGOCIADO,VLRABATIMENTO,CODMORA,DATAMORA,VLRPERCMORA,CODMULTA,DATAMULTA,VLRPERCMULTA,CODDESCONTO01,
	DATADESCONTO01,VLRPERCDESCONTO01,CODDESCONTO02,DATADESCONTO02,VLRPERCDESCONTO02,CODDESCONTO03,DATADESCONTO03,VLRPERCDESCONTO03,
	ACEITE,DATAACEITE,CODSITUACAO,TIPOBAIXA,SITPAGAMENTO,VLRMINTITULO,VLRMAXTITULO,TIPOPESTERCEIRO,CNPJ_CPF_TERCEIRO,CODSISLEGADO,
	DTHRSITTITULO,INDALTERAVALOR,TIPOCALCULO,NOMEFANTASIACEDENTE,NOMEFANTASIACEDENTEORI,NOMEFANTASIASACADO,NUMCODBARRAS,NUMPARCELA,
	QTDPARCELA,INDBLOQUEIO,INDPARCIAL,QTDPAGTO,INDVALORPERC_MIN,INDVALORPERC_MAX,ISPBCEDENTE,TIPOAUTRECDIVERGENTE,ISPBSACADA,
	CANALPAGTO,MEIOPAGTO,SITPAGAMENTOCIP,ULTNUMREFCADTIT,ULTNUMSEQCADTIT,ULTNUMREFBAIXAOPERAC,ULTNUMSEQBAIXAOPERAC,ULTNUMREFBAIXAEFET,
	ULTNUMSEQBAIXAEFET,ULTNUMREFACEITE,ULTNUMSEQACEITE,ULTNUMREFTERC,ULTNUMSEQTERC,SEQMENSAGEM,TEXTO,SEQFATURA,CODMODELO,SEQDETANTES,
	SEQDETDEPOIS,CABECALHO,TPDADOS,SEQMODELO,NUMNOTAFISCAL,VLRNOTAFISCAL,DATAEMISSAONOTA,NUMIDENTCBAIXAOPERAC,NUMREFBAIXAOPERAC,
	TIPOBAIXAOPERACIONAL,DATABAIXAOPERACIONAL,VLRBAIXAOPERACIONAL,TIPOPESPORTADOR,CNPJ_CPF_PORTADOR,
	NOME_PORTADOR,
	TIPOPESAGREGADOR,CNPJ_CPF_AGREGADOR,NOMEAGREGADOR,ISPBINICIADORPAGTO,AGENCIARECEBEDORA,
	DATAHORARECBTTITULO,
	DATAHORACANCEL,INDCONTINGENCIA,
	ORIGEMCANCELAMENTO,NUMIDENTCBAIXAEFET,NUMREFBAIXAEFET,DATABAIXAEFETIVA,VLRBAIXAEFETIVA,TIPOBAIXAEFETIVA,DATACALCULO,VLRMORA,
	VLRMULTA,VLRDESCONTO,VLRCOBRAR,TIPOPESTERC,CNPJ_CPF_TERC,NUMIDENTCTERC,NUMREFTERC,TIPOPESAUTORIZADOR,CNPJ_CPF_AUTORIZADOR '
	
	SET @COMANDO_AUX_ACEITE = ',
	situacaopedido,codretorno,SEQINCLUSAO '
	
	SET @COMANDO_AUX_ACEITE_tipopesquisaaceite_null = ',
	null,null,null '
	
	SET @COMANDO_AUX_INSERT = @COMANDO_AUX + @COMANDO_AUX_ACEITE
	if @FLAG_ACEITE = 0
	begin
		SET @COMANDO_AUX_SELECT = @COMANDO_AUX + @COMANDO_AUX_ACEITE_tipopesquisaaceite_null
	end
	else 
	begin
		SET @COMANDO_AUX_SELECT = @COMANDO_AUX_INSERT
	end
	/*
	if @FLAG_ACEITE = 0
	begin 
		SET @COMANDO_AUX = @COMANDO_AUX + @COMANDO_AUX_ACEITE_tipopesquisaaceite_null
	end*/
	
	set @COMANDO = 'select ' + @COMANDO_AUX + @COMANDO_AUX_ACEITE

	set @FROM = ' FROM #TEMP_TITULOS_FILTRO '

	--SET @PARAMETROS = ''
	
	/*SET @DROP = ' DROP TABLE #TEMP_TITULOS_FILTRO_AUX '
	
	IF EXISTS (SELECT * FROM sys.objects WHERE name = '#TEMP_TITULOS_FILTRO_AUX')
	BEGIN
		EXECUTE SP_EXECUTESQL @DROP, 
				  @PARAMETROS,
					@CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO, 
					@NUMIDENTCDDA = @NUMIDENTCDDA,
					@TIPOPESQUISA = @TIPOPESQUISA,
					@CODCONDICAO = @CODCONDICAO, 
					@TIPOPESCEDENTE = @TIPOPESCEDENTE, 
					@CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE,
					@DATAVENCIMENTOINI = @DATAVENCIMENTOINI,
					@DATAVENCIMENTOFIM = @DATAVENCIMENTOFIM,
					@CODSISLEGADO = @CODSISLEGADO,
					@P_TIPOPESQUISAACEITE = @P_TIPOPESQUISAACEITE
	END*/

	if @debugging = 1 
	begin
		select * FROM #TEMP_TITULOS_FILTRO
		SELECT * FROM #TEMP_TITULOS_FILTRO_AUX
	end		

	--SELECT
	IF @P_TIPOPESQUISAACEITE IS NOT NULL AND @P_TIPOPESQUISAACEITE <> ''
	BEGIN
		--ACEITE = '' OU 'S' OU NULL 
		IF @P_TIPOPESQUISAACEITE = 'NN'
		BEGIN

			--ACEITE IGUAL A 'S'
			
			SET @COMANDO = ' INSERT INTO #TEMP_TITULOS_FILTRO_AUX ( ' + @COMANDO_AUX_INSERT + ' ) SELECT ' + @COMANDO_AUX_SELECT + ' FROM #TEMP_TITULOS_FILTRO WHERE ACEITE = ''S'' ' 
			EXECUTE SP_EXECUTESQL @COMANDO, 
				@PARAMETROS,
					@CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO, 
					@NUMIDENTCDDA = @NUMIDENTCDDA,
					@TIPOPESQUISA = @TIPOPESQUISA,
					@CODCONDICAO = @CODCONDICAO, 
					@TIPOPESCEDENTE = @TIPOPESCEDENTE, 
					@CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE,
					@DATAVENCIMENTOINI = @DATAVENCIMENTOINI,
					@DATAVENCIMENTOFIM = @DATAVENCIMENTOFIM,
					@CODSISLEGADO = @CODSISLEGADO,
					@P_TIPOPESQUISAACEITE = @P_TIPOPESQUISAACEITE
			
			if @debugging = 1 
			begin 
				select @COMANDO as comando_NN_NULL_S
				SELECT * FROM #TEMP_TITULOS_FILTRO_AUX
			end
				
			--UNION ALL ACEITE = ''
			SET @COMANDO = ' INSERT INTO #TEMP_TITULOS_FILTRO_AUX ( ' + @COMANDO_AUX_INSERT + ' ) SELECT ' + @COMANDO_AUX_SELECT + ' FROM #TEMP_TITULOS_FILTRO WHERE ACEITE = '''' ' 
			EXECUTE SP_EXECUTESQL @COMANDO, 
				@PARAMETROS,
					@CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO, 
					@NUMIDENTCDDA = @NUMIDENTCDDA,
					@TIPOPESQUISA = @TIPOPESQUISA,
					@CODCONDICAO = @CODCONDICAO, 
					@TIPOPESCEDENTE = @TIPOPESCEDENTE, 
					@CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE,
					@DATAVENCIMENTOINI = @DATAVENCIMENTOINI,
					@DATAVENCIMENTOFIM = @DATAVENCIMENTOFIM,
					@CODSISLEGADO = @CODSISLEGADO,
					@P_TIPOPESQUISAACEITE = @P_TIPOPESQUISAACEITE

			if @debugging = 1 
			begin
				select @COMANDO as comando_NN_blank
				SELECT * FROM #TEMP_TITULOS_FILTRO_AUX
			end
				
			--UNION ALL ACEITE = NULL
			SET @COMANDO = ' INSERT INTO #TEMP_TITULOS_FILTRO_AUX ( ' + @COMANDO_AUX_INSERT + ' ) SELECT ' + @COMANDO_AUX_SELECT + ' FROM #TEMP_TITULOS_FILTRO WHERE ACEITE IS NULL ' 
			EXECUTE SP_EXECUTESQL @COMANDO, 
				@PARAMETROS,
					@CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO, 
					@NUMIDENTCDDA = @NUMIDENTCDDA,
					@TIPOPESQUISA = @TIPOPESQUISA,
					@CODCONDICAO = @CODCONDICAO, 
					@TIPOPESCEDENTE = @TIPOPESCEDENTE, 
					@CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE,
					@DATAVENCIMENTOINI = @DATAVENCIMENTOINI,
					@DATAVENCIMENTOFIM = @DATAVENCIMENTOFIM,
					@CODSISLEGADO = @CODSISLEGADO,
					@P_TIPOPESQUISAACEITE = @P_TIPOPESQUISAACEITE
			
			if @debugging = 1
			begin
				select @COMANDO as comando_NN_NULL
				SELECT * FROM #TEMP_TITULOS_FILTRO_AUX
			end
			
			if @debugging = 1 
				select * FROM #TEMP_TITULOS_FILTRO	
			
			--SELECT DE SAIDA
			SET @COMANDO = ' SELECT * FROM #TEMP_TITULOS_FILTRO_AUX ' 			
		END
		--ACEITE IGUAL A '' OU NULL
		else IF @P_TIPOPESQUISAACEITE = 'B'
		BEGIN
			
			--ACEITE = ''
			SET @COMANDO = ' INSERT INTO #TEMP_TITULOS_FILTRO_AUX ( ' + @COMANDO_AUX_INSERT + ' ) SELECT ' + @COMANDO_AUX_SELECT + ' FROM #TEMP_TITULOS_FILTRO WHERE ACEITE = '''' ' 
			EXECUTE SP_EXECUTESQL @COMANDO, 
				@PARAMETROS,
					@CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO, 
					@NUMIDENTCDDA = @NUMIDENTCDDA,
					@TIPOPESQUISA = @TIPOPESQUISA,
					@CODCONDICAO = @CODCONDICAO, 
					@TIPOPESCEDENTE = @TIPOPESCEDENTE, 
					@CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE,
					@DATAVENCIMENTOINI = @DATAVENCIMENTOINI,
					@DATAVENCIMENTOFIM = @DATAVENCIMENTOFIM,
					@CODSISLEGADO = @CODSISLEGADO,
					@P_TIPOPESQUISAACEITE = @P_TIPOPESQUISAACEITE

			--UNION ALL ACEITE = NULL
			SET @COMANDO = ' INSERT INTO #TEMP_TITULOS_FILTRO_AUX ( ' + @COMANDO_AUX_INSERT + ' ) SELECT ' + @COMANDO_AUX_SELECT + ' FROM #TEMP_TITULOS_FILTRO WHERE ACEITE IS NULL ' 
			EXECUTE SP_EXECUTESQL @COMANDO, 
				@PARAMETROS,
					@CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO, 
					@NUMIDENTCDDA = @NUMIDENTCDDA,
					@TIPOPESQUISA = @TIPOPESQUISA,
					@CODCONDICAO = @CODCONDICAO, 
					@TIPOPESCEDENTE = @TIPOPESCEDENTE, 
					@CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE,
					@DATAVENCIMENTOINI = @DATAVENCIMENTOINI,
					@DATAVENCIMENTOFIM = @DATAVENCIMENTOFIM,
					@CODSISLEGADO = @CODSISLEGADO,
					@P_TIPOPESQUISAACEITE = @P_TIPOPESQUISAACEITE

			--SELECT DE SAIDA
			SET @COMANDO = ' SELECT * FROM #TEMP_TITULOS_FILTRO_AUX ' 			
		END
		--ACEITE ESPECÍFICO ('S', 'N', 'X')
		ELSE
		BEGIN
		
			SET @COMANDO = @COMANDO + ' FROM #TEMP_TITULOS_FILTRO ' + ' WHERE ACEITE = @P_TIPOPESQUISAACEITE '
		END
	END
	else
	begin
		set @comando = @comando + @from
	end
	
	--ORDER BY
		--TIPOREGISTRO ASC
	IF @P_ORDEM = 'C'
	BEGIN
		set @COMANDO = @COMANDO + ' ORDER BY CNPJ_CPF_SACADO, NUMIDENTCDDA, TIPOREGISTRO, SEQFATURA, SEQMENSAGEM, SEQDETANTES, SEQDETDEPOIS, NUMNOTAFISCAL, DATACALCULO '
	END
		--TIPOREGISTRO DESC
	ELSE
	BEGIN
		set @COMANDO = @COMANDO + ' ORDER BY CNPJ_CPF_SACADO, NUMIDENTCDDA, TIPOREGISTRO DESC, SEQFATURA, SEQMENSAGEM, SEQDETANTES, SEQDETDEPOIS, NUMNOTAFISCAL, DATACALCULO '
	END

	if @debugging = 1 
		select @P_TIPOPESQUISAACEITE as tipopesquisa_final, @comando as comando_final

	--SELECT RESULTADO FINAL
	
	EXECUTE SP_EXECUTESQL @COMANDO, 
			@PARAMETROS,
				@CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO, 
				@NUMIDENTCDDA = @NUMIDENTCDDA,
				@TIPOPESQUISA = @TIPOPESQUISA,
				@CODCONDICAO = @CODCONDICAO, 
				@TIPOPESCEDENTE = @TIPOPESCEDENTE, 
				@CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE,
				@DATAVENCIMENTOINI = @DATAVENCIMENTOINI,
				@DATAVENCIMENTOFIM = @DATAVENCIMENTOFIM,
				@CODSISLEGADO = @CODSISLEGADO,
				@P_TIPOPESQUISAACEITE = @P_TIPOPESQUISAACEITE

END
GO
--------------------------------------------------------------------------------------------------------

INSERT INTO VERSAO_SISTEMA (
	[VERSAO],
	[NOMESCRIPT],
	[CODUSUARIO],
	[DATAATU])
SELECT 
	'V15_01_1_01B', 
	'P_PESQUISA_TITULO_POR_SACADO', 
	SYSTEM_USER, 
	GETDATE() 
GO