USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_ALTERAR_MANUT_PREPARADA_ENVIO')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_ALTERAR_MANUT_PREPARADA_ENVIO AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE [dbo].[SP_ALTERAR_MANUT_PREPARADA_ENVIO](
	@ERRO INT OUTPUT
) AS
BEGIN
	
	/*
		18/03/2019 - EDUARDOK, RFAQUINI - RETIRADO VALIDAÇÃO DE @FLAGDIAUTIL
		
		20/05/2019 - RFAQUINI, ELIANE	- ALTERADA SELEÇÃO INICIAL PARA DESCONSIDERAR MANUTENÇÕES COM TIPOMANUTENCAOTIT = BAIXA
											CASO O SISTEMA LEGADO ENVIE PARA O DDA UMA BAIXA COM DATAPAGTO SUPERIOR A DATA DO SISTEMA DDA, 
											O DDA DEVE IGNORAR ESSA MANUTENÇÃO
		
		07/08/2019 - EDUARDOK, RFAQUINI - CORREÇÃO DA VALIDAÇÃO DO CAMPO DATAPAGTOBAIXA: DESCONSIDERA O HORÁRIO POIS ISSO AFETAVA A COMPARAÇÃO DATAPAGTOBAIXA <= @DATAPROCESSAMENTO
		
		16/08/2019 - EDUARDOK - REMOVIDO VALIDAÇÃO, EVITAR DEADLOCKS
		
		04/02/2021 - ELIANE, RFAQUINI - SEPARAÇÃO DA ATUALIZAÇÃO DO CAMPO NUMREFBAIXAOPERAC PARA TITULOS QUE NÃO ACEITAM PAGAMENTO PARCIAL (QUE NÃO SEJAM CARTÃO)
		
		27/02/2023 - RFAQUINI - EXCLUSÃO DE CODEVENTOS 8116 (ADDA116/DDA0116) (CATÁLOGO 5.06 - Modernização da Cobrança)
								POIS NÃO TEM NUMIDENTCDDA PARA REALIZAR OS JOINS NA #TEMP_MANUT_TITULOS_SEL
	*/

	DECLARE 
		@DATAPROCESSAMENTO DATETIME, 
		@DATAULTPROCESSAMENTO DATETIME, 
		@COUNT INT, 
		@ULTNUMPEDIDORESERVADO NUMERIC(10), 
		@DATAHORAEXEC DATETIME, 
		@P_SQLERRO INTEGER, 
		@LOG_ERRO VARCHAR(8000)
	SELECT 
		@DATAPROCESSAMENTO = DATAPROCESSAMENTO, 
		@DATAULTPROCESSAMENTO = DATAULTPROCESSAMENTO 
	FROM PARAMETROS
	
	-- UM ULTIMO TRATAMENTO PARA TODAS AS MANUTS LIBERADAS PARA ENVIO: SE ESTIVERMOS EM FIM DE SEMANA/FERIADO, TUDO O QUE TIVER SIDO SEPARADO PARA GERACAO DE ARQUIVO SERA ALTERADO PARA MENSAGEM
	-- DEVIDO A GRADE ESPECIAL DA CIP

	-- TITULOS
	----------
	SELECT @DATAHORAEXEC = GETDATE()

	--- TROCAR PEDIDOS QUE NÃO SÃO INCLUSÃO PARA ROBO
	UPDATE MANUT_TITULOS SET FORMAENVIO = 'R'
	WHERE SITUACAOPEDIDO = '0' 
	AND DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND TIPOMANUTENCAOTIT <> 'I' 
	AND FORMAENVIO = 'P'
	
	IF @@ERROR <> 0
		GOTO TRATAERRO
	
	-- SE ALGUM PROCESSO ANTERIOR NAO FOI COMPLETADO POR MAIS DE 3 MINUTOS, LIBERAR ESSES REGISTROS (SITUACAO "SOLICITADO")
	UPDATE MANUT_TITULOS SET 
		SPID = NULL, 
		DATAHORAPROCESSO = NULL,
		AGUARDAPENDENTE = CASE
			WHEN AGUARDAPENDENTE = 'N' 
				THEN NULL
			ELSE AGUARDAPENDENTE
		END
	WHERE SITUACAOPEDIDO = '0' 
	AND DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SPID IS NOT NULL 
	AND DATAHORAPROCESSO IS NOT NULL 
	AND @DATAHORAEXEC > DATEADD(MINUTE, 3, DATAHORAPROCESSO)
	
	IF @@ERROR <> 0
		GOTO TRATAERRO
	
	-- RESERVAR PEDIDOS PARA ESSE PROCESSO 
	/*UPDATE MANUT_TITULOS SET 
		SPID = @@SPID, 
		DATAHORAPROCESSO = @DATAHORAEXEC, 
		AGUARDAPENDENTE = 'S' 
	WHERE DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SITUACAOPEDIDO = '0'
	AND FORMAENVIO IN ('R', 'M')
	AND SPID IS NULL 
	AND DATAHORAPROCESSO IS NULL*/
	--20/05/2019 - rfaquini - alterada seleção inicial para desconsiderar manutenções com TIPOMANUTENCAOTIT = baixa[...]
	--AND TIPOMANUTENCAOTIT <> 'B'
	--27/02/2023 - ELIANE, RFAQUINI - EXCLUSÃO DE CODEVENTOS 8116 (ADDA116/DDA0116) (CATÁLOGO 5.06 - Modernização da Cobrança)
	--AND CODEVENTO <> '8116'

	--27/02/2023 - ELIANE, RFAQUINI - EXCLUSÃO DE CODEVENTOS 8116 (ADDA116/DDA0116) (CATÁLOGO 5.06 - Modernização da Cobrança)
	UPDATE MANUT_TITULOS SET 
		SPID = @@SPID, 
		DATAHORAPROCESSO = @DATAHORAEXEC, 
		AGUARDAPENDENTE = CASE
			WHEN CODEVENTO = '8116'
				THEN 'N' 
			ELSE 
				'S' 
		END
	WHERE DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SITUACAOPEDIDO = '0'
	AND FORMAENVIO IN ('R', 'M')
	AND SPID IS NULL 
	AND DATAHORAPROCESSO IS NULL

 	IF @@ERROR <> 0
		GOTO TRATAERRO

	-- RESERVAR PEDIDOS PARA ESSE PROCESSO 
	/*UPDATE MANUT_TITULOS SET SPID = @@SPID, DATAHORAPROCESSO = @DATAHORAEXEC, AGUARDAPENDENTE = 'S' 
	WHERE DATAPEDIDO >= @DATAULTPROCESSAMENTO AND DATAPEDIDO <= @DATAPROCESSAMENTO AND SITUACAOPEDIDO = '0'
	AND FORMAENVIO IN ('R', 'M')
	AND SPID IS NULL AND DATAHORAPROCESSO IS NULL
		--20/05/2019 - rfaquini - alterada seleção inicial para desconsiderar manutenções com TIPOMANUTENCAOTIT = baixa[...]
	AND TIPOMANUTENCAOTIT = 'B'
	--07/08/2019
	AND CAST(DATAPAGTOBAIXA AS DATE) <= @DATAPROCESSAMENTO*/--16/08/2019 - removido validação, evitar deadlocks

 	IF @@ERROR <> 0
		GOTO TRATAERRO

	-- MARCAR DATAHORA PARA PRIORIDADE NOVA 
	UPDATE MANUT_TITULOS SET 
		DATAHORAPROCESSO = @DATAHORAEXEC, 
		AGUARDAPENDENTE = 'S'
	WHERE DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SITUACAOPEDIDO IN ('0', '4')
	AND FORMAENVIO = 'P'
	AND SPID IS NULL 
	AND DATAHORAPROCESSO IS NULL

	IF @@ERROR <> 0
		GOTO TRATAERRO

	-- MARCAR PROCESSO E NOVA HORA PARA PRIORIDADE PARADA (MAIOR QUE 1 MINUTO) E MUDAR PARA ROBO 
	UPDATE MANUT_TITULOS SET 
		SPID = @@SPID, 
		DATAHORAPROCESSO = @DATAHORAEXEC, 
		AGUARDAPENDENTE = 'S', 
		FORMAENVIO = 'R'
	WHERE DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SITUACAOPEDIDO IN ('0', '4')
	AND FORMAENVIO = 'P'
	AND SPID IS NULL 
	AND DATAHORAPROCESSO IS NOT NULL
	AND @DATAHORAEXEC > DATEADD(MINUTE, 1, DATAHORAPROCESSO)

	IF @@ERROR <> 0
		GOTO TRATAERRO

	-- SELECIONA PEDIDOS QUE NAO SERAO CONTROLADOS
	SELECT 
		CONVERT(NUMERIC(17), NULL) SEQINCLUSAO,
		IDENTITY (INT, 1,1) CONTADOR,
		CONVERT(NUMERIC(10), NULL) NUMPEDIDO 
	INTO #TEMP_MANUT_TITULOS_DIRETO
	WHERE 1 = 0

	IF @@ERROR <> 0
		GOTO TRATAERRO	

	INSERT INTO #TEMP_MANUT_TITULOS_DIRETO (SEQINCLUSAO)
	SELECT M1.SEQINCLUSAO 
	FROM MANUT_TITULOS M1 
	WHERE M1.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND M1.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND M1.SPID = @@SPID 
	AND M1.DATAHORAPROCESSO = @DATAHORAEXEC 
	AND M1.SITUACAOPEDIDO = '0' 
	AND M1.TIPOMANUTENCAOTIT IN ('I', 'C') 
	
	--27/02/2023 - ELIANE, RFAQUINI - EXCLUSÃO DE CODEVENTOS 8116 (ADDA116/DDA0116) (CATÁLOGO 5.06 - Modernização da Cobrança)
	INSERT INTO #TEMP_MANUT_TITULOS_DIRETO (
		SEQINCLUSAO
	)
	SELECT 
		MANUT_TITULOS.SEQINCLUSAO 
	FROM MANUT_TITULOS 
	WHERE MANUT_TITULOS.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND MANUT_TITULOS.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND MANUT_TITULOS.SPID = @@SPID 
	AND MANUT_TITULOS.DATAHORAPROCESSO = @DATAHORAEXEC 
	AND MANUT_TITULOS.SITUACAOPEDIDO = '0' 
	AND MANUT_TITULOS.TIPOMANUTENCAOTIT = 'D'
	AND MANUT_TITULOS.CODEVENTO = '8116'

	--27/02/2023 - ELIANE, RFAQUINI - EXCLUSÃO DE CODEVENTOS 8116 (ADDA116/DDA0116) (CATÁLOGO 5.06 - Modernização da Cobrança)
	/*INSERT INTO #TEMP_MANUT_TITULOS_DIRETO (SEQINCLUSAO)
	SELECT M1.SEQINCLUSAO 
	FROM MANUT_TITULOS M1 
	WHERE M1.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND M1.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND M1.SPID = @@SPID 
	AND M1.DATAHORAPROCESSO = @DATAHORAEXEC 
	AND M1.SITUACAOPEDIDO = '0' 
	AND M1.codevento = '8116'*/

	IF @@ERROR <> 0
		GOTO TRATAERRO
	
	SELECT @COUNT = COUNT(*) 
	FROM #TEMP_MANUT_TITULOS_DIRETO
	
	IF @@ERROR <> 0
		GOTO TRATAERRO
	
	IF @COUNT > 0 
	BEGIN
		-- AVANCA O ULTIMO NUMERO DE PEDIDO NA QUANTIDADE DE PEDIDOS RESERVADOS	
		
		EXEC SP_GERA_NUMPEDIDO @COUNT, @ULTNUMPEDIDORESERVADO OUT
		
		IF @@ERROR <> 0
			GOTO TRATAERRO
		
		-- ULTRAPASSOU O NUMERO MAXIMO DE TENTATIVAS PARA RESERVAR O NUMERO DE PEDIDO
		IF(@ULTNUMPEDIDORESERVADO = -1)
		GOTO TRATAERRO
	

		-- NUMERA OS PEDIDOS
		UPDATE #TEMP_MANUT_TITULOS_DIRETO SET 
			NUMPEDIDO = (@ULTNUMPEDIDORESERVADO - (CONTADOR - 1))
		
		IF @@ERROR <> 0
			GOTO TRATAERRO	
		
		-- PEDIDOS ANTES SOLICITADOS, AGORA NUMERADOS, PREPARADOS PARA ENVIO E COM SEQUENCIAIS ATUALIZADOS
		UPDATE MT SET 
			NUMPEDIDO = TEMP.NUMPEDIDO, 
			SITUACAOPEDIDO = '4', 
			AGUARDAPENDENTE = 'N', 
			NUMPEDIDOPEND = NULL
		FROM MANUT_TITULOS MT
		INNER JOIN #TEMP_MANUT_TITULOS_DIRETO TEMP 
		ON (MT.SEQINCLUSAO = TEMP.SEQINCLUSAO)
		WHERE MT.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
		AND MT.DATAPEDIDO <= @DATAPROCESSAMENTO 
		AND MT.SPID = @@SPID 
		AND MT.DATAHORAPROCESSO = @DATAHORAEXEC 
		
		IF @@ERROR <> 0
			GOTO TRATAERRO	
	
	END	
	
	-- SELECIONA PEDIDOS 8400
	SELECT
		CONVERT(NUMERIC(19), NULL) NUMIDENTCDDA,
		CONVERT(NUMERIC(17), NULL) SEQINCLUSAO,
		CONVERT(DATETIME, NULL) DATAPEDIDO,
		CONVERT(DATETIME, NULL) DATALEGADO,
		CONVERT(VARCHAR (10), NULL) CODSISLEGADO,
		CONVERT(VARCHAR (35), NULL) NUMCTRLLEGADO
	INTO #TEMP_MANUT_TITULOS_8400
	WHERE 1 = 0
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- SELECIONA PEDIDOS 8400 PARADOS
	INSERT INTO #TEMP_MANUT_TITULOS_8400 (
		NUMIDENTCDDA, SEQINCLUSAO, DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO
	)
	SELECT 
		M1.NUMIDENTCDDA, M1.SEQINCLUSAO, M1.DATAPEDIDO, M1.DATALEGADO, M1.CODSISLEGADO, M1.NUMCTRLLEGADO 
	FROM MANUT_TITULOS M1 
	WHERE M1.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND M1.DATAPEDIDO <= @DATAPROCESSAMENTO 
	--AND M1.SPID = @@SPID 
	--AND M1.DATAHORAPROCESSO = @DATAHORAEXEC 
	AND M1.SITUACAOPEDIDO IN ('0','1','2','4') 
	AND M1.NUMIDENTCDDA IS NOT NULL
	AND M1.CODEVENTO = '8400'
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- RETIRA PEDIDOS 8400 MAIS NOVOS 
	DELETE M1 
	FROM #TEMP_MANUT_TITULOS_8400 M1
	WHERE M1.DATAPEDIDO = (SELECT MAX (M2.DATAPEDIDO) 
		FROM #TEMP_MANUT_TITULOS_8400 M2
		WHERE M1.NUMIDENTCDDA = M2.NUMIDENTCDDA)
		
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- CANCELA PEDIDOS 8400 MAIS ANTIGOS
	UPDATE MANUT_TITULOS SET 
		SITUACAOPEDIDO = '3' 
	FROM MANUT_TITULOS MANUT
	INNER JOIN #TEMP_MANUT_TITULOS_8400 TEMP ON 
		(MANUT.DATAPEDIDO = TEMP.DATAPEDIDO
		AND MANUT.DATALEGADO = TEMP.DATALEGADO
		AND MANUT.NUMCTRLLEGADO = TEMP.NUMCTRLLEGADO
		AND MANUT.CODSISLEGADO = TEMP.CODSISLEGADO)
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	 -- SELECIONA PEDIDOS QUE SERAO CONTROLADOS
	SELECT
		CONVERT(NUMERIC(19), NULL) NUMIDENTCDDA,
		CONVERT(NUMERIC(17), NULL) SEQINCLUSAO
	INTO #TEMP_MANUT_TITULOS
	WHERE 1 = 0
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	INSERT INTO #TEMP_MANUT_TITULOS (
		NUMIDENTCDDA, SEQINCLUSAO
	)
	SELECT 
		M1.NUMIDENTCDDA, MIN (M1.SEQINCLUSAO) 
	FROM MANUT_TITULOS M1 
	WHERE M1.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND M1.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND M1.SPID = @@SPID 
	AND M1.DATAHORAPROCESSO = @DATAHORAEXEC 
	AND M1.SITUACAOPEDIDO = '0' 
	AND M1.NUMIDENTCDDA IS NOT NULL
	GROUP BY M1.NUMIDENTCDDA
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- NAO ENVIA PEDIDO DE TITULO QUE CONTEM PEDIDO PENDENTE	
	DELETE TEMP 
	FROM #TEMP_MANUT_TITULOS TEMP 
	INNER JOIN MANUT_TITULOS M1 
		ON (TEMP.NUMIDENTCDDA = M1.NUMIDENTCDDA)
	WHERE M1.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND M1.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND M1.SITUACAOPEDIDO IN ('1', '2', '4') 
	AND TEMP.SEQINCLUSAO <> M1.SEQINCLUSAO
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- MANTEM O PEDIDO MAIS ANTIGO, CASO TENHA MAIS DE UM PEDIDO SOLICITADO DO MESMO TITULO
	DELETE TEMP 
	FROM #TEMP_MANUT_TITULOS TEMP 
	INNER JOIN MANUT_TITULOS M1 
		ON (TEMP.NUMIDENTCDDA = M1.NUMIDENTCDDA)
	WHERE M1.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND M1.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND M1.SITUACAOPEDIDO = '0' 
	AND TEMP.SEQINCLUSAO > M1.SEQINCLUSAO
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- MESMO TRATAMENTO, AGORA PARA PEDIDOS NOVOS EM SITUACAO DE SOLICITADOS (AINDA SEM MARCACAO DE PENDENCIA)
	SELECT
		CONVERT(VARCHAR(19), NULL) NUMIDENTCDDA,
		CONVERT(NUMERIC(17), NULL) SEQINCLUSAO,
		IDENTITY (INT, 1,1) CONTADOR,
		CONVERT(NUMERIC(10), NULL) NUMPEDIDO,
		CONVERT(NUMERIC(19), NULL) ULTNUMREFCADTIT,
		CONVERT(NUMERIC(19), NULL) ULTNUMREFBAIXAOPERAC,
		CONVERT(NUMERIC(19), NULL) ULTNUMREFBAIXAEFET,
		CONVERT(NUMERIC(19), NULL) ULTNUMREFACEITE,
		CONVERT(NUMERIC(19), NULL) ULTNUMREFTERC
	INTO #TEMP_MANUT_TITULOS_SEL
	WHERE 1 = 0
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	INSERT INTO #TEMP_MANUT_TITULOS_SEL (
		NUMIDENTCDDA, SEQINCLUSAO
	)
	SELECT 
		NUMIDENTCDDA, SEQINCLUSAO 
	FROM #TEMP_MANUT_TITULOS
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	UPDATE SEL SET 
		ULTNUMREFCADTIT = TITULOS.ULTNUMREFCADTIT,
		ULTNUMREFACEITE = TITULOS.ULTNUMREFACEITE,
		ULTNUMREFTERC = TITULOS.ULTNUMREFTERC,
		ULTNUMREFBAIXAOPERAC = TITULOS.ULTNUMREFBAIXAOPERAC,
		ULTNUMREFBAIXAEFET = TITULOS.ULTNUMREFBAIXAEFET
	FROM #TEMP_MANUT_TITULOS_SEL SEL 
	INNER JOIN TITULOS 
	ON (SEL.NUMIDENTCDDA = TITULOS.NUMIDENTCDDA)
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	SELECT @COUNT = COUNT(*) 
	FROM #TEMP_MANUT_TITULOS_SEL
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	IF @COUNT > 0 
	BEGIN
	
		-- AVANCA O ULTIMO NUMERO DE PEDIDO NA QUANTIDADE DE PEDIDOS RESERVADOS	
		EXEC SP_GERA_NUMPEDIDO @COUNT, @ULTNUMPEDIDORESERVADO OUT
		
		IF @@ERROR <> 0
			GOTO TRATAERRO	

		-- ULTRAPASSOU O NUMERO MAXIMO DE TENTATIVAS PARA RESERVAR O NUMERO DE PEDIDO
		IF(@ULTNUMPEDIDORESERVADO = -1)
			GOTO TRATAERRO
	
		-- NUMERA OS PEDIDOS
		UPDATE #TEMP_MANUT_TITULOS_SEL SET 
			NUMPEDIDO = (@ULTNUMPEDIDORESERVADO - (CONTADOR - 1))
		
		IF @@ERROR <> 0
			GOTO TRATAERRO	

		-- PEDIDOS ANTES SOLICITADOS, AGORA NUMERADOS, PREPARADOS PARA ENVIO E COM SEQUENCIAIS ATUALIZADOS
		UPDATE MT SET 
			NUMPEDIDO = TEMP.NUMPEDIDO, 
			SITUACAOPEDIDO = '4', 
			AGUARDAPENDENTE = 'N', 
			NUMPEDIDOPEND = NULL, 
			NUMREFCADTIT = TEMP.ULTNUMREFCADTIT,
			NUMREFTERC = TEMP.ULTNUMREFTERC,
			NUMREFACEITE = TEMP.ULTNUMREFACEITE,
			--04/02/2021 - ELIANE, RFAQUINI - SEPARAÇÃO DA ATUALIZAÇÃO DO CAMPO NUMREFBAIXAOPERAC PARA TITULOS QUE NÃO ACEITAM PAGAMENTO PARCIAL (QUE NÃO SEJAM CARTÃO)
			--NUMREFBAIXAOPERAC = TEMP.ULTNUMREFBAIXAOPERAC,
			NUMREFBAIXAEFET = TEMP.ULTNUMREFBAIXAEFET
		FROM MANUT_TITULOS MT
		INNER JOIN #TEMP_MANUT_TITULOS_SEL TEMP 
		ON (MT.SEQINCLUSAO = TEMP.SEQINCLUSAO)
		WHERE MT.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
		AND MT.DATAPEDIDO <= @DATAPROCESSAMENTO 
		AND MT.SPID = @@SPID 
		AND MT.DATAHORAPROCESSO = @DATAHORAEXEC
		
		IF @@ERROR <> 0
			GOTO TRATAERRO	
		
		--04/02/2021 - ELIANE, RFAQUINI - SEPARAÇÃO DA ATUALIZAÇÃO DO CAMPO NUMREFBAIXAOPERAC PARA TITULOS QUE NÃO ACEITAM PAGAMENTO PARCIAL (QUE NÃO SEJAM CARTÃO)
		UPDATE MT SET 
			NUMREFBAIXAOPERAC = TEMP.ULTNUMREFBAIXAOPERAC
		FROM MANUT_TITULOS MT
		INNER JOIN #TEMP_MANUT_TITULOS_SEL TEMP 
		ON (MT.SEQINCLUSAO = TEMP.SEQINCLUSAO)
		WHERE MT.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
		AND MT.DATAPEDIDO <= @DATAPROCESSAMENTO 
		AND MT.SPID = @@SPID 
		AND MT.DATAHORAPROCESSO = @DATAHORAEXEC
		AND MT.INDPARCIAL = 'N'
		
		IF @@ERROR <> 0
			GOTO TRATAERRO
		
	END	

	SELECT
		GETDATE() DATAPEDIDO,
		GETDATE() DATALEGADO,
		CONVERT(VARCHAR(10), '') CODSISLEGADO,
		CONVERT(VARCHAR(35), '') NUMCTRLLEGADO,
		CONVERT(NUMERIC(19), 0) NUMIDENTCDDA,
		CONVERT(NUMERIC(10), 0) NUMPEDIDO,
		CONVERT(NUMERIC(17), 0) SEQINCLUSAO,
		CONVERT(NUMERIC(17), 0) NUMPEDIDOPEND
	INTO #TEMP_TITULOS_AGUARDANDO
	WHERE 1 = 0
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- AQUILO QUE ESTA AGUARDANDO OUTROS PEDIDOS PENDENTES...
	INSERT INTO #TEMP_TITULOS_AGUARDANDO (
		DATAPEDIDO, DATALEGADO, NUMCTRLLEGADO, CODSISLEGADO, NUMIDENTCDDA, NUMPEDIDO, SEQINCLUSAO
	)
	SELECT 
		DATAPEDIDO, DATALEGADO, NUMCTRLLEGADO, CODSISLEGADO, NUMIDENTCDDA, NUMPEDIDO, SEQINCLUSAO FROM MANUT_TITULOS
	WHERE DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SITUACAOPEDIDO = '0' 
	AND AGUARDAPENDENTE = 'S'
	AND SPID = @@SPID
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	/*CREATE INDEX IDX_TEMP_TITULOS_AGUARDANDO ON #TEMP_TITULOS_AGUARDANDO (DATAPEDIDO, DATALEGADO, NUMCTRLLEGADO, CODSISLEGADO)
	IF @@ERROR <> 0
		GOTO TRATAERRO*/


	SELECT 
		CONVERT(NUMERIC(19), 0) NUMIDENTCDDA,
		CONVERT(NUMERIC(10), 0) NUMPEDIDO
	INTO #TEMP_TITULOS_PENDENTES
	WHERE 1 = 0
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- A RELACAO DESSES PEDIDOS QUE ESTAO PENDENTES....
	INSERT INTO #TEMP_TITULOS_PENDENTES (
		NUMIDENTCDDA, NUMPEDIDO
	)
	SELECT 
		TEMP.NUMIDENTCDDA, TEMP.NUMPEDIDO 
	FROM MANUT_TITULOS MANUT
	INNER JOIN #TEMP_TITULOS_AGUARDANDO TEMP 
		ON (MANUT.SITUACAOPEDIDO IN ('1', '2', '4')
		AND MANUT.NUMIDENTCDDA = TEMP.NUMIDENTCDDA
		AND MANUT.SEQINCLUSAO != TEMP.SEQINCLUSAO)			
	WHERE MANUT.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND MANUT.DATAPEDIDO <= @DATAPROCESSAMENTO 
	GROUP BY TEMP.NUMIDENTCDDA, TEMP.NUMPEDIDO
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	/*CREATE INDEX IDX_TEMP_TITULOS_PENDENTES ON #TEMP_TITULOS_PENDENTES (NUMIDENTCDDA, NUMPEDIDO)
	IF @@ERROR <> 0
		GOTO TRATAERRO*/

	-- MARCANDO NOS PEDIDOS QUE ESTAO AGUARDANDO QUAL O NUMERO DO PEDIDO PENDENTE
	UPDATE MANUT_TITULOS SET 
		NUMPEDIDOPEND = PENDENTE.NUMPEDIDO 
	FROM MANUT_TITULOS MANUT
	INNER JOIN #TEMP_TITULOS_AGUARDANDO AGUARDANDO 
		ON (MANUT.DATAPEDIDO = AGUARDANDO.DATAPEDIDO
		AND MANUT.DATALEGADO = AGUARDANDO.DATALEGADO
		AND MANUT.NUMCTRLLEGADO = AGUARDANDO.NUMCTRLLEGADO
		AND MANUT.CODSISLEGADO = AGUARDANDO.CODSISLEGADO)
	INNER JOIN #TEMP_TITULOS_PENDENTES PENDENTE 
		ON (AGUARDANDO.NUMIDENTCDDA = PENDENTE.NUMIDENTCDDA)
	WHERE MANUT.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND MANUT.DATAPEDIDO <= @DATAPROCESSAMENTO 
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- ADAPTADO ACIMA DEVIDO A PROBLEMAS DE DESEMPENHO
	/*

	UPDATE MANUT_TITULOS SET NUMPEDIDOPEND = 
		(SELECT TOP 1 P.NUMPEDIDO FROM MANUT_TITULOS P 
		 WHERE P.SITUACAOPEDIDO IN ('1', '2', '4') 
		 AND P.NUMIDENTCDDA = MT.NUMIDENTCDDA
		 AND P.SEQINCLUSAO != MT.SEQINCLUSAO) 
	FROM MANUT_TITULOS MT
	WHERE MT.DATAPEDIDO >= @DATAULTPROCESSAMENTO AND MT.DATAPEDIDO <= @DATAPROCESSAMENTO AND
	MT.SITUACAOPEDIDO = '0' AND MT.AGUARDAPENDENTE = 'S' AND MT.SPID = @@SPID

	*/

	-- BENEFICIARIO
	---------------
	SELECT @DATAHORAEXEC = GETDATE()

	-- SE ALGUM PROCESSO ANTERIOR NAO FOI COMPLETADO POR MAIS DE 3 MINUTOS, LIBERAR ESSES REGISTROS (SITUACAO "SOLICITADO")
	UPDATE MANUT_BENEFICIARIO SET 
		SPID = NULL, 
		DATAHORAPROCESSO = NULL,
		AGUARDAPENDENTE = CASE
			WHEN AGUARDAPENDENTE = 'N' 
				THEN NULL
			ELSE 
				AGUARDAPENDENTE
			END
	WHERE SITUACAOPEDIDO = '0' 
	AND DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SPID IS NOT NULL 
	AND DATAHORAPROCESSO IS NOT NULL 
	AND @DATAHORAEXEC > DATEADD(MINUTE, 3, DATAHORAPROCESSO)
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- RESERVAR PEDIDOS PARA ESSE PROCESSO E TAMBEM ALTERA TIPOENVIO PARA MENSAGEM: 1) NA CONSULTA DE BENEFICIARIO PQ NAO EXISTE POR ARQUIVO 2) EM FIM DE SEMANA POR CAUSA DA GRADE DA CIP 3) DESDE QUE NAO SEJA CARGA INICIAL (K), QUE POSSUI APENAS ARQUIVO
	UPDATE MANUT_BENEFICIARIO SET 
	SPID = @@SPID, 
	DATAHORAPROCESSO = @DATAHORAEXEC, 
	AGUARDAPENDENTE = 'S', 
	TIPOENVIO = CASE
		WHEN (TIPOMANUTENCAO != 'K') AND ISNULL(TIPOMANUTENCAO,'') = 'C' 
			THEN 'M' 
		ELSE 
			TIPOENVIO 
		END 
	WHERE DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SITUACAOPEDIDO = '0'
	AND SPID IS NULL 
	AND DATAHORAPROCESSO IS NULL
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- SELECIONA PEDIDOS QUE NAO SERAO CONTROLADOS
	SELECT 
		CONVERT(NUMERIC(17), NULL) SEQ_PEDIDO,
		IDENTITY (INT, 1,1) CONTADOR,
		CONVERT(NUMERIC(10), NULL) NUMPEDIDO
	INTO #TEMP_MANUT_BENEFICIARIO_DIRETO
	WHERE 1 = 0
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	INSERT INTO #TEMP_MANUT_BENEFICIARIO_DIRETO (SEQ_PEDIDO)
	SELECT M1.SEQ_PEDIDO 
	FROM MANUT_BENEFICIARIO M1 
	WHERE M1.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND M1.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND M1.SPID = @@SPID 
	AND M1.DATAHORAPROCESSO = @DATAHORAEXEC 
	AND M1.SITUACAOPEDIDO = '0' 
	AND M1.TIPOMANUTENCAO IN ('K','I', 'C') 
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	SELECT @COUNT = COUNT(*) 
	FROM #TEMP_MANUT_BENEFICIARIO_DIRETO
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	IF @COUNT > 0 
	BEGIN

		-- AVANCA O ULTIMO NUMERO DE PEDIDO NA QUANTIDADE DE PEDIDOS RESERVADOS	
		EXEC SP_GERA_NUMPEDIDO @COUNT, @ULTNUMPEDIDORESERVADO OUT
 	
		IF @@ERROR <> 0
			GOTO TRATAERRO	

		-- ULTRAPASSOU O NUMERO MAXIMO DE TENTATIVAS PARA RESERVAR O NUMERO DE PEDIDO
		IF(@ULTNUMPEDIDORESERVADO = -1)
			GOTO TRATAERRO
	
		-- NUMERA OS PEDIDOS
		UPDATE #TEMP_MANUT_BENEFICIARIO_DIRETO SET 
			NUMPEDIDO = (@ULTNUMPEDIDORESERVADO - (CONTADOR - 1))
 	
		IF @@ERROR <> 0
			GOTO TRATAERRO	
	
		-- PEDIDOS ANTES SOLICITADOS, AGORA NUMERADOS, PREPARADOS PARA ENVIO E COM SEQUENCIAIS ATUALIZADOS
		UPDATE MT SET 
			NUMPEDIDO = TEMP.NUMPEDIDO, 
			SITUACAOPEDIDO = '4', 
			AGUARDAPENDENTE = 'N', 
			NUMPEDIDOPEND = NULL
		FROM MANUT_BENEFICIARIO MT
		INNER JOIN #TEMP_MANUT_BENEFICIARIO_DIRETO TEMP 
			ON (MT.SEQ_PEDIDO = TEMP.SEQ_PEDIDO)
		WHERE MT.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
		AND MT.DATAPEDIDO <= @DATAPROCESSAMENTO 
		AND MT.SPID = @@SPID 
		AND MT.DATAHORAPROCESSO = @DATAHORAEXEC 
 	
		IF @@ERROR <> 0
			GOTO TRATAERRO	
		
	END

	SELECT
		CONVERT(NUMERIC(19), NULL) NUMIDENTCBENEFICIARIO,
		CONVERT(NUMERIC(15), NULL) SEQ_PEDIDO
	INTO #TEMP_MANUT_BENEFICIARIO
	WHERE 1 = 0 
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	INSERT INTO #TEMP_MANUT_BENEFICIARIO (
		NUMIDENTCBENEFICIARIO, SEQ_PEDIDO
	)
	SELECT 
		M1.NUMIDENTCBENEFICIARIO, MIN (M1.SEQ_PEDIDO) 
	FROM MANUT_BENEFICIARIO M1 
	WHERE M1.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND M1.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND M1.SPID = @@SPID 
	AND M1.DATAHORAPROCESSO = @DATAHORAEXEC 
	AND M1.SITUACAOPEDIDO = '0'
	AND M1.NUMIDENTCBENEFICIARIO IS NOT NULL
	GROUP BY M1.NUMIDENTCBENEFICIARIO
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	-- NAO ENVIA PEDIDO DE BENEFICIARIO QUE CONTEM PEDIDO PENDENTE
	DELETE TEMP 
	FROM #TEMP_MANUT_BENEFICIARIO TEMP 
	INNER JOIN MANUT_BENEFICIARIO M1 
		ON (TEMP.NUMIDENTCBENEFICIARIO = M1.NUMIDENTCBENEFICIARIO)
	WHERE M1.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND M1.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND M1.SITUACAOPEDIDO IN ('1', '2', '4') 
	AND TEMP.SEQ_PEDIDO <> M1.SEQ_PEDIDO
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- MANTEM O PEDIDO MAIS ANTIGO, CASO TENHA MAIS DE UM PEDIDO SOLICITADO DO MESMO BENEFICIARIO
	DELETE TEMP 
	FROM #TEMP_MANUT_BENEFICIARIO TEMP 
	INNER JOIN MANUT_BENEFICIARIO M1 
		ON (TEMP.NUMIDENTCBENEFICIARIO = M1.NUMIDENTCBENEFICIARIO)
	WHERE M1.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND M1.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND M1.SITUACAOPEDIDO = '0'
	AND TEMP.SEQ_PEDIDO > M1.SEQ_PEDIDO
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- PARA ESSES LIBERADOS, SAO ATRIBUIDOS OS SEQUENCIAIS MAIS ATUALIZADOS DE TITULO
	--	UPDATE #TEMP_MANUT_BENEFICIARIO_PENDENTES SET NUMREFCADBENEFICIARIO = BENEFICIARIO.NUMREFCADBENEFICIARIO FROM #TEMP_MANUT_BENEFICIARIO_PENDENTES TEMP
	--	INNER JOIN BENEFICIARIO ON (TEMP.AGUARDAPENDENTE = 'N' AND BENEFICIARIO.NUMIDENTCBENEFICIARIO = TEMP.NUMIDENTCBENEFICIARIO)


	-- MESMO TRATAMENTO, AGORA PARA PEDIDOS NOVOS EM SITUACAO DE SOLICITADOS (AINDA SEM MARCACAO DE PENDENCIA)
	SELECT
		CONVERT(NUMERIC(19), NULL) NUMIDENTCBENEFICIARIO,
		CONVERT(NUMERIC(19), NULL) SEQ_PEDIDO,
		IDENTITY (INT, 1,1) CONTADOR,
		CONVERT(NUMERIC(10), NULL) NUMPEDIDO,
		CONVERT(NUMERIC(19), NULL) NUMREFCADBENEFICIARIO
	INTO #TEMP_MANUT_BENEFICIARIO_SEL
	WHERE 1 = 0
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	INSERT INTO #TEMP_MANUT_BENEFICIARIO_SEL (
		NUMIDENTCBENEFICIARIO, SEQ_PEDIDO
	)
	SELECT 
		NUMIDENTCBENEFICIARIO, SEQ_PEDIDO 
	FROM #TEMP_MANUT_BENEFICIARIO
	
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	UPDATE SEL SET 
		NUMREFCADBENEFICIARIO = BENEFICIARIO.NUMREFCADBENEFICIARIO
	FROM #TEMP_MANUT_BENEFICIARIO_SEL SEL 
	INNER JOIN BENEFICIARIO 
		ON (SEL.NUMIDENTCBENEFICIARIO = BENEFICIARIO.NUMIDENTCBENEFICIARIO)
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	SELECT @COUNT = COUNT(*) 
	FROM #TEMP_MANUT_BENEFICIARIO_SEL
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	IF @COUNT > 0 
	BEGIN

		-- AVANCA O ULTIMO NUMERO DE PEDIDO NA QUANTIDADE DE PEDIDOS RESERVADOS	
		EXEC SP_GERA_NUMPEDIDO @COUNT, @ULTNUMPEDIDORESERVADO OUT
 	
		IF @@ERROR <> 0
			GOTO TRATAERRO	
	
		-- ULTRAPASSOU O NUMERO MAXIMO DE TENTATIVAS PARA RESERVAR O NUMERO DE PEDIDO
		IF(@ULTNUMPEDIDORESERVADO = -1)
			GOTO TRATAERRO
	
		-- NUMERA OS PEDIDOS
		UPDATE #TEMP_MANUT_BENEFICIARIO_SEL SET
			NUMPEDIDO = (@ULTNUMPEDIDORESERVADO - (CONTADOR - 1))
 	
		IF @@ERROR <> 0
			GOTO TRATAERRO	
	
		-- PEDIDOS ANTES SOLICITADOS, AGORA NUMERADOS, PREPARADOS PARA ENVIO E COM SEQUENCIAIS ATUALIZADOS
		UPDATE MT SET 
			NUMPEDIDO = TEMP.NUMPEDIDO, 
			SITUACAOPEDIDO = '4', 
			AGUARDAPENDENTE = 'N', 
			NUMPEDIDOPEND = NULL, 
			NUMREFCADBENEFICIARIO = TEMP.NUMREFCADBENEFICIARIO
		FROM MANUT_BENEFICIARIO MT
		INNER JOIN #TEMP_MANUT_BENEFICIARIO_SEL TEMP 
			ON (MT.SEQ_PEDIDO = TEMP.SEQ_PEDIDO)
		WHERE MT.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
		AND MT.DATAPEDIDO <= @DATAPROCESSAMENTO 
		AND MT.SPID = @@SPID 
		AND MT.DATAHORAPROCESSO = @DATAHORAEXEC
 	
		IF @@ERROR <> 0
			GOTO TRATAERRO	
		
	END

	SELECT
		GETDATE() DATAPEDIDO,
		GETDATE() DATALEGADO,
		CONVERT(VARCHAR(10), '') CODSISLEGADO,
		CONVERT(VARCHAR(35), '') NUMCTRLLEGADO,
		CONVERT(NUMERIC(19), 0) NUMIDENTCBENEFICIARIO,
		CONVERT(NUMERIC(10), 0) NUMPEDIDO,
		CONVERT(NUMERIC(15), 0) SEQ_PEDIDO,
		CONVERT(NUMERIC(10), 0) NUMPEDIDOPEND
	INTO #TEMP_BENEFICIARIO_AGUARDANDO
	WHERE 1 = 0
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	CREATE INDEX IDX_TEMP_BENEFICIARIO_AGUARDANDO ON #TEMP_BENEFICIARIO_AGUARDANDO (DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO)
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- AQUILO QUE ESTA AGUARDANDO OUTROS PEDIDOS PENDENTES...
	INSERT INTO #TEMP_BENEFICIARIO_AGUARDANDO(
		DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO, NUMIDENTCBENEFICIARIO, NUMPEDIDO, SEQ_PEDIDO
	)
	SELECT 
		DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO, NUMIDENTCBENEFICIARIO, NUMPEDIDO, SEQ_PEDIDO 
	FROM MANUT_BENEFICIARIO MANUT
	WHERE MANUT.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND MANUT.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND MANUT.SITUACAOPEDIDO = '0' 
	AND MANUT.AGUARDAPENDENTE = 'S' 
	AND MANUT.SPID = @@SPID
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	SELECT 
		CONVERT(NUMERIC(19), 0) NUMIDENTCBENEFICIARIO,
		CONVERT(NUMERIC(10), 0) NUMPEDIDO
	INTO #TEMP_BENEFICIARIO_PENDENTE
	WHERE 1 = 0
 	IF @@ERROR <> 0
		GOTO TRATAERRO	

	CREATE INDEX IDX_TEMP_BENEFICIARIO_PENDENTE ON #TEMP_BENEFICIARIO_PENDENTE (NUMIDENTCBENEFICIARIO, NUMPEDIDO)
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- A RELACAO DESSES PEDIDOS QUE ESTAO PENDENTES....
	INSERT INTO #TEMP_BENEFICIARIO_PENDENTE(
		NUMIDENTCBENEFICIARIO, NUMPEDIDO
	)
	SELECT MANUT.NUMIDENTCBENEFICIARIO, MANUT.NUMPEDIDO 
	FROM MANUT_BENEFICIARIO MANUT
	INNER JOIN #TEMP_BENEFICIARIO_AGUARDANDO AGUARDANDO 
		ON (MANUT.SITUACAOPEDIDO IN ('1', '2', '4')
		AND MANUT.NUMIDENTCBENEFICIARIO = AGUARDANDO.NUMIDENTCBENEFICIARIO
		AND MANUT.SEQ_PEDIDO != AGUARDANDO.SEQ_PEDIDO)
	WHERE MANUT.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND MANUT.DATAPEDIDO <= @DATAPROCESSAMENTO 
	GROUP BY MANUT.NUMIDENTCBENEFICIARIO, MANUT.NUMPEDIDO
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- MARCANDO NOS PEDIDOS QUE ESTAO AGUARDANDO QUAL O NUMERO DO PEDIDO PENDENTE
	UPDATE MANUT_BENEFICIARIO SET
		NUMPEDIDOPEND = PENDENTE.NUMPEDIDO
	FROM MANUT_BENEFICIARIO MANUT
	INNER JOIN #TEMP_BENEFICIARIO_AGUARDANDO AGUARDANDO 
		ON (MANUT.DATAPEDIDO = AGUARDANDO.DATAPEDIDO 
		AND MANUT.DATALEGADO = AGUARDANDO.DATALEGADO
		AND MANUT.CODSISLEGADO = AGUARDANDO.CODSISLEGADO 
		AND MANUT.NUMCTRLLEGADO = AGUARDANDO.NUMCTRLLEGADO)
	INNER JOIN #TEMP_BENEFICIARIO_PENDENTE PENDENTE 
		ON (AGUARDANDO.NUMIDENTCBENEFICIARIO = PENDENTE.NUMIDENTCBENEFICIARIO)
	WHERE MANUT.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND MANUT.DATAPEDIDO <= @DATAPROCESSAMENTO 
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- ADAPTADO ACIMA DEVIDO A PROBLEMAS DE DESEMPENHO
	/*
	UPDATE MANUT_BENEFICIARIO SET NUMPEDIDOPEND = 
		(SELECT TOP 1 P.NUMPEDIDO FROM MANUT_BENEFICIARIO P 
		 WHERE P.SITUACAOPEDIDO IN ('1', '2', '4') 
		 AND P.NUMIDENTCBENEFICIARIO = MB.NUMIDENTCBENEFICIARIO
		 AND P.SEQ_PEDIDO != MB.SEQ_PEDIDO) 
	FROM MANUT_BENEFICIARIO MB
	WHERE MB.DATAPEDIDO >= @DATAULTPROCESSAMENTO AND MB.DATAPEDIDO <= @DATAPROCESSAMENTO AND
	MB.SITUACAOPEDIDO = '0' AND MB.AGUARDAPENDENTE = 'S' AND MB.SPID = @@SPID
	*/

	-- SACADO
	----------
	SELECT @DATAHORAEXEC = GETDATE()

	-- SE ALGUM PROCESSO ANTERIOR NAO FOI COMPLETADO POR MAIS DE 3 MINUTOS, LIBERAR ESSES REGISTROS (SITUACAO "SOLICITADO")
	UPDATE MANUT_SACELETRONICO SET 
		SPID = NULL, 
		DATAHORAPROCESSO = NULL,
		AGUARDAPENDENTE = CASE
			WHEN AGUARDAPENDENTE = 'N' 
				THEN NULL
			ELSE 
				AGUARDAPENDENTE
			END
	WHERE SITUACAOPEDIDO = '0' 
	AND DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SPID IS NOT NULL 
	AND DATAHORAPROCESSO IS NOT NULL 
	AND @DATAHORAEXEC > DATEADD(MINUTE, 3, DATAHORAPROCESSO)
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- RESERVAR PEDIDOS PARA ESSE PROCESSO
	UPDATE MANUT_SACELETRONICO SET 
		SPID = @@SPID, 
		DATAHORAPROCESSO = @DATAHORAEXEC, 
		AGUARDAPENDENTE = 'S'
	WHERE DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SITUACAOPEDIDO = '0'
	AND SPID IS NULL 
	AND DATAHORAPROCESSO IS NULL
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	-- SELECIONA PEDIDOS QUE NAO SERAO CONTROLADOS
	SELECT
		IDENTITY (INT, 1,1) CONTADOR,
		CONVERT(CHAR (1), '') TIPOMANUTENCAO,
		CONVERT(NUMERIC(17), NULL) SEQ_PEDIDO,
		CONVERT(NUMERIC(10), NULL) NUMPEDIDO,
		CONVERT(VARCHAR(14), NULL) CNPJ_CPF_SACADO,
		CONVERT(NUMERIC(19), NULL) NUMREFCADPAG,
		CONVERT(NUMERIC(19), NULL) NUMIDENTCPAG
	INTO #TEMP_MANUT_SACELETRONICO_DIRETO
	WHERE 1 = 0
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	INSERT INTO #TEMP_MANUT_SACELETRONICO_DIRETO (
		TIPOMANUTENCAO, SEQ_PEDIDO, CNPJ_CPF_SACADO
	)
	SELECT 
		M1.TIPOMANUTENCAO, M1.SEQ_PEDIDO, M1.CNPJ_CPF_SACADO 
	FROM MANUT_SACELETRONICO M1 
	WHERE M1.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND M1.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND M1.SPID = @@SPID 
	AND M1.DATAHORAPROCESSO = @DATAHORAEXEC 
	AND M1.SITUACAOPEDIDO = '0' 
	AND M1.TIPOMANUTENCAO IN ('I', 'C') 
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	SELECT @COUNT = COUNT(*) FROM #TEMP_MANUT_SACELETRONICO_DIRETO
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	IF @COUNT > 0 
	BEGIN
	
		-- AVANCA O ULTIMO NUMERO DE PEDIDO NA QUANTIDADE DE PEDIDOS RESERVADOS	
		EXEC SP_GERA_NUMPEDIDO @COUNT, @ULTNUMPEDIDORESERVADO OUT
 	 
		IF @@ERROR <> 0
			GOTO TRATAERRO	

		-- ULTRAPASSOU O NUMERO MAXIMO DE TENTATIVAS PARA RESERVAR O NUMERO DE PEDIDO
		IF(@ULTNUMPEDIDORESERVADO = -1)
		GOTO TRATAERRO
	
		-- NUMERA OS PEDIDOS
		UPDATE #TEMP_MANUT_SACELETRONICO_DIRETO SET 
			NUMPEDIDO = (@ULTNUMPEDIDORESERVADO - (CONTADOR - 1))
 	 
		IF @@ERROR <> 0
			GOTO TRATAERRO	
		
		-- ATUALIZA NUMREFCADPAG 
		UPDATE SEL SET 
			NUMREFCADPAG = SACELETRONICO.NUMREFCADPAG, 
			NUMIDENTCPAG = SACELETRONICO.NUMIDENTCPAG
		FROM #TEMP_MANUT_SACELETRONICO_DIRETO SEL 
		INNER JOIN SACELETRONICO 
			ON (SEL.CNPJ_CPF_SACADO = SACELETRONICO.CNPJ_CPF_SACADO)
		WHERE SEL.TIPOMANUTENCAO = 'I'
 	 
		IF @@ERROR <> 0
			GOTO TRATAERRO	

		-- PEDIDOS ANTES SOLICITADOS, AGORA NUMERADOS, PREPARADOS PARA ENVIO E COM SEQUENCIAIS ATUALIZADOS
		UPDATE MT SET 
			NUMPEDIDO = TEMP.NUMPEDIDO, 
			SITUACAOPEDIDO = '4', 
			AGUARDAPENDENTE = 'N', 
			NUMPEDIDOPEND = NULL, 
			NUMREFCADPAG = TEMP.NUMREFCADPAG, 
			NUMIDENTCPAG = TEMP.NUMIDENTCPAG
		FROM MANUT_SACELETRONICO MT
		INNER JOIN #TEMP_MANUT_SACELETRONICO_DIRETO TEMP 
			ON (MT.SEQ_PEDIDO = TEMP.SEQ_PEDIDO)
		WHERE MT.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
		AND MT.DATAPEDIDO <= @DATAPROCESSAMENTO 
		AND MT.SPID = @@SPID 
		AND MT.DATAHORAPROCESSO = @DATAHORAEXEC 
 	 
		IF @@ERROR <> 0
			GOTO TRATAERRO	
	
	END	

	-- SELECIONA PEDIDOS QUE SERAO CONTROLADOS	
	SELECT
		CONVERT(VARCHAR(14), NULL) CNPJ_CPF_SACADO,
		CONVERT(NUMERIC(17), NULL) SEQ_PEDIDO
	INTO #TEMP_MANUT_SACELETRONICO
	WHERE 1 = 0
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	INSERT INTO #TEMP_MANUT_SACELETRONICO (
		CNPJ_CPF_SACADO, SEQ_PEDIDO
	)
	SELECT 
		M1.CNPJ_CPF_SACADO, MIN (M1.SEQ_PEDIDO) 
	FROM MANUT_SACELETRONICO M1 
	WHERE M1.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND M1.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND M1.SPID = @@SPID 
	AND M1.DATAHORAPROCESSO = @DATAHORAEXEC 
	AND M1.SITUACAOPEDIDO = '0' 
	AND M1.CNPJ_CPF_SACADO IS NOT NULL
	GROUP BY M1.CNPJ_CPF_SACADO
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- NAO ENVIA PEDIDO DE TITULO QUE CONTEM PEDIDO PENDENTE	
	DELETE TEMP FROM #TEMP_MANUT_SACELETRONICO TEMP 
	INNER JOIN MANUT_SACELETRONICO M1 
		ON (TEMP.CNPJ_CPF_SACADO = M1.CNPJ_CPF_SACADO)
	WHERE M1.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND M1.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND M1.SITUACAOPEDIDO IN ('1', '2', '4') 
	AND TEMP.SEQ_PEDIDO <> M1.SEQ_PEDIDO
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- MANTEM O PEDIDO MAIS ANTIGO, CASO TENHA MAIS DE UM PEDIDO SOLICITADO DO MESMO TITULO

	DELETE TEMP FROM #TEMP_MANUT_SACELETRONICO TEMP 
	INNER JOIN MANUT_SACELETRONICO M1 
		ON (TEMP.CNPJ_CPF_SACADO = M1.CNPJ_CPF_SACADO)
	WHERE M1.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND M1.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND M1.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND M1.SITUACAOPEDIDO = '0' 
	AND TEMP.SEQ_PEDIDO > M1.SEQ_PEDIDO
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	-- MESMO TRATAMENTO, AGORA PARA PEDIDOS NOVOS EM SITUACAO DE SOLICITADOS (AINDA SEM MARCACAO DE PENDENCIA)
	SELECT 
		CONVERT(VARCHAR(14), NULL) CNPJ_CPF_SACADO,
		CONVERT(NUMERIC(17), NULL) SEQ_PEDIDO,
		IDENTITY (INT, 1,1) CONTADOR,
		CONVERT(NUMERIC(10), NULL) NUMPEDIDO,
		CONVERT(NUMERIC(19), NULL) ULTNUMREFCADPAG,
		CONVERT(NUMERIC(19), NULL) ULTNUMIDENTCPAG
	INTO #TEMP_MANUT_SACELETRONICO_SEL
	WHERE 1 = 0
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	INSERT INTO #TEMP_MANUT_SACELETRONICO_SEL (
		CNPJ_CPF_SACADO, SEQ_PEDIDO
	)
	SELECT 
		CNPJ_CPF_SACADO, SEQ_PEDIDO 
	FROM #TEMP_MANUT_SACELETRONICO
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	UPDATE SEL SET 
		ULTNUMREFCADPAG = SACELETRONICO.NUMREFCADPAG, 
		ULTNUMIDENTCPAG = SACELETRONICO.NUMIDENTCPAG
	FROM #TEMP_MANUT_SACELETRONICO_SEL SEL 
	INNER JOIN SACELETRONICO 
		ON (SEL.CNPJ_CPF_SACADO = SACELETRONICO.CNPJ_CPF_SACADO)
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	SELECT @COUNT = COUNT(*) 
		FROM #TEMP_MANUT_SACELETRONICO_SEL
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	IF @COUNT > 0 
	BEGIN
	
		-- AVANCA O ULTIMO NUMERO DE PEDIDO NA QUANTIDADE DE PEDIDOS RESERVADOS	
		EXEC SP_GERA_NUMPEDIDO @COUNT, @ULTNUMPEDIDORESERVADO OUT
 
		IF @@ERROR <> 0
			GOTO TRATAERRO	

		-- ULTRAPASSOU O NUMERO MAXIMO DE TENTATIVAS PARA RESERVAR O NUMERO DE PEDIDO
		IF(@ULTNUMPEDIDORESERVADO = -1)
			GOTO TRATAERRO 
	
		-- NUMERA OS PEDIDOS
		UPDATE #TEMP_MANUT_SACELETRONICO_SEL SET 
			NUMPEDIDO = (@ULTNUMPEDIDORESERVADO - (CONTADOR - 1))
 
		IF @@ERROR <> 0
			GOTO TRATAERRO	
	
 -- PEDIDOS ANTES SOLICITADOS, AGORA NUMERADOS, PREPARADOS PARA ENVIO E COM SEQUENCIAIS ATUALIZADOS
	
		UPDATE MT SET 
			NUMPEDIDO = TEMP.NUMPEDIDO, 
			SITUACAOPEDIDO = '4', 
			AGUARDAPENDENTE = 'N', 
			NUMPEDIDOPEND = NULL, 
			NUMREFCADPAG = TEMP.ULTNUMREFCADPAG, 
			NUMIDENTCPAG = TEMP.ULTNUMIDENTCPAG
		FROM MANUT_SACELETRONICO MT
		INNER JOIN #TEMP_MANUT_SACELETRONICO_SEL TEMP 
			ON (MT.SEQ_PEDIDO = TEMP.SEQ_PEDIDO)
		WHERE MT.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
		AND MT.DATAPEDIDO <= @DATAPROCESSAMENTO 
		AND MT.SPID = @@SPID 
		AND MT.DATAHORAPROCESSO = @DATAHORAEXEC
 
		IF @@ERROR <> 0
			GOTO TRATAERRO	

	END

	-- MARCANDO NUMERO DO PEDIDO PENDENTE QUE ESTA SEGURANDO AS MANUTENCOES COM AGUARDAPENDENTE = 'S'

	SELECT
		GETDATE() DATAPEDIDO,
		GETDATE() DATALEGADO,
		CONVERT(VARCHAR(10), '') CODSISLEGADO,
		CONVERT(VARCHAR(35), '') NUMCTRLLEGADO,
		CONVERT(VARCHAR(14), '') CNPJ_CPF_SACADO,
		CONVERT(NUMERIC(10), 0) NUMPEDIDO,
		CONVERT(NUMERIC(17), 0) SEQ_PEDIDO,
		CONVERT(NUMERIC(10), 0) NUMPEDIDOPEND
	INTO #TEMP_SACADO_AGUARDANDO
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	CREATE INDEX IDX_TEMP_SACADO_AGUARDANDO ON #TEMP_SACADO_AGUARDANDO (DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO)
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	


	-- AQUILO QUE ESTA AGUARDANDO OUTROS PEDIDOS PENDENTES...
	INSERT INTO #TEMP_SACADO_AGUARDANDO (
		DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO, CNPJ_CPF_SACADO, NUMPEDIDO, SEQ_PEDIDO
	)
	SELECT 
		DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO, CNPJ_CPF_SACADO, NUMPEDIDO, SEQ_PEDIDO 
	FROM MANUT_SACELETRONICO MANUT
	WHERE DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND	SITUACAOPEDIDO = '0' 
	AND AGUARDAPENDENTE = 'S' 
	AND SPID = @@SPID
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	SELECT
		CONVERT(VARCHAR(14), '') CNPJ_CPF_SACADO,
		CONVERT(NUMERIC(10), 0) NUMPEDIDO
	INTO #TEMP_SACADO_PENDENTE
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	CREATE INDEX IDX_TEMP_SACADO_PENDENTE ON #TEMP_SACADO_PENDENTE (CNPJ_CPF_SACADO, NUMPEDIDO)
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	


	-- A RELACAO DESSES PEDIDOS QUE ESTAO PENDENTES....
	INSERT INTO #TEMP_SACADO_PENDENTE (
		CNPJ_CPF_SACADO, NUMPEDIDO
	)
	SELECT 
		MANUT.CNPJ_CPF_SACADO, MANUT.NUMPEDIDO 
	FROM MANUT_SACELETRONICO MANUT
	INNER JOIN #TEMP_SACADO_AGUARDANDO AGUARDANDO 
		ON (MANUT.SITUACAOPEDIDO IN ('1', '2', '4')
		AND MANUT.CNPJ_CPF_SACADO = AGUARDANDO.CNPJ_CPF_SACADO
		AND MANUT.SEQ_PEDIDO != AGUARDANDO.SEQ_PEDIDO)
	WHERE MANUT.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND MANUT.DATAPEDIDO <= @DATAPROCESSAMENTO 
	GROUP BY MANUT.CNPJ_CPF_SACADO, MANUT.NUMPEDIDO
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- MARCANDO NOS PEDIDOS QUE ESTAO AGUARDANDO QUAL O NUMERO DO PEDIDO PENDENTE
	UPDATE MANUT_SACELETRONICO SET
		NUMPEDIDOPEND = PENDENTE.NUMPEDIDO
	FROM MANUT_SACELETRONICO MANUT
	INNER JOIN #TEMP_SACADO_AGUARDANDO AGUARDANDO
		ON (MANUT.DATAPEDIDO = AGUARDANDO.DATAPEDIDO
		AND MANUT.DATALEGADO = AGUARDANDO.DATALEGADO
		AND MANUT.NUMCTRLLEGADO = AGUARDANDO.NUMCTRLLEGADO
		AND MANUT.CODSISLEGADO = AGUARDANDO.CODSISLEGADO)
	INNER JOIN #TEMP_SACADO_PENDENTE PENDENTE
		ON (AGUARDANDO.CNPJ_CPF_SACADO = PENDENTE.CNPJ_CPF_SACADO)
	WHERE MANUT.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND MANUT.DATAPEDIDO <= @DATAPROCESSAMENTO 
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	-- ADAPTADO ACIMA DEVIDO A PROBLEMAS DE DESEMPENHO
	/*
	UPDATE MANUT_SACELETRONICO SET NUMPEDIDOPEND = 
		(SELECT TOP 1 P.NUMPEDIDO FROM MANUT_SACELETRONICO P 
		 WHERE P.SITUACAOPEDIDO IN ('1', '2', '4') 
		 AND P.CNPJ_CPF_SACADO = MS.CNPJ_CPF_SACADO
		 AND P.SEQ_PEDIDO != MS.SEQ_PEDIDO) 
	FROM MANUT_SACELETRONICO MS
	WHERE MS.DATAPEDIDO >= @DATAULTPROCESSAMENTO AND MS.DATAPEDIDO <= @DATAPROCESSAMENTO AND
	MS.SITUACAOPEDIDO = '0' AND MS.AGUARDAPENDENTE = 'S' AND MS.SPID = @@SPID
	*/

	-- MENSAGENS GEN
	-----------------
	-- APENAS NUMERANDO OS PEDIDOS

	SELECT @DATAHORAEXEC = GETDATE()

	-- SE ALGUM PROCESSO ANTERIOR NAO FOI COMPLETADO POR MAIS DE 3 MINUTOS, LIBERAR ESSES REGISTROS
	UPDATE MANUT_GENERICA SET 
		SPID = NULL, 
		DATAHORAPROCESSO = NULL 
	WHERE SITUACAOPEDIDO = '0'
	AND DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SPID IS NOT NULL 
	AND DATAHORAPROCESSO IS NOT NULL 
	AND @DATAHORAEXEC > DATEADD(MINUTE, 3, DATAHORAPROCESSO)
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	UPDATE MANUT_GENERICA SET 
		SPID = @@SPID, 
		DATAHORAPROCESSO = @DATAHORAEXEC
	WHERE SITUACAOPEDIDO = '0' 
	AND DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO
	AND SPID IS NULL 
	AND DATAHORAPROCESSO IS NULL
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	SELECT 
		CONVERT(DATETIME, NULL) DATAPEDIDO,
		CONVERT(DATETIME, NULL) DATALEGADO,
		CONVERT(VARCHAR(35), NULL) NUMCTRLLEGADO,
		CONVERT(VARCHAR(10), NULL) CODSISLEGADO,
		CONVERT(NUMERIC(10), NULL) NUMPEDIDO,
		IDENTITY (INT, 1,1) SEQ_PEDIDO
	INTO #TEMP_MANUT_GENERICA
	WHERE 1 = 0
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	INSERT INTO #TEMP_MANUT_GENERICA(
		DATAPEDIDO, DATALEGADO, NUMCTRLLEGADO, CODSISLEGADO
	)
	SELECT 
		DATAPEDIDO, DATALEGADO, NUMCTRLLEGADO, CODSISLEGADO FROM MANUT_GENERICA
	WHERE SITUACAOPEDIDO = '0' 
	AND DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SPID = @@SPID
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	SELECT @COUNT = COUNT(*) FROM #TEMP_MANUT_GENERICA
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	IF @COUNT > 0 
	BEGIN

		EXEC SP_GERA_NUMPEDIDO @COUNT, @ULTNUMPEDIDORESERVADO OUT
 
		IF @@ERROR <> 0
			GOTO TRATAERRO	

		-- ULTRAPASSOU O NUMERO MAXIMO DE TENTATIVAS PARA RESERVAR O NUMERO DE PEDIDO OU ULTRAPASSOU O MAXIMO PARA NUMERO DE PEDIDO NO SISTEMA
		IF(@ULTNUMPEDIDORESERVADO = -1)
			GOTO TRATAERRO
	
		UPDATE #TEMP_MANUT_GENERICA SET 
			NUMPEDIDO = (@ULTNUMPEDIDORESERVADO - (SEQ_PEDIDO - 1))
 
		IF @@ERROR <> 0
			GOTO TRATAERRO	
	
		UPDATE MANUT_GENERICA SET 
			NUMPEDIDO = T.NUMPEDIDO, 
			SITUACAOPEDIDO = '4' 
		FROM #TEMP_MANUT_GENERICA T 
		INNER JOIN MANUT_GENERICA G
			ON (G.DATAPEDIDO = T.DATAPEDIDO 
			AND G.DATALEGADO = T.DATALEGADO 
			AND G.NUMCTRLLEGADO = T.NUMCTRLLEGADO 
			AND G.CODSISLEGADO = T.CODSISLEGADO)
		WHERE G.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
		AND G.DATAPEDIDO <= @DATAPROCESSAMENTO 
 
		IF @@ERROR <> 0
			GOTO TRATAERRO	

	END	

	-- MENSAGENS EXTRATO DE PROCESSAMENTO
	-----------------
	-- APENAS NUMERANDO OS PEDIDOS

	SELECT @DATAHORAEXEC = GETDATE()

	-- SE ALGUM PROCESSO ANTERIOR NAO FOI COMPLETADO POR MAIS DE 3 MINUTOS, LIBERAR ESSES REGISTROS
	UPDATE MANUT_EXTRATO_PROCESSAMENTO SET 
		SPID = NULL, 
		DATAHORAPROCESSO = NULL 
	WHERE SITUACAOPEDIDO = '0'
	AND DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SPID IS NOT NULL 
	AND DATAHORAPROCESSO IS NOT NULL 
	AND @DATAHORAEXEC > DATEADD(MINUTE, 3, DATAHORAPROCESSO)
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	UPDATE MANUT_EXTRATO_PROCESSAMENTO SET 
		SPID = @@SPID, 
		DATAHORAPROCESSO = @DATAHORAEXEC
	WHERE SITUACAOPEDIDO = '0' 
	AND DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO
	AND SPID IS NULL 
	AND DATAHORAPROCESSO IS NULL
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	SELECT 
		CONVERT(DATETIME, NULL) DATAPEDIDO,
		CONVERT(DATETIME, NULL) DATALEGADO,
		CONVERT(VARCHAR(35), NULL) NUMCTRLLEGADO,
		CONVERT(VARCHAR(10), NULL) CODSISLEGADO,
		CONVERT(NUMERIC(10), NULL) NUMPEDIDO,
		IDENTITY (INT, 1,1) SEQ_PEDIDO
	INTO #TEMP_MANUT_EXTRATO_PROCESSAMENTO
	WHERE 1 = 0
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	INSERT INTO #TEMP_MANUT_EXTRATO_PROCESSAMENTO(
		DATAPEDIDO, DATALEGADO, NUMCTRLLEGADO, CODSISLEGADO
	)
	SELECT 
		DATAPEDIDO, DATALEGADO, NUMCTRLLEGADO, CODSISLEGADO 
	FROM MANUT_EXTRATO_PROCESSAMENTO
	WHERE SITUACAOPEDIDO = '0' 
	AND DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SPID = @@SPID
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	SELECT @COUNT = COUNT(*) 
	FROM #TEMP_MANUT_EXTRATO_PROCESSAMENTO
 
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	IF @COUNT > 0 
	BEGIN
		EXEC SP_GERA_NUMPEDIDO @COUNT, @ULTNUMPEDIDORESERVADO OUT
 	
		IF @@ERROR <> 0
			GOTO TRATAERRO	

		-- ULTRAPASSOU O NUMERO MAXIMO DE TENTATIVAS PARA RESERVAR O NUMERO DE PEDIDO OU ULTRAPASSOU O MAXIMO PARA NUMERO DE PEDIDO NO SISTEMA
		IF(@ULTNUMPEDIDORESERVADO = -1)
			GOTO TRATAERRO
	
		UPDATE #TEMP_MANUT_EXTRATO_PROCESSAMENTO SET 
			NUMPEDIDO = (@ULTNUMPEDIDORESERVADO - (SEQ_PEDIDO - 1))
 	
		IF @@ERROR <> 0
			GOTO TRATAERRO	
	
		UPDATE MANUT_EXTRATO_PROCESSAMENTO SET 
			NUMPEDIDO = T.NUMPEDIDO, 
			SITUACAOPEDIDO = '4' 
		FROM #TEMP_MANUT_EXTRATO_PROCESSAMENTO T 
		INNER JOIN MANUT_EXTRATO_PROCESSAMENTO P
			ON (P.DATAPEDIDO = T.DATAPEDIDO 
			AND P.DATALEGADO = T.DATALEGADO 
			AND P.NUMCTRLLEGADO = T.NUMCTRLLEGADO 
			AND P.CODSISLEGADO = T.CODSISLEGADO)
		WHERE P.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
		AND P.DATAPEDIDO <= @DATAPROCESSAMENTO 
 	
		IF @@ERROR <> 0
			GOTO TRATAERRO	

	END	

	-- MENSAGENS EXTRATO 
	-----------------
	-- APENAS NUMERANDO OS PEDIDOS

	SELECT @DATAHORAEXEC = GETDATE()

	-- SE ALGUM PROCESSO ANTERIOR NAO FOI COMPLETADO POR MAIS DE 3 MINUTOS, LIBERAR ESSES REGISTROS
	UPDATE MANUT_EXTRATO SET 
		SPID = NULL, 
		DATAHORAPROCESSO = NULL 
	WHERE SITUACAOPEDIDO = '0'
	AND DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SPID IS NOT NULL 
	AND DATAHORAPROCESSO IS NOT NULL 
	AND @DATAHORAEXEC > DATEADD(MINUTE, 3, DATAHORAPROCESSO)
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	UPDATE MANUT_EXTRATO SET 
		SPID = @@SPID, 
		DATAHORAPROCESSO = @DATAHORAEXEC
	WHERE SITUACAOPEDIDO = '0' 
	AND DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO
	AND SPID IS NULL 
	AND DATAHORAPROCESSO IS NULL
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	SELECT 
		CONVERT(DATETIME, NULL) DATAPEDIDO,
		CONVERT(DATETIME, NULL) DATALEGADO,
		CONVERT(VARCHAR(35), NULL) NUMCTRLLEGADO,
		CONVERT(VARCHAR(10), NULL) CODSISLEGADO,
		CONVERT(NUMERIC(10), NULL) NUMPEDIDO,
		IDENTITY (INT, 1,1) SEQ_PEDIDO
	INTO #TEMP_MANUT_EXTRATO
	WHERE 1 = 0
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	INSERT INTO #TEMP_MANUT_EXTRATO(
		DATAPEDIDO, DATALEGADO, NUMCTRLLEGADO, CODSISLEGADO
	)
	SELECT 
		DATAPEDIDO, DATALEGADO, NUMCTRLLEGADO, CODSISLEGADO 
	FROM MANUT_EXTRATO
	WHERE SITUACAOPEDIDO = '0' 
	AND DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND SPID = @@SPID
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	

	SELECT @COUNT = COUNT(*) 
	FROM #TEMP_MANUT_EXTRATO
 	
	IF @@ERROR <> 0
		GOTO TRATAERRO	
	
	IF @COUNT > 0 
	BEGIN

		EXEC SP_GERA_NUMPEDIDO @COUNT, @ULTNUMPEDIDORESERVADO OUT
 	 
		IF @@ERROR <> 0
		GOTO TRATAERRO	

		-- ULTRAPASSOU O NUMERO MAXIMO DE TENTATIVAS PARA RESERVAR O NUMERO DE PEDIDO OU ULTRAPASSOU O MAXIMO PARA NUMERO DE PEDIDO NO SISTEMA
		IF(@ULTNUMPEDIDORESERVADO = -1)
			GOTO TRATAERRO
	
		UPDATE #TEMP_MANUT_EXTRATO SET 
			NUMPEDIDO = (@ULTNUMPEDIDORESERVADO - (SEQ_PEDIDO - 1))
 		
		IF @@ERROR <> 0
			GOTO TRATAERRO	
	
		UPDATE MANUT_EXTRATO SET 
			NUMPEDIDO = T.NUMPEDIDO, 
			SITUACAOPEDIDO = '4' 
		FROM #TEMP_MANUT_EXTRATO T 
		INNER JOIN MANUT_EXTRATO P
			ON (P.DATAPEDIDO = T.DATAPEDIDO 
			AND P.DATALEGADO = T.DATALEGADO 
			AND P.NUMCTRLLEGADO = T.NUMCTRLLEGADO 
			AND P.CODSISLEGADO = T.CODSISLEGADO)
		WHERE P.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
		AND P.DATAPEDIDO <= @DATAPROCESSAMENTO 
 		
		IF @@ERROR <> 0
			GOTO TRATAERRO	

	END	

	RETURN

	TRATAERRO:
	
	IF(@ULTNUMPEDIDORESERVADO = -1) -- ULTRAPASSOU NUMERO MAXIMO DE TENTATIVAS PARA RESERVAR NUMERO DE PEDIDO
	BEGIN
		SELECT @ERRO = 1
		RETURN
	END

END

GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO],
	[NOMESCRIPT],
	[CODUSUARIO],
	[DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_ALTERAR_MANUT_PREPARADA_ENVIO',
	SYSTEM_USER, 
	GETDATE() 
GO