USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_EXISTE_CANCELAMENTO_BAIXA_TITULO_DESTINATARIA_PREPARADO_ENVIO_ARQUIVO')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_EXISTE_CANCELAMENTO_BAIXA_TITULO_DESTINATARIA_PREPARADO_ENVIO_ARQUIVO AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE dbo.SP_EXISTE_CANCELAMENTO_BAIXA_TITULO_DESTINATARIA_PREPARADO_ENVIO_ARQUIVO AS  
BEGIN   
  
	DECLARE @DATAULTPROCESSAMENTO DATETIME  
	
	SELECT @DATAULTPROCESSAMENTO = DATAULTPROCESSAMENTO 
	FROM PARAMETROS  
  
	-- TUDO QUE ESTIVER PREPARADO PARA ENVIO COM TIPO MANUTENCAO "B"  
	SELECT DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO 
		INTO #TEMP 
	FROM MANUT_TITULOS  
	WHERE TIPOMANUTENCAOTIT = 'D'
	AND CODEVENTO = '8116' 
	AND SITUACAOPEDIDO = '4' 
	AND TIPOENVIO = 'X'  
	AND DATAPEDIDO >= @DATAULTPROCESSAMENTO  
  
	-- ... COM EXCECAO DO QUE JA ESTA RESERVADO PELA GERACAO DE ARQUIVO  
	DELETE #TEMP 
	FROM #TEMP, 
		TEMP_CANCELAMENTO_BAIXA_TITULO_GERACAO_ARQUIVO   
	WHERE #TEMP.DATAPEDIDO = TEMP_CANCELAMENTO_BAIXA_TITULO_GERACAO_ARQUIVO.DATAPEDIDO 
	AND #TEMP.DATALEGADO = TEMP_CANCELAMENTO_BAIXA_TITULO_GERACAO_ARQUIVO.DATALEGADO 
	AND #TEMP.NUMCTRLLEGADO = TEMP_CANCELAMENTO_BAIXA_TITULO_GERACAO_ARQUIVO.NUMCTRLLEGADO 
	AND #TEMP.CODSISLEGADO = TEMP_CANCELAMENTO_BAIXA_TITULO_GERACAO_ARQUIVO.CODSISLEGADO  
  
	-- RETORNA O QUE SOBROU  
	SELECT 1 
	FROM #TEMP  
END  
GO 

INSERT INTO VERSAO_SISTEMA (
	[VERSAO],
	[NOMESCRIPT],
	[CODUSUARIO],
	[DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_EXISTE_CANCELAMENTO_BAIXA_TITULO_DESTINATARIA_PREPARADO_ENVIO_ARQUIVO',
	SYSTEM_USER, 
	GETDATE() 
GO