USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_INCLUI_RECEBE_ADDA115_RR2_CAT505')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_INCLUI_RECEBE_ADDA115_RR2_CAT505 AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE dbo.SP_INCLUI_RECEBE_ADDA115_RR2_CAT505
(
			@NUMCTRLDDA					VARCHAR(20),
			@NUMIDENTCDDA				NUMERIC(19, 0),
			@NUMREFALTCADTIT			NUMERIC(19, 0),
			@DATAHORASITUACAOTITULO		DATETIME,
			@NUMIDENTCBAIXAOPERAC		NUMERIC(19, 0),
			@DATAHORACANCELAMENTOBAIXA	DATETIME,
			@QTDPAGTOREGTD				INT,
			@VLRSALDOATUAL				NUMERIC(19, 5),
			@NUMULTIDENTCBAIXAOPERAC	NUMERIC(19, 0),
			@NUMULTREFBAIXAOPERAC		NUMERIC(19, 0),
			@NUMULTSEQBAIXAOPERAC		NUMERIC(19, 0),
			@NUMULTIDENTCBAIXAEFETIVA	NUMERIC(19, 0),
			@NUMULTREFBAIXAEFETIVA		NUMERIC(19, 0),
			@NUMULTSEQBAIXAEFETIVA		NUMERIC(19, 0),
			@CODSITUACAOTIT				VARCHAR(2),
			@DATAHORADDA				DATETIME,
			@DATAMOVTO					DATETIME,
			@CODPROCESSA				VARCHAR(1),
			@DATAMANUTENCAO				DATETIME,
			@TIPORETORNO				VARCHAR(1),
			@NOMEARQRET					VARCHAR(255),
			@INDIMPORTACAOVALIDA		CHAR(1),
			@SEQ_RECEBE					NUMERIC(15, 0) OUTPUT
) AS BEGIN
	INSERT INTO RECEBE_ADDA115_RR2(NUMCTRLDDA, NUMIDENTCDDA, NUMREFALTCADTIT, DATAHORASITUACAOTITULO, NUMIDENTCBAIXAOPERAC, DATAHORACANCELAMENTOBAIXA, QTDPAGTOREGTD, VLRSALDOATUAL,
			NUMULTIDENTCBAIXAOPERAC, NUMULTREFBAIXAOPERAC, NUMULTSEQBAIXAOPERAC, NUMULTIDENTCBAIXAEFETIVA, NUMULTREFBAIXAEFETIVA, NUMULTSEQBAIXAEFETIVA, CODSITUACAOTIT,
			DATAHORADDA, DATAMOVTO, CODPROCESSA, DATAMANUTENCAO, TIPORETORNO, NOMEARQRET, INDIMPORTACAOVALIDA)
		VALUES (@NUMCTRLDDA, @NUMIDENTCDDA, @NUMREFALTCADTIT, @DATAHORASITUACAOTITULO, @NUMIDENTCBAIXAOPERAC, @DATAHORACANCELAMENTOBAIXA, @QTDPAGTOREGTD, @VLRSALDOATUAL,
				@NUMULTIDENTCBAIXAOPERAC, @NUMULTREFBAIXAOPERAC, @NUMULTSEQBAIXAOPERAC, @NUMULTIDENTCBAIXAEFETIVA, @NUMULTREFBAIXAEFETIVA, @NUMULTSEQBAIXAEFETIVA, @CODSITUACAOTIT,
				@DATAHORADDA, @DATAMOVTO, @CODPROCESSA, @DATAMANUTENCAO, @TIPORETORNO, @NOMEARQRET, @INDIMPORTACAOVALIDA)

	SELECT @SEQ_RECEBE = @@IDENTITY
END
GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO], 
	[NOMESCRIPT], 
	[CODUSUARIO], 
	[DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_INCLUI_RECEBE_ADDA115_RR2_CAT505', 
	SYSTEM_USER, 
	GETDATE() 
GO
