USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_INCLUI_RECEBE_ADDA116_RR2')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_INCLUI_RECEBE_ADDA116_RR2 AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE dbo.SP_INCLUI_RECEBE_ADDA116_RR2
(
	/*
		23/03/2023 - RFAQUINI - CRIAÇÃO
	*/

	@NUMCTRLDDA VARCHAR(20),
	@NUMIDENTCDDA NUMERIC(19, 0),
	@NUMREFALTCADTIT NUMERIC(19, 0),
	@DATAHORASITUACAO DATETIME,
	
	@NUMIDENTCBAIXA NUMERIC(19, 0),
	@DATAHORACANCELAMENTOBAIXA DATETIME,
	@CODMOTIVO VARCHAR(3),
	@QTDPAGTOREGTD INT,
	
	@VLRSALDOATUAL NUMERIC(19, 5),
	@NUMULTIDENTCBAIXA NUMERIC(19, 0),
	@SITPAGTO VARCHAR(2),
	@DATAHORADDA DATETIME,
	
	@DATAMOVTO DATETIME,
	@CODPROCESSA VARCHAR(1),
	@DATAMANUTENCAO DATETIME,
	@TIPORETORNO VARCHAR(1),
	
	@NOMEARQRET VARCHAR(255),
	@INDIMPORTACAOVALIDA CHAR(1),
	
	@SEQ_RECEBE NUMERIC(15, 0) OUTPUT
) AS BEGIN

	/*
		02/03/2023 - RFAQUINI - CRIAÇÃO (CATÁLOGO 5.06 - Modernização da Cobrança)
	*/
	
	INSERT INTO RECEBE_ADDA116_RR2(
		NUMCTRLDDA, NUMIDENTCDDA, NUMREFALTCADTIT, DATAHORASITUACAO, 
		NUMIDENTCBAIXA, DATAHORACANCELAMENTOBAIXA, CODMOTIVO, QTDPAGTOREGTD, 
		VLRSALDOATUAL, NUMULTIDENTCBAIXA, SITPAGTO, DATAHORADDA,
		DATAMOVTO, CODPROCESSA, DATAMANUTENCAO, TIPORETORNO, 
		NOMEARQRET, INDIMPORTACAOVALIDA
	) VALUES (
		@NUMCTRLDDA, @NUMIDENTCDDA, @NUMREFALTCADTIT, @DATAHORASITUACAO, 
		@NUMIDENTCBAIXA, @DATAHORACANCELAMENTOBAIXA, @CODMOTIVO, @QTDPAGTOREGTD, 
		@VLRSALDOATUAL, @NUMULTIDENTCBAIXA, @SITPAGTO, @DATAHORADDA, 
		@DATAMOVTO, @CODPROCESSA, @DATAMANUTENCAO, @TIPORETORNO, 
		@NOMEARQRET, @INDIMPORTACAOVALIDA
	)

	SELECT @SEQ_RECEBE = @@IDENTITY
END
GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO], 
	[NOMESCRIPT], 
	[CODUSUARIO], 
	[DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_INCLUI_RECEBE_ADDA116_RR2', 
	SYSTEM_USER, 
	GETDATE() 
GO

