USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_INCLUI_RECEBE_ADDA118_RECUSADOS')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_INCLUI_RECEBE_ADDA118_RECUSADOS AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE SP_INCLUI_RECEBE_ADDA118_RECUSADOS(
	@P_DATAMOVTO DATETIME,
	@P_NUMPEDIDO NUMERIC(10),
	@P_NUMIDENTCDDA NUMERIC(19),
	@P_NUMREFBAIXAEFET NUMERIC(19),
	--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)
	@P_TIPOBAIXA VARCHAR(2),
	@P_ISPBSACADA VARCHAR(8),
	@P_CODIFSACADA VARCHAR(3),
	@P_DATAPAGTOBAIXA DATETIME,
	@P_DATAHORAPAGTOBAIXA DATETIME,
	@P_VLRPAGTOBAIXA NUMERIC(19,5),
	@P_NUMCODBARRAS VARCHAR(44),
	@P_CANALPAGTO CHAR(1),
	@P_MEIOPAGTO CHAR(1),
	@P_NUMIDENTCBAIXAOPERAC NUMERIC(19),
	@P_CODPROCESSA CHAR(1),
	@P_DATAMANUTENCAO DATETIME,
	@P_TIPORETORNO CHAR(1),
	@P_NOMEARQRET VARCHAR(255),
	@P_INDIMPORTACAOVALIDA CHAR(1),
	@P_NUMREFCADTIT NUMERIC(19),
	@P_SEQ_RECEBE NUMERIC(15) OUT
) AS
BEGIN

	/*
		28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)
	*/

	INSERT INTO RECEBE_DDA0118_ADDA118_RECUSADOS
	( 
		DATAMOVTO,			NUMPEDIDO,				NUMIDENTCDDA,				NUMREFBAIXAEFET,			TIPOBAIXA,
		ISPBSACADA,			CODIFSACADA, 			DATAPAGTOBAIXA,				DATAHORAPAGTOBAIXA,			VLRPAGTOBAIXA,
		NUMCODBARRAS,		CANALPAGTO,				MEIOPAGTO, 					NUMIDENTCBAIXAOPERAC,		CODPROCESSA,
		DATAMANUTENCAO,		TIPORETORNO,			NOMEARQRET, 				INDIMPORTACAOVALIDA,		NUMREFCADTIT
	) 
	VALUES 
	(
		@P_DATAMOVTO,		@P_NUMPEDIDO,			@P_NUMIDENTCDDA,			@P_NUMREFBAIXAEFET,			@P_TIPOBAIXA,
		@P_ISPBSACADA,		@P_CODIFSACADA,			@P_DATAPAGTOBAIXA,			@P_DATAHORAPAGTOBAIXA,		@P_VLRPAGTOBAIXA,
		@P_NUMCODBARRAS,	@P_CANALPAGTO,			@P_MEIOPAGTO,				@P_NUMIDENTCBAIXAOPERAC,	@P_CODPROCESSA,
		@P_DATAMANUTENCAO,  @P_TIPORETORNO,			@P_NOMEARQRET,				@P_INDIMPORTACAOVALIDA,		@P_NUMREFCADTIT
	)

	SELECT @P_SEQ_RECEBE = @@IDENTITY

END
GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO], 
    [NOMESCRIPT], 
    [CODUSUARIO], 
    [DATAATU]
)
SELECT
	'V15_01_1_01B', 
	'SP_INCLUI_RECEBE_ADDA118_RECUSADOS', 
	SYSTEM_USER, 
	GETDATE() 
GO