USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_INCLUI_RECEBE_ADDA114_RET_RECUSADOS')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_INCLUI_RECEBE_ADDA114_RET_RECUSADOS AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE dbo.SP_INCLUI_RECEBE_ADDA114_RET_RECUSADOS
(
	@DATAMOVTO DATETIME, 
	@NUMPEDIDO NUMERIC(10, 0), 
	@CODPROCESSA CHAR(1), 
	@TIPORETORNO CHAR(2), 
	@NOMEARQRET VARCHAR(255), 
	@CODIFSACADA VARCHAR(3), 
	@ISPBIFSACADA VARCHAR(8), 
	--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)
	@TIPOBAIXATIT VARCHAR(2), 
	@DATAHORABAIXA DATETIME, 
	@DATAPAGTOBAIXA DATETIME, 
	@VLRPAGTOBAIXA NUMERIC(19, 5), 
	@NUMCODBARRAS VARCHAR(44), 
	@CANALPAGTO VARCHAR(1), 
	@MEIOPAGTO VARCHAR(1), 
	@INDCONTIGENCIA VARCHAR(1), 
	
	--16/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)	
	@ISPBINICIADORPAGTO VARCHAR(8),
	
	@TIPOPESPORTADOR VARCHAR(1), 
	@CPNJ_CPF_PORTADOR VARCHAR(14), 
	
	--03/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
	@NOME_PORTADOR VARCHAR(80),
	
	--16/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)	
	@TIPOPESAGREGADOR CHAR(1),
	@CNPJ_CPF_AGREGADOR VARCHAR(14),
	@NOMEAGREGADOR VARCHAR(50),
	@AGENCIARECEBEDORA VARCHAR(4),
	
	--26/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)		
	@DATAHORARECBTTITULO DATETIME, 
	
	@SEQ_RECEBE NUMERIC(15, 0) OUTPUT
) AS BEGIN

	/*
		03/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
								REMOÇÃO DE ALIAS
								
		26/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)	

		16/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)	
		
		28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)
	*/
	
	INSERT INTO RECEBE_ADDA114_RET_RECUSADOS(
		DATAMANUTENCAO, CODREJEICAO, DATAMOVTO, NUMPEDIDO, 
		CODPROCESSA, TIPORETORNO, NOMEARQRET, CODIFSACADA, 
		ISPBIFSACADA, TIPOBAIXATIT, DATAHORABAIXA, DATAPAGTOBAIXA, 
		VLRPAGTOBAIXA, NUMCODBARRAS, CANALPAGTO, MEIOPAGTO, 
		INDCONTINGENCIA, 

		--16/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)	
		ISPBINICIADORPAGTO,
		
		TIPOPESPORTADOR, CNPJ_CPF_PORTADOR,
		
		--03/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
		NOME_PORTADOR, 	

		--16/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)	
		TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, AGENCIARECEBEDORA,
		
		--26/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)		
		DATAHORARECBTTITULO, 

		INDIMPORTACAOVALIDA		
	) 
	VALUES (
		GETDATE(), NULL, @DATAMOVTO, @NUMPEDIDO, 
		@CODPROCESSA, @TIPORETORNO, @NOMEARQRET, @CODIFSACADA, 
		@ISPBIFSACADA, @TIPOBAIXATIT, @DATAHORABAIXA, @DATAPAGTOBAIXA, 
		@VLRPAGTOBAIXA, @NUMCODBARRAS, @CANALPAGTO, @MEIOPAGTO, 
		@INDCONTIGENCIA, 
		
		--16/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)	
		@ISPBINICIADORPAGTO,
		
		@TIPOPESPORTADOR, @CPNJ_CPF_PORTADOR, 
		
		--03/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
		@NOME_PORTADOR,
		
		--16/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)	
		@TIPOPESAGREGADOR, @CNPJ_CPF_AGREGADOR, @NOMEAGREGADOR, @AGENCIARECEBEDORA,
	
		--26/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)		
		@DATAHORARECBTTITULO, 
		
		CASE
			WHEN @TIPORETORNO = 'M' 
				THEN 'S'
			ELSE NULL
		END
	)

	SELECT @SEQ_RECEBE = @@IDENTITY
END
GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO], 
	[NOMESCRIPT], 
	[CODUSUARIO], 
	[DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_INCLUI_RECEBE_ADDA114_RET_RECUSADOS', 
	SYSTEM_USER, 
	GETDATE() 
GO