USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_INCLUI_RECEBE_ADDA108_RR2_CAT505')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_INCLUI_RECEBE_ADDA108_RR2_CAT505 AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE dbo.SP_INCLUI_RECEBE_ADDA108_RR2_CAT505
(
	@NUMIDENTCDDA NUMERIC(19, 0),
	@NUMREFCADTITBAIXAOPERAC NUMERIC(19, 0),
	@NUMREFALTCADTIT NUMERIC(19, 0),			
	@NUMIDENTCBAIXAOPERAC NUMERIC(19, 0),
	@NUMREFBAIXAOPERAC NUMERIC(19, 0),
	@NUMSEQBAIXAOPERAC NUMERIC(19, 0),
	@NUMCTRLDDA VARCHAR(20),
	--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)	
	@TIPOBAIXATIT VARCHAR(2),
	@ISPBIFSACADA VARCHAR(8),
	@CODIFSACADA VARCHAR(3),
	@TIPOPESPORTADOR VARCHAR(1),
	@CNPJ_CPF_PORTADOR VARCHAR(14),
	--04/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
	@NOME_PORTADOR VARCHAR(80),
	--25/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
	@DATAHORARECBTTITULO DATETIME,
	@DATAHORABAIXAOPERAC DATETIME,
	@DATABAIXAOPERAC DATETIME,
	@VLRBAIXAOPERAC NUMERIC(19, 5),
	@NUMCODBARRASBAIXAOPE VARCHAR(44),
	@CANALPAGTO VARCHAR(1),
	@MEIOPAGTO VARCHAR(1),
	@DATAHORASITBAIXAOPERAC DATETIME,
	@INDCONTINGENCIA VARCHAR(1),
	@QTDPAGTOREGTD INT,
	@VLRSALDOATUAL NUMERIC(19, 5),
	@CODSITUACAOTIT VARCHAR(2),
	@DATAHORADDA DATETIME,
	@DATAMOVTO DATETIME,
	@CODPROCESSA VARCHAR(1),
	@DATAMANUTENCAO DATETIME,
	@TIPORETORNO VARCHAR(1),
	@NOMEARQRET VARCHAR(255),
	@INDIMPORTACAOVALIDA CHAR(1),
	@SEQ_RECEBE NUMERIC(15, 0) OUTPUT
) AS BEGIN

	/*
		04/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
								REMOÇÃO DE ALIAS
		
		25/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
		
		28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)	
	*/
	
	INSERT INTO RECEBE_ADDA108_RR2 (
		NUMIDENTCDDA, NUMREFCADTITBAIXAOPERAC, NUMREFALTCADTIT, NUMIDENTCBAIXAOPERAC, 
		NUMREFBAIXAOPERAC, NUMSEQBAIXAOPERAC, NUMCTRLDDA, TIPOBAIXATIT, 
		ISPBIFSACADA, CODIFSACADA, TIPOPESPORTADOR, CNPJ_CPF_PORTADOR, 
		--04/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
		--25/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
		NOME_PORTADOR, DATAHORARECBTTITULO, DATAHORABAIXAOPERAC, DATABAIXAOPERAC, 
		VLRBAIXAOPERAC, NUMCODBARRASBAIXAOPE, CANALPAGTO, MEIOPAGTO,
		DATAHORASITUACAOBAIXAOPERAC, INDCONTINGENCIA, QTDPAGTOREGTD, VLRSALDOATUAL, 
		CODSITUACAOTIT, DATAHORADDA, DATAMOVTO, CODPROCESSA, 
		DATAMANUTENCAO, TIPORETORNO, NOMEARQRET, INDIMPORTACAOVALIDA
	)
	VALUES (
		@NUMIDENTCDDA, @NUMREFCADTITBAIXAOPERAC, @NUMREFALTCADTIT, @NUMIDENTCBAIXAOPERAC, 
		@NUMREFBAIXAOPERAC, @NUMSEQBAIXAOPERAC, @NUMCTRLDDA, @TIPOBAIXATIT, 
		@ISPBIFSACADA, @CODIFSACADA, @TIPOPESPORTADOR, @CNPJ_CPF_PORTADOR,
		--04/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
		--25/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
		@NOME_PORTADOR, @DATAHORARECBTTITULO, @DATAHORABAIXAOPERAC, @DATABAIXAOPERAC, 
		@VLRBAIXAOPERAC, @NUMCODBARRASBAIXAOPE, @CANALPAGTO, @MEIOPAGTO,
		@DATAHORASITBAIXAOPERAC, @INDCONTINGENCIA, @QTDPAGTOREGTD, @VLRSALDOATUAL, 
		@CODSITUACAOTIT, @DATAHORADDA, @DATAMOVTO, @CODPROCESSA, 
		@DATAMANUTENCAO, @TIPORETORNO, @NOMEARQRET, @INDIMPORTACAOVALIDA
	)

	SELECT @SEQ_RECEBE = @@IDENTITY
END
GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO], 
	[NOMESCRIPT], 
	[CODUSUARIO], 
	[DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_INCLUI_RECEBE_ADDA108_RR2_CAT505', 
	SYSTEM_USER, 
	GETDATE() 
GO