USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_INCLUI_RECEBE_ADDA108_RET_RECUSADOS')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_INCLUI_RECEBE_ADDA108_RET_RECUSADOS AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE dbo.SP_INCLUI_RECEBE_ADDA108_RET_RECUSADOS
(
	@P_DATAMOVTO DATETIME, 
	@P_NUMPEDIDO NUMERIC(10, 0), 
	@P_NUMIDENTCDDA NUMERIC(19, 0), 
	@P_CODPROCESSA CHAR(1), 
	@P_TIPORETORNO CHAR(2), 			
	@P_NOMEARQRET VARCHAR(255), 
	--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)
	@P_TIPOBAIXATIT VARCHAR(2), 
	@P_ISPBIFSACADA VARCHAR(8), 
	@P_CODIFSACADA VARCHAR(3), 
	@P_TIPOPESPORTADOR VARCHAR(1), 
	@P_CNPJ_CPF_PORTADOR VARCHAR(14), 
	
	--03/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
	@P_NOME_PORTADOR VARCHAR(80), 
	
	--16/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)	
	@P_TIPOPESAGREGADOR CHAR(1),
	@P_CNPJ_CPF_AGREGADOR VARCHAR(14),
	@P_NOMEAGREGADOR VARCHAR(50),
	@P_AGENCIARECEBEDORA VARCHAR(4),
	
	--23/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
	@P_DATAHORARECBTTITULO DATETIME, 
	
	@P_DATAHORABAIXA DATETIME, 
	@P_DATAPAGTOBAIXA DATETIME, 
	@P_VLRPAGTOBAIXA NUMERIC(19, 5), 
	@P_NUMCODBARRAS VARCHAR(44), 
	@P_CANALPAGTO VARCHAR(1), 
	@P_MEIOPAGTO VARCHAR(1), 
	@P_INDCONTINGENCIA VARCHAR(1), 
	
	--16/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)	
	@P_ISPBINICIADORPAGTO VARCHAR(8),
	
	@P_SEQ_RECEBE NUMERIC(15, 0) OUTPUT
) AS BEGIN
	
	/*
		03/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
								REMOÇÃO DE ALIAS
		
		23/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
		
		16/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
								ADEQUAÇÃO AO CATÁLOGO DA MODERNIZAÇÃO DE COBRANÇA (CATÁLOGO 5.06 - Modernização da Cobrança)
								REMOÇÃO E TRATAMENTO DOS CAMPOS
									@P_NUMREFCADTIT NUMERIC(19, 0), 
									@P_NUMREFBAIXAOPERAC NUMERIC(19, 0), 
								INCLUSÃO E TRATAMENTO DOS CAMPOS
								
		28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)
	*/
	
	INSERT INTO RECEBE_ADDA108_RET_RECUSADOS (
		DATAMANUTENCAO, CODREJEICAO, DATAMOVTO, NUMPEDIDO, 
		NUMIDENTCDDA, CODPROCESSA, TIPORETORNO, NOMEARQRET, 
		TIPOBAIXATIT, ISPBIFSACADA, CODIFSACADA, TIPOPESPORTADOR, 
		CNPJ_CPF_PORTADOR, 
		
		--03/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
		NOME_PORTADOR, 
		
		--16/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)	
		TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, AGENCIARECEBEDORA,
	
		--23/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
		DATAHORARECBTTITULO, DATAHORABAIXA, DATAPAGTOBAIXA, VLRPAGTOBAIXA, 
		NUMCODBARRAS, CANALPAGTO, MEIOPAGTO, INDCONTINGENCIA, 
		
		--16/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)	
		ISPBINICIADORPAGTO,
	
		INDIMPORTACAOVALIDA
	) 
	VALUES (
		GETDATE(), NULL, @P_DATAMOVTO, @P_NUMPEDIDO, 
		@P_NUMIDENTCDDA, @P_CODPROCESSA, @P_TIPORETORNO, @P_NOMEARQRET, 
		@P_TIPOBAIXATIT, @P_ISPBIFSACADA, @P_CODIFSACADA, @P_TIPOPESPORTADOR, 
		@P_CNPJ_CPF_PORTADOR,

		--03/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
		@P_NOME_PORTADOR, 
		
		--16/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)	
		@P_TIPOPESAGREGADOR, @P_CNPJ_CPF_AGREGADOR, @P_NOMEAGREGADOR, @P_AGENCIARECEBEDORA,
		
		--23/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
		@P_DATAHORARECBTTITULO, @P_DATAHORABAIXA, @P_DATAPAGTOBAIXA, @P_VLRPAGTOBAIXA, 
		@P_NUMCODBARRAS, @P_CANALPAGTO, @P_MEIOPAGTO, @P_INDCONTINGENCIA, 
		
		--16/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)	
		@P_ISPBINICIADORPAGTO,
	
		CASE
			WHEN @P_TIPORETORNO = 'M' 
				THEN 'S'
			ELSE NULL
		END
	)

	SELECT @P_SEQ_RECEBE = @@IDENTITY
END
GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO], 
	[NOMESCRIPT], 
	[CODUSUARIO], 
	[DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_INCLUI_RECEBE_ADDA108_RET_RECUSADOS', 
	SYSTEM_USER, 
	GETDATE() 
GO