USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_INCLUI_RECEBE_ADDA114_RET_RECUSADOS_CAT505')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_INCLUI_RECEBE_ADDA114_RET_RECUSADOS_CAT505 AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE dbo.SP_INCLUI_RECEBE_ADDA114_RET_RECUSADOS_CAT505
(
	@DATAMOVTO DATETIME, 
	@NUMPEDIDO NUMERIC(10, 0), 
	@CODPROCESSA CHAR(1), 
	@TIPORETORNO CHAR(2), 
	@NOMEARQRET VARCHAR(255), 
	@CODIFSACADA VARCHAR(3), 
	@ISPBIFSACADA VARCHAR(8), 
	--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)	
	@TIPOBAIXATIT VARCHAR(2), 
	@DATAHORABAIXA DATETIME, 
	@DATAPAGTOBAIXA DATETIME, 
	@VLRPAGTOBAIXA NUMERIC(19, 5), 
	@NUMCODBARRAS VARCHAR(44), 
	@CANALPAGTO VARCHAR(1), 
	@MEIOPAGTO VARCHAR(1), 
	@INDCONTIGENCIA VARCHAR(1), 
	@TIPOPESPORTADOR VARCHAR(1), 
	@CPNJ_CPF_PORTADOR VARCHAR(14), 
	--03/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
	@NOME_PORTADOR VARCHAR(80),
	--26/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)		
	@DATAHORARECBTTITULO DATETIME, 
	@SEQ_RECEBE NUMERIC(15, 0) OUTPUT
) AS BEGIN

	/*
		03/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
								REMOÇÃO DE ALIAS
								
		26/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)		
		
		28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)	
	*/
	
	INSERT INTO RECEBE_ADDA114_RET_RECUSADOS(
		DATAMANUTENCAO, CODREJEICAO, DATAMOVTO, NUMPEDIDO, 
		CODPROCESSA, TIPORETORNO, NOMEARQRET, CODIFSACADA, 
		ISPBIFSACADA, TIPOBAIXATIT, DATAHORABAIXA, DATAPAGTOBAIXA, 
		VLRPAGTOBAIXA, NUMCODBARRAS, CANALPAGTO, MEIOPAGTO, 
		--03/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
		INDCONTINGENCIA, TIPOPESPORTADOR, CNPJ_CPF_PORTADOR, NOME_PORTADOR, 	
		--26/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)		
		DATAHORARECBTTITULO, 
		INDIMPORTACAOVALIDA
		
	) 
	VALUES (
		GETDATE(), NULL, @DATAMOVTO, @NUMPEDIDO, 
		@CODPROCESSA, @TIPORETORNO, @NOMEARQRET, @CODIFSACADA, 
		@ISPBIFSACADA, @TIPOBAIXATIT, @DATAHORABAIXA, @DATAPAGTOBAIXA, 
		@VLRPAGTOBAIXA, @NUMCODBARRAS, @CANALPAGTO, @MEIOPAGTO, 
		--03/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
		@INDCONTIGENCIA, @TIPOPESPORTADOR, @CPNJ_CPF_PORTADOR, @NOME_PORTADOR,
		--26/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)		
		@DATAHORARECBTTITULO, 
		CASE
			WHEN @TIPORETORNO = 'M' 
				THEN 'S'
			ELSE NULL
		END
	)

	SELECT @SEQ_RECEBE = @@IDENTITY
END
GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO], 
	[NOMESCRIPT], 
	[CODUSUARIO], 
	[DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_INCLUI_RECEBE_ADDA114_RET_RECUSADOS_CAT505', 
	SYSTEM_USER, 
	GETDATE() 
GO