USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_LIMPEZA_DIARIA_REC')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_LIMPEZA_DIARIA_REC AS BEGIN RETURN END')
END
GO
ALTER PROCEDURE dbo.SP_LIMPEZA_DIARIA_REC   
AS  
BEGIN  
  
 /*  
  PROCEDURE DE LIMPEZA DAS TABELAS DE ARQUIVOS E MENSAGENS DOS EVENTOS   
   - DDA/ADDA_0101  
   - DDA/ADDA_0102  
   - DDA/ADDA 108  
  Lógica de funcionamento  
   # Aceitos:   
    - movimenta os registros da RECEBE_cod_evento_ACEITOS para a respectiva pass,   
    usando a temp da tabela principal para movimentar dos registros  
   # Recusados:   
    - movimenta os registros das tabelas secundárias e da RECEBE_cod_evento_RECUSADOS (principal) para a respectiva pass,   
    usando a temp da tabela principal para movimentar dos registros  
  
  --15/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOME_PORTADOR E DATAHORARECBTTITULO (CATÁLOGOS 5.03 E 5.04)  

  --21/03/2023 - JLSANTOS - INCLUSÃO NA RECEBE_ADDA108_RR2_PASS E TRATAMENTO DOS CAMPOS TIPOPESAGREGADOR, NOMEAGREGADOR, AGENCIARECEBEDORA E CNPJ_CPF_AGREGADOR (CATÁLOGO 5.06)
 */  
  
 DECLARE @MSGERRO VARCHAR(255)  
  
 DECLARE @DATALIMPEZA DATETIME, @DATAPROCESSAMENTO DATETIME, @DATAHORA DATETIME, @SQLERRO INTEGER, @INDLIMPEZA CHAR,
		 @QTD_REG_DIARIA_REC INT

 SELECT @QTD_REG_DIARIA_REC = QTD_REG_DIARIA  
 FROM PARAMETROS_LIMPEZA 
 WHERE NOME_PROCESSO = 'SP_LIMPEZA_DIARIA_REC' 
  
 SELECT @DATALIMPEZA = DATEADD (DD, -30,DATAPROCESSAMENTO), @DATAPROCESSAMENTO = DATAPROCESSAMENTO,   
  @DATAHORA = GETDATE(), @INDLIMPEZA = ISNULL(INDLIMPEZA,'N')  
  FROM PARAMETROS  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 IF (@INDLIMPEZA = 'N' OR DATEDIFF (DD, @DATAPROCESSAMENTO,  @DATAHORA) < -7 ) /* NÃO EXECUTA LIMPEZA SE A DATAPROCESSAMENTO FOR MAIOR QUE 7 DIAS DO RELÓGIO */  
 RETURN   
  
 -- ######################################################### ADDA101 ACEITOS #########################################################   
  
 -------------------------------------------------- LIMPEZA RECEBE_ADDA101_RET_ACEITOS --------------------------------------------------   
  
 -- #TMP_RECEBE_ADDA101_RET_ACEITOS_SEL   
 SELECT TOP (@QTD_REG_DIARIA_REC) SEQ_RECEBE, NUMPEDIDO, DATAMOVTO   
   INTO #TMP_RECEBE_ADDA101_RET_ACEITOS_SEL   
   FROM RECEBE_ADDA101_RET_ACEITOS  
    WHERE DATAMOVTO < @DATALIMPEZA  
   ORDER BY DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 CREATE NONCLUSTERED INDEX IDX_RECEBE_ADDA101_RET_ACEITOS_SEL ON dbo.#TMP_RECEBE_ADDA101_RET_ACEITOS_SEL  
  (SEQ_RECEBE, NUMPEDIDO, DATAMOVTO)  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 INSERT INTO RECEBE_ADDA101_RET_ACEITOS_PASS  
  (  
   DATALIMPEZA,  NUMCTRLDDA,    DATAMOVTO,    NUMPEDIDO,   NUMIDENTCDDA,  
   CODPROCESSA,  CODREJEICAO,   TIPOMANUTENCAOTIT,  DATAMANUTENCAO,  TIPORETORNO,  
   NOMEARQRET,   INDIMPORTACAOVALIDA, NUMREFCADTIT,   NUMSEQCADTIT,  NUMCODBARRAS,  
   DATAHORADDA,  SEQ_RECEBE  
  )  
  SELECT   
   @DATAPROCESSAMENTO, R.NUMCTRLDDA,   R.DATAMOVTO,   R.NUMPEDIDO,  R.NUMIDENTCDDA,  
   R.CODPROCESSA,  R.CODREJEICAO,   R.TIPOMANUTENCAOTIT, R.DATAMANUTENCAO, R.TIPORETORNO,  
   R.NOMEARQRET,  R.INDIMPORTACAOVALIDA, R.NUMREFCADTIT,   R.NUMSEQCADTIT,  R.NUMCODBARRAS,  
   R.DATAHORADDA,  R.SEQ_RECEBE  
  FROM RECEBE_ADDA101_RET_ACEITOS R  
   INNER JOIN #TMP_RECEBE_ADDA101_RET_ACEITOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
    AND R.NUMPEDIDO = SEL.NUMPEDIDO  
    AND R.DATAMOVTO = SEL.DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
   
 DELETE R FROM RECEBE_ADDA101_RET_ACEITOS R  
  INNER JOIN #TMP_RECEBE_ADDA101_RET_ACEITOS_SEL SEL  
  ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
  AND R.NUMPEDIDO = SEL.NUMPEDIDO  
  AND R.DATAMOVTO = SEL.DATAMOVTO  
     
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DROP INDEX IDX_RECEBE_ADDA101_RET_ACEITOS_SEL ON dbo.#TMP_RECEBE_ADDA101_RET_ACEITOS_SEL  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DROP TABLE #TMP_RECEBE_ADDA101_RET_ACEITOS_SEL  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 /* ############################################### LIMPEZA DDA/ADDA101 RECUSADOS    ##########################################################  
 -- limpeza dos registros das tabelas secundárias relacionados aos registros recusados da principal (RECEBE_ADDA101_RET_RECUSADOS)  
  -- RECEBE_CALCULOS_ADDA0101_RET  
  -- RECEBE_MENSAGENS_ADDA101_RET  
  -- RECEBE_NOTAS_FISCAIS_ADDA101_RET  
  Após a limpeza das tabelas secundárias, limpa-se a principal  
 */  
 -- TEMP DA TABELA #TMP_RECEBE_ADDA101_RET_RECUSADOS_SEL   
 SELECT TOP (@QTD_REG_DIARIA_REC)   
   SEQ_RECEBE, NUMPEDIDO, DATAMOVTO  
   INTO #TMP_RECEBE_ADDA101_RET_RECUSADOS_SEL   
   FROM RECEBE_ADDA101_RET_RECUSADOS  
    WHERE DATAMOVTO < @DATALIMPEZA  
   ORDER BY DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
   
 CREATE NONCLUSTERED INDEX IDX_RECEBE_ADDA101_RET_RECUSADOS_SEL ON dbo.#TMP_RECEBE_ADDA101_RET_RECUSADOS_SEL  
  (SEQ_RECEBE, NUMPEDIDO, DATAMOVTO)  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
    
 INSERT INTO RECEBE_CALCULOS_ADDA0101_RET_PASS   
  (  
   DATALIMPEZA,  SEQ_RECEBE,  NUMIDENTCDDA, DATAMOVTO,  DATAHORADDA,  
   NUMPEDIDO,    DATAVALCALC, VLRJUROS,  VLRMULTA,  VLRDESC,  
   VLRCOBRAR,   TIPORETORNO, NOMEARQRET  
  )  
  SELECT   
   @DATAPROCESSAMENTO, R.SEQ_RECEBE, R.NUMIDENTCDDA, R.DATAMOVTO, R.DATAHORADDA,  
   R.NUMPEDIDO,  R.DATAVALCALC, R.VLRJUROS,  R.VLRMULTA,  R.VLRDESC,  
   R.VLRCOBRAR,  R.TIPORETORNO, R.NOMEARQRET  
  FROM RECEBE_CALCULOS_ADDA0101_RET R  
   INNER JOIN #TMP_RECEBE_ADDA101_RET_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
     
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 INSERT INTO RECEBE_MENSAGENS_ADDA101_RET_PASS   
  (   
   DATALIMPEZA,  SEQ_RECEBE,  NUMCTRLDDA,  DATAMOVTO,  NUMIDENTCDDA,  
   NUMPEDIDO,   SEQMENSAGEM, TEXTO,   CODPROCESSA, CODREJEICAO,  
   TIPORETORNO,  NOMEARQRET  
  )  
  SELECT   
   @DATAPROCESSAMENTO, R.SEQ_RECEBE, R.NUMCTRLDDA, R.DATAMOVTO, R.NUMIDENTCDDA,  
   R.NUMPEDIDO,  R.SEQMENSAGEM, R.TEXTO,  R.CODPROCESSA, R.CODREJEICAO,  
   R.TIPORETORNO,  R.NOMEARQRET  
  FROM RECEBE_MENSAGENS_ADDA101_RET R  
   INNER JOIN #TMP_RECEBE_ADDA101_RET_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
   
 INSERT INTO RECEBE_NOTAS_FISCAIS_ADDA101_RET_PASS   
  (   
   DATALIMPEZA,   SEQ_RECEBE,   NUMCTRLDDA,  DATAMOVTO,  NUMPEDIDO,  
   NUMIDENTCDDA,   NUMNOTAFISCAL,  DATAEMISSAO, VLRNOTAFISCAL, CODPROCESSA,  
   CODREJEICAO,   TIPORETORNO,  NOMEARQRET  
  )  
  SELECT  
   @DATAPROCESSAMENTO,  R.SEQ_RECEBE,  R.NUMCTRLDDA, R.DATAMOVTO,  R.NUMPEDIDO,  
   R.NUMIDENTCDDA,   R.NUMNOTAFISCAL, R.DATAEMISSAO, R.VLRNOTAFISCAL, R.CODPROCESSA,  
   R.CODREJEICAO,   R.TIPORETORNO,  R.NOMEARQRET  
  FROM RECEBE_NOTAS_FISCAIS_ADDA101_RET R  
  INNER JOIN #TMP_RECEBE_ADDA101_RET_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
  
     
  -- insert da pass da tabela principal dos títulos recusados para o evento 101  
 INSERT INTO RECEBE_ADDA101_RET_RECUSADOS_PASS   
  (  
   DATALIMPEZA,   SEQ_RECEBE,     NUMCTRLDDA,    DATAMOVTO,    NUMPEDIDO,  
   TIPOMANUTENCAOTIT,  NUMIDENTCDDA,    TIPOBAIXA,    DATAPAGTOBAIXA,   VLRPAGTOBAIXA,  
   NUMCODBARRAS,   CODIFSACADA,    CODIFCEDENTE,   TIPOPESCEDENTE,   CNPJ_CPF_CEDENTE,  
   NOMECEDENTE,   TIPOPESCEDENTEORI,   CNPJ_CPF_CEDENTEORI, NOMECEDENTEORI,   ENDCEDENTEORI,  
   CIDCEDENTEORI,   UFCEDENTEORI,    CEPCEDENTEORI,   TIPOPESSACADO,   CNPJ_CPF_SACADO,  
   NOMESACADO,    ENDSACADO,     CIDSACADO,    UFSACADO,    CEPSACADO,  
   TIPOPESSACADOR,   CNPJ_CPF_SACADOR,   NOMESACADOR,   CODCARTEIRA,   CODMOEDACNAB,  
   IDENTNOSSONUMERO,  DATAVENCIMENTO,    VLRTITULO,    SEUNUMERO,    CODESPECIEDOC,  
   DATAEMISSAO,   QTDEDIASPROTESTO,   DATALIMPAGTO,   TIPOPAGTO,    INDTITULONEGOCIADO,  
   VLRABATIMENTO,   DATAMORA,     CODMORA,    VLRPERCMORA,   CODMULTA,  
   DATAMULTA,    VLRPERCMULTA,    DATADESCONTO01,   CODDESCONTO01,   VLRPERCDESCONTO01,  
   DATADESCONTO02,   CODDESCONTO02,    VLRPERCDESCONTO02,  DATADESCONTO03,   CODDESCONTO03,  
   VLRPERCDESCONTO03,  VLRMINTITULO,    VLRMAXTITULO,   CODPROCESSA,   CODREJEICAO,  
   DATAMANUTENCAO,   TIPORETORNO,    NOMEARQRET,    INDIMPORTACAOVALIDA, LINHADIGITAVEL,  
   NUMPARCELA,    QTDPARCELA,     TIPOAUTRECDIVERGENTE, INDBLOQUEIO,   INDPARCIAL,  
   QTDPAGTO,    INDVALORPERC_MIN,   INDVALORPERC_MAX,  NUMREFCADTIT,   NUMSEQCADTIT,  
   NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI,  NOMEFANTASIASACADO,  TIPOCALCULO  
  )  
  SELECT   
   @DATAPROCESSAMENTO,  R.SEQ_RECEBE,    R.NUMCTRLDDA,   R.DATAMOVTO,   R.NUMPEDIDO,  
    R.TIPOMANUTENCAOTIT, R.NUMIDENTCDDA,    R.TIPOBAIXA,   R.DATAPAGTOBAIXA,  R.VLRPAGTOBAIXA,  
    R.NUMCODBARRAS,  R.CODIFSACADA,    R.CODIFCEDENTE,   R.TIPOPESCEDENTE,  R.CNPJ_CPF_CEDENTE,  
    R.NOMECEDENTE,   R.TIPOPESCEDENTEORI,  R.CNPJ_CPF_CEDENTEORI, R.NOMECEDENTEORI,  R.ENDCEDENTEORI,  
    R.CIDCEDENTEORI,  R.UFCEDENTEORI,    R.CEPCEDENTEORI,  R.TIPOPESSACADO,  R.CNPJ_CPF_SACADO,  
    R.NOMESACADO,   R.ENDSACADO,    R.CIDSACADO,   R.UFSACADO,    R.CEPSACADO,  
    R.TIPOPESSACADOR,  R.CNPJ_CPF_SACADOR,   R.NOMESACADOR,   R.CODCARTEIRA,   R.CODMOEDACNAB,  
    R.IDENTNOSSONUMERO, R.DATAVENCIMENTO,   R.VLRTITULO,   R.SEUNUMERO,   R.CODESPECIEDOC,  
    R.DATAEMISSAO,   R.QTDEDIASPROTESTO,   R.DATALIMPAGTO,   R.TIPOPAGTO,   R.INDTITULONEGOCIADO,  
    R.VLRABATIMENTO,  R.DATAMORA,     R.CODMORA,    R.VLRPERCMORA,   R.CODMULTA,  
    R.DATAMULTA,   R.VLRPERCMULTA,    R.DATADESCONTO01,  R.CODDESCONTO01,  R.VLRPERCDESCONTO01,  
    R.DATADESCONTO02,  R.CODDESCONTO02,   R.VLRPERCDESCONTO02, R.DATADESCONTO03,  R.CODDESCONTO03,  
    R.VLRPERCDESCONTO03, R.VLRMINTITULO,    R.VLRMAXTITULO,   R.CODPROCESSA,   R.CODREJEICAO,  
    R.DATAMANUTENCAO,  R.TIPORETORNO,    R.NOMEARQRET,   R.INDIMPORTACAOVALIDA, R.LINHADIGITAVEL,  
    R.NUMPARCELA,   R.QTDPARCELA,    R.TIPOAUTRECDIVERGENTE, R.INDBLOQUEIO,   R.INDPARCIAL,  
    R.QTDPAGTO,   R.INDVALORPERC_MIN,   R.INDVALORPERC_MAX,  R.NUMREFCADTIT,   R.NUMSEQCADTIT,  
    R.NOMEFANTASIACEDENTE, R.NOMEFANTASIACEDENTEORI, R.NOMEFANTASIASACADO, R.TIPOCALCULO  
  FROM RECEBE_ADDA101_RET_RECUSADOS R  
   INNER JOIN #TMP_RECEBE_ADDA101_RET_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
  
   
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DELETE R FROM RECEBE_CALCULOS_ADDA0101_RET R  
  INNER JOIN #TMP_RECEBE_ADDA101_RET_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DELETE R FROM RECEBE_MENSAGENS_ADDA101_RET R  
  INNER JOIN #TMP_RECEBE_ADDA101_RET_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
   
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
   
 DELETE R FROM RECEBE_NOTAS_FISCAIS_ADDA101_RET R  
  INNER JOIN #TMP_RECEBE_ADDA101_RET_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 -- limpeza da tabela principal dos  evento 101 dos títulos recusados  
 DELETE R FROM RECEBE_ADDA101_RET_RECUSADOS R  
  INNER JOIN #TMP_RECEBE_ADDA101_RET_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DROP INDEX IDX_RECEBE_ADDA101_RET_RECUSADOS_SEL ON dbo.#TMP_RECEBE_ADDA101_RET_RECUSADOS_SEL  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DROP TABLE #TMP_RECEBE_ADDA101_RET_RECUSADOS_SEL  
   
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
   
   
 -- ######################################################### ADDA102 #########################################################   
  
 -------------------------------------------------- LIMPEZA RECEBE_ADDA102_RET_ACEITOS --------------------------------------------------   
  
 -- #TMP_RECEBE_ADDA102_RET_ACEITOS_SEL   
 SELECT TOP (@QTD_REG_DIARIA_REC) SEQ_RECEBE, NUMPEDIDO, DATAMOVTO   
   INTO #TMP_RECEBE_ADDA102_RET_ACEITOS_SEL   
   FROM RECEBE_ADDA102_RET_ACEITOS  
    WHERE DATAMOVTO < @DATALIMPEZA  
   ORDER BY DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 CREATE NONCLUSTERED INDEX IDX_RECEBE_ADDA102_RET_ACEITOS_SEL ON dbo.#TMP_RECEBE_ADDA102_RET_ACEITOS_SEL  
  (SEQ_RECEBE, NUMPEDIDO, DATAMOVTO)  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
 INSERT INTO RECEBE_ADDA102_RET_ACEITOS_PASS  
  (  
   DATALIMPEZA,NUMCTRLDDA,DATAMOVTO,NUMPEDIDO,NUMIDENTCDDA,CODPROCESSA,CODREJEICAO,TIPOMANUTENCAOTIT,  
   DATAMANUTENCAO,TIPORETORNO,NOMEARQRET,INDIMPORTACAOVALIDA,NUMREFCADTIT,NUMSEQCADTIT,NUMCODBARRAS,DATAHORADDA,SEQ_RECEBE  
  )  
  SELECT   
   @DATAPROCESSAMENTO,R.NUMCTRLDDA,R.DATAMOVTO,R.NUMPEDIDO,R.NUMIDENTCDDA,R.CODPROCESSA,R.CODREJEICAO,R.TIPOMANUTENCAOTIT,  
   R.DATAMANUTENCAO,R.TIPORETORNO,R.NOMEARQRET,R.INDIMPORTACAOVALIDA,R.NUMREFCADTIT,R.NUMSEQCADTIT,R.NUMCODBARRAS,R.DATAHORADDA,R.SEQ_RECEBE  
  FROM RECEBE_ADDA102_RET_ACEITOS R  
   INNER JOIN #TMP_RECEBE_ADDA102_RET_ACEITOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
    AND R.NUMPEDIDO = SEL.NUMPEDIDO  
    AND R.DATAMOVTO = SEL.DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
   
 DELETE R FROM RECEBE_ADDA102_RET_ACEITOS R  
  INNER JOIN #TMP_RECEBE_ADDA102_RET_ACEITOS_SEL SEL  
  ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
  AND R.NUMPEDIDO = SEL.NUMPEDIDO  
  AND R.DATAMOVTO = SEL.DATAMOVTO  
     
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DROP INDEX IDX_RECEBE_ADDA102_RET_ACEITOS_SEL ON dbo.#TMP_RECEBE_ADDA102_RET_ACEITOS_SEL  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DROP TABLE #TMP_RECEBE_ADDA102_RET_ACEITOS_SEL  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
  
  
  
 /* -------------------------------------------- LIMPEZA DDA/ADDA102 RECUSADOS ------------------------------------------------------  
 -- limpeza dos registros das tabelas secundárias relacionados aos registros recusados da principal (RECEBE_ADDA101_RET_RECUSADOS)  
  -- RECEBE_CALCULOS_ADDA0102_RET  
  -- RECEBE_MENSAGENS_ADDA102_RET  
  -- RECEBE_NOTAS_FISCAIS_ADDA102_RET  
  Após a limpeza das tabelas secundárias, limpa-se a principal  
 */  
 -- TEMP DA TABELA #TMP_RECEBE_ADDA101_RET_RECUSADOS_SEL   
 SELECT TOP (@QTD_REG_DIARIA_REC)   
   SEQ_RECEBE, NUMPEDIDO, DATAMOVTO  
   INTO #TMP_RECEBE_ADDA102_RET_RECUSADOS_SEL   
   FROM RECEBE_ADDA102_RET_RECUSADOS  
    WHERE DATAMOVTO < @DATALIMPEZA  
   ORDER BY DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
   
 CREATE NONCLUSTERED INDEX IDX_RECEBE_ADDA102_RET_RECUSADOS_SEL ON dbo.#TMP_RECEBE_ADDA102_RET_RECUSADOS_SEL  
  (SEQ_RECEBE, NUMPEDIDO, DATAMOVTO)  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
    
 INSERT INTO RECEBE_CALCULOS_ADDA0102_RET_PASS   
  (  
   DATALIMPEZA,  SEQ_RECEBE,  NUMIDENTCDDA, DATAMOVTO,  DATAHORADDA,  
   NUMPEDIDO,    DATAVALCALC, VLRJUROS,  VLRMULTA,  VLRDESC,  
   VLRCOBRAR,   TIPORETORNO, NOMEARQRET  
  )  
  SELECT   
   @DATAPROCESSAMENTO, R.SEQ_RECEBE, R.NUMIDENTCDDA, R.DATAMOVTO, R.DATAHORADDA,  
   R.NUMPEDIDO,  R.DATAVALCALC, R.VLRJUROS,  R.VLRMULTA,  R.VLRDESC,  
   R.VLRCOBRAR,  R.TIPORETORNO, R.NOMEARQRET  
  FROM RECEBE_CALCULOS_ADDA0102_RET R  
   INNER JOIN #TMP_RECEBE_ADDA102_RET_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
     
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 INSERT INTO RECEBE_MENSAGENS_ADDA102_RET_PASS   
  (   
   DATALIMPEZA,  SEQ_RECEBE,  NUMCTRLDDA,  DATAMOVTO,  NUMIDENTCDDA,  
   NUMPEDIDO,   SEQMENSAGEM, TEXTO,   CODPROCESSA, CODREJEICAO,  
   TIPORETORNO,  NOMEARQRET  
  )  
  SELECT  
   @DATAPROCESSAMENTO, R.SEQ_RECEBE, R.NUMCTRLDDA, R.DATAMOVTO, R.NUMIDENTCDDA,  
   R.NUMPEDIDO,   R.SEQMENSAGEM, R.TEXTO,  R.CODPROCESSA, R.CODREJEICAO,  
   R.TIPORETORNO,  R.NOMEARQRET  
  FROM RECEBE_MENSAGENS_ADDA102_RET R  
   INNER JOIN #TMP_RECEBE_ADDA102_RET_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 INSERT INTO RECEBE_NOTAS_FISCAIS_ADDA102_RET_PASS   
  (   
   DATALIMPEZA,   SEQ_RECEBE,   NUMCTRLDDA,   DATAMOVTO,   NUMPEDIDO,  
   NUMIDENTCDDA,   NUMNOTAFISCAL,  DATAEMISSAO,  VLRNOTAFISCAL,  CODPROCESSA,  
   CODREJEICAO,   TIPORETORNO,  NOMEARQRET  
  )  
  SELECT   
   @DATAPROCESSAMENTO,  R.SEQ_RECEBE,  R.NUMCTRLDDA, R.DATAMOVTO,  R.NUMPEDIDO,   
   R.NUMIDENTCDDA,   R.NUMNOTAFISCAL, R.DATAEMISSAO, R.VLRNOTAFISCAL, R.CODPROCESSA,   
   R.CODREJEICAO,   R.TIPORETORNO,  R.NOMEARQRET  
  FROM RECEBE_NOTAS_FISCAIS_ADDA102_RET R  
   INNER JOIN #TMP_RECEBE_ADDA102_RET_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 -- insert da pass da tabela principal dos títulos recusados para o evento 102  
 INSERT INTO RECEBE_ADDA102_RET_RECUSADOS_PASS   
  (  
   DATALIMPEZA,   SEQ_RECEBE,    NUMCTRLDDA,    DATAMOVTO,     NUMPEDIDO,  
   TIPOMANUTENCAOTIT,  NUMIDENTCDDA,   INDRMANUTBENFCRIOOR, NOMEFANTASIACEDENTEORI,  ENDCEDENTEORI,  
   CIDCEDENTEORI,   UFCEDENTEORI,   CEPCEDENTEORI,   INDRMANUTBENFCRIOFINL,  TIPOPESCEDENTE,  
   CNPJ_CPF_CEDENTE,  NOMECEDENTE,   NOMEFANTASIACEDENTE, TIPOPESSACADO,    CNPJ_CPF_SACADO,  
   INDRMANUTPAGDRTIT,  NOMESACADO,    NOMEFANTASIASACADO,  ENDSACADO,     CIDSACADO,   
   UFSACADO,    CEPSACADO,    INDRMANUTSACDRAVALST, TIPOPESSACADOR,    CNPJ_CPF_SACADOR,  
   NOMESACADOR,   INDRMANUTDOCTIT,  CODCARTEIRA,   CODESPECIEDOC,    SEUNUMERO,  
   TIPOPAGTO,    NUMPARCELA,    QTDPARCELA,    INDTITULONEGOCIADO,   INDRMANUTINSTCPGTOTIT,  
   DATAVENCIMENTO,   VLRTITULO,    QTDEDIASPROTESTO,  DATALIMPAGTO,    INDBLOQUEIO,  
   VLRABATIMENTO,   QTDPAGTO,    TIPOMODELOCALCULO,  INDRMANUTINSTCVLRRECBT,  TIPOAUTRECDIVERGENTE,  
   INDVALORPERC_MIN,  VLRMINTITULO,   INDVALORPERC_MAX,  VLRMAXTITULO,    INDRMANUTJUROSTIT,  
   DATAMORA,    CODMORA,    VLRPERCMORA,   INDRMANUTMULTATIT,   CODMULTA,  
   DATAMULTA,    VLRPERCMULTA,   INDRMANUTDESCTTIT,  DATADESCONTO01,    CODDESCONTO01,  
   VLRPERCDESCONTO01,  DATADESCONTO02,   CODDESCONTO02,   VLRPERCDESCONTO02,   DATADESCONTO03,  
   CODDESCONTO03,   VLRPERCDESCONTO03,  INDRMANUTHISTNOTAFIS, INDRMANUTHISTTXTINF,  NUMREFCADTIT,  
   NUMSEQCADTIT,   CODPROCESSA,   CODREJEICAO,   DATAMANUTENCAO,    TIPORETORNO,  
   NOMEARQRET,    INDIMPORTACAOVALIDA  
  )  
  SELECT   
   @DATAPROCESSAMENTO,  R.SEQ_RECEBE,   R.NUMCTRLDDA,   R.DATAMOVTO,    R.NUMPEDIDO,  
   R.TIPOMANUTENCAOTIT, R.NUMIDENTCDDA,   R.INDRMANUTBENFCRIOOR, R.NOMEFANTASIACEDENTEORI, R.ENDCEDENTEORI,  
   R.CIDCEDENTEORI,  R.UFCEDENTEORI,   R.CEPCEDENTEORI,  R.INDRMANUTBENFCRIOFINL, R.TIPOPESCEDENTE,  
   R.CNPJ_CPF_CEDENTE,  R.NOMECEDENTE,   R.NOMEFANTASIACEDENTE, R.TIPOPESSACADO,   R.CNPJ_CPF_SACADO,  
   R.INDRMANUTPAGDRTIT, R.NOMESACADO,   R.NOMEFANTASIASACADO, R.ENDSACADO,    R.CIDSACADO,  
   R.UFSACADO,    R.CEPSACADO,   R.INDRMANUTSACDRAVALST, R.TIPOPESSACADOR,   R.CNPJ_CPF_SACADOR,  
   R.NOMESACADOR,   R.INDRMANUTDOCTIT,  R.CODCARTEIRA,   R.CODESPECIEDOC,   R.SEUNUMERO,  
   R.TIPOPAGTO,   R.NUMPARCELA,   R.QTDPARCELA,   R.INDTITULONEGOCIADO,  R.INDRMANUTINSTCPGTOTIT,  
   R.DATAVENCIMENTO,  R.VLRTITULO,   R.QTDEDIASPROTESTO,  R.DATALIMPAGTO,    R.INDBLOQUEIO,  
   R.VLRABATIMENTO,  R.QTDPAGTO,    R.TIPOMODELOCALCULO, R.INDRMANUTINSTCVLRRECBT, R.TIPOAUTRECDIVERGENTE,  
   R.INDVALORPERC_MIN,  R.VLRMINTITULO,   R.INDVALORPERC_MAX,  R.VLRMAXTITULO,    R.INDRMANUTJUROSTIT,  
   R.DATAMORA,    R.CODMORA,    R.VLRPERCMORA,   R.INDRMANUTMULTATIT,  R.CODMULTA,  
   R.DATAMULTA,   R.VLRPERCMULTA,   R.INDRMANUTDESCTTIT, R.DATADESCONTO01,   R.CODDESCONTO01,  
   R.VLRPERCDESCONTO01, R.DATADESCONTO02,  R.CODDESCONTO02,  R.VLRPERCDESCONTO02,  R.DATADESCONTO03,  
   R.CODDESCONTO03,  R.VLRPERCDESCONTO03, R.INDRMANUTHISTNOTAFIS, R.INDRMANUTHISTTXTINF,  R.NUMREFCADTIT,  
   R.NUMSEQCADTIT,   R.CODPROCESSA,   R.CODREJEICAO,   R.DATAMANUTENCAO,   R.TIPORETORNO,  
   R.NOMEARQRET,   R.INDIMPORTACAOVALIDA  
  FROM RECEBE_ADDA102_RET_RECUSADOS R  
   INNER JOIN #TMP_RECEBE_ADDA102_RET_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
   
 DELETE R FROM RECEBE_CALCULOS_ADDA0102_RET R  
  INNER JOIN #TMP_RECEBE_ADDA102_RET_RECUSADOS_SEL  SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DELETE R FROM RECEBE_MENSAGENS_ADDA102_RET R  
  INNER JOIN #TMP_RECEBE_ADDA102_RET_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
   
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
   
 DELETE R FROM RECEBE_NOTAS_FISCAIS_ADDA102_RET R  
  INNER JOIN #TMP_RECEBE_ADDA102_RET_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
   
 -- limpeza da tabela principal dos  evento 101 dos títulos recusados  
 DELETE R FROM RECEBE_ADDA102_RET_RECUSADOS R  
  INNER JOIN #TMP_RECEBE_ADDA102_RET_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DROP INDEX IDX_RECEBE_ADDA102_RET_RECUSADOS_SEL ON dbo.#TMP_RECEBE_ADDA102_RET_RECUSADOS_SEL  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DROP TABLE #TMP_RECEBE_ADDA102_RET_RECUSADOS_SEL  
   
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 -- ############################################################## ADDA108 ##############################################################  
  
 -------------------------------------------------- LIMPEZA RECEBE_ADDA108_RR2 ----------------------------------------------------------   
  
 -- #TMP_RECEBE_ADDA108_RR2_SEL   
 SELECT TOP (@QTD_REG_DIARIA_REC) SEQ_RECEBE, NUMIDENTCDDA, DATAMOVTO  
   INTO #TMP_RECEBE_ADDA108_RR2_SEL  
   FROM RECEBE_ADDA108_RR2  
    WHERE DATAMOVTO < @DATALIMPEZA  
   ORDER BY DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 CREATE NONCLUSTERED INDEX IDX_RECEBE_ADDA108_RR2_SEL ON dbo.#TMP_RECEBE_ADDA108_RR2_SEL  
  (SEQ_RECEBE, NUMIDENTCDDA, DATAMOVTO)  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
   
 INSERT INTO RECEBE_ADDA108_RR2_PASS  
  (   
   DATALIMPEZA,     SEQ_RECEBE,    NUMIDENTCDDA,   NUMREFCADTITBAIXAOPERAC, NUMREFALTCADTIT,   
   NUMIDENTCBAIXAOPERAC,   NUMREFBAIXAOPERAC,  NUMSEQBAIXAOPERAC,  NUMCTRLDDA,     TIPOBAIXATIT,   
   ISPBIFSACADA,     CODIFSACADA,   TIPOPESPORTADOR,  CNPJ_CPF_PORTADOR,   DATAHORABAIXAOPERAC,   
   DATABAIXAOPERAC,    VLRBAIXAOPERAC,   NUMCODBARRASBAIXAOPE, CANALPAGTO,     MEIOPAGTO,   
   DATAHORASITUACAOBAIXAOPERAC, INDCONTINGENCIA,  QTDPAGTOREGTD,   VLRSALDOATUAL,    CODSITUACAOTIT,  
   DATAHORADDA,     DATAMOVTO,    CODPROCESSA,   DATAMANUTENCAO,    TIPORETORNO,   
   NOMEARQRET,      INDIMPORTACAOVALIDA, CODREJEICAO,  
   --15/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOME_PORTADOR E DATAHORARECBTTITULO (CATÁLOGOS 5.03 E 5.04)  
   NOME_PORTADOR, DATAHORARECBTTITULO,
   --21/03/2023 - JLSANTOS - INCLUSÃO E TRATAMENTO DOS CAMPOS TIPOPESAGREGADOR, NOMEAGREGADOR, AGENCIARECEBEDORA E CNPJ_CPF_AGREGADOR (CATÁLOGO 5.06)  
   TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR,AGENCIARECEBEDORA
  )  
  SELECT   
   @DATALIMPEZA,     R.SEQ_RECEBE,   R.NUMIDENTCDDA,   R.NUMREFCADTITBAIXAOPERAC, R.NUMREFALTCADTIT,   
   R.NUMIDENTCBAIXAOPERAC,   R.NUMREFBAIXAOPERAC, R.NUMSEQBAIXAOPERAC, R.NUMCTRLDDA,    R.TIPOBAIXATIT,   
   R.ISPBIFSACADA,     R.CODIFSACADA,   R.TIPOPESPORTADOR,  R.CNPJ_CPF_PORTADOR,  R.DATAHORABAIXAOPERAC,   
   R.DATABAIXAOPERAC,    R.VLRBAIXAOPERAC,  R.NUMCODBARRASBAIXAOPE, R.CANALPAGTO,    R.MEIOPAGTO,   
   R.DATAHORASITUACAOBAIXAOPERAC, R.INDCONTINGENCIA,  R.QTDPAGTOREGTD,  R.VLRSALDOATUAL,   R.CODSITUACAOTIT,  
   R.DATAHORADDA,     R.DATAMOVTO,   R.CODPROCESSA,   R.DATAMANUTENCAO,   R.TIPORETORNO,   
   R.NOMEARQRET,     R.INDIMPORTACAOVALIDA, R.CODREJEICAO,  
   --15/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOME_PORTADOR E DATAHORARECBTTITULO (CATÁLOGOS 5.03 E 5.04)  
   R.NOME_PORTADOR, R.DATAHORARECBTTITULO,   
   --21/03/2023 - JLSANTOS - INCLUSÃO E TRATAMENTO DOS CAMPOS TIPOPESAGREGADOR, NOMEAGREGADOR, AGENCIARECEBEDORA E CNPJ_CPF_AGREGADOR (CATÁLOGO 5.06)  
   R.TIPOPESAGREGADOR, R.CNPJ_CPF_AGREGADOR, R.NOMEAGREGADOR,R.AGENCIARECEBEDORA
  FROM RECEBE_ADDA108_RR2 R  
   INNER JOIN #TMP_RECEBE_ADDA108_RR2_SEL SEL  
   ON  R.SEQ_RECEBE =  SEL.SEQ_RECEBE  
    AND R.NUMIDENTCDDA = SEL.NUMIDENTCDDA  
    AND R.DATAMOVTO =  SEL.DATAMOVTO  
       
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
   
 DELETE R FROM RECEBE_ADDA108_RR2 R  
  INNER JOIN #TMP_RECEBE_ADDA108_RR2_SEL SEL  
  ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
  AND R.NUMIDENTCDDA = SEL.NUMIDENTCDDA  
  AND R.DATAMOVTO = SEL.DATAMOVTO  
     
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DROP INDEX IDX_RECEBE_ADDA108_RR2_SEL ON dbo.#TMP_RECEBE_ADDA108_RR2_SEL  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DROP TABLE #TMP_RECEBE_ADDA108_RR2_SEL  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 -- ############################################################## ADDA118 ##############################################################  
    
 -------------------------------------------------- LIMPEZA RECEBE_DDA0118_ADDA118_ACEITOS --------------------------------------------------   
  
 -- #TMP_RECEBE_DDA0118_ADDA118_ACEITOS_SEL   
 SELECT TOP (@QTD_REG_DIARIA_REC) SEQ_RECEBE, NUMPEDIDO, DATAMOVTO   
   INTO #TMP_RECEBE_DDA0118_ADDA118_ACEITOS_SEL   
   FROM RECEBE_DDA0118_ADDA118_ACEITOS  
    WHERE DATAMOVTO < @DATALIMPEZA  
   ORDER BY DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 CREATE NONCLUSTERED INDEX IDX_RECEBE_DDA0118_ADDA118_ACEITOS_SEL ON dbo.#TMP_RECEBE_DDA0118_ADDA118_ACEITOS_SEL  
  (SEQ_RECEBE, NUMPEDIDO, DATAMOVTO)  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
   
 INSERT INTO RECEBE_DDA0118_ADDA118_ACEITOS_PASS  
  (   
   DATALIMPEZA,   DATAMOVTO,   NUMPEDIDO,   NUMIDENTCDDA,  NUMREFCADTIT,  
   NUMIDENTCBAIXAEFET,  NUMREFBAIXAEFET, NUMSEQBAIXAEFET, NUMCTRLDDA,   CODPROCESSA,  
   CODREJEICAO,   DATAMANUTENCAO,  TIPORETORNO,  NOMEARQRET,   INDIMPORTACAOVALIDA,  
   SEQ_RECEBE,    DATAHORADDA  
  )  
  SELECT   
   @DATAPROCESSAMENTO,  R.DATAMOVTO,  R.NUMPEDIDO,  R.NUMIDENTCDDA,  R.NUMREFCADTIT,  
   R.NUMIDENTCBAIXAEFET, R.NUMREFBAIXAEFET, R.NUMSEQBAIXAEFET, R.NUMCTRLDDA,  R.CODPROCESSA,  
   R.CODREJEICAO,   R.DATAMANUTENCAO, R.TIPORETORNO,  R.NOMEARQRET,  R.INDIMPORTACAOVALIDA,  
   R.SEQ_RECEBE,   R.DATAHORADDA  
  FROM RECEBE_DDA0118_ADDA118_ACEITOS R  
   INNER JOIN #TMP_RECEBE_DDA0118_ADDA118_ACEITOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
    AND R.NUMPEDIDO = SEL.NUMPEDIDO  
    AND R.DATAMOVTO = SEL.DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
   
 DELETE R FROM RECEBE_DDA0118_ADDA118_ACEITOS R  
  INNER JOIN #TMP_RECEBE_DDA0118_ADDA118_ACEITOS_SEL SEL  
  ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
  AND R.NUMPEDIDO = SEL.NUMPEDIDO  
  AND R.DATAMOVTO = SEL.DATAMOVTO  
     
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DROP INDEX IDX_RECEBE_DDA0118_ADDA118_ACEITOS_SEL ON dbo.#TMP_RECEBE_DDA0118_ADDA118_ACEITOS_SEL  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DROP TABLE #TMP_RECEBE_DDA0118_ADDA118_ACEITOS_SEL  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 -------------------------------------------------- LIMPEZA RECEBE_DDA0118_ADDA118_RECUSADOS --------------------------------------------------   
  
 SELECT TOP (@QTD_REG_DIARIA_REC)   
   SEQ_RECEBE, NUMPEDIDO, DATAMOVTO  
   INTO #TMP_RECEBE_DDA0118_ADDA118_RECUSADOS_SEL   
   FROM RECEBE_DDA0118_ADDA118_RECUSADOS  
    WHERE DATAMOVTO < @DATALIMPEZA  
   ORDER BY DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 CREATE NONCLUSTERED INDEX IDX_RECEBE_DDA0118_ADDA118_RECUSADOS_SEL ON dbo.#TMP_RECEBE_DDA0118_ADDA118_RECUSADOS_SEL  
  (SEQ_RECEBE, NUMPEDIDO, DATAMOVTO)  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
  
 INSERT INTO RECEBE_DDA0118_ADDA118_RECUSADOS_PASS   
  (  
   DATALIMPEZA,    DATAMOVTO,   NUMPEDIDO,    NUMIDENTCDDA,  NUMREFCADTIT,  
   NUMREFBAIXAEFET,   TIPOBAIXA,   CODIFSACADA,   ISPBSACADA,   DATAPAGTOBAIXA,  
   DATAHORAPAGTOBAIXA,   VLRPAGTOBAIXA,  NUMCODBARRAS,   CANALPAGTO,   MEIOPAGTO,  
   NUMIDENTCBAIXAOPERAC,  NUMCTRLDDA,   CODPROCESSA,   CODREJEICAO,  DATAMANUTENCAO,  
   TIPORETORNO,    NOMEARQRET,   INDIMPORTACAOVALIDA, SEQ_RECEBE  
  )  
  SELECT   
   @DATAPROCESSAMENTO,   R.DATAMOVTO,  R.NUMPEDIDO,   R.NUMIDENTCDDA,  R.NUMREFCADTIT,  
    R.NUMREFBAIXAEFET,   R.TIPOBAIXA,  R.CODIFSACADA,   R.ISPBSACADA,  R.DATAPAGTOBAIXA,  
    R.DATAHORAPAGTOBAIXA,  R.VLRPAGTOBAIXA, R.NUMCODBARRAS,   R.CANALPAGTO,  R.MEIOPAGTO,  
    R.NUMIDENTCBAIXAOPERAC, R.NUMCTRLDDA,  R.CODPROCESSA,   R.CODREJEICAO,  R.DATAMANUTENCAO,  
    R.TIPORETORNO,    R.NOMEARQRET,  R.INDIMPORTACAOVALIDA, R.SEQ_RECEBE  
  FROM RECEBE_DDA0118_ADDA118_RECUSADOS R  
   INNER JOIN #TMP_RECEBE_DDA0118_ADDA118_RECUSADOS_SEL SEL  
   ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
   AND R.NUMPEDIDO = SEL.NUMPEDIDO  
   AND R.DATAMOVTO = SEL.DATAMOVTO  
     
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DELETE R FROM RECEBE_DDA0118_ADDA118_RECUSADOS R  
  INNER JOIN #TMP_RECEBE_DDA0118_ADDA118_RECUSADOS_SEL SEL  
  ON R.SEQ_RECEBE = SEL.SEQ_RECEBE  
  AND R.NUMPEDIDO = SEL.NUMPEDIDO  
  AND R.DATAMOVTO = SEL.DATAMOVTO  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DROP INDEX IDX_RECEBE_DDA0118_ADDA118_RECUSADOS_SEL ON dbo.#TMP_RECEBE_DDA0118_ADDA118_RECUSADOS_SEL  
  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
  
 DROP TABLE #TMP_RECEBE_DDA0118_ADDA118_RECUSADOS_SEL  
 SELECT @SQLERRO = @@ERROR     
 IF @SQLERRO <> 0 GOTO TRATAERRO  
   
 -------------------------------------------------- TRATAMENTO DE ERROS --------------------------------------------------   
 RETURN  
 TRATAERRO:  
 SELECT @MSGERRO = CONVERT(VARCHAR(10),@SQLERRO)  
  RAISERROR(@MSGERRO,15,1)  
  RETURN  
  
END  
GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO], 
    [NOMESCRIPT], 
    [CODUSUARIO], 
    [DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_LIMPEZA_DIARIA_REC', 
	SYSTEM_USER, 
	GETDATE() 
GO