USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_LIMPEZA_DIARIA_MANUT')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_LIMPEZA_DIARIA_MANUT AS BEGIN RETURN END')
END
GO
ALTER PROCEDURE dbo.SP_LIMPEZA_DIARIA_MANUT
AS
BEGIN

	/*
		15/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOME_PORTADOR E DATAHORARECBTTITULO (CATÁLOGOS 5.03 E 5.04)
		
		22/03/2023 - JLSANTOS - INCLUSÃO NA TABELA MANUT_TITULOS_PASS, TRATAMENTO DOS CAMPOS TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO, AGENCIARECEBEDORA E CODMOTIVO (CATÁLOGO 5.06)
								INCLUSÃO NA TABELA MANUT_SACELETRONICO_PASS, TRATAMENTO DOS CAMPOS DATAHORADDA
	*/

    DECLARE @MSGERRO VARCHAR(255)

	DECLARE @DATALIMPEZA DATETIME, @DATAPROCESSAMENTO DATETIME, @DATAHORA DATETIME, @SQLERRO INTEGER, @INDLIMPEZA CHAR

	SELECT @DATALIMPEZA = DATEADD (DD, -30,DATAPROCESSAMENTO), @DATAPROCESSAMENTO = DATAPROCESSAMENTO, 
	       @DATAHORA = GETDATE(), @INDLIMPEZA = ISNULL(INDLIMPEZA,'N')
	FROM PARAMETROS
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

    IF (@INDLIMPEZA = 'N' OR DATEDIFF (DD, @DATAPROCESSAMENTO,  @DATAHORA) < -7 ) /* NÃO EXECUTA LIMPEZA SE A DATAPROCESSAMENTO FOR MAIOR QUE 7 DAIS DO RELÓGIO */
	    RETURN 


    SELECT TOP 50000 CODSISLEGADO, DATALEGADO, DATAPEDIDO, NUMCTRLLEGADO 
    INTO #TMP_MANUT_EXTRATO_SEL 
    FROM MANUT_EXTRATO	
    WHERE DATAPEDIDO < @DATALIMPEZA
    ORDER BY DATAPEDIDO
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO


    CREATE CLUSTERED INDEX IDX_TMP_MANUT_EXTRATO_SEL 
	ON dbo.#TMP_MANUT_EXTRATO_SEL
	(DATAPEDIDO, CODSISLEGADO, DATALEGADO, NUMCTRLLEGADO)
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO

      INSERT INTO MANUT_EXTRATO_PASS 
      (DATALIMPEZA,DATAPEDIDO,CODSISLEGADO,DATALEGADO,NUMCTRLLEGADO,
	  DATAMOVTO,
      NUMPEDIDO,NUMIDENTCDDA,DATAINIAPURACAO,DATAFIMAPURACAO,TIPOCONSULTA,TIPORETORNO,
      SITUACAOPEDIDO,CODRETORNO,NOMEARQRET,TIPOENVIO,FORMAENVIO,SPID,DATAHORAPROCESSO,
      SEQ_PEDIDO)
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.CODSISLEGADO,M.DATALEGADO,M.NUMCTRLLEGADO,
	  DATAMOVTO,
      NUMPEDIDO,NUMIDENTCDDA,DATAINIAPURACAO,DATAFIMAPURACAO,TIPOCONSULTA,TIPORETORNO,
      SITUACAOPEDIDO,CODRETORNO,NOMEARQRET,TIPOENVIO,FORMAENVIO,SPID,DATAHORAPROCESSO,
      SEQ_PEDIDO
      FROM MANUT_EXTRATO M
	  INNER JOIN #TMP_MANUT_EXTRATO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_EXTRATO_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_EXTRATO_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_EXTRATO_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_EXTRATO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

	  DELETE M
      FROM MANUT_EXTRATO M
	  INNER JOIN #TMP_MANUT_EXTRATO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_EXTRATO_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_EXTRATO_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_EXTRATO_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_EXTRATO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  
	  
	
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	DROP INDEX IDX_TMP_MANUT_EXTRATO_SEL ON dbo.#TMP_MANUT_EXTRATO_SEL
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	DROP TABLE #TMP_MANUT_EXTRATO_SEL
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO


	/*LIMPEZA DE MANUT_EXTRATO_PROCESSAMENTO*/ 
    SELECT TOP 50000 CODSISLEGADO, DATALEGADO, DATAPEDIDO, NUMCTRLLEGADO INTO #TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL 
    FROM MANUT_EXTRATO_PROCESSAMENTO	
    WHERE DATAPEDIDO < @DATALIMPEZA
    ORDER BY DATAPEDIDO
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

    CREATE NONCLUSTERED INDEX IDX_TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL 
    ON dbo.#TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL
	(DATAPEDIDO, CODSISLEGADO, DATALEGADO, NUMCTRLLEGADO)
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO

      INSERT INTO MANUT_EXTRATO_PROCESSAMENTO_PASS 
      ( DATALIMPEZA,DATAPEDIDO,CODSISLEGADO,DATALEGADO,NUMCTRLLEGADO,
      NUMPEDIDO,NUMCTRLDDA,DATAREFERENCIA,DATAHORAINI,DATAHORAFIM,TPMSGARQ,
      CODMSGARQ,TIPORETORNO,SITUACAOPEDIDO,CODRETORNO,NOMEARQRET,TIPOENVIO,
      FORMAENVIO,SPID,DATAHORAPROCESSO,SEQ_PEDIDO)
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.CODSISLEGADO,M.DATALEGADO,M.NUMCTRLLEGADO,
      NUMPEDIDO,NUMCTRLDDA,DATAREFERENCIA,DATAHORAINI,DATAHORAFIM,TPMSGARQ,
      CODMSGARQ,TIPORETORNO,SITUACAOPEDIDO,CODRETORNO,NOMEARQRET,TIPOENVIO,
      FORMAENVIO,SPID,DATAHORAPROCESSO,SEQ_PEDIDO
      FROM MANUT_EXTRATO_PROCESSAMENTO M 
	  INNER JOIN #TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

	  DELETE M
      FROM MANUT_EXTRATO_PROCESSAMENTO M
	  INNER JOIN #TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  


   
   SELECT @SQLERRO = @@ERROR		 
   IF @SQLERRO <> 0 GOTO TRATAERRO

   DROP INDEX IDX_TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL ON dbo.#TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL
   SELECT @SQLERRO = @@ERROR		 
   IF @SQLERRO <> 0 GOTO TRATAERRO

   DROP TABLE #TMP_MANUT_EXTRATO_PROCESSAMENTO_SEL
   SELECT @SQLERRO = @@ERROR		 
   IF @SQLERRO <> 0 GOTO TRATAERRO


			/*LIMPEZA DE MANUT_BENEFICIARIO*/ 
    SELECT TOP 50000 DATAPEDIDO,DATALEGADO,NUMCTRLLEGADO,CODSISLEGADO INTO #TMP_MANUT_BENEFICIARIO_SEL 
    FROM MANUT_BENEFICIARIO	
	WHERE DATAPEDIDO < @DATALIMPEZA
	ORDER BY DATAPEDIDO
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

    CREATE NONCLUSTERED INDEX IDX_TMP_MANUT_BENEFICIARIO_SEL 
    ON dbo.#TMP_MANUT_BENEFICIARIO_SEL
	(DATAPEDIDO,DATALEGADO,NUMCTRLLEGADO,CODSISLEGADO)
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO

      INSERT INTO MANUT_BENEFICIARIO_PASS 
      ( DATALIMPEZA,DATAPEDIDO,DATALEGADO,NUMCTRLLEGADO,CODSISLEGADO,
      NUMPEDIDO,TIPOMANUTENCAO,ISPBADM,NUMIDENTCBENEFICIARIO,TIPOPESSOABENEFICIARIO,
      CNPJ_CPF_BENEFICIARIO,CNPJ_BASE_BENEFICIARIO,NOMEBENEFICIARIO,NOMEFANTASIABENEFICIARIO,
      SITUACAOBENEFICIARIO,DTHRSITBENEFICIARIO,DATAINIBENEFICIARIO,DATAFIMBENEFICIARIO,
      SITUACAORELACIONAMENTO,DTHRSITRELACIONAMENTO,DTHRINIBENEFICIARIO,DTHRBENEFICIARIO,
      DATABENEFICIARIOANTIGA,DATABENEFICIARIORECENTE,DATAINISITUACAO,DATAFIMSITUACAO,
      TIPOSOLICITACAO,NUMCTRLDDA,TIPORETORNO,SITUACAOPEDIDO,CODRETORNO,
      NOMEARQ,NOMEARQRET,ATUALIZABASE,NOMEARQREM,SEQ_PEDIDO,TIPOENVIO,FORMAENVIO,
      SPID,DATAHORAPROCESSO,NUMREFCADBENEFICIARIO,NUMSEQCADBENEFICIARIO,
      AGUARDAPENDENTE,NUMREFCADBENEFICIARIO_RET,NUMPEDIDOPEND)
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.DATALEGADO,M.NUMCTRLLEGADO,M.CODSISLEGADO,
      NUMPEDIDO,TIPOMANUTENCAO,ISPBADM,NUMIDENTCBENEFICIARIO,TIPOPESSOABENEFICIARIO,
      CNPJ_CPF_BENEFICIARIO,CNPJ_BASE_BENEFICIARIO,NOMEBENEFICIARIO,NOMEFANTASIABENEFICIARIO,
      SITUACAOBENEFICIARIO,DTHRSITBENEFICIARIO,DATAINIBENEFICIARIO,DATAFIMBENEFICIARIO,
      SITUACAORELACIONAMENTO,DTHRSITRELACIONAMENTO,DTHRINIBENEFICIARIO,DTHRBENEFICIARIO,
      DATABENEFICIARIOANTIGA,DATABENEFICIARIORECENTE,DATAINISITUACAO,DATAFIMSITUACAO,
      TIPOSOLICITACAO,NUMCTRLDDA,TIPORETORNO,SITUACAOPEDIDO,CODRETORNO,
      NOMEARQ,NOMEARQRET,ATUALIZABASE,NOMEARQREM,SEQ_PEDIDO,TIPOENVIO,FORMAENVIO,
      SPID,DATAHORAPROCESSO,NUMREFCADBENEFICIARIO,NUMSEQCADBENEFICIARIO,
      AGUARDAPENDENTE,NUMREFCADBENEFICIARIO_RET,NUMPEDIDOPEND
      FROM MANUT_BENEFICIARIO M 
	  INNER JOIN #TMP_MANUT_BENEFICIARIO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_BENEFICIARIO_SEL.DATAPEDIDO
	  AND M.DATALEGADO = #TMP_MANUT_BENEFICIARIO_SEL.DATALEGADO
	  AND M.CODSISLEGADO = #TMP_MANUT_BENEFICIARIO_SEL.CODSISLEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_BENEFICIARIO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

      INSERT INTO MANUT_CONVENIOS_PASS 
      ( DATALIMPEZA,DATAPEDIDO,DATALEGADO,NUMCTRLLEGADO,CODSISLEGADO,
      TIPOPRODCONVENIO,TIPOCARTEIRACOBRANCA,CODAGENCIA,TIPOAGENCIA,TIPOCONTA,NUMCONTA,
      SITUACAOCONVENIO,DATAINICONVENIO,DATAFIMCONVENIO,ISPBINCORPORADO,CODCLIENTECONV,
      TIPOMANUTENCAOCONVENIO,CODREJEICAO)
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.DATALEGADO,M.NUMCTRLLEGADO,M.CODSISLEGADO,
      TIPOPRODCONVENIO,TIPOCARTEIRACOBRANCA,CODAGENCIA,TIPOAGENCIA,TIPOCONTA,NUMCONTA,
      SITUACAOCONVENIO,DATAINICONVENIO,DATAFIMCONVENIO,ISPBINCORPORADO,CODCLIENTECONV,
      TIPOMANUTENCAOCONVENIO,CODREJEICAO
      FROM MANUT_CONVENIOS M
	  INNER JOIN #TMP_MANUT_BENEFICIARIO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_BENEFICIARIO_SEL.DATAPEDIDO
	  AND M.DATALEGADO = #TMP_MANUT_BENEFICIARIO_SEL.DATALEGADO
	  AND M.CODSISLEGADO = #TMP_MANUT_BENEFICIARIO_SEL.CODSISLEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_BENEFICIARIO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  
	  
      INSERT INTO MANUT_REPRESENTANTES_PASS
      ( DATALIMPEZA,DATAPEDIDO,DATALEGADO,NUMCTRLLEGADO,CODSISLEGADO,
      CNPJ_CPF_REPRESENTANTE,TIPOPESSOAREPRESENTANTE,TIPOMANUTENCAOREPRESENTANTE,
      DATALOGREPRESENTANTE,CODREJEICAO)
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.DATALEGADO,M.NUMCTRLLEGADO,M.CODSISLEGADO,
      CNPJ_CPF_REPRESENTANTE,TIPOPESSOAREPRESENTANTE,TIPOMANUTENCAOREPRESENTANTE,
      DATALOGREPRESENTANTE,CODREJEICAO
      FROM MANUT_REPRESENTANTES M	  
	  INNER JOIN #TMP_MANUT_BENEFICIARIO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_BENEFICIARIO_SEL.DATAPEDIDO
	  AND M.DATALEGADO = #TMP_MANUT_BENEFICIARIO_SEL.DATALEGADO
	  AND M.CODSISLEGADO = #TMP_MANUT_BENEFICIARIO_SEL.CODSISLEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_BENEFICIARIO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

	  DELETE M
      FROM MANUT_REPRESENTANTES M	  
	  INNER JOIN #TMP_MANUT_BENEFICIARIO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_BENEFICIARIO_SEL.DATAPEDIDO
	  AND M.DATALEGADO = #TMP_MANUT_BENEFICIARIO_SEL.DATALEGADO
	  AND M.CODSISLEGADO = #TMP_MANUT_BENEFICIARIO_SEL.CODSISLEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_BENEFICIARIO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  	  

	  DELETE M
      FROM MANUT_CONVENIOS M
	  INNER JOIN #TMP_MANUT_BENEFICIARIO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_BENEFICIARIO_SEL.DATAPEDIDO
	  AND M.DATALEGADO = #TMP_MANUT_BENEFICIARIO_SEL.DATALEGADO
	  AND M.CODSISLEGADO = #TMP_MANUT_BENEFICIARIO_SEL.CODSISLEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_BENEFICIARIO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  	  
	  
	  DELETE M
      FROM MANUT_BENEFICIARIO M
	  INNER JOIN #TMP_MANUT_BENEFICIARIO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_BENEFICIARIO_SEL.DATAPEDIDO
	  AND M.DATALEGADO = #TMP_MANUT_BENEFICIARIO_SEL.DATALEGADO
	  AND M.CODSISLEGADO = #TMP_MANUT_BENEFICIARIO_SEL.CODSISLEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_BENEFICIARIO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  
   
   SELECT @SQLERRO = @@ERROR		 
   IF @SQLERRO <> 0 GOTO TRATAERRO

   DROP INDEX IDX_TMP_MANUT_BENEFICIARIO_SEL ON dbo.#TMP_MANUT_BENEFICIARIO_SEL
   SELECT @SQLERRO = @@ERROR		 
   IF @SQLERRO <> 0 GOTO TRATAERRO

   DROP TABLE #TMP_MANUT_BENEFICIARIO_SEL
   SELECT @SQLERRO = @@ERROR		 
   IF @SQLERRO <> 0 GOTO TRATAERRO


	/*LIMPEZA DE MANUT_TITULOS*/ 
    SELECT TOP 50000 CODSISLEGADO, DATALEGADO, DATAPEDIDO, NUMCTRLLEGADO INTO #TMP_MANUT_TITULOS_SEL 
    FROM MANUT_TITULOS	
    WHERE DATAPEDIDO < @DATALIMPEZA
    ORDER BY DATAPEDIDO
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

    CREATE CLUSTERED INDEX IDX_MANUT_TITULOS_SEL 
    ON dbo.#TMP_MANUT_TITULOS_SEL
	(DATAPEDIDO, CODSISLEGADO, DATALEGADO, NUMCTRLLEGADO)
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO

	  --sp_help MANUT_TITULOS_PASS 
      INSERT INTO MANUT_TITULOS_PASS (
		  DATALIMPEZA,DATAPEDIDO,DATALEGADO,CODSISLEGADO,NUMCTRLLEGADO,
		  NUMPEDIDO,NUMIDENTCDDA,CODEVENTO,CODIFSACADA,TIPOMANUTENCAOTIT,CODIFCEDENTE,
		  TIPOPESCEDENTE,CNPJ_CPF_CEDENTE,NOMECEDENTE,TIPOPESCEDENTEORI,CNPJ_CPF_CEDENTEORI,
		  NOMECEDENTEORI,ENDCEDENTEORI,CIDCEDENTEORI,UFCEDENTEORI,CEPCEDENTEORI,TIPOPESSACADO,
		  CNPJ_CPF_SACADO,NOMESACADO,ENDSACADO,CIDSACADO,UFSACADO,CEPSACADO,TIPOPESSACADOR,
		  CNPJ_CPF_SACADOR,NOMESACADOR,CODCARTEIRA,CODMOEDACNAB,IDENTNOSSONUMERO,NUMCODBARRAS,
		  DATAVENCIMENTO,VLRTITULO,SEUNUMERO,CODESPECIEDOC,DATAEMISSAO,QTDEDIASPROTESTO,
		  DATALIMPAGTO,TIPOPAGTO,INDTITULONEGOCIADO,VLRABATIMENTO,CODMORA,DATAMORA,VLRPERCMORA,
		  CODMULTA,DATAMULTA,VLRPERCMULTA,CODDESCONTO01,DATADESCONTO01,VLRPERCDESCONTO01,
		  CODDESCONTO02,DATADESCONTO02,VLRPERCDESCONTO02,
		  CODDESCONTO03,DATADESCONTO03,VLRPERCDESCONTO03,
		  VLRMINTITULO,VLRMAXTITULO,TIPOBAIXA,DATAPAGTOBAIXA,VLRPAGTOBAIXA,
		  ACEITE,NUMCTRLDDA,DATAHORADDA,TIPOPESTERCEIRO,CNPJ_CPF_TERCEIRO,
		  NUMIDENTCDDA2,DATAVENCTOINI,DATAVENCTOFIM,DATACADASTINI,DATACADASTFIM,TIPOCONSULTA,
		  CNPJBASE,BUSCABASESACADO,CODSITUACAO,TIPORETORNO,SITUACAOPEDIDO,CODRETORNO,
		  NOMEARQRET,NOMEARQREM,TIPOCALCULO,INDALTERAVALOR,DATACALCULO,VLRCALCULADODESC,VLRCALCULADOMORA,
		  VLRCALCULADOMULTA,VLRCOBRAR,SEQINCLUSAO,LINHADIGITAVEL,TIPOENVIO,FORMAENVIO,ISPBCEDENTE,
		  ISPBSACADA,NUMPARCELA,QTDPARCELA,TIPOAUTRECDIVERGENTE,INDBLOQUEIO,INDPARCIAL,QTDPAGTO,
		  INDVALORPERC_MIN,INDVALORPERC_MAX,NUMREFCADTIT,NUMSEQCADTIT,SPID,DATAHORAPROCESSO,
		  NOMEFANTASIACEDENTE,NOMEFANTASIACEDENTEORI,NOMEFANTASIASACADO,
		  AGUARDAPENDENTE,CANALPAGTO,MEIOPAGTO,NUMIDENTCBAIXAOPERAC,NUMREFBAIXAOPERAC,NUMSEQBAIXAOPERAC,
		  NUMIDENTCBAIXAEFET,NUMREFBAIXAEFET,NUMSEQBAIXAEFET,NUMREFACEITE,NUMSEQACEITE,NUMIDENTCTERC,
		  NUMREFTERC,NUMSEQTERC,NUMREFCADTIT_RET,NUMREFBAIXAOPERAC_RET,NUMREFBAIXAEFET_RET,NUMREFACEITE_RET,
		  NUMREFTERC_RET,NUMPEDIDOPEND,TIPOPESAUTORIZADOR,CNPJ_CPF_AUTORIZADOR,INDCONTINGENCIA,TIPOPESPORTADOR,
		  CNPJ_CPF_PORTADOR,DATAHORACANCELAMENTOBAIXAOPERAC,DATAREGHISTORICO,
		  --15/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOME_PORTADOR E DATAHORARECBTTITULO (CATÁLOGOS 5.03 E 5.04)
		  NOME_PORTADOR, DATAHORARECBTTITULO, 
		  --22/03/2023 - JLSANTOS - INCLUSÃO E TRATAMENTO DOS CAMPOS TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO, AGENCIARECEBEDORA E CODMOTIVO (CATÁLOGO 5.06)
		  TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO, AGENCIARECEBEDORA, CODMOTIVO
	  )
      SELECT 
		  @DATAPROCESSAMENTO,M.DATAPEDIDO,M.DATALEGADO,M.CODSISLEGADO,M.NUMCTRLLEGADO,
		  NUMPEDIDO,NUMIDENTCDDA,CODEVENTO,CODIFSACADA,TIPOMANUTENCAOTIT,CODIFCEDENTE,
		  TIPOPESCEDENTE,CNPJ_CPF_CEDENTE,NOMECEDENTE,TIPOPESCEDENTEORI,CNPJ_CPF_CEDENTEORI,
		  NOMECEDENTEORI,ENDCEDENTEORI,CIDCEDENTEORI,UFCEDENTEORI,CEPCEDENTEORI,TIPOPESSACADO,
		  CNPJ_CPF_SACADO,NOMESACADO,ENDSACADO,CIDSACADO,UFSACADO,CEPSACADO,TIPOPESSACADOR,
		  CNPJ_CPF_SACADOR,NOMESACADOR,CODCARTEIRA,CODMOEDACNAB,IDENTNOSSONUMERO,NUMCODBARRAS,
		  DATAVENCIMENTO,VLRTITULO,SEUNUMERO,CODESPECIEDOC,DATAEMISSAO,QTDEDIASPROTESTO,
		  DATALIMPAGTO,TIPOPAGTO,INDTITULONEGOCIADO,VLRABATIMENTO,CODMORA,DATAMORA,VLRPERCMORA,
		  CODMULTA,DATAMULTA,VLRPERCMULTA,CODDESCONTO01,DATADESCONTO01,VLRPERCDESCONTO01,
		  CODDESCONTO02,DATADESCONTO02,VLRPERCDESCONTO02,
		  CODDESCONTO03,DATADESCONTO03,VLRPERCDESCONTO03,
		  VLRMINTITULO,VLRMAXTITULO,TIPOBAIXA,DATAPAGTOBAIXA,VLRPAGTOBAIXA,
		  ACEITE,NUMCTRLDDA,DATAHORADDA,TIPOPESTERCEIRO,CNPJ_CPF_TERCEIRO,
		  NUMIDENTCDDA2,DATAVENCTOINI,DATAVENCTOFIM,DATACADASTINI,DATACADASTFIM,TIPOCONSULTA,
		  CNPJBASE,BUSCABASESACADO,CODSITUACAO,TIPORETORNO,SITUACAOPEDIDO,CODRETORNO,
		  NOMEARQRET,NOMEARQREM,TIPOCALCULO,INDALTERAVALOR,DATACALCULO,VLRCALCULADODESC,VLRCALCULADOMORA,
		  VLRCALCULADOMULTA,VLRCOBRAR,SEQINCLUSAO,LINHADIGITAVEL,TIPOENVIO,FORMAENVIO,ISPBCEDENTE,
		  ISPBSACADA,NUMPARCELA,QTDPARCELA,TIPOAUTRECDIVERGENTE,INDBLOQUEIO,INDPARCIAL,QTDPAGTO,
		  INDVALORPERC_MIN,INDVALORPERC_MAX,NUMREFCADTIT,NUMSEQCADTIT,SPID,DATAHORAPROCESSO,
		  NOMEFANTASIACEDENTE,NOMEFANTASIACEDENTEORI,NOMEFANTASIASACADO,
		  AGUARDAPENDENTE,CANALPAGTO,MEIOPAGTO,NUMIDENTCBAIXAOPERAC,NUMREFBAIXAOPERAC,NUMSEQBAIXAOPERAC,
		  NUMIDENTCBAIXAEFET,NUMREFBAIXAEFET,NUMSEQBAIXAEFET,NUMREFACEITE,NUMSEQACEITE,NUMIDENTCTERC,
		  NUMREFTERC,NUMSEQTERC,NUMREFCADTIT_RET,NUMREFBAIXAOPERAC_RET,NUMREFBAIXAEFET_RET,NUMREFACEITE_RET,
		  NUMREFTERC_RET,NUMPEDIDOPEND,TIPOPESAUTORIZADOR,CNPJ_CPF_AUTORIZADOR,INDCONTINGENCIA,TIPOPESPORTADOR,
		  CNPJ_CPF_PORTADOR,DATAHORACANCELAMENTOBAIXAOPERAC,DATAREGHISTORICO,
		  --15/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOME_PORTADOR E DATAHORARECBTTITULO (CATÁLOGOS 5.03 E 5.04)
		  NOME_PORTADOR, DATAHORARECBTTITULO,
		  --22/03/2023 - JLSANTOS - INCLUSÃO E TRATAMENTO DOS CAMPOS TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO, AGENCIARECEBEDORA E CODMOTIVO (CATÁLOGO 5.06)
		  TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO, AGENCIARECEBEDORA, CODMOTIVO
      FROM MANUT_TITULOS M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

      INSERT INTO MANUT_MODELO_PASS
      ( DATALIMPEZA,DATAPEDIDO,DATALEGADO,CODSISLEGADO,NUMCTRLLEGADO,
      SEQFATURA,SEQMODELO,CABECALHO,TPDADOS)
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.DATALEGADO,M.CODSISLEGADO,M.NUMCTRLLEGADO,
      SEQFATURA,SEQMODELO,CABECALHO,TPDADOS
      FROM MANUT_MODELO M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

	  INSERT INTO MANUT_DET_ANTES_CABEC_PASS
      ( DATALIMPEZA,DATAPEDIDO,DATALEGADO,CODSISLEGADO,NUMCTRLLEGADO,
      SEQFATURA,SEQDETANTES,TEXTO)
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.DATALEGADO,M.CODSISLEGADO,M.NUMCTRLLEGADO,
      SEQFATURA,SEQDETANTES,TEXTO
      FROM MANUT_DET_ANTES_CABEC M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  


      INSERT INTO MANUT_DET_APOS_CABEC_PASS
      ( DATALIMPEZA,DATAPEDIDO,DATALEGADO,CODSISLEGADO,NUMCTRLLEGADO,
      SEQFATURA,SEQDETAPOS,TEXTO)
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.DATALEGADO,M.CODSISLEGADO,M.NUMCTRLLEGADO,
      SEQFATURA,SEQDETAPOS,TEXTO
      FROM MANUT_DET_APOS_CABEC M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

      INSERT INTO MANUT_ANEXO_FATURA_PASS
      ( DATALIMPEZA,DATAPEDIDO,DATALEGADO,CODSISLEGADO,NUMCTRLLEGADO,
      SEQFATURA,CODMODELO,TIPOMANUTENCAO)
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.DATALEGADO,M.CODSISLEGADO,M.NUMCTRLLEGADO,
      SEQFATURA,CODMODELO,TIPOMANUTENCAO
      FROM MANUT_ANEXO_FATURA M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

      INSERT INTO MANUT_CALCULOS_PASS
      ( DATALIMPEZA,DATAPEDIDO,DATALEGADO,CODSISLEGADO,NUMCTRLLEGADO,
      DATACALCULO,VLRMORA,VLRMULTA,VLRDESCONTO,VLRCOBRAR)
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.DATALEGADO,M.CODSISLEGADO,M.NUMCTRLLEGADO,
      DATACALCULO,VLRMORA,VLRMULTA,VLRDESCONTO,VLRCOBRAR
      FROM MANUT_CALCULOS M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

      INSERT INTO MANUT_COMPLEMENTOS_PASS
      ( DATALIMPEZA,DATAPEDIDO,DATALEGADO,CODSISLEGADO,NUMCTRLLEGADO,
      TIPOCOMPLEMENTO,TIPOMANUTENCAO,CODALEGACAO,DATAREFERENCIA,VLRREFERENCIA,
      TEXTO,TIPOPESTERCEIRO,CNPJ_CPF_TERCEIRO)
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.DATALEGADO,M.CODSISLEGADO,M.NUMCTRLLEGADO,
      TIPOCOMPLEMENTO,TIPOMANUTENCAO,CODALEGACAO,DATAREFERENCIA,VLRREFERENCIA,
      TEXTO,TIPOPESTERCEIRO,CNPJ_CPF_TERCEIRO
      FROM MANUT_COMPLEMENTOS M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

      INSERT INTO MANUT_MENSAGENS_PASS
      ( DATALIMPEZA,DATAPEDIDO,DATALEGADO,CODSISLEGADO,NUMCTRLLEGADO,
      CODEVENTO,SEQMENSAGEM,TEXTO)
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.DATALEGADO,M.CODSISLEGADO,M.NUMCTRLLEGADO,
      CODEVENTO,SEQMENSAGEM,TEXTO
      FROM MANUT_MENSAGENS M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

      INSERT INTO MANUT_NOTAS_FISCAIS_PASS
      ( DATALIMPEZA,DATAPEDIDO,DATALEGADO,CODSISLEGADO,NUMCTRLLEGADO,
      CODEVENTO,NUMNOTAFISCAL,DATAEMISSAO,VLRNOTAFISCAL)
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.DATALEGADO,M.CODSISLEGADO,M.NUMCTRLLEGADO,
      CODEVENTO,NUMNOTAFISCAL,DATAEMISSAO,VLRNOTAFISCAL
      FROM MANUT_NOTAS_FISCAIS M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

 	  DELETE M
      FROM MANUT_MODELO M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

	  DELETE M
      FROM MANUT_DET_ANTES_CABEC M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

	  DELETE M
      FROM MANUT_DET_APOS_CABEC M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

	  DELETE M
      FROM MANUT_ANEXO_FATURA M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

	  DELETE M
      FROM MANUT_CALCULOS M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

	  DELETE M
      FROM MANUT_COMPLEMENTOS M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

	  DELETE M
      FROM MANUT_MENSAGENS M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

	  DELETE M
      FROM MANUT_NOTAS_FISCAIS M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  


	  DELETE M
      FROM MANUT_TITULOS M
	  INNER JOIN #TMP_MANUT_TITULOS_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_TITULOS_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_TITULOS_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_TITULOS_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_TITULOS_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  


	
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	DROP INDEX IDX_MANUT_TITULOS_SEL ON dbo.#TMP_MANUT_TITULOS_SEL
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	DROP TABLE #TMP_MANUT_TITULOS_SEL
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

		/*LIMPEZA DE MANUT_SACELETRONICO*/ 
    SELECT TOP 50000 CODSISLEGADO, DATALEGADO, DATAPEDIDO, NUMCTRLLEGADO INTO #TMP_MANUT_MANUT_SACELETRONICO_SEL 
    FROM MANUT_SACELETRONICO	
    WHERE DATAPEDIDO < @DATALIMPEZA
    ORDER BY DATAPEDIDO
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

    CREATE CLUSTERED INDEX IDX_TMP_MANUT_SACELETRONICO_SEL 
    ON dbo.#TMP_MANUT_MANUT_SACELETRONICO_SEL
	(DATAPEDIDO, CODSISLEGADO, DATALEGADO, NUMCTRLLEGADO)
    
      SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO

      INSERT INTO MANUT_SACELETRONICO_PASS
      ( DATALIMPEZA,DATAPEDIDO,DATALEGADO,CODSISLEGADO,NUMCTRLLEGADO,
      NUMPEDIDO,TIPOMANUTENCAO,TIPOSACADO,CNPJ_CPF_SACADO,TIPOPESSOASACADO,
      AGENCIASACADO,TPCONTASACADO,CONTASACADO,DATAINIADESAO,DATAFIMADESAO,
      TIPOAVMANUTTIT,TIPOAVMANUTTITC,NUMCTRLDDA,CNPJBASE,
      DATAATUALINI,DATAATUALFIM,CODSITUACAOSAC,TIPORETORNO,SITUACAOPEDIDO,
      CODRETORNO,NOMEARQRET,ATULZABASE,NOMEARQREM,TIPOENVIO,FORMAENVIO,
      NUMIDENTCPAG,NUMREFCADPAG,NUMSEQCADPAG,NUMREFCADPAG_RET,
      SPID,DATAHORAPROCESSO,AGUARDAPENDENTE,SEQ_PEDIDO,NUMPEDIDOPEND,
	  --22/03/2023 - JLSANTOS - INCLUSÃO E TRATAMENTO DOS CAMPOS DATAHORADDA
	  DATAHORADDA
	  )
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.DATALEGADO,M.CODSISLEGADO,M.NUMCTRLLEGADO,
      NUMPEDIDO,TIPOMANUTENCAO,TIPOSACADO,CNPJ_CPF_SACADO,TIPOPESSOASACADO,
      AGENCIASACADO,TPCONTASACADO,CONTASACADO,DATAINIADESAO,DATAFIMADESAO,
      TIPOAVMANUTTIT,TIPOAVMANUTTITC,NUMCTRLDDA,CNPJBASE,
      DATAATUALINI,DATAATUALFIM,CODSITUACAOSAC,TIPORETORNO,SITUACAOPEDIDO,
      CODRETORNO,NOMEARQRET,ATULZABASE,NOMEARQREM,TIPOENVIO,FORMAENVIO,
      NUMIDENTCPAG,NUMREFCADPAG,NUMSEQCADPAG,NUMREFCADPAG_RET,
      SPID,DATAHORAPROCESSO,AGUARDAPENDENTE,SEQ_PEDIDO,NUMPEDIDOPEND,
	  --22/03/2023 - JLSANTOS - INCLUSÃO E TRATAMENTO DOS CAMPOS DATAHORADDA
	  DATAHORADDA
      FROM MANUT_SACELETRONICO M
	  INNER JOIN #TMP_MANUT_MANUT_SACELETRONICO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

      INSERT INTO MANUT_CONTA_CLIENTE_PASS
      ( DATALIMPEZA,DATAPEDIDO,DATALEGADO,CODSISLEGADO,NUMCTRLLEGADO,
      NUMPEDIDO,TIPOMANUTENCAO,TPAGENCIA,AGENCIA,TPCONTA,CONTA,DATAADESAO)
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.DATALEGADO,M.CODSISLEGADO,M.NUMCTRLLEGADO,
      NUMPEDIDO,TIPOMANUTENCAO,TPAGENCIA,AGENCIA,TPCONTA,CONTA,DATAADESAO
      FROM MANUT_CONTA_CLIENTE M
	  INNER JOIN #TMP_MANUT_MANUT_SACELETRONICO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

      INSERT INTO MANUT_AGREGADOS_PASS
      ( DATALIMPEZA,DATAPEDIDO,DATALEGADO,CODSISLEGADO,NUMCTRLLEGADO,
      CNPJ_CPF_AGREGADO,TIPOPESSOA,TIPOMANUTENCAO,SITUACAOPEDIDO,CODRETORNO)
      SELECT @DATAPROCESSAMENTO,M.DATAPEDIDO,M.DATALEGADO,M.CODSISLEGADO,M.NUMCTRLLEGADO,
      CNPJ_CPF_AGREGADO,TIPOPESSOA,TIPOMANUTENCAO,SITUACAOPEDIDO,CODRETORNO
      FROM MANUT_AGREGADOS M
	  INNER JOIN #TMP_MANUT_MANUT_SACELETRONICO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  
	  
	  DELETE M
      FROM MANUT_CONTA_CLIENTE M
	  INNER JOIN #TMP_MANUT_MANUT_SACELETRONICO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

	  DELETE M
      FROM MANUT_AGREGADOS M
	  INNER JOIN #TMP_MANUT_MANUT_SACELETRONICO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  


	  DELETE M
      FROM MANUT_SACELETRONICO M
	  INNER JOIN #TMP_MANUT_MANUT_SACELETRONICO_SEL 
	  ON M.DATAPEDIDO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.DATAPEDIDO
	  AND M.CODSISLEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.CODSISLEGADO
	  AND M.DATALEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.DATALEGADO
	  AND M.NUMCTRLLEGADO = #TMP_MANUT_MANUT_SACELETRONICO_SEL.NUMCTRLLEGADO	  
	  SELECT @SQLERRO = @@ERROR		 
	  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS	  

	DELETE FROM TAREFAS_DDA WHERE DATEDIFF(HH, DATAULTIMO, GETDATE() ) > 48  
	  
   
   SELECT @SQLERRO = @@ERROR		 
   IF @SQLERRO <> 0 GOTO TRATAERRO

   DROP INDEX IDX_TMP_MANUT_SACELETRONICO_SEL ON dbo.#TMP_MANUT_MANUT_SACELETRONICO_SEL
   SELECT @SQLERRO = @@ERROR		 
   IF @SQLERRO <> 0 GOTO TRATAERRO

   DROP TABLE #TMP_MANUT_MANUT_SACELETRONICO_SEL
   SELECT @SQLERRO = @@ERROR		 
   IF @SQLERRO <> 0 GOTO TRATAERRO


   RETURN
	TRATAERRO:
        SELECT @MSGERRO = CONVERT(VARCHAR(10),@SQLERRO)
		RAISERROR(@MSGERRO,15,1)
		RETURN
	TRATAERRO_TRANS:
        SELECT @MSGERRO = CONVERT(VARCHAR(10),@SQLERRO)
		RAISERROR(@MSGERRO,15,1)
		RETURN

END
GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO], 
    [NOMESCRIPT], 
    [CODUSUARIO], 
    [DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_LIMPEZA_DIARIA_MANUT',
	SYSTEM_USER, 
	GETDATE()
GO


