USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_PROCESSA_DDA0106R1_ADDA106')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_PROCESSA_DDA0106R1_ADDA106 AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE [dbo].[SP_PROCESSA_DDA0106R1_ADDA106](
	@P_TIMEOUT INT, 
	@P_SQLERRO INT OUT
) 
AS BEGIN

	/*
		27/02/2019 - RFAQUINI - VALIDAÇÃO PARA TÍTULOS NÃO ENCONTRADOS 
		
		13/11/2019 - EDUARDOK - REENVIO DE MANUT_TITULOS REJEITADOS
		
		21/11/2019 - RFAQUINI - CONSULTA SEM INFORMAÇÕES NA CIP
		
		24/08/2020 - ELIANE, RFAQUINI - ALTERAÇÃO PROVISÓRIA PARA NÃO INSERÇÃO DE BAIXAS OPERACIONAIS/EFETIVAS SEM NUMITENCBAIXA(OPERAC/EFET)
		
		02/09/2020 - ELIANE, RFAQUINI - RETIRAMOS POR CAUSA DE TÍTULOS DE OUTROS BANCOS NÃO ENTRAREM NA BASE
		
		12/11/2020 - ELIANE, RFAQUINI - AJUSTES PARA EVITAR INSERÇÕES COM DUPLICIDADES NO PROCESSAMENTO - ERRO DE PK (RA 2964, 2968 - BOR)
		
		31/01/2021 - ELIANE - AJUSTES PARA EVITAR INSERÇÕES COM DUPLICIDADES NO PROCESSAMENTO - ERRO DE PK (RA 2964, 2968 - BOR)
							  FILTRO PARA 8107
							  CAMPO NUMPEDIDOANT NOT NULL
		
		01/02/2021 - RFAQUINI - AJUSTE COLLATION (RA 3012 BOR)	
		
		08/04/2021 - RFAQUINI - REMOÇÃO DE ALIAS PARA TABELAS E #TEMP
		
		14/10/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
								REMOÇÃO DE ALIAS
								
		25/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
		13/03/2023 - ELIANE   - TRATANDO CATALOGO MODERNIZACAO - DESCONTINUANDO BAIXAS EFETIVAS...
		                        NAS CONSULTAS, ASSUMIMOS A POSIÇÃO DA CIP.
		                        SOMENTE AS BAIXAS DEFINITIVAS DEVEM ASSINALAR TIPOS DE BAIXA NO TÍTULO E
		                        DEVEM SEMPRE ESTAR DE ACORDO COM A SITUAÇÃO DO TÍTULO.
	*/
	
	/*
		DOMINIO DE REJEICOES (CODREJEICAO)	

		'01' - TITULO NAO ENCONTRADO
		'06' - PEDIDO CORRESPONDENTE NAO ENCONTRADO (APENAS RETORNO VIA MSG)
		'14' - ATUALIZACAO DE TITULO JA CADASTRADO (PARA UM PEDIDO DE CONSULTA COM BUSCABASESACADO S)
		'15' - RESULTADOS DE CONSULTA DESATUALIZADOS
	*/
	
	/*
		--EXEC
		DECLARE @P_SQLERRO INT
		EXEC SP_PROCESSA_DDA0106R1_ADDA106 5, @P_SQLERRO OUTPUT
		SELECT @P_SQLERRO
		GO
	*/

	DECLARE 
		@DATAULTPROCESSAMENTO DATETIME, 
		@DATAPROCESSAMENTO DATETIME, 
		@TIMESTAMP DATETIME, 
		@SQLERRO INT,
		@VRSMANUAL VARCHAR (07) /* 13/03/2023 */

	
	SELECT 
		@DATAULTPROCESSAMENTO = DATAULTPROCESSAMENTO, 
		@DATAPROCESSAMENTO = DATAPROCESSAMENTO, 
		@TIMESTAMP = GETDATE()
	FROM PARAMETROS
	WHERE CODSISTEMA = 'DDA-AUTK'


	SELECT @VRSMANUAL = VRSMANUAL FROM VWIB_VRSMANUAL WITH (NOLOCK)  /* 13/03/2023 */


	--DELETA RESERVAS POR TIMEOUT
	DELETE 
	FROM TEMP_RECEBE_DDA0106R1_ADDA106
	WHERE DATAHORAPROC < DATEADD(MINUTE, -(@P_TIMEOUT), @TIMESTAMP)

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	--BUSCA O QUE ESTA PENDENTE
	SELECT * 
		INTO #TEMP_RECEBE
	FROM RECEBE_DDA0106R1_ADDA106_ADDA107 
	WHERE CODPROCESSA = '0'
	AND DATAMOVTO >= @DATAULTPROCESSAMENTO
	AND DATAMOVTO <= @DATAPROCESSAMENTO 
	AND INDIMPORTACAOVALIDA = 'S'

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	--REMOVE O QUE AINDA ESTA RESERVADO
	DELETE #TEMP_RECEBE
	FROM #TEMP_RECEBE
	INNER JOIN TEMP_RECEBE_DDA0106R1_ADDA106
		ON (TEMP_RECEBE_DDA0106R1_ADDA106.SEQ_RECEBE = #TEMP_RECEBE.SEQ_RECEBE
		AND TEMP_RECEBE_DDA0106R1_ADDA106.DATAMOVTO = #TEMP_RECEBE.DATAMOVTO)

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	--RESERVA O QUE ESTA LIVRE
	INSERT INTO TEMP_RECEBE_DDA0106R1_ADDA106(
		SEQ_RECEBE, DATAMOVTO, DATAHORAPROC
	)
	SELECT 
		#TEMP_RECEBE.SEQ_RECEBE, #TEMP_RECEBE.DATAMOVTO, @TIMESTAMP
	FROM #TEMP_RECEBE 

	--PK DUPLICADA, PROCESSOS SIMULTANEOS?
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	--PREPARACAO DO PROCESSAMENTO

	--27/02/2019 - RFAQUINI - VALIDAÇÃO PARA TÍTULOS NÃO ENCONTRADOS
	--02/09/2020 - ELIANE, RFAQUINI - RETIRAMOS POR CAUSA DE TÍTULOS DE OUTROS BANCOS NÃO ENTRAREM NA BASE
	--CODREJEICAO "01" - TITULO NAO ENCONTRADO
	/*UPDATE #TEMP_RECEBE SET 
		CODREJEICAO = '01', 
		CODPROCESSA = '2' 
	FROM #TEMP_RECEBE 
	WHERE #TEMP_RECEBE.CODPROCESSA = '0' 
	AND #TEMP_RECEBE.CODREJEICAO IS NULL 
	AND NOT EXISTS (SELECT 1 FROM TITULOS 
						WHERE NUMIDENTCDDA = #TEMP_RECEBE.NUMIDENTCDDA
					)
	*/
	
	--COD REJEICAO "06" PARA RECEBES VIA MENSAGEM SEM UMA MANUT CORRESPONDENTE
	UPDATE #TEMP_RECEBE SET 
		CODPROCESSA = '2', 
		CODREJEICAO = '06'
	FROM #TEMP_RECEBE
	WHERE #TEMP_RECEBE.TIPORETORNO = 'M'

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	UPDATE #TEMP_RECEBE SET 
		CODPROCESSA = CASE 
			WHEN SITREQDDA IS NOT NULL 
			AND SITREQDDA = 3 
				THEN '3' 
			ELSE '0' 
			END, 
		CODREJEICAO = NULL 
	FROM #TEMP_RECEBE 
	INNER JOIN MANUT_TITULOS 
		ON (MANUT_TITULOS.NUMPEDIDO = #TEMP_RECEBE.NUMPEDIDO)
	WHERE MANUT_TITULOS.DATAPEDIDO >= @DATAULTPROCESSAMENTO
	AND MANUT_TITULOS.DATAPEDIDO <= @DATAPROCESSAMENTO
	AND MANUT_TITULOS.SITUACAOPEDIDO = '2' 

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	--TODOS OS TITULOS QUE NAO FOREM DA INSTITUICAO OU DE PAGADOR ELETRONICO PROPRIO DO BANCO E ATIVO, DEVE SER SOMENTE MARCADO COMO PROCESSADO (NO FINAL DA PROCEDURE)
	UPDATE #TEMP_RECEBE SET 
		CODPROCESSA = '1'
	FROM #TEMP_RECEBE 
	INNER JOIN PARAMETROS 
		ON (PARAMETROS.ISPB = #TEMP_RECEBE.ISPBCEDENTE)
	AND CODPROCESSA = '0'

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	UPDATE #TEMP_RECEBE SET 
		CODPROCESSA = '1'
	FROM #TEMP_RECEBE 
	INNER JOIN SACELETRONICO 
		ON (#TEMP_RECEBE.CNPJ_CPF_SACADO = SACELETRONICO.CNPJ_CPF_SACADO 
		AND SACELETRONICO.TIPOSACADO = 'P' 
		AND SACELETRONICO.SITUACAOSACADO = '1')
	AND CODPROCESSA = '0'

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	UPDATE #TEMP_RECEBE SET 
		CODPROCESSA = '1'
	FROM #TEMP_RECEBE 
	INNER JOIN AGREGADOS 
		ON (#TEMP_RECEBE.CNPJ_CPF_SACADO = AGREGADOS.CNPJ_CPF_AGREGADO)
	INNER JOIN SACELETRONICO 
		ON (AGREGADOS.CNPJ_CPF_SACADO = SACELETRONICO.CNPJ_CPF_SACADO 
		AND SACELETRONICO.TIPOSACADO = 'P' 
		AND SACELETRONICO.SITUACAOSACADO = '1')
	AND CODPROCESSA = '0'

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO
	
	--EXCLUI RESULTADOS MAIS ANTIGOS DE CADA TITULO
	SELECT MAX(DATAHORADDA) DATAHORADDA, NUMIDENTCDDA
		INTO #TEMP_MAX
	FROM #TEMP_RECEBE
	WHERE CODPROCESSA = '0'
	GROUP BY NUMIDENTCDDA

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	UPDATE #TEMP_RECEBE SET 
		CODPROCESSA = '4'
	FROM #TEMP_RECEBE 
	WHERE #TEMP_RECEBE.CODPROCESSA = '1'
	AND #TEMP_RECEBE.DATAHORADDA < (SELECT #TEMP_MAX.DATAHORADDA 
										FROM #TEMP_MAX  
										WHERE #TEMP_MAX.NUMIDENTCDDA = #TEMP_RECEBE.NUMIDENTCDDA
									)

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	--TABELA TEMPORARIA DE MANUTS
	SELECT MANUT_TITULOS.*
		INTO #TEMP_MANUT 
	FROM MANUT_TITULOS 
	WHERE MANUT_TITULOS.DATAPEDIDO >= @DATAULTPROCESSAMENTO 
	AND MANUT_TITULOS.DATAPEDIDO <= @DATAPROCESSAMENTO 
	AND MANUT_TITULOS.SITUACAOPEDIDO = '2'
	/*AND MANUT_TITULOS.TIPORETORNO = 'M'*/
	AND EXISTS (SELECT 1 FROM #TEMP_RECEBE 
					WHERE #TEMP_RECEBE.NUMPEDIDO = MANUT_TITULOS.NUMPEDIDO
					AND #TEMP_RECEBE.CODPROCESSA = '1'
				)

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO
	
	/*
	--COD REJEICAO "14" PARA ATUALIZACAO DE TITULOS JA EXISTENTES POREM COM PEDIDO MARCADO EM BUSCABASESACADO COM S (NECESSARIAMENTE RETORNO VIA MENSAGEM)
	UPDATE #TEMP_RECEBE SET 
		CODPROCESSA = '2', 
		CODREJEICAO = '14' 
	FROM #TEMP_RECEBE 
	INNER JOIN #TEMP_MANUT  
		ON (#TEMP_RECEBE.CODPROCESSA = '0' 
		AND #TEMP_RECEBE.CODREJEICAO IS NULL
		AND #TEMP_MANUT.BUSCABASESACADO = 'S' 
		AND #TEMP_MANUT.TIPORETORNO = 'M'
		AND #TEMP_RECEBE.NUMPEDIDO = #TEMP_MANUT.NUMPEDIDO 
		AND ISNULL(#TEMP_MANUT.NOMEARQRET, '') = ISNULL(#TEMP_RECEBE.NOMEARQRET, '')) 
	INNER JOIN TITULOS 
		ON (TITULOS.NUMIDENTCDDA = #TEMP_RECEBE.NUMIDENTCDDA)
		
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO
	*/
	
	UPDATE #TEMP_MANUT SET 
		SITUACAOPEDIDO = '5', 
		CODRETORNO = '1'
	FROM #TEMP_MANUT
	INNER JOIN #TEMP_RECEBE 
		ON (#TEMP_RECEBE.CODPROCESSA = '2' 
		AND #TEMP_RECEBE.CODREJEICAO IS NOT NULL
		AND #TEMP_MANUT.NUMPEDIDO = #TEMP_RECEBE.NUMPEDIDO 
		AND ISNULL(#TEMP_RECEBE.NOMEARQRET, '') = ISNULL(#TEMP_MANUT.NOMEARQRET, ''))

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	--O RESTO PODE SER DADO COMO ACEITO E PROCESSADO
	UPDATE #TEMP_MANUT SET 
		SITUACAOPEDIDO = '5', 
		CODRETORNO = '0' 
	WHERE SITUACAOPEDIDO = '2'
	AND TIPORETORNO = 'M'

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	--SEPARANDO AS INCLUSÕES DE NOVOS TITULOS DAS ATUALIZACOES DE TITULOS EXISTENTES
	SELECT * 
		INTO #TEMP_INCLUSAO
	FROM #TEMP_RECEBE
	WHERE #TEMP_RECEBE.CODPROCESSA = '1'

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	DELETE #TEMP_INCLUSAO 
	FROM #TEMP_INCLUSAO
	INNER JOIN TITULOS
		ON (TITULOS.NUMIDENTCDDA = #TEMP_INCLUSAO.NUMIDENTCDDA)

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO
	
	--TRATAMENTO PARA OUTROS MEMBROS DO TITULO: 

	--NOTA FISCAL
	SELECT RECEBE_NOTAS_FISCAIS_DDA0106R1_ADDA106_ADDA107.* 
		INTO #TEMP_NOTAS
	FROM RECEBE_NOTAS_FISCAIS_DDA0106R1_ADDA106_ADDA107 
	INNER JOIN #TEMP_RECEBE 
		ON (#TEMP_RECEBE.CODPROCESSA = '1' 
		AND #TEMP_RECEBE.CODREJEICAO IS NULL 
		AND RECEBE_NOTAS_FISCAIS_DDA0106R1_ADDA106_ADDA107.SEQ_RECEBE = #TEMP_RECEBE.SEQ_RECEBE
		AND RECEBE_NOTAS_FISCAIS_DDA0106R1_ADDA106_ADDA107.DATAMOVTO = #TEMP_RECEBE.DATAMOVTO
		AND RECEBE_NOTAS_FISCAIS_DDA0106R1_ADDA106_ADDA107.NUMIDENTCDDA = #TEMP_RECEBE.NUMIDENTCDDA
		AND ISNULL(RECEBE_NOTAS_FISCAIS_DDA0106R1_ADDA106_ADDA107.NUMPEDIDO, -1) = ISNULL(#TEMP_RECEBE.NUMPEDIDO, -1))

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	--MENSAGEM
	SELECT RECEBE_MENSAGENS_DDA0106R1_ADDA106_ADDA107.* 
		INTO #TEMP_MENSAGENS
	FROM RECEBE_MENSAGENS_DDA0106R1_ADDA106_ADDA107 
	INNER JOIN #TEMP_RECEBE 
		ON (#TEMP_RECEBE.CODPROCESSA = '1' 
		AND #TEMP_RECEBE.CODREJEICAO IS NULL 
		AND RECEBE_MENSAGENS_DDA0106R1_ADDA106_ADDA107.SEQ_RECEBE = #TEMP_RECEBE.SEQ_RECEBE
		AND RECEBE_MENSAGENS_DDA0106R1_ADDA106_ADDA107.DATAMOVTO = #TEMP_RECEBE.DATAMOVTO
		AND RECEBE_MENSAGENS_DDA0106R1_ADDA106_ADDA107.NUMIDENTCDDA = #TEMP_RECEBE.NUMIDENTCDDA
		AND ISNULL(RECEBE_MENSAGENS_DDA0106R1_ADDA106_ADDA107.NUMPEDIDO, -1) = ISNULL(#TEMP_RECEBE.NUMPEDIDO, -1))

	SELECT @SQLERRO = @@ERROR
	IF @SQLERRO <> 0 GOTO TRATAERRO

	--CALCULOS
	SELECT RECEBE_CALCULOS_DDA0106R1_ADDA106.* 
		INTO #TEMP_CALCULOS
	FROM RECEBE_CALCULOS_DDA0106R1_ADDA106
	INNER JOIN #TEMP_RECEBE 
		ON (#TEMP_RECEBE.CODPROCESSA = '1' 
		AND #TEMP_RECEBE.CODREJEICAO IS NULL 
		AND RECEBE_CALCULOS_DDA0106R1_ADDA106.SEQ_RECEBE = #TEMP_RECEBE.SEQ_RECEBE
		AND RECEBE_CALCULOS_DDA0106R1_ADDA106.DATAMOVTO = #TEMP_RECEBE.DATAMOVTO
		AND RECEBE_CALCULOS_DDA0106R1_ADDA106.NUMIDENTCDDA = #TEMP_RECEBE.NUMIDENTCDDA
		AND ISNULL(RECEBE_CALCULOS_DDA0106R1_ADDA106.NUMPEDIDO, -1) = ISNULL(#TEMP_RECEBE.NUMPEDIDO, -1))

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	--TERCEIROS
	SELECT RECEBE_TERCEIROS_DDA0106R1_ADDA106.* 
		INTO #TEMP_TERCEIROS
	FROM RECEBE_TERCEIROS_DDA0106R1_ADDA106 
	INNER JOIN #TEMP_RECEBE 
		ON (#TEMP_RECEBE.CODPROCESSA = '1' 
		AND #TEMP_RECEBE.CODREJEICAO IS NULL 
		AND RECEBE_TERCEIROS_DDA0106R1_ADDA106.SEQ_RECEBE = #TEMP_RECEBE.SEQ_RECEBE
		AND RECEBE_TERCEIROS_DDA0106R1_ADDA106.DATAMOVTO = #TEMP_RECEBE.DATAMOVTO
		AND RECEBE_TERCEIROS_DDA0106R1_ADDA106.NUMIDENTCDDA = #TEMP_RECEBE.NUMIDENTCDDA
		AND ISNULL(RECEBE_TERCEIROS_DDA0106R1_ADDA106.NUMPEDIDO, -1) = ISNULL(#TEMP_RECEBE.NUMPEDIDO, -1))

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	--BAIXAS OPERACIONAIS
	SELECT RECEBE_BAIXAS_OPERACIONAIS_DDA0106R1_ADDA106.* 
		INTO #TEMP_OPERACIONAIS
	FROM RECEBE_BAIXAS_OPERACIONAIS_DDA0106R1_ADDA106 
	INNER JOIN #TEMP_RECEBE 
		ON (#TEMP_RECEBE.CODPROCESSA = '1' 
		AND #TEMP_RECEBE.CODREJEICAO IS NULL 
		AND RECEBE_BAIXAS_OPERACIONAIS_DDA0106R1_ADDA106.SEQ_RECEBE = #TEMP_RECEBE.SEQ_RECEBE
		AND RECEBE_BAIXAS_OPERACIONAIS_DDA0106R1_ADDA106.DATAMOVTO = #TEMP_RECEBE.DATAMOVTO
		AND RECEBE_BAIXAS_OPERACIONAIS_DDA0106R1_ADDA106.NUMIDENTCDDA = #TEMP_RECEBE.NUMIDENTCDDA
		AND ISNULL(RECEBE_BAIXAS_OPERACIONAIS_DDA0106R1_ADDA106.NUMPEDIDO, -1) = ISNULL(#TEMP_RECEBE.NUMPEDIDO, -1))

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	--BAIXAS EFETIVAS
	SELECT RECEBE_BAIXAS_EFETIVAS_DDA0106R1_ADDA106.* 
		INTO #TEMP_EFETIVAS
	FROM RECEBE_BAIXAS_EFETIVAS_DDA0106R1_ADDA106
	INNER JOIN #TEMP_RECEBE
		ON (#TEMP_RECEBE.CODPROCESSA = '1' 
		AND #TEMP_RECEBE.CODREJEICAO IS NULL 
		AND RECEBE_BAIXAS_EFETIVAS_DDA0106R1_ADDA106.SEQ_RECEBE = #TEMP_RECEBE.SEQ_RECEBE
		AND RECEBE_BAIXAS_EFETIVAS_DDA0106R1_ADDA106.DATAMOVTO = #TEMP_RECEBE.DATAMOVTO
		AND RECEBE_BAIXAS_EFETIVAS_DDA0106R1_ADDA106.NUMIDENTCDDA = #TEMP_RECEBE.NUMIDENTCDDA
		AND ISNULL(RECEBE_BAIXAS_EFETIVAS_DDA0106R1_ADDA106.NUMPEDIDO, -1) = ISNULL(#TEMP_RECEBE.NUMPEDIDO, -1))

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	--APLICANDO RESULTADOS
	BEGIN TRANSACTION
		--INCLUSOES DE TITULOS NOVOS
		INSERT INTO TITULOS (
			NUMIDENTCDDA, 		
			NUMCODBARRAS, VLRTITULO, SEUNUMERO, 
			CODESPECIEDOC, DATAEMISSAO, TIPOPAGTO, INDTITULONEGOCIADO, 
			VLRABATIMENTO
		)  
		SELECT
			#TEMP_INCLUSAO.NUMIDENTCDDA, 	
			'', 0, '', 
			'', GETDATE(), '', '', 
			0   
		FROM #TEMP_INCLUSAO 
		GROUP BY #TEMP_INCLUSAO.NUMIDENTCDDA 

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS

		--ATUALIZACAO DE TODOS OS TITULOS (NOVOS E EXISTENTES)
		UPDATE TITULOS SET 
			CODIFCEDENTE = #TEMP_RECEBE.CODIFCEDENTE, 
			TIPOPESCEDENTE = #TEMP_RECEBE.TIPOPESCEDENTE, 
			CNPJ_CPF_CEDENTE = #TEMP_RECEBE.CNPJ_CPF_CEDENTE, 
			NOMECEDENTE = #TEMP_RECEBE.NOMECEDENTE, 
			NOMEFANTASIACEDENTE = #TEMP_RECEBE.NOMEFANTASIACEDENTE, 
			TIPOPESCEDENTEORI = #TEMP_RECEBE.TIPOPESCEDENTEORI, 
			CNPJ_CPF_CEDENTEORI = #TEMP_RECEBE.CNPJ_CPF_CEDENTEORI, 
			NOMECEDENTEORI = #TEMP_RECEBE.NOMECEDENTEORI, 
			ENDCEDENTEORI = #TEMP_RECEBE.ENDCEDENTEORI, 
			CIDCEDENTEORI = #TEMP_RECEBE.CIDCEDENTEORI, 
			UFCEDENTEORI = #TEMP_RECEBE.UFCEDENTEORI, 
			CEPCEDENTEORI = #TEMP_RECEBE.CEPCEDENTEORI, 
			TIPOPESSACADO = #TEMP_RECEBE.TIPOPESSACADO, 
			CNPJ_CPF_SACADO = #TEMP_RECEBE.CNPJ_CPF_SACADO, 
			NOMESACADO = #TEMP_RECEBE.NOMESACADO, 
			NOMEFANTASIASACADO = #TEMP_RECEBE.NOMEFANTASIASACADO, 
			ENDSACADO = #TEMP_RECEBE.ENDSACADO, 
			CIDSACADO = #TEMP_RECEBE.CIDSACADO, 
			UFSACADO = #TEMP_RECEBE.UFSACADO, 
			CEPSACADO = #TEMP_RECEBE.CEPSACADO, 
			TIPOPESSACADOR = #TEMP_RECEBE.TIPOPESSACADOR, 
			CNPJ_CPF_SACADOR = #TEMP_RECEBE.CNPJ_CPF_SACADOR, 
			NOMESACADOR = #TEMP_RECEBE.NOMESACADOR, 
			CODCARTEIRA = #TEMP_RECEBE.CODCARTEIRA, 
			CODMOEDACNAB = #TEMP_RECEBE.CODMOEDACNAB, 
			IDENTNOSSONUMERO = #TEMP_RECEBE.IDENTNOSSONUMERO, 
			NUMCODBARRAS = #TEMP_RECEBE.NUMCODBARRAS, 
			DATAVENCIMENTO = #TEMP_RECEBE.DATAVENCIMENTO, 
			VLRTITULO = #TEMP_RECEBE.VLRTITULO, 
			SEUNUMERO = #TEMP_RECEBE.SEUNUMERO, 
			CODESPECIEDOC = #TEMP_RECEBE.CODESPECIEDOC, 
			DATAEMISSAO = #TEMP_RECEBE.DATAEMISSAO, 
			QTDEDIASPROTESTO = #TEMP_RECEBE.QTDEDIASPROTESTO, 
			DATALIMPAGTO = #TEMP_RECEBE.DATALIMPAGTO, 
			TIPOPAGTO = #TEMP_RECEBE.TIPOPAGTO, 
			INDTITULONEGOCIADO = #TEMP_RECEBE.INDTITULONEGOCIADO, 
			VLRABATIMENTO = #TEMP_RECEBE.VLRABATIMENTO, 
			CODMORA = #TEMP_RECEBE.CODMORA, 
			DATAMORA = #TEMP_RECEBE.DATAMORA, 
			VLRPERCMORA = #TEMP_RECEBE.VLRPERCMORA, 
			CODMULTA = #TEMP_RECEBE.CODMULTA, 
			DATAMULTA = #TEMP_RECEBE.DATAMULTA, 
			VLRPERCMULTA = #TEMP_RECEBE.VLRPERCMULTA, 
			CODDESCONTO01 = #TEMP_RECEBE.CODDESCONTO01, 
			DATADESCONTO01 = #TEMP_RECEBE.DATADESCONTO01, 
			VLRPERCDESCONTO01 = #TEMP_RECEBE.VLRPERCDESCONTO01, 
			CODDESCONTO02 = #TEMP_RECEBE.CODDESCONTO02, 
			DATADESCONTO02 = #TEMP_RECEBE.DATADESCONTO02, 
			VLRPERCDESCONTO02 = #TEMP_RECEBE.VLRPERCDESCONTO02, 
			CODDESCONTO03 = #TEMP_RECEBE.CODDESCONTO03, 
			DATADESCONTO03 = #TEMP_RECEBE.DATADESCONTO03, 
			VLRPERCDESCONTO03 = #TEMP_RECEBE.VLRPERCDESCONTO03, 
			CODSITUACAO = SUBSTRING(#TEMP_RECEBE.CODSITUACAO, 2, 1), 
			DTHRSITTITULO = #TEMP_RECEBE.DTHRSIT, 
			DATAHORADDA = #TEMP_RECEBE.DATAHORADDA, 
			TIPOCALCULO = #TEMP_RECEBE.TIPOCALCULO, 
			ULTNUMREFCADTIT = #TEMP_RECEBE.NUMREFCADTITULO, 
			ULTNUMSEQCADTIT = #TEMP_RECEBE.NUMSEQCADTITULO, 
			ISPBCEDENTE = #TEMP_RECEBE.ISPBCEDENTE, 
			LINHADIGITAVEL = #TEMP_RECEBE.LINHADIGITAVEL, 
			NUMPARCELA = #TEMP_RECEBE.NUMPARCELA, 
			QTDPARCELA = #TEMP_RECEBE.QTDPARCELA, 
			INDBLOQUEIO = #TEMP_RECEBE.INDBLOQPAGTO, 
			INDPARCIAL = #TEMP_RECEBE.INDPAGTOPARCIAL, 
			QTDPAGTO = #TEMP_RECEBE.QTDPAGTOPARCIAL, 
			TIPOAUTRECDIVERGENTE = #TEMP_RECEBE.TIPOAUTVLRDIVERGENTE, 
			INDVALORPERC_MIN = #TEMP_RECEBE.TIPOVLRPERCMIN, 
			VLRMINTITULO = #TEMP_RECEBE.VLRMINTITULO, 
			INDVALORPERC_MAX = #TEMP_RECEBE.TIPOVLRPERCMAX, 
			VLRMAXTITULO = #TEMP_RECEBE.VLRMAXTITULO, 
			ULTNUMREFACEITE = #TEMP_RECEBE.NUMREFCADACEITE, 
			ULTNUMSEQACEITE = #TEMP_RECEBE.NUMSEQCADACEITE, 
			ACEITE = #TEMP_RECEBE.ACEITE, 
			QTDPAGTOREG = #TEMP_RECEBE.QTDPAGTOPARCIALREGISTRADO, 
			VLRSALDOATUAL = #TEMP_RECEBE.VLRSALDOTITULO, 
			SITPAGAMENTOCIP = #TEMP_RECEBE.SITPAGTO, 	
			ULTNUMREFBAIXAEFET = NULL, 
			ULTNUMREFBAIXAOPERAC = NULL, 
			ULTNUMREFTERC = NULL, 
			ULTNUMSEQBAIXAEFET = NULL, 
			ULTNUMSEQBAIXAOPERAC = NULL
		FROM #TEMP_RECEBE, TITULOS 
		WHERE #TEMP_RECEBE.CODPROCESSA = '1'
		AND #TEMP_RECEBE.CODREJEICAO IS NULL
		AND #TEMP_RECEBE.NUMIDENTCDDA = TITULOS.NUMIDENTCDDA
		
		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS

		--NOTAS FISCAIS ATUAIS
		DELETE NOTAS_FISCAIS 
		FROM NOTAS_FISCAIS 
		INNER JOIN #TEMP_RECEBE 
			ON (#TEMP_RECEBE.CODPROCESSA = '1' 
			AND NOTAS_FISCAIS.NUMIDENTCDDA = #TEMP_RECEBE.NUMIDENTCDDA)

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS

		INSERT INTO NOTAS_FISCAIS(
			NUMIDENTCDDA, NUMNOTAFISCAL, DATAEMISSAO, VLRNOTAFISCAL
		)
		SELECT 
			#TEMP_NOTAS.NUMIDENTCDDA, #TEMP_NOTAS.NUMNOTAFISCAL, #TEMP_NOTAS.DATAEMISSAO, #TEMP_NOTAS.VLRNOTAFISCAL
		FROM #TEMP_NOTAS 

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS

		--12/11/2020 - ELIANE, RFAQUINI - AJUSTES PARA EVITAR INSERÇÕES COM DUPLICIDADES NO PROCESSAMENTO - ERRO DE PK (RA 2964, 2968 - BOR)
		--MENSAGENS ATUAIS
		/*DELETE MENSAGENS 
		FROM MENSAGENS
		INNER JOIN #TEMP_RECEBE 
			ON (#TEMP_RECEBE.CODPROCESSA = '1' 
			AND MENSAGENS.NUMIDENTCDDA = #TEMP_RECEBE.NUMIDENTCDDA)

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS

		INSERT INTO MENSAGENS(
			NUMIDENTCDDA, SEQMENSAGEM, TEXTO
		)
		SELECT 
			#TEMP_MENSAGENS.NUMIDENTCDDA, #TEMP_MENSAGENS.SEQMENSAGEM, #TEMP_MENSAGENS.TEXTO 
		FROM #TEMP_MENSAGENS*/

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS

		--CALCULOS ATUAIS
		DELETE CALCULOS 
		FROM CALCULOS
		INNER JOIN #TEMP_RECEBE 
			ON (#TEMP_RECEBE.CODPROCESSA = '1' 
			AND #TEMP_RECEBE.NUMIDENTCDDA = CALCULOS.NUMIDENTCDDA)

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS

		INSERT INTO CALCULOS(
			NUMIDENTCDDA, DATACALCULO, VLRMORA, VLRMULTA, VLRDESCONTO, VLRCOBRAR
		)
		SELECT 
			NUMIDENTCDDA, DATAVALCALC, VLRJUROS, VLRMULTA, VLRDESC, VLRCOBRAR
		FROM #TEMP_CALCULOS
		--*12/11/2020 - ELIANE, RFAQUINI - AJUSTES PARA EVITAR INSERÇÕES COM DUPLICIDADES NO PROCESSAMENTO - ERRO DE PK (RA 2964, 2968 - BOR)
		GROUP BY NUMIDENTCDDA, DATAVALCALC, VLRJUROS, VLRMULTA, VLRDESC, VLRCOBRAR

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS

		--TERCEIROS ATUAIS
		DELETE TERCEIROS 
		FROM TERCEIROS
		INNER JOIN #TEMP_RECEBE 
			ON (#TEMP_RECEBE.CODPROCESSA = '1' 
			AND TERCEIROS.NUMIDENTCDDA = #TEMP_RECEBE.NUMIDENTCDDA)

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS

		INSERT INTO TERCEIROS(
			NUMIDENTCDDA, NUMIDENTCTERC, NUMCTRLDDA, NUMREFTERC, DATAMOVTO, DATAHORADDA, TIPOPESTERC, CNPJ_CPF_TERC
		)
		SELECT
			NUMIDENTCDDA, NUMIDENTCTERC, NUMCTRLDDA, NUMREFTERC, DATAMOVTO, DATAHORADDA, TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO 
		FROM #TEMP_TERCEIROS
		--12/11/2020 - ELIANE, RFAQUINI - AJUSTES PARA EVITAR INSERÇÕES COM DUPLICIDADES NO PROCESSAMENTO - ERRO DE PK (RA 2964, 2968 - BOR)
		GROUP BY NUMIDENTCDDA, NUMIDENTCTERC, NUMCTRLDDA, NUMREFTERC, DATAMOVTO, DATAHORADDA, TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS

		UPDATE TITULOS SET 
			ULTNUMREFTERC = #TEMP_TERCEIROS.NUMREFTERC
		FROM TITULOS
		INNER JOIN #TEMP_RECEBE 
		ON (#TEMP_RECEBE.CODPROCESSA = '1' 
			AND #TEMP_RECEBE.CODREJEICAO IS NULL 
			AND #TEMP_RECEBE.NUMIDENTCDDA = TITULOS.NUMIDENTCDDA)
		INNER JOIN #TEMP_TERCEIROS
			ON (#TEMP_TERCEIROS.NUMIDENTCDDA = TITULOS.NUMIDENTCDDA)

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS

		--BAIXAS OPERACIONAIS ATUAIS
		DELETE BAIXAS_OPERACIONAIS 
		FROM BAIXAS_OPERACIONAIS
		INNER JOIN #TEMP_RECEBE 
			ON (#TEMP_RECEBE.CODPROCESSA = '1' 
			AND BAIXAS_OPERACIONAIS.NUMIDENTCDDA = #TEMP_RECEBE.NUMIDENTCDDA)

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS


		/*--------------------------------------------------------------------------------*/
		/* 13/03/2023 - Eliane - Tratamento para a Modernização...   INICIO DE TRECHO...  */
		/*--------------------------------------------------------------------------------*/
                IF @VRSMANUAL <= '5.05'  
                
                BEGIN /* Catalogo anterior à MODERNIZAÇÃO - SOMENTE AVISO DE LIQUIDAÇÃO */

                        INSERT INTO BAIXAS_OPERACIONAIS(
			NUMIDENTCDDA, NUMIDENTCBAIXAOPERAC, NUMCTRLDDA, NUMREFBAIXAOPERAC, 
			NUMSEQBAIXAOPERAC, NUMREFCADTIT, DATAMOVTO, DATAHORADDA, 
			TIPOBAIXA, DATABAIXA, DATAHORABAIXA, VLRBAIXA, 
			NUMCODBARRAS, SITBAIXA, DATAHORASITUACAO, ISPBSACADA, 
			CODIFSACADA, NUMCTRLDDACANCEL, DATAHORACANCEL, SITPAGTO, 
			SITUACAOTIT, CANALPAGTO, MEIOPAGTO, INDCONTINGENCIA, 
			TIPOPESPORTADOR, CNPJ_CPF_PORTADOR, NUMSEQCADTIT,
			--14/10/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
			--25/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
			NOME_PORTADOR, DATAHORARECBTTITULO

		)
		--31/01/2021 - ELIANE - AJUSTES PARA EVITAR INSERÇÕES COM DUPLICIDADES NO PROCESSAMENTO - ERRO DE PK (RA 2964, 2968 - BOR)
		SELECT
			#TEMP_OPERACIONAIS.NUMIDENTCDDA, #TEMP_OPERACIONAIS.NUMIDENTCBAIXAOPERAC, '0'/*31/03/2021*/, 
			MAX(#TEMP_OPERACIONAIS.NUMREFBAIXAOPERAC), MAX(#TEMP_OPERACIONAIS.NUMSEQBAIXAOPERAC), MAX(#TEMP_RECEBE.NUMREFCADTITULO)/*31/03/2021*/, MAX(#TEMP_RECEBE.DATAMOVTO), MAX(#TEMP_RECEBE.DATAHORADDA), 
			MAX(#TEMP_OPERACIONAIS.TIPOBAIXA), MAX(#TEMP_OPERACIONAIS.DATABAIXA), MAX(#TEMP_OPERACIONAIS.DATAHORABAIXA), MAX(#TEMP_OPERACIONAIS.VLRBAIXA), 
			MAX(#TEMP_OPERACIONAIS.NUMCODBARRAS), MAX(#TEMP_OPERACIONAIS.SITBAIXA), MAX(#TEMP_OPERACIONAIS.DATAHORASITUACAO), MAX(#TEMP_OPERACIONAIS.ISPBSACADA), 
			MAX(#TEMP_OPERACIONAIS.CODIFSACADA), MAX(#TEMP_OPERACIONAIS.NUMCTRLDDACANCEL), MAX(#TEMP_OPERACIONAIS.DATAHORACANCEL), MAX(#TEMP_OPERACIONAIS.SITPAGTO), 
			MAX(#TEMP_RECEBE.CODSITUACAO), MAX(#TEMP_OPERACIONAIS.CANALPAGTO), MAX(#TEMP_OPERACIONAIS.MEIOPAGTO), MAX(#TEMP_OPERACIONAIS.INDCONTINGENCIA), 
			MAX(#TEMP_OPERACIONAIS.TIPOPESPORTADOR), MAX(#TEMP_OPERACIONAIS.CNPJ_CPF_PORTADOR), MAX(#TEMP_RECEBE.NUMSEQCADTITULO),/*31/03/2021*/
			--14/10/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
			--25/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
			MAX(#TEMP_OPERACIONAIS.NOME_PORTADOR), MAX(#TEMP_OPERACIONAIS.DATAHORARECBTTITULO)

		FROM #TEMP_OPERACIONAIS
		INNER JOIN #TEMP_RECEBE
			ON (#TEMP_RECEBE.CODPROCESSA = '1' 
			AND #TEMP_OPERACIONAIS.SEQ_RECEBE = #TEMP_RECEBE.SEQ_RECEBE)
		--24/08/2020 - ELIANE, RFAQUINI - ALTERAÇÃO PROVISÓRIA PARA NÃO INSERÇÃO DE BAIXAS OPERACIONAIS/EFETIVAS SEM NUMITENCBAIXA(OPERAC/EFET)
		WHERE #TEMP_OPERACIONAIS.NUMIDENTCBAIXAOPERAC IS NOT NULL
		--31/01/2021 - ELIANE - AJUSTES PARA EVITAR INSERÇÕES COM DUPLICIDADES NO PROCESSAMENTO - ERRO DE PK (RA 2964, 2968 - BOR)
		GROUP BY #TEMP_OPERACIONAIS.NUMIDENTCDDA, #TEMP_OPERACIONAIS.NUMIDENTCBAIXAOPERAC
			
		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS


                END   /* Catalogo anterior à MODERNIZAÇÃO - SOMENTE AVISO DE LIQUIDAÇÃO */
            
                
                ELSE /*********************** MODERNIZAÇÃO ******************************/

                BEGIN /* Catalogo MODERNIZAÇÃO - SOMENTE BAIXAS OPERACIONAIS */


		INSERT INTO BAIXAS_OPERACIONAIS(
			NUMIDENTCDDA, NUMIDENTCBAIXAOPERAC, NUMCTRLDDA, NUMREFBAIXAOPERAC, 
			NUMSEQBAIXAOPERAC, NUMREFCADTIT, DATAMOVTO, DATAHORADDA, 
			TIPOBAIXA, DATABAIXA, DATAHORABAIXA, VLRBAIXA, 
			NUMCODBARRAS, SITBAIXA, DATAHORASITUACAO, ISPBSACADA, 
			CODIFSACADA, NUMCTRLDDACANCEL, DATAHORACANCEL, SITPAGTO, 
			SITUACAOTIT, CANALPAGTO, MEIOPAGTO, INDCONTINGENCIA, 
			TIPOPESPORTADOR, CNPJ_CPF_PORTADOR, NUMSEQCADTIT,
			--14/10/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
			--25/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
			NOME_PORTADOR, DATAHORARECBTTITULO,
			
			TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, AGENCIARECEBEDORA /* CAT MODERNIZAÇÃO */

		)
		--31/01/2021 - ELIANE - AJUSTES PARA EVITAR INSERÇÕES COM DUPLICIDADES NO PROCESSAMENTO - ERRO DE PK (RA 2964, 2968 - BOR)
		SELECT
			#TEMP_OPERACIONAIS.NUMIDENTCDDA, #TEMP_OPERACIONAIS.NUMIDENTCBAIXAOPERAC, '0'/*31/03/2021*/, 
			MAX(#TEMP_OPERACIONAIS.NUMREFBAIXAOPERAC), MAX(ISNULL (#TEMP_OPERACIONAIS.NUMSEQBAIXAOPERAC, 0)), MAX(#TEMP_RECEBE.NUMREFCADTITULO)/*31/03/2021*/, 
			MAX(#TEMP_RECEBE.DATAMOVTO), MAX(#TEMP_RECEBE.DATAHORADDA), 
			MAX(#TEMP_OPERACIONAIS.TIPOBAIXA), MAX(#TEMP_OPERACIONAIS.DATABAIXA), MAX(#TEMP_OPERACIONAIS.DATAHORABAIXA), MAX(#TEMP_OPERACIONAIS.VLRBAIXA), 
			MAX(#TEMP_OPERACIONAIS.NUMCODBARRAS), MAX(#TEMP_OPERACIONAIS.SITBAIXA), MAX(#TEMP_OPERACIONAIS.DATAHORASITUACAO), MAX(#TEMP_OPERACIONAIS.ISPBSACADA), 
			MAX(#TEMP_OPERACIONAIS.CODIFSACADA), MAX(#TEMP_OPERACIONAIS.NUMCTRLDDACANCEL), MAX(#TEMP_OPERACIONAIS.DATAHORACANCEL), MAX(#TEMP_OPERACIONAIS.SITPAGTO), 
			MAX(#TEMP_RECEBE.CODSITUACAO), MAX(#TEMP_OPERACIONAIS.CANALPAGTO), MAX(#TEMP_OPERACIONAIS.MEIOPAGTO), MAX(#TEMP_OPERACIONAIS.INDCONTINGENCIA), 
			MAX(#TEMP_OPERACIONAIS.TIPOPESPORTADOR), MAX(#TEMP_OPERACIONAIS.CNPJ_CPF_PORTADOR), MAX(#TEMP_RECEBE.NUMSEQCADTITULO),/*31/03/2021*/
			--14/10/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
			--25/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
			MAX(#TEMP_OPERACIONAIS.NOME_PORTADOR), MAX(#TEMP_OPERACIONAIS.DATAHORARECBTTITULO),
			
			MAX(#TEMP_OPERACIONAIS.TIPOPESAGREGADOR), MAX(#TEMP_OPERACIONAIS.CNPJ_CPF_AGREGADOR), MAX (#TEMP_OPERACIONAIS.NOMEAGREGADOR), 	/* CAT MODERNIZAÇÃO */
			MAX (#TEMP_OPERACIONAIS.AGENCIARECEBEDORA) 					/* CAT MODERNIZAÇÃO */

		FROM #TEMP_OPERACIONAIS
		INNER JOIN #TEMP_RECEBE
			ON (#TEMP_RECEBE.CODPROCESSA = '1' 
			AND #TEMP_OPERACIONAIS.SEQ_RECEBE = #TEMP_RECEBE.SEQ_RECEBE)
		--24/08/2020 - ELIANE, RFAQUINI - ALTERAÇÃO PROVISÓRIA PARA NÃO INSERÇÃO DE BAIXAS OPERACIONAIS/EFETIVAS SEM NUMITENCBAIXA(OPERAC/EFET)
		WHERE #TEMP_OPERACIONAIS.NUMIDENTCBAIXAOPERAC IS NOT NULL
		--31/01/2021 - ELIANE - AJUSTES PARA EVITAR INSERÇÕES COM DUPLICIDADES NO PROCESSAMENTO - ERRO DE PK (RA 2964, 2968 - BOR)
		GROUP BY #TEMP_OPERACIONAIS.NUMIDENTCDDA, #TEMP_OPERACIONAIS.NUMIDENTCBAIXAOPERAC
			
		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS


                END   /* Catalogo MODERNIZAÇÃO - SOMENTE BAIXAS OPERACIONAIS */

		/*--------------------------------------------------------------------------------*/
		/* 13/03/2023 - Eliane - Tratamento para a Modernização...   FIM    DE TRECHO...  */
		/*--------------------------------------------------------------------------------*/

		SELECT MAX(NUMSEQBAIXAOPERAC) NUMSEQBAIXAOPERAC, NUMIDENTCDDA
			INTO #MAX_OPERACIONAIS 
		FROM #TEMP_OPERACIONAIS
		GROUP BY NUMIDENTCDDA


		/*--------------------------------------------------------------------------------*/
		/* 13/03/2023 - Eliane - Tratamento para a Modernização...   INICIO DE TRECHO...  */
		/*--------------------------------------------------------------------------------*/
               IF @VRSMANUAL <= '5.05'  

               BEGIN /* Catalogo anterior à MODERNIZAÇÃO */

		UPDATE TITULOS SET 
			ULTNUMREFBAIXAOPERAC = #TEMP_OPERACIONAIS.NUMREFBAIXAOPERAC, 
			ULTNUMSEQBAIXAOPERAC = ISNULL (#TEMP_OPERACIONAIS.NUMSEQBAIXAOPERAC, 0) 
		FROM TITULOS
		INNER JOIN #TEMP_RECEBE 
			ON (#TEMP_RECEBE.CODPROCESSA = '1' 
			AND #TEMP_RECEBE.CODREJEICAO IS NULL 
			AND #TEMP_RECEBE.NUMIDENTCDDA = TITULOS.NUMIDENTCDDA)
		INNER JOIN #TEMP_OPERACIONAIS
			ON (#TEMP_RECEBE.NUMIDENTCDDA = #TEMP_OPERACIONAIS.NUMIDENTCDDA)
		INNER JOIN #MAX_OPERACIONAIS 
			ON (#TEMP_OPERACIONAIS.NUMIDENTCDDA = #MAX_OPERACIONAIS.NUMIDENTCDDA 
			AND #TEMP_OPERACIONAIS.NUMSEQBAIXAOPERAC = #MAX_OPERACIONAIS.NUMSEQBAIXAOPERAC)

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS

               END   /* Catalogo anterior à MODERNIZAÇÃO */
               
               ELSE
               
               BEGIN /* CÁTALOGO DA MODERNIZACAO EM DIANTE... */
               
               SELECT MAX(NUMIDENTCBAIXAOPERAC) NUMIDENTCBAIXAOPERAC, NUMIDENTCDDA
	       	INTO #MAX_OPERACIONAISNOVAS 
	       FROM #TEMP_OPERACIONAIS
	       GROUP BY NUMIDENTCDDA

               
		UPDATE TITULOS SET 
			ULTNUMREFBAIXAOPERAC = #TEMP_OPERACIONAIS.NUMREFBAIXAOPERAC, 
			ULTNUMSEQBAIXAOPERAC = #TEMP_OPERACIONAIS.NUMSEQBAIXAOPERAC,
			
			TIPOBAIXA            = CASE WHEN #TEMP_OPERACIONAIS.TIPOBAIXA = '0' THEN '0'  /* BAIXA INTEGRAL INTERBANCARIA */
					            WHEN #TEMP_OPERACIONAIS.TIPOBAIXA = '1' THEN '1'  /* BAIXA INTEGRAL INTRABANCARIA */
					            WHEN #TEMP_OPERACIONAIS.TIPOBAIXA = '2' THEN NULL /* BAIXA PARCIAL  INTRABANCARIA */
					            WHEN #TEMP_OPERACIONAIS.TIPOBAIXA = '3' THEN NULL /* BAIXA PARCIAL  INTERBANCARIA */
					            WHEN #TEMP_OPERACIONAIS.TIPOBAIXA = '4' THEN '4'  /* BAIXA VIA PIX                */
					            WHEN #TEMP_OPERACIONAIS.TIPOBAIXA = '5' THEN '5'  /* BAIXA INTEGRAL POR SOLICITAÇÃO DO CEDENTE */
					            WHEN #TEMP_OPERACIONAIS.TIPOBAIXA = '6' THEN NULL /* BAIXA INTEGRAL POR ENVIO PARA PROTESTO */
					            WHEN #TEMP_OPERACIONAIS.TIPOBAIXA = '7' THEN '7'  /* BAIXA INTEGRAL POR DECURSO DE PRAZO    */
					            WHEN #TEMP_OPERACIONAIS.TIPOBAIXA = '8' THEN '8'  /* BAIXA INTEGRAL POR SOLICITAÇÃO DA IF DESTINATÁRIA */
					            ELSE TITULOS.TIPOBAIXA
					       END					       
		FROM TITULOS
		INNER JOIN #TEMP_RECEBE 
			ON (#TEMP_RECEBE.CODPROCESSA = '1' 
			AND #TEMP_RECEBE.CODREJEICAO IS NULL 
			AND #TEMP_RECEBE.NUMIDENTCDDA = TITULOS.NUMIDENTCDDA)
		INNER JOIN #TEMP_OPERACIONAIS
			ON (#TEMP_RECEBE.NUMIDENTCDDA = #TEMP_OPERACIONAIS.NUMIDENTCDDA)
		INNER JOIN #MAX_OPERACIONAISNOVAS 
			ON (#TEMP_OPERACIONAIS.NUMIDENTCDDA = #MAX_OPERACIONAISNOVAS.NUMIDENTCDDA 
			AND #TEMP_OPERACIONAIS.NUMIDENTCBAIXAOPERAC = #MAX_OPERACIONAISNOVAS.NUMIDENTCBAIXAOPERAC)

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS
               
               END   /* CÁTALOGO DA MODERNIZACAO EM DIANTE... */
		
		/*--------------------------------------------------------------------------------*/
		/* 13/03/2023 - Eliane - Tratamento para a Modernização...   FIM    DE TRECHO...  */
		/*--------------------------------------------------------------------------------*/

		--BAIXAS EFETIVAS ATUAIS
		DELETE BAIXAS_EFETIVAS 
		FROM BAIXAS_EFETIVAS 
		INNER JOIN #TEMP_RECEBE 
			ON (#TEMP_RECEBE.CODPROCESSA = '1' 
			AND BAIXAS_EFETIVAS.NUMIDENTCDDA = #TEMP_RECEBE.NUMIDENTCDDA)

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS

		INSERT INTO BAIXAS_EFETIVAS(
			NUMIDENTCDDA, NUMIDENTCBAIXAEFET, NUMCTRLDDA, NUMREFBAIXAEFET, 
			NUMSEQBAIXAEFET, NUMREFCADTIT, DATAMOVTO, DATAHORADDA, 
			TIPOBAIXA, DATAHORABAIXA, DATABAIXA, VLRBAIXA, 
			NUMCODBARRAS, DATAHORASITUACAO, ISPBCEDENTE, CODIFCEDENTE, 
			CANALPAGTO, MEIOPAGTO, NUMIDENTCBAIXAOPERAC, NUMSEQCADTIT
		)
		--31/01/2021 - ELIANE - AJUSTES PARA EVITAR INSERÇÕES COM DUPLICIDADES NO PROCESSAMENTO - ERRO DE PK (RA 2964, 2968 - BOR)
		SELECT
			#TEMP_EFETIVAS.NUMIDENTCDDA, #TEMP_EFETIVAS.NUMIDENTCBAIXAEFET, '0', 
			MAX(#TEMP_EFETIVAS.NUMREFBAIXAEFET), 
			MAX(#TEMP_EFETIVAS.NUMSEQBAIXAEFET), MAX(#TEMP_RECEBE.NUMREFCADTITULO), MAX(#TEMP_RECEBE.DATAMOVTO), MAX(#TEMP_RECEBE.DATAHORADDA), 
			MAX(#TEMP_EFETIVAS.TIPOBAIXA), MAX(#TEMP_EFETIVAS.DATAHORABAIXA), MAX(#TEMP_EFETIVAS.DATABAIXA), MAX(#TEMP_EFETIVAS.VLRBAIXA), 
			MAX(#TEMP_EFETIVAS.NUMCODBARRAS), MAX(#TEMP_EFETIVAS.DATAHORASITUACAO), MAX(#TEMP_EFETIVAS.ISPBCEDENTE), MAX(#TEMP_EFETIVAS.CODIFCEDENTE), 
			MAX(#TEMP_EFETIVAS.CANALPAGTO), MAX(#TEMP_EFETIVAS.MEIOPAGTO), MAX(#TEMP_EFETIVAS.NUMIDENTCBAIXAOPERAC), MAX(#TEMP_RECEBE.NUMSEQCADTITULO)
		FROM #TEMP_EFETIVAS
		INNER JOIN #TEMP_RECEBE 
			ON (#TEMP_RECEBE.CODPROCESSA = '1' 
			AND #TEMP_EFETIVAS.SEQ_RECEBE = #TEMP_RECEBE.SEQ_RECEBE)
		--24/08/2020 - ELIANE, RFAQUINI - ALTERAÇÃO PROVISÓRIA PARA NÃO INSERÇÃO DE BAIXAS OPERACIONAIS/EFETIVAS SEM NUMITENCBAIXA(OPERAC/EFET)
		WHERE #TEMP_EFETIVAS.NUMIDENTCBAIXAEFET IS NOT NULL
		--31/01/2021 - ELIANE - AJUSTES PARA EVITAR INSERÇÕES COM DUPLICIDADES NO PROCESSAMENTO - ERRO DE PK (RA 2964, 2968 - BOR)
		GROUP BY #TEMP_EFETIVAS.NUMIDENTCDDA, #TEMP_EFETIVAS.NUMIDENTCBAIXAEFET

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS

		SELECT MAX(NUMSEQBAIXAEFET) NUMSEQBAIXAEFET, NUMIDENTCDDA
			INTO #MAX_TEMP_EFETIVAS 
		FROM #TEMP_EFETIVAS
		GROUP BY NUMIDENTCDDA

		/*--------------------------------------------------------------------------------*/
		/* 13/03/2023 - Eliane - Tratamento para a Modernização...   INICIO DE TRECHO...  */
		/*--------------------------------------------------------------------------------*/
                IF @VRSMANUAL <= '5.05'  
                
                BEGIN /* Catalogo anterior à MODERNIZAÇÃO */

		UPDATE TITULOS SET 
			ULTNUMREFBAIXAEFET = #TEMP_EFETIVAS.NUMREFBAIXAEFET, 
			ULTNUMSEQBAIXAEFET = #TEMP_EFETIVAS.NUMSEQBAIXAEFET, 
			TIPOBAIXA = #TEMP_EFETIVAS.TIPOBAIXA
		FROM TITULOS
		INNER JOIN #TEMP_RECEBE 
			ON (#TEMP_RECEBE.CODPROCESSA = '1' 
			AND #TEMP_RECEBE.CODREJEICAO IS NULL 
			AND #TEMP_RECEBE.NUMIDENTCDDA = TITULOS.NUMIDENTCDDA)
		INNER JOIN #TEMP_EFETIVAS 
			ON (#TEMP_RECEBE.NUMIDENTCDDA = #TEMP_EFETIVAS.NUMIDENTCDDA)
		INNER JOIN #MAX_TEMP_EFETIVAS
			ON (#TEMP_EFETIVAS.NUMIDENTCDDA = #MAX_TEMP_EFETIVAS.NUMIDENTCDDA 
			AND #TEMP_EFETIVAS.NUMSEQBAIXAEFET = #MAX_TEMP_EFETIVAS.NUMSEQBAIXAEFET)

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS
		
                END    /* Catalogo anterior à MODERNIZAÇÃO */

		/*--------------------------------------------------------------------------------*/
		/* 13/03/2023 - Eliane - Tratamento para a Modernização...   FIM    DE TRECHO...  */
		/*--------------------------------------------------------------------------------*/

		UPDATE MANUT_TITULOS SET 
			SITUACAOPEDIDO = '5', 
			CODRETORNO = '2' --21/11/2019 - CONSULTA SEM INFORMAÇÕES NA CIP
		FROM MANUT_TITULOS
		INNER JOIN #TEMP_RECEBE 
			ON (#TEMP_RECEBE.NUMPEDIDO = MANUT_TITULOS.NUMPEDIDO)
		WHERE MANUT_TITULOS.DATAPEDIDO >= @DATAULTPROCESSAMENTO
		AND MANUT_TITULOS.DATAPEDIDO <= @DATAPROCESSAMENTO 
		AND MANUT_TITULOS.SITUACAOPEDIDO = '2'
		AND #TEMP_RECEBE.DATAMOVTO >= @DATAULTPROCESSAMENTO
		AND #TEMP_RECEBE.DATAMOVTO <= @DATAPROCESSAMENTO
		AND #TEMP_RECEBE.CODPROCESSA = '3'

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERRO
	   		
		UPDATE MANUT_TITULOS SET 
			SITUACAOPEDIDO = '5', 
			CODRETORNO = '0'
		FROM MANUT_TITULOS
		WHERE MANUT_TITULOS.DATAPEDIDO >= @DATAULTPROCESSAMENTO
		AND MANUT_TITULOS.DATAPEDIDO <= @DATAPROCESSAMENTO 
		AND MANUT_TITULOS.SITUACAOPEDIDO = '2'
		AND MANUT_TITULOS.TIPORETORNO = 'X'
		AND EXISTS (SELECT 1 
						FROM #TEMP_RECEBE 
						WHERE #TEMP_RECEBE.DATAMOVTO >= @DATAULTPROCESSAMENTO
						AND #TEMP_RECEBE.DATAMOVTO <= @DATAPROCESSAMENTO
						AND #TEMP_RECEBE.NOMEARQRET = MANUT_TITULOS.NOMEARQRET
						AND #TEMP_RECEBE.CODPROCESSA <> '2'
						AND #TEMP_RECEBE.TIPORETORNO = 'X'
						AND #TEMP_RECEBE.SITREQDDA IS NOT NULL
						AND #TEMP_RECEBE.SITREQDDA = 6
					)

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERRO

		UPDATE MANUT_TITULOS SET 
			SITUACAOPEDIDO = '5', 
			CODRETORNO = '1'
		FROM MANUT_TITULOS 
		WHERE MANUT_TITULOS.DATAPEDIDO >= @DATAULTPROCESSAMENTO
		AND MANUT_TITULOS.DATAPEDIDO <= @DATAPROCESSAMENTO 
		AND MANUT_TITULOS.SITUACAOPEDIDO = '2'
		AND MANUT_TITULOS.TIPORETORNO = 'X'
		AND EXISTS (SELECT 1 
				FROM #TEMP_RECEBE 
				WHERE #TEMP_RECEBE.DATAMOVTO >= @DATAULTPROCESSAMENTO
				AND #TEMP_RECEBE.DATAMOVTO <= @DATAPROCESSAMENTO
				AND #TEMP_RECEBE.NOMEARQRET = MANUT_TITULOS.NOMEARQRET
				AND #TEMP_RECEBE.CODPROCESSA = '2' 
				AND #TEMP_RECEBE.TIPORETORNO = 'X'
				AND #TEMP_RECEBE.SITREQDDA IS NOT NULL
				AND #TEMP_RECEBE.SITREQDDA = 6
					)

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERRO

		--MANUTS PROCESSADAS
		UPDATE MANUT_TITULOS SET 
			SITUACAOPEDIDO = '5', 
			CODRETORNO = #TEMP_MANUT.CODRETORNO
		FROM MANUT_TITULOS 
		INNER JOIN #TEMP_MANUT
			ON (MANUT_TITULOS.DATAPEDIDO = #TEMP_MANUT.DATAPEDIDO
			AND MANUT_TITULOS.DATALEGADO = #TEMP_MANUT.DATALEGADO
			AND MANUT_TITULOS.CODSISLEGADO = #TEMP_MANUT.CODSISLEGADO
			AND MANUT_TITULOS.NUMCTRLLEGADO = #TEMP_MANUT.NUMCTRLLEGADO)
		WHERE MANUT_TITULOS.TIPORETORNO = 'M'

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS
		
		/*
		--MANUTS PROCESSADAS: TITULOS RETORNADOS QUE NAO SAO DA IF NEM PERTENCEM A PAGADOR ELETRONICO PROPRIO E ATIVO (MARCADOS COM CODPROCESSA "X")
		UPDATE MANUT_TITULOS SET 
			SITUACAOPEDIDO = '5', 
			CODRETORNO = '0'
		FROM MANUT_TITULOS 
		INNER JOIN #TEMP_RECEBE 
			ON (MANUT_TITULOS.SITUACAOPEDIDO = '2' 
			AND #TEMP_RECEBE.CODPROCESSA = 'X')

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS

		--RECEBES PROCESSADAS: TITULOS RETORNADOS QUE NAO SAO DA IF NEM PERTENCEM A PAGADOR ELETRONICO PROPRIO E ATIVO (MARCADOS COM CODPROCESSA "X")
		UPDATE RECEBE_DDA0106R1_ADDA106_ADDA107 SET 
			CODPROCESSA = '1', 
			CODREJEICAO = NULL
		FROM RECEBE_DDA0106R1_ADDA106_ADDA107
		INNER JOIN #TEMP_RECEBE  
			ON (RECEBE_DDA0106R1_ADDA106_ADDA107.CODPROCESSA = '0' 
			AND #TEMP_RECEBE.CODPROCESSA = 'X')

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERROTRANS
		*/
		
		--RECEBES PROCESSADAS
		UPDATE RECEBE_DDA0106R1_ADDA106_ADDA107 SET 
			CODPROCESSA = CASE 
				WHEN #TEMP_RECEBE.CODPROCESSA = '2' 
					THEN '2' 
				ELSE '1' 
				END, 
			DATAMANUTENCAO = @TIMESTAMP, 
			CODREJEICAO = #TEMP_RECEBE.CODREJEICAO
		FROM RECEBE_DDA0106R1_ADDA106_ADDA107 
		INNER JOIN #TEMP_RECEBE 
			ON (RECEBE_DDA0106R1_ADDA106_ADDA107.CODPROCESSA = '0'
			AND #TEMP_RECEBE.CODPROCESSA != 'X'
			AND #TEMP_RECEBE.SEQ_RECEBE = RECEBE_DDA0106R1_ADDA106_ADDA107.SEQ_RECEBE
			AND #TEMP_RECEBE.DATAMOVTO = RECEBE_DDA0106R1_ADDA106_ADDA107.DATAMOVTO)
			/*AND ISNULL(#TEMP_RECEBE.NUMPEDIDO, -1) = ISNULL(RECEBE_DDA0106R1_ADDA106_ADDA107.NUMPEDIDO, -1))*/
			
		COMMIT TRANSACTION
	
		--13/11/2019 - REENVIO DE MANUTENCAO REJEITADA
		--IF EXISTS (

		--01/02/2021 - RFAQUINI - AJUSTE COLLATION (RA 3012 BOR)												  
		CREATE TABLE #MANUT_TITULOS_REENVIO (
			PK_REGULARIZACAO_8107 VARCHAR (100) COLLATE DATABASE_DEFAULT, 
			DATAPEDIDO_REJEITADA DATETIME, 
			DATALEGADO_REJEITADA DATETIME, 
			CODSISLEGADO_REJEITADA VARCHAR (10) COLLATE DATABASE_DEFAULT, 
			NUMCTRLLEGADO_REJEITADA VARCHAR(35) COLLATE DATABASE_DEFAULT
		)
	  
		INSERT INTO #MANUT_TITULOS_REENVIO(
			PK_REGULARIZACAO_8107
		)
		SELECT
			PK_REGULARIZACAO_8107
		FROM MANUT_TITULOS
		WHERE DATAPEDIDO >= @DATAULTPROCESSAMENTO
		AND DATAPEDIDO <= @DATAPROCESSAMENTO
		AND PK_REGULARIZACAO_8107 IS NOT NULL--31/01/2021 - ELIANE - FILTRO PARA 8107
		AND CODEVENTO = '8107'--BUSCA A CONSULTA CRIADA A PARTIR DE MANUTS REJEITADAS
	
		IF EXISTS (SELECT 1 FROM #MANUT_TITULOS_REENVIO)
		BEGIN
			UPDATE #MANUT_TITULOS_REENVIO SET 
				DATAPEDIDO_REJEITADA = SUBSTRING(PK_REGULARIZACAO_8107, 1, 8), 
				DATALEGADO_REJEITADA = SUBSTRING(PK_REGULARIZACAO_8107, 9, 8), 
				CODSISLEGADO_REJEITADA = SUBSTRING(PK_REGULARIZACAO_8107, 17, 10), 
				NUMCTRLLEGADO_REJEITADA = SUBSTRING(PK_REGULARIZACAO_8107, 27, 35)

			UPDATE MANUT_TITULOS SET 
				NUMPEDIDO = NULL, 
				SITUACAOPEDIDO = '0', 
				CODRETORNO = NULL, 
				NOMEARQREM = NULL, 
				NOMEARQRET = NULL, 
				DATAHORAPROCESSO = NULL, 
				SPID = NULL, 
				ENVIOID = NULL
			FROM #MANUT_TITULOS_REENVIO
			INNER JOIN MANUT_TITULOS
				ON (MANUT_TITULOS.DATAPEDIDO = #MANUT_TITULOS_REENVIO.DATAPEDIDO_REJEITADA
				AND MANUT_TITULOS.CODSISLEGADO = #MANUT_TITULOS_REENVIO.CODSISLEGADO_REJEITADA
				AND MANUT_TITULOS.DATALEGADO = #MANUT_TITULOS_REENVIO.DATALEGADO_REJEITADA
				AND MANUT_TITULOS.NUMCTRLLEGADO = #MANUT_TITULOS_REENVIO.NUMCTRLLEGADO_REJEITADA)
			WHERE SITUACAOPEDIDO = '5'--VERIFICAR SE O PEDIDO JA NÃO FOI ENVIADO
			AND CODRETORNO = '1'

			INSERT INTO LOG_REENVIO (
				--31/01/2021 - ELIANE - CAMPO NUMPEDIDOANT NOT NULL
				NUMPEDIDOANT, /*NOMEARQREM, NOMEARQRET, TIPORETORNO, */
				DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO, TIPOPEDIDO
			)
			SELECT 
				--31/01/2021 - ELIANE - CAMPO NUMPEDIDOANT NOT NULL
				1, /*NOMEARQREM, NOMEARQRET, TIPORETORNO, */
				DATAPEDIDO_REJEITADA, DATALEGADO_REJEITADA, CODSISLEGADO_REJEITADA, NUMCTRLLEGADO_REJEITADA, 'T'--TITULO
			FROM #MANUT_TITULOS_REENVIO
		END
		
	RETURN

	TRATAERROTRANS:
		ROLLBACK TRANSACTION
		GOTO TRATAERRO

	TRATAERRO:
		SELECT @P_SQLERRO = @SQLERRO
		RETURN
END
GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO], 
    [NOMESCRIPT], 
    [CODUSUARIO], 
    [DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_PROCESSA_DDA0106R1_ADDA106', 
	SYSTEM_USER, 
	GETDATE() 
GO