USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_PROCESSA_DDA0108_ADDA108_RR2')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_PROCESSA_DDA0108_ADDA108_RR2 AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE [dbo].[SP_PROCESSA_DDA0108_ADDA108_RR2](
	@P_TIMEOUT INT, 
	@P_SQLERRO INT OUT
) 
AS
BEGIN 
	
	/*		
		14/10/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
								REMOÇÃO DE ALIAS
								
		25/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
		
		06/02/2023 - ELIANE, RFAQUINI - REMOÇÃO DE VALIDAÇÃO POR NÃO TRAZER RESULTADO
						A PROCEDURE SP_PROCESSA_DDA0108_ADDA108_RR2 VALIDA SE CHEGOU UMA R2 
						PARA O QUAL TENHAMOS JÁ RECEBIDO UMA R1 PARA O MESMO NUMCTRLDDA. 
						NO ENTANTO, A CADA MENSAGEM/ARQUIVO DISTRIBUÍDO PELA CIP, ELA DÁ UM 
						NUMCTRLDDA DIFERENTE, SENDO ESSE O CONTROLE DELA, DEÇSSA FORMA, 
						REMOVEMOS A VALIDAÇÃO CORRESPONDENTE.
		06/02/2023 - ELIANE, RFAQUINI - REMOÇÃO DE VALIDAÇÃO POR NÃO TRAZER RESULTADO
		14/02/2023 - ELIANE - TRATAMENTO PARA O CATÁLOGO DA MODERNIZAÇÃO.
	*/
/*------------------ Catalogo anterior à modernização -------------------------*/
/* TIPOBAIXA EFETIVA --> Tipo de baixa do título			       */
/* 									       */
/* 0 Baixa Efetiva Integral Interbancária			    	       */
/* 1 Baixa Efetiva Integral Intrabancária			 	       */
/* 2 Baixa Efetiva Integral por Solicitação do Cedente	 		       */
/* 3 Baixa Efetiva Integral por envio para protesto	 		       */
/* 4 Baixa Efetiva Integral por decurso de prazo		 	       */
/* 5 Baixa Efetiva Parcial Intrabancária			 	       */
/* 6 Baixa Efetiva Parcial Interbancária			 	       */
/* 7 Baixa Efetiva por solicitação da Instituição Destinatária		       */
/* ----------------------------------------------------------------------------*/
/* CATALOGO DA MODERNIZAÇÃO...                                                 */
/* 0 - BAIXA INTEGRAL INTERBANCARIA					       */
/* 1 - BAIXA INTEGRAL INTRABANCARIA					       */
/* 5 - BAIXA INTEGRAL POR SOLICITAÇÃO DO CEDENTE			       */
/* 6 - BAIXA INTEGRAL POR ENVIO PARA PROTESTO				       */
/* 7 - BAIXA INTEGRAL POR DECURSO DE PRAZO				       */
/* 2 - BAIXA PARCIAL  INTRABANCARIA					       */
/* 3 - BAIXA PARCIAL  INTERBANCARIA					       */
/* 8 - BAIXA INTEGRAL POR SOLICITAÇÃO DA IF DESTINATÁRIA		       */
/* 									       */
/* 4 - BAIXA INTEGRAL VIA PIX 						       */
/* -----------------------------------------------------------------------------*/
/* CODSITUACAO que fica no título:					        */
/* 1 - EM ABERTO; 						       		*/
/* 2 - Baixado por solicitação do Cedente.	 		       		*/
/* 3 - Baixado por liquidação intrabancaria.			      		*/
/* 4 - Baixado por liquidação interbancaria.			       		*/
/* 5 - Baixado por Decurso de Prazo.				       		*/
/* 6 - Baixado para envio a Protesto..				       		*/
/*------------------------------------------------------------------------------*/	
	
	/*  

		MARCACOES DIFERENCIADAS (CODPROCESSA)  

		"5" - AVISO JA RECEBIDO COMO R1 --> 14/02/2023 - Não fazer mais este tipo de validação. 
		"4" - DUPLICIDADE DE AVISO (APENAS O MAIS RECENTE GERA ATUALIZACAO NA BASE)  

		DOMINIOS DE REJEICOES (CODREJEICAO)  

		'01' - TITULO NAO CADASTRADO  
		'26' - BAIXA OPERACIONAL JA CADASTRADA  

	*/  

	DECLARE 
		@DATAULTPROCESSAMENTO DATETIME,   
		@DATAPROCESSAMENTO DATETIME,  
		@SQLERRO INTEGER,  
		@TIMESTAMP DATETIME,  
		@ISPB CHAR(8),
		@VRSMANUAL VARCHAR (07) /* 14/02/2023 */

  
	SELECT 
		@DATAULTPROCESSAMENTO = DATAULTPROCESSAMENTO, 
		@DATAPROCESSAMENTO = DATAPROCESSAMENTO, 
		@TIMESTAMP = GETDATE(), 
		@ISPB = ISPB  
	FROM PARAMETROS 
	WHERE CODSISTEMA = 'DDA-AUTK'    
     
	SELECT @VRSMANUAL = VRSMANUAL FROM VWIB_VRSMANUAL WITH (NOLOCK)  /* 14/02/2023 */

    -- TIMEOUT DAS TABELAS DE RESERVA  
    DELETE 
	FROM TEMP_RECEBE_ADDA108_RR2 
	WHERE DATEADD(MINUTE, @P_TIMEOUT, DATAHORAPROC) < @TIMESTAMP  
  
	SELECT @SQLERRO = @@ERROR  
	IF @SQLERRO <> 0 GOTO TRATAERRO   
  
	-- TRATAMENTO DE RECEBES ACEITAS  
	-- SELECIONA TUDO PENDENTE  
	SELECT * 
		INTO #TEMP_RR2 
	FROM RECEBE_ADDA108_RR2  
	WHERE DATAMOVTO >= @DATAULTPROCESSAMENTO 
	AND DATAMOVTO <= @DATAPROCESSAMENTO 
	AND CODPROCESSA = '0' 
	AND INDIMPORTACAOVALIDA = 'S'  
  
	SELECT @SQLERRO = @@ERROR  
	IF @SQLERRO <> 0 GOTO TRATAERRO   
  
	-- DELETA TUDO QUE ESTA RESERVADO  
	DELETE TEMP 
	FROM #TEMP_RR2 TEMP  
	INNER JOIN TEMP_RECEBE_ADDA108_RR2 RESERVA 
		ON (RESERVA.SEQ_RECEBE = TEMP.SEQ_RECEBE   
		AND RESERVA.NUMIDENTCDDA = TEMP.NUMIDENTCDDA 
		AND RESERVA.DATAMOVTO = TEMP.DATAMOVTO)  
  
	SELECT @SQLERRO = @@ERROR  
	IF @SQLERRO <> 0 GOTO TRATAERRO   
  
	-- RESERVA O QUE ESTA LIVRE  
	INSERT INTO TEMP_RECEBE_ADDA108_RR2(
		SEQ_RECEBE, NUMIDENTCDDA, DATAMOVTO, DATAHORAPROC
	)  
	SELECT 
		SEQ_RECEBE, NUMIDENTCDDA, DATAMOVTO, @TIMESTAMP 
	FROM #TEMP_RR2  
  
	-- PK DUPLICADA, PROCESSOS SIMULTANEOS?  
	SELECT @SQLERRO = @@ERROR  
	IF @SQLERRO <> 0 GOTO TRATAERRO   
    
   
	IF(EXISTS(SELECT 1 FROM #TEMP_RR2))  
	BEGIN  
	/** REJEICOES **/  
  
	-- CODREJEICAO '01' - TITULO NAO ENCONTRADO  
	UPDATE #TEMP_RR2 SET 
		CODREJEICAO = '01', 
		CODPROCESSA = '2'   
  
	SELECT @SQLERRO = @@ERROR  
	IF @SQLERRO <> 0 GOTO TRATAERRO   

	UPDATE #TEMP_RR2 SET 
		CODREJEICAO = NULL, 
		CODPROCESSA = '0'   
	FROM #TEMP_RR2   
	INNER JOIN TITULOS 
		ON (TITULOS.NUMIDENTCDDA = #TEMP_RR2.NUMIDENTCDDA)

	SELECT @SQLERRO = @@ERROR  
	IF @SQLERRO <> 0 GOTO TRATAERRO   
  
	UPDATE #TEMP_RR2 SET 
		CODREJEICAO = '13', 
		CODPROCESSA = '2', 
		DATAMANUTENCAO = GETDATE()   
	FROM #TEMP_RR2   
	WHERE #TEMP_RR2.DATAMOVTO <= @DATAPROCESSAMENTO   
	AND #TEMP_RR2.DATAMOVTO >= @DATAULTPROCESSAMENTO   
	AND #TEMP_RR2.CODPROCESSA = '0'    
	AND EXISTS (SELECT 1 
				FROM RECEBE_ADDA108_RR2   
				WHERE #TEMP_RR2.NUMIDENTCDDA = RECEBE_ADDA108_RR2.NUMIDENTCDDA  
				AND #TEMP_RR2.NUMIDENTCBAIXAOPERAC = RECEBE_ADDA108_RR2.NUMIDENTCBAIXAOPERAC   
				AND RECEBE_ADDA108_RR2.DATAMOVTO <= @DATAPROCESSAMENTO   
				AND RECEBE_ADDA108_RR2.DATAMOVTO >= @DATAULTPROCESSAMENTO  
				AND RECEBE_ADDA108_RR2.CODPROCESSA = '1')  

	SELECT @SQLERRO = @@ERROR     
	IF @SQLERRO <> 0 GOTO TRATAERRO  
    
	UPDATE #TEMP_RR2 SET 
		CODREJEICAO = '13', 
		CODPROCESSA = '2', 
		DATAMANUTENCAO = GETDATE()   
	FROM #TEMP_RR2   
	WHERE #TEMP_RR2.DATAMOVTO <= @DATAPROCESSAMENTO   
	AND #TEMP_RR2.DATAMOVTO >= @DATAULTPROCESSAMENTO  
	AND #TEMP_RR2.CODPROCESSA = '0'    
	AND #TEMP_RR2.SEQ_RECEBE < (SELECT MAX (#TEMP_RR2_2.SEQ_RECEBE) 
						FROM #TEMP_RR2 #TEMP_RR2_2   
						WHERE #TEMP_RR2.NUMIDENTCDDA = #TEMP_RR2_2.NUMIDENTCDDA  
						AND #TEMP_RR2.NUMIDENTCBAIXAOPERAC = #TEMP_RR2_2.NUMIDENTCBAIXAOPERAC   
						AND #TEMP_RR2_2.DATAMOVTO <= @DATAPROCESSAMENTO   
						AND #TEMP_RR2_2.DATAMOVTO >= @DATAULTPROCESSAMENTO  
						AND #TEMP_RR2_2.CODPROCESSA = '0')  

	SELECT @SQLERRO = @@ERROR     
	IF @SQLERRO <> 0 GOTO TRATAERRO  
  
  
	-- CODREJEICAO '26' - BAIXA OPERACIONAL JA REGISTRADA  
	UPDATE #TEMP_RR2 SET 
		CODREJEICAO = '26', 
		CODPROCESSA = '2' 
	FROM #TEMP_RR2  
	INNER JOIN BAIXAS_OPERACIONAIS 
		ON (BAIXAS_OPERACIONAIS.NUMIDENTCDDA = #TEMP_RR2.NUMIDENTCDDA  
		AND BAIXAS_OPERACIONAIS.NUMIDENTCBAIXAOPERAC = #TEMP_RR2.NUMIDENTCBAIXAOPERAC) 
	WHERE #TEMP_RR2.CODPROCESSA = '0'   

	SELECT @SQLERRO = @@ERROR  
	IF @SQLERRO <> 0 GOTO TRATAERRO   
    
	-- BAIXA JA RECEBIDA EM UMA ADDA/DDA0108R1  - 14/02/2023 Retirar tudo isso daqui!!!
	--UPDATE #TEMP_RR2 SET 
	--	CODREJEICAO = '26', 
	--	CODPROCESSA = '2'   
	--FROM #TEMP_RR2  
	--WHERE CODPROCESSA = '0'  
	--AND ISPBIFSACADA IS NOT NULL 
	--AND ISPBIFSACADA = @ISPB -- R1 A SER RECEBIDA: A PROPRIA INSTITUICAO GEROU O TITULO (ISPBIFSACADA EH ENVIADA SOMENTE PARA IF DESTINATARIA) E ACONTECE DE SER A IF ONDE A BAIXA FOI FEITA  

	--SELECT @SQLERRO = @@ERROR     
	--IF @SQLERRO <> 0 GOTO TRATAERRO  
  
	--06/02/2023 - ELIANE, RFAQUINI - REMOÇÃO DE VALIDAÇÃO POR NÃO TRAZER RESULTADO
	-- R1 RECEBIDA  
	/*
	--UPDATE #TEMP_RR2 SET 
	--	CODREJEICAO = '26', 
	--	CODPROCESSA = '2'   
	--FROM #TEMP_RR2 
	--INNER JOIN RECEBE_ADDA108_RET_ACEITOS   
	--	ON (RECEBE_ADDA108_RET_ACEITOS.NUMCTRLDDA = #TEMP_RR2.NUMCTRLDDA)
	--WHERE #TEMP_RR2.CODPROCESSA = '0'  
	--AND RECEBE_ADDA108_RET_ACEITOS.DATAMOVTO >= @DATAULTPROCESSAMENTO 
	--AND RECEBE_ADDA108_RET_ACEITOS.DATAMOVTO <= @DATAPROCESSAMENTO  

	--SELECT @SQLERRO = @@ERROR     
	--IF @SQLERRO <> 0 GOTO TRATAERRO 
	*/	
    
	-- MAIS NENHUMA REJEICAO A SER VERIFICADA, TUDO PODE SER DADO COMO PROCESSADO E ACEITO  
	UPDATE #TEMP_RR2 SET 
		CODPROCESSA = '1' 
	WHERE CODPROCESSA = '0' 
	AND CODREJEICAO IS NULL  

	SELECT @SQLERRO = @@ERROR  
	IF @SQLERRO <> 0 GOTO TRATAERRO  
	

		/*----------------------------------------------------------------------------*/
                /* 14/02/2023 - Neste ponto podemos chegar com N baixas para o mesmo título ! */
                /* Decidir com qual delas faremos o UPDATE em TÍTULOS !                       */
                /*----------------------------------------------------------------------------------------------*/
                /* 14/02/2023 - Eliane.  Selecionando a mais recente baixa do título, que pode ser DEVOLUÇÃO... */
                /* INICIO DO TRECHO.                                                                            */
                /*----------------------------------------------------------------------------------------------*/
                
		--MAX_NUMIDENTCBAIXA POR TÍTULO - MODERNIZAÇÃO
		--14/02/2023 - ELIANE - TRATAMENTO DO CAMPO NUMIDENTBAIXAOPERAC (CATÁLOGO MODERNIZAÇÃO)
		SELECT MAX(#TEMP_RR2.NUMIDENTCBAIXAOPERAC) NUMIDENTCBAIXAOPERAC, #TEMP_RR2.NUMIDENTCDDA NUMIDENTCDDA
			INTO #TEMP_MAX_NUMIDENTCBAIXAOPERAC
		FROM #TEMP_RR2 
		WHERE #TEMP_RR2.CODPROCESSA = '1'
		AND #TEMP_RR2.CODREJEICAO IS NULL
		GROUP BY #TEMP_RR2.NUMIDENTCDDA
		
                /*----------------------------------------------------------------------------------------------*/
                /* 14/02/2023 - Eliane.  Selecionando a mais recente baixa do título, que pode ser DEVOLUÇÃO... */
                /* FIM DO TRECHO.                                                                               */
                /*----------------------------------------------------------------------------------------------*/
	

	BEGIN TRANSACTION  
  
	INSERT INTO BAIXAS_OPERACIONAIS  
	(  
		NUMIDENTCDDA, NUMIDENTCBAIXAOPERAC, NUMCTRLDDA, NUMREFBAIXAOPERAC,  
		NUMSEQBAIXAOPERAC, NUMREFCADTIT, NUMSEQCADTIT, DATAMOVTO,  
		DATAHORADDA, TIPOBAIXA, DATABAIXA, DATAHORABAIXA,  
		VLRBAIXA, NUMCODBARRAS, SITBAIXA, DATAHORASITUACAO,  
		ISPBSACADA, CODIFSACADA, NUMCTRLDDACANCEL, DATAHORACANCEL,  
		SITPAGTO, SITUACAOTIT, CANALPAGTO, MEIOPAGTO,  
		INDCONTINGENCIA, TIPOPESPORTADOR, CNPJ_CPF_PORTADOR, QTDPAGTOREG, 
		--14/10/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
		--25/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)		
		VLRSALDOATUAL, NOME_PORTADOR, DATAHORARECBTTITULO,
		TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO. AGENCIARECEBEDORA /* CAT MODERNIZAÇÃO */
	)   
	SELECT  
		#TEMP_RR2.NUMIDENTCDDA, #TEMP_RR2.NUMIDENTCBAIXAOPERAC,  #TEMP_RR2.NUMCTRLDDA,   #TEMP_RR2.NUMREFBAIXAOPERAC,  
		ISNULL (#TEMP_RR2.NUMSEQBAIXAOPERAC, 0) /* 14/02/2023 */, #TEMP_RR2.NUMREFALTCADTIT, NULL, #TEMP_RR2.DATAMOVTO,  
		#TEMP_RR2.DATAHORADDA, #TEMP_RR2.TIPOBAIXATIT, #TEMP_RR2.DATABAIXAOPERAC,  #TEMP_RR2.DATAHORABAIXAOPERAC,  
		#TEMP_RR2.VLRBAIXAOPERAC, #TEMP_RR2.NUMCODBARRASBAIXAOPE, 'A', /* BAIXA ATIVA */ #TEMP_RR2.DATAHORASITUACAOBAIXAOPERAC,  
		#TEMP_RR2.ISPBIFSACADA, #TEMP_RR2.CODIFSACADA, NULL, NULL,  
		NULL, #TEMP_RR2.CODSITUACAOTIT, #TEMP_RR2.CANALPAGTO, #TEMP_RR2.MEIOPAGTO,  
		#TEMP_RR2.INDCONTINGENCIA, #TEMP_RR2.TIPOPESPORTADOR, #TEMP_RR2.CNPJ_CPF_PORTADOR, #TEMP_RR2.QTDPAGTOREGTD,  
		--14/10/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
		--25/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)		
		#TEMP_RR2.VLRSALDOATUAL, #TEMP_RR2.NOME_PORTADOR, #TEMP_RR2.DATAHORARECBTTITULO,
		#TEMP_RR2.TIPOPESAGREGADOR, #TEMP_RR2.CNPJ_CPF_AGREGADOR, #TEMP_RR2.NOMEAGREGADOR, 	/* CAT MODERNIZAÇÃO */
		#TEMP_RR2.ISPBINICIADORPAGTO. #TEMP_RR2.AGENCIARECEBEDORA 					/* CAT MODERNIZAÇÃO */

	FROM #TEMP_RR2 
	WHERE #TEMP_RR2.CODPROCESSA = '1'   

	SELECT @SQLERRO = @@ERROR  
	IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  
        IF @VRSMANUAL <= '5.05'  
            
           BEGIN /* Catalogo anterior à MODERNIZAÇÃO - SOMENTE AVISO DE LIQUIDAÇÃO */
    	     
	     --ATUALIZACAO DAS INFORMAÇÕES DO TITULO, AVALIANDO SE O SEQUENCIAL DA BAIXA OPERACIONAL EH MAIOR  
	     UPDATE TITULOS SET   
	     	TITULOS.SITPAGAMENTO = '2', /* SITUACAO "BAIXA ENVIADA/RECEBIDA" */  
	     	TITULOS.SITPAGAMENTOCIP = #TEMP_RR2.CODSITUACAOTIT,  
	     	TITULOS.ULTNUMREFBAIXAOPERAC = #TEMP_RR2.NUMREFBAIXAOPERAC,  
	     	TITULOS.ULTNUMSEQBAIXAOPERAC = #TEMP_RR2.NUMSEQBAIXAOPERAC,  
	     	TITULOS.INDCONTINGENCIA = ISNULL(#TEMP_RR2.INDCONTINGENCIA, TITULOS.INDCONTINGENCIA),  
	     	TITULOS.TIPOPESPORTADOR = ISNULL(#TEMP_RR2.TIPOPESPORTADOR, TITULOS.TIPOPESPORTADOR),  
	     	TITULOS.CNPJ_CPF_PORTADOR = ISNULL(#TEMP_RR2.CNPJ_CPF_PORTADOR, TITULOS.CNPJ_CPF_PORTADOR),  
	     	TITULOS.QTDPAGTOREG = ISNULL(#TEMP_RR2.QTDPAGTOREGTD, TITULOS.QTDPAGTOREG),  
	     	TITULOS.VLRSALDOATUAL = ISNULL(#TEMP_RR2.VLRSALDOATUAL, TITULOS.VLRSALDOATUAL) 
	     FROM TITULOS  
	     INNER JOIN #TEMP_RR2 
	     	ON (TITULOS.NUMIDENTCDDA = #TEMP_RR2.NUMIDENTCDDA   
	     	AND #TEMP_RR2.NUMSEQBAIXAOPERAC > ISNULL(TITULOS.ULTNUMSEQBAIXAOPERAC, -1)) 
	     WHERE #TEMP_RR2.CODPROCESSA = '1'   
	     
	     SELECT @SQLERRO = @@ERROR  
	     IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
	
           END   /* Catalogo anterior à MODERNIZAÇÃO - SOMENTE AVISO DE LIQUIDAÇÃO */
         ELSE
           BEGIN /* Modernização em diante LIQUIDAÇÃO OU BAIXA EFETIVAMENTE. */
 	     UPDATE TITULOS SET   
 	     
	     	TITULOS.SITPAGAMENTO = '2', /* SITUACAO "BAIXA ENVIADA/RECEBIDA" */  
	     	TITULOS.SITPAGAMENTOCIP = #TEMP_RR2.CODSITUACAOTIT,  
	     	TITULOS.ULTNUMREFBAIXAOPERAC = #TEMP_RR2.NUMREFBAIXAOPERAC,  
	     	TITULOS.ULTNUMSEQBAIXAOPERAC = ISNULL (#TEMP_RR2.NUMSEQBAIXAOPERAC, 0),  
	     	TITULOS.INDCONTINGENCIA = ISNULL(#TEMP_RR2.INDCONTINGENCIA, TITULOS.INDCONTINGENCIA),  
	     	
	     	
	     	
	     	TITULOS.TIPOPESPORTADOR = ISNULL(#TEMP_RR2.TIPOPESPORTADOR, TITULOS.TIPOPESPORTADOR),  
	     	TITULOS.CNPJ_CPF_PORTADOR = ISNULL(#TEMP_RR2.CNPJ_CPF_PORTADOR, TITULOS.CNPJ_CPF_PORTADOR),  
	     	TITULOS.QTDPAGTOREG = ISNULL(#TEMP_RR2.QTDPAGTOREGTD, TITULOS.QTDPAGTOREG),  
	     	TITULOS.VLRSALDOATUAL = ISNULL(#TEMP_RR2.VLRSALDOATUAL, TITULOS.VLRSALDOATUAL), 
/*---------------------------------------------------------------*/				
/* dados que serão atualizados a partir da MODERNIZAÇÃO - inicio */

		CODSITUACAO = CASE WHEN #TEMP_RR2.TIPOBAIXATIT IN ('0', '9', '11') /* Baixa Operacional Integral Interbancária */
		                   THEN '4' /* título liquidado - LIQ INTERBANCÁRIA */
		                   WHEN #TEMP_RR2.TIPOBAIXATIT = '1' /* Baixa Operacional Integral Intrabancária */
		                   THEN '3' /* título liquidado - LIQ INTRABANCÁRIA */
		                   WHEN #TEMP_RR2.TIPOBAIXATIT IN ('5', '8') /* Baixa por solicitação do Cedente/Destinatária */
				   THEN '2' /* título baixado por solicitação do cedente */
		                   WHEN #TEMP_RR2.TIPOBAIXATIT = '6' /* Baixa integral por envio para protesto   */
				   THEN '6' /* título baixado por envio para protesto */
		                   WHEN #TEMP_RR2.TIPOBAIXATIT = '7' /* Baixa integral por decurso de prazo      */
				   THEN '5' /* título baixado por decurso de prazo */
		                   
		                   WHEN #TEMP_RR2.TIPOBAIXATIT = '4' /* Pago via PIX - NÃO TENHO COMO DISTINGUIR IF REC  */
				   THEN '4' /* título baixado por decurso de prazo */
		                   
		                   ELSE TITULOS.CODSITUACAO /* Continua como está. Baixas Parciais não alteram situação do título. */
		              END,
				
		/* 13/03/2023 - Eliane - Acrescentei MEIO e CANAL para as BAIXAS definitivas... */
		MEIOPAGTO    	  = CASE WHEN #TEMP_RR2.TIPOBAIXATIT IN ('2','3','10','12') /* Baixas Parciais, não baixar o título */
		                       THEN TITULOS.MEIOPAGTO
		                       ELSE  #TEMP_RR2.MEIOPAGTO
		                  END,
		CANALPAGTO    	  = CASE WHEN #TEMP_RR2.TIPOBAIXATIT IN ('2','3','10','12') /* Baixas Parciais, não baixar o título */
		                       THEN TITULOS.CANALPAGTO
		                       ELSE  #TEMP_RR2.CANALPAGTO
		                  END,
		/* 13/03/2023 - Eliane - Acrescentei MEIO e CANAL para as BAIXAS definitivas... */

                TIPOBAIXA      = CASE WHEN #TEMP_RR2.TIPOBAIXATIT IN ('2','3','10','12') /* Baixas Parciais, não baixar o título */
                                      THEN TITULOS.TIPOBAIXA          /* Fica como estava */
                                      ELSE #TEMP_RR2.TIPOBAIXATIT     /* Já estará na codificação da modernização */
                                 END,
                DATAPAGTOBAIXA = CASE WHEN #TEMP_RR2.TIPOBAIXATIT IN ('2','3','10','12') /* Baixas Parciais, não baixar o título */
                                      THEN TITULOS.DATAPAGTOBAIXA     /* Fica como estava */
                                      ELSE #TEMP_RR2.DATABAIXAOPERAC  /* Já estará na codificação da modernização */
                                 END,
                VLRPAGTOBAIXA  = CASE WHEN #TEMP_RR2.TIPOBAIXATIT IN ('2','3','10','12') /* Baixas Parciais, não baixar o título */
                                      THEN TITULOS.VLRPAGTOBAIXA      /* Fica como estava */
                                      ELSE #TEMP_RR2.VLRBAIXAOPERAC   /* Já estará na codificação da modernização */
                                 END

/* dados que serão atualizados a partir da MODERNIZAÇÃO - fim    */
/*---------------------------------------------------------------*/				

	     FROM TITULOS  
	     INNER JOIN #TEMP_RR2 
	     	ON (TITULOS.NUMIDENTCDDA    = #TEMP_RR2.NUMIDENTCDDA)
	     INNER JOIN #TEMP_MAX_NUMIDENTCBAIXAOPERAC
	        ON (#TEMP_MAX_NUMIDENTCBAIXAOPERAC.NUMIDENTCDDA 	= #TEMP_RR2.NUMIDENTCDDA AND
	            #TEMP_MAX_NUMIDENTCBAIXAOPERAC.NUMIDENTCBAIXAOPERAC = #TEMP_RR2.NUMIDENTCBAIXAOPERAC)

	     WHERE #TEMP_RR2.CODPROCESSA = '1'   
	     
	     SELECT @SQLERRO = @@ERROR  
	     IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
          
           END   /* Modernização em diante LIQUIDAÇÃO OU BAIXA EFETIVAMENTE. */

	-- RECEBES PROCESSADAS  
	UPDATE RECEBE_ADDA108_RR2 SET 
		CODPROCESSA = #TEMP_RR2.CODPROCESSA, 
		CODREJEICAO = #TEMP_RR2.CODREJEICAO, 
		DATAMANUTENCAO = @TIMESTAMP   
	FROM RECEBE_ADDA108_RR2   
	INNER JOIN #TEMP_RR2   
		ON (RECEBE_ADDA108_RR2.SEQ_RECEBE = #TEMP_RR2.SEQ_RECEBE 
		AND RECEBE_ADDA108_RR2.NUMIDENTCDDA = #TEMP_RR2.NUMIDENTCDDA 
		AND RECEBE_ADDA108_RR2.DATAMOVTO = #TEMP_RR2.DATAMOVTO)  

	SELECT @SQLERRO = @@ERROR     
	IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  

	COMMIT TRANSACTION  

	END  
  
RETURN  

TRATAERRO_TRANS:  
	ROLLBACK TRANSACTION  
	GOTO TRATAERRO  

TRATAERRO:  
	SELECT @P_SQLERRO = @SQLERRO  
	RETURN  
END  

GO
  
INSERT INTO VERSAO_SISTEMA (
	[VERSAO], 
    [NOMESCRIPT], 
    [CODUSUARIO], 
    [DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_PROCESSA_DDA0108_ADDA108_RR2', 
	SYSTEM_USER, 
	GETDATE() 
GO  