USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME = 'SP_PESQUISA_TITULO_POR_SACADO')
BEGIN
	EXEC ('CREATE PROCEDURE DBO.SP_PESQUISA_TITULO_POR_SACADO AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE DBO.SP_PESQUISA_TITULO_POR_SACADO (
	@P_CNPJ_CPF_SACADO VARCHAR (15) = NULL, 
	@P_NUMIDENTCDDA NUMERIC (19, 0) = NULL, 
	@P_TIPOPESQUISA VARCHAR (10) = 'SACADO', 
	@P_ORDEM VARCHAR (3) = 'D', 
	@P_CODCONDICAO VARCHAR (30) = NULL, 
	@P_TIPOPESCEDENTE VARCHAR (3) = NULL, 
	@P_CNPJ_CPF_CEDENTE VARCHAR (15) = NULL, 
	@P_DATAVENCIMENTOINI DATETIME = NULL, 
	@P_DATAVENCIMENTOFIM DATETIME = NULL, 
	@P_CODSISLEGADO VARCHAR (15) = NULL) 
AS 

	/*
		29/04/2019 - ELIANE - MUDANDO AS REGRAS DE SELEÇÃO DE TÍTULOS QUE NÃO SÃO CARTÃO E PARA 
								TÍTULOS DE CARTÃO. 
		
		19/06/2019 - EDUARDOK - (PERFORMANCE) REMOVER OR DO SELECT - ALTERADO PARA UNION ALL 
								/ ALTERAR PARA PADRÃO ANSI(INNER JOIN) / ALTERAR OS COMANDOS COM 
								SELECT 
		
		10/10/2019 - EDUARDOK/BANCO INTER - ALTERAÇÃO/CRIAÇÃO #TITULOS, AJUSTE PARA O FILTRO DE 
											AGREGADOS. 
		
		03/11/2021 - ELIANE - ENCONTRADO AMBIENTE ONDE CODSITUACAO ESTÁ COM 2 DÍGITOS E COM 1 
								DÍGITO. RA 10916. 
		
		11/02/2022 - ELIANE - ALTERANDO A PROCEDURE PARA BUSCAR APENAS TÍTULOS DE SACADO 
								ELETRÔNICO NO PRÓPRIO BANCO. 
		
		16/03/2022 - ELIANE - ISENTANDO A CONSULTA PONTUAL A UM TÍTULO, DO FLAG DE SACADO = 'P' 
		
		30/06/2022 - ELIANE - NOSSAS DBAS SUGEREM RETIRARMOS OS UNIONS DA PROC... 
								 NÃO AUTORIZARAM O COMANDO OPTION (MAXDOP 1) PROPOSTO PELO ITM. 
								 AVALIANDO AS PROCEDURES QUE GERENCIAM AINFORMAÇÃO DE TERCEIRO NO 
								 TÍTULO, VIMOS QUE ESTA INFORMAÇÃO DEIXOU DE FICAR NO TÍTULO PARA 
								 FICAR APENAS EM TERCEIROS. DESSA FORMA, O ACESSO A TITULOS DEVE 
								 SER RETIRADO PARA SER ACESSADO VIA TABELA TERCEIROS.			 

		01/07/2022 - ELIANE - CRIANDO TABELA DE APOIO PARA RETIRADA DE DUPLICIDADES DE NUMIDENTCDDA
		
		13/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOMEPORTADOR E DATAHORARECBTTITULO (CATÁLOGO 5.03 E 5.04)
								REMOÇÃO DE ALIAS
		06/10/2022 - ELIANE, JLSANTOS, RFAQUINI - ALTERAÇÃO NA CONSULTA QUE RESTRINGIA APENAS PARA SACADOS PRÓPRIOS  
													 ALTERAMOS A PROCEDURE PARA ATENDER TANTO IFS QUE   
													 EFETUAM A CONSULTA APENAS PARA SACADOS PRÓPRIOS   
													 QUANTO IFS QUE FAZEM A CONSULTA SEM ESTA RESTRIÇÃO.  
						
		08/03/2023 - QUICKWINS - ALTERAÇÃO NA CRIAÇÃO DA #TEMP POR CAUSA DE TRAVAMENTOS NO ITM
					
		28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)	
		
		29/03/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
	*/
 
	/* 
		SELECT T.CNPJ_CPF_SACADO, COUNT(*) 
		FROM TITULOS T WITH (NOLOCK) 
		INNER JOIN SACELETRONICO S WITH (NOLOCK) 
			ON (T.CNPJ_CPF_SACADO = S.CNPJ_CPF_SACADO) 
		WHERE S.SITUACAOSACADO = '1' 
		GROUP BY T.CNPJ_CPF_SACADO 
		HAVING COUNT(*) > 1 
		AND COUNT(*) < 5 
		GO 
	*/ 

	/*
		EXEC SP_PESQUISA_TITULO_POR_SACADO '90060847948', NULL, 'SACADO', 'D', NULL, NULL, NULL, NULL, NULL, NULL
	*/
 
BEGIN 
 
	IF (SELECT OBJECT_ID('TEMPDB..#TEMP_TITULOS_FILTRO')) IS NOT NULL 
	BEGIN
		DROP TABLE #TEMP_TITULOS_FILTRO 
	END

	IF (SELECT OBJECT_ID('TEMPDB..#TITULOS')) IS NOT NULL 
	BEGIN
		DROP TABLE #TITULOS 
	END
 
	DECLARE 
		@CNPJ_CPF_SACADO VARCHAR (15), 
		@NUMIDENTCDDA NUMERIC (19, 0), 
		@TIPOPESQUISA VARCHAR (10), 
		@CODCONDICAO VARCHAR (30), 
		@TIPOPESCEDENTE VARCHAR (3), 
		@CNPJ_CPF_CEDENTE VARCHAR (15), 
		@DATAVENCIMENTOINI DATETIME, 
		@DATAVENCIMENTOFIM DATETIME, 
		@CODSISLEGADO VARCHAR (15), 
		@EH_SACELETRONICOPROPRIO VARCHAR (01), /* 11/02/2022 */   
		--06/10/2022 - ELIANE, JLSANTOS, RFAQUINI - ALTERAÇÃO NA CONSULTA QUE RESTRINGIA APENAS PARA SACADOS PRÓPRIOS  
		@CODIF VARCHAR(04)  			  
 
	SELECT 
		@P_CNPJ_CPF_SACADO = CASE 
								WHEN @P_CNPJ_CPF_SACADO = '' 
									THEN NULL 
								ELSE @P_CNPJ_CPF_SACADO 
							END, 
		@P_TIPOPESQUISA = CASE 
							WHEN @P_TIPOPESQUISA = '' 
								THEN NULL 
							ELSE @P_TIPOPESQUISA 
						END, 
		@P_CODCONDICAO = CASE 
							WHEN @P_CODCONDICAO = '' 
								THEN NULL 
							ELSE @P_CODCONDICAO 
						END, 
		@P_TIPOPESCEDENTE = CASE 
								WHEN @P_TIPOPESCEDENTE = '' 
									THEN NULL 
								ELSE @P_TIPOPESCEDENTE 
							END, 
		@P_CNPJ_CPF_CEDENTE = CASE 
								WHEN @P_CNPJ_CPF_CEDENTE = '' 
									THEN NULL 
								ELSE @P_CNPJ_CPF_CEDENTE 
							END, 
		@P_CODSISLEGADO = CASE 
							WHEN @P_CODSISLEGADO = '' 
								THEN NULL 
							ELSE @P_CODSISLEGADO 
						END 
 
	SELECT 
		@CNPJ_CPF_SACADO = RTRIM (@P_CNPJ_CPF_SACADO), 
		@NUMIDENTCDDA = @P_NUMIDENTCDDA, 
		@TIPOPESQUISA = @P_TIPOPESQUISA, 
		@CODCONDICAO = RTRIM (@P_CODCONDICAO), 
		@TIPOPESCEDENTE = RTRIM (@P_TIPOPESCEDENTE), 
		@CNPJ_CPF_CEDENTE = RTRIM (@P_CNPJ_CPF_CEDENTE), 
		@DATAVENCIMENTOINI = @P_DATAVENCIMENTOINI, 
		@DATAVENCIMENTOFIM = @P_DATAVENCIMENTOFIM, 
		@CODSISLEGADO = RTRIM (@P_CODSISLEGADO) 
 
	--06/10/2022 - ELIANE, JLSANTOS, RFAQUINI - ALTERAÇÃO NA CONSULTA QUE RESTRINGIA APENAS PARA SACADOS PRÓPRIOS  
	SELECT   
		@CODIF = CODIF  
	FROM PARAMETROS WITH (NOLOCK)  	  
	
	--08/03/2023 - QUICKWINS - ALTERAÇÃO NA CRIAÇÃO DA #TEMP POR CAUSA DE TRAVAMENTOS NO ITM	
	CREATE TABLE #TEMP_TITULOS_FILTRO (
		TIPOREGISTRO INT NULL,
		NUMIDENTCDDA  NUMERIC(19, 0)  NULL,
		CODIFSACADA  CHAR(3)  NULL,
		CODIFCEDENTE  CHAR(3)  NULL,
		TIPOPESCEDENTE  CHAR(1)  NULL,
		CNPJ_CPF_CEDENTE  VARCHAR(14)  NULL,
		NOMECEDENTE  VARCHAR(50)  NULL,
		TIPOPESCEDENTEORI  CHAR(1)  NULL,
		CNPJ_CPF_CEDENTEORI  VARCHAR(14)  NULL,
		NOMECEDENTEORI  VARCHAR(50)  NULL,
		ENDCEDENTEORI  VARCHAR(50)  NULL,
		CIDCEDENTEORI  VARCHAR(50)  NULL,
		UFCEDENTEORI  CHAR(2)  NULL,
		CEPCEDENTEORI  CHAR(8)  NULL,
		TIPOPESSACADO  CHAR(1)  NULL,
		CNPJ_CPF_SACADO  VARCHAR(14)  NULL,
		NOMESACADO  VARCHAR(50)  NULL,
		ENDSACADO  VARCHAR(50)  NULL,
		CIDSACADO  VARCHAR(50)  NULL,
		UFSACADO  CHAR(2)  NULL,
		CEPSACADO  CHAR(8)  NULL,
		TIPOPESSACADOR  CHAR(1)  NULL,
		CNPJ_CPF_SACADOR  VARCHAR(14)  NULL,
		NOMESACADOR  VARCHAR(50)  NULL,
		CODCARTEIRA  CHAR(1)  NULL,
		CODMOEDACNAB  CHAR(2)  NULL,
		IDENTNOSSONUMERO  VARCHAR(20)  NULL,
		LINHADIGITAVEL  VARCHAR(47)  NULL,
		DATAVENCIMENTO  DATETIME  NULL,
		VLRTITULO  NUMERIC(19, 5)  NULL,
		SEUNUMERO  VARCHAR(15)  NULL,
		CODESPECIEDOC  CHAR(2)  NULL,
		DATAEMISSAO  DATETIME  NULL,
		QTDEDIASPROTESTO  INT  NULL,
		DATALIMPAGTO  DATETIME  NULL,
		TIPOPAGTO  INT  NULL, 
		INDTITULONEGOCIADO  CHAR(1)  NULL,
		VLRABATIMENTO  NUMERIC(19, 5)  NULL,
		CODMORA  CHAR(1)  NULL,
		DATAMORA  DATETIME  NULL,
		VLRPERCMORA  NUMERIC(19, 5)  NULL,
		CODMULTA  CHAR(1)  NULL,
		DATAMULTA  DATETIME  NULL,
		VLRPERCMULTA  NUMERIC(19, 5)  NULL,
		CODDESCONTO01  CHAR(1)  NULL,
		DATADESCONTO01  DATETIME  NULL,
		VLRPERCDESCONTO01  NUMERIC(19, 5)  NULL,
		CODDESCONTO02  CHAR(1)  NULL,
		DATADESCONTO02  DATETIME  NULL,
		VLRPERCDESCONTO02  NUMERIC(19, 5)  NULL,
		CODDESCONTO03  CHAR(1)  NULL,
		DATADESCONTO03  DATETIME  NULL,
		VLRPERCDESCONTO03  NUMERIC(19, 5)  NULL,
		ACEITE  CHAR(1)  NULL,
		DATAACEITE  DATETIME  NULL,
		CODSITUACAO  CHAR(2)  NULL,
		--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)	
		TIPOBAIXA  VARCHAR(2)  NULL,
		SITPAGAMENTO  CHAR(1)  NULL,
		VLRMINTITULO  NUMERIC(19, 5)  NULL,
		VLRMAXTITULO  NUMERIC(19, 5)  NULL,
		TIPOPESTERCEIRO  CHAR(1)  NULL,
		CNPJ_CPF_TERCEIRO  VARCHAR(14)  NULL,
		CODSISLEGADO  VARCHAR(10)  NULL,
		DTHRSITTITULO  DATETIME  NULL,
		INDALTERAVALOR  CHAR(1)  NULL,
		TIPOCALCULO  CHAR(2)  NULL,
		NOMEFANTASIACEDENTE  VARCHAR(80)  NULL,
		NOMEFANTASIACEDENTEORI  VARCHAR(80)  NULL,
		NOMEFANTASIASACADO  VARCHAR(80)  NULL,
		NUMCODBARRAS  VARCHAR(44)  NULL,
		NUMPARCELA  INT  NULL, 
		QTDPARCELA  INT  NULL, 
		INDBLOQUEIO  CHAR(1)  NULL,
		INDPARCIAL  CHAR(1)  NULL,
		QTDPAGTO  INT  NULL, 
		INDVALORPERC_MIN  CHAR(1)  NULL,
		INDVALORPERC_MAX  CHAR(1)  NULL,
		ISPBCEDENTE  VARCHAR(8)  NULL,
		TIPOAUTRECDIVERGENTE  CHAR(1)  NULL,
		ISPBSACADA  VARCHAR(8)  NULL,
		CANALPAGTO  CHAR(1)  NULL,
		MEIOPAGTO  CHAR(1)  NULL,
		SITPAGAMENTOCIP  CHAR(2)  NULL,
		ULTNUMREFCADTIT  NUMERIC(19, 0)  NULL,
		ULTNUMSEQCADTIT  NUMERIC(19, 0)  NULL,
		ULTNUMREFBAIXAOPERAC  NUMERIC(19, 0)  NULL,
		ULTNUMSEQBAIXAOPERAC  NUMERIC(19, 0)  NULL,
		ULTNUMREFBAIXAEFET  NUMERIC(19, 0)  NULL,
		ULTNUMSEQBAIXAEFET  NUMERIC(19, 0)  NULL,
		ULTNUMREFACEITE  NUMERIC(19, 0)  NULL,
		ULTNUMSEQACEITE  NUMERIC(19, 0)  NULL,
		ULTNUMREFTERC  NUMERIC(19, 0)  NULL,
		ULTNUMSEQTERC  NUMERIC(19, 0)  NULL,
		
		--MENSAGENS 							
		SEQMENSAGEM  INTEGER  NULL,
		TEXTO  VARCHAR(100)  NULL,
		
		--ANEXO FATURA 							
		SEQFATURA  NUMERIC(17, 0)  NULL,
		CODMODELO  INTEGER  NULL,
		SEQDETANTES  NUMERIC(17, 0)  NULL,
		SEQDETDEPOIS  NUMERIC(17, 0)  NULL,
		CABECALHO  VARCHAR(255)  NULL,
		TPDADOS  VARCHAR(2)  NULL,
		SEQMODELO  NUMERIC(17, 0)  NULL,
		
		--NOTAS FISCAIS 							
		NUMNOTAFISCAL  VARCHAR(15)  NULL,
		VLRNOTAFISCAL  NUMERIC(19, 5)  NULL,
		DATAEMISSAONOTA  DATETIME  NULL,
		
		--BAIXAS OPERACIONAIS 							
		NUMIDENTCBAIXAOPERAC  NUMERIC(19, 0)  NULL,
		NUMREFBAIXAOPERAC  NUMERIC(19, 0)  NULL,
		--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)	
		TIPOBAIXAOPERACIONAL  VARCHAR(2)  NULL, 
		DATABAIXAOPERACIONAL  DATETIME  NULL,
		VLRBAIXAOPERACIONAL  NUMERIC(19, 5)  NULL,
		TIPOPESPORTADOR  CHAR(1)  NULL, 
		CNPJ_CPF_PORTADOR  VARCHAR(14)  NULL,
		--13/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOMEPORTADOR E DATAHORARECBTTITULO (CATÁLOGO 5.03 E 5.04)							
		NOME_PORTADOR  VARCHAR(80)  NULL,
		--29/03/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
		TIPOPESAGREGADOR CHAR(1) NULL,
		CNPJ_CPF_AGREGADOR VARCHAR(14) NULL,
		NOMEAGREGADOR VARCHAR(50) NULL,
		ISPBINICIADORPAGTO VARCHAR(8) NULL,
		AGENCIARECEBEDORA VARCHAR(4) NULL,
		CODMOTIVO VARCHAR(3) NULL,						 
		DATAHORARECBTTITULO  DATETIME  NULL,
		DATAHORACANCEL  DATETIME  NULL,
		INDCONTINGENCIA  CHAR(1)  NULL, 
		ORIGEMCANCELAMENTO  CHAR(1)  NULL, 
		
		--BAIXAS EFETIVAS 							
		NUMIDENTCBAIXAEFET  NUMERIC(19, 0)  NULL,
		NUMREFBAIXAEFET  NUMERIC(19, 0)  NULL,
		DATABAIXAEFETIVA  DATETIME  NULL,
		VLRBAIXAEFETIVA  NUMERIC(19, 5)  NULL,
		--13/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOMEPORTADOR E DATAHORARECBTTITULO (CATÁLOGO 5.03 E 5.04)							
		TIPOBAIXAEFETIVA  VARCHAR(2)  NULL, 
											 
		--CALCULOS 							
		DATACALCULO  DATETIME  NULL,
		VLRMORA  NUMERIC(19, 5)  NULL,
		VLRMULTA  NUMERIC(19, 5)  NULL,
		VLRDESCONTO  NUMERIC(19, 5)  NULL,
		VLRCOBRAR  NUMERIC(19, 5)  NULL,
		
		--TERCEIROS 							
		TIPOPESTERC  CHAR(1)  NULL, 
		CNPJ_CPF_TERC  VARCHAR(14)  NULL,
		NUMIDENTCTERC  NUMERIC(19, 0)  NULL,
		NUMREFTERC  NUMERIC(19, 0)  NULL,
		TIPOPESAUTORIZADOR  CHAR(1)  NULL, 
		CNPJ_CPF_AUTORIZADOR VARCHAR(14)  NULL,
	)
 
	/*-------------------------------------------------------------------------------------*/ 
	CREATE TABLE #TITULOS (
		NUMIDENTCDDA NUMERIC (19, 0) 
	) 
	CREATE NONCLUSTERED INDEX IDX_TEMP_TITULOS ON #TITULOS (NUMIDENTCDDA) 
 
	/*-------------------------------------------------------------------------------------*/ 
	/* 01/07/2022 - CRIANDO TABELA DE APOIO PARA RETIRADA DE DUPLICIDADES DE NUMIDENTCDDA. */ 
	CREATE TABLE #TITULOS_APOIO (
		NUMIDENTCDDA NUMERIC (19, 0) 
	) 
	CREATE NONCLUSTERED INDEX IDX_TEMP_TITULOSAPOIO ON #TITULOS (NUMIDENTCDDA) 
	/* 01/07/2022 - CRIANDO TABELA DE APOIO PARA RETIRADA DE DUPLICIDADES DE NUMIDENTCDDA. */ 
	/*-------------------------------------------------------------------------------------*/ 
 
 
	/*---11/02/2022 - VERIFICANDO SE SACADO É ELETRÔNICO NO PRÓPRIO BANCO ---*/   
	SELECT @EH_SACELETRONICOPROPRIO = 'N'   
   
	--06/10/2022 - ELIANE, JLSANTOS, RFAQUINI - ALTERAÇÃO NA CONSULTA QUE RESTRINGIA APENAS PARA SACADOS PRÓPRIOS  
	IF (@CNPJ_CPF_SACADO IS NOT NULL)  
	BEGIN  
		IF (@CODIF = '077')  
		BEGIN  
			IF ((SELECT TIPOSACADO   
					FROM SACELETRONICO   
					WHERE CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO) = 'P') /* SACADO PRÓPRIO */   
			BEGIN  
				SELECT @EH_SACELETRONICOPROPRIO = 'S'   
			END  
		END  
   
		ELSE  
		BEGIN  
			SELECT @EH_SACELETRONICOPROPRIO = 'S' 
		END
	END
 
	IF @EH_SACELETRONICOPROPRIO = 'S' 
	BEGIN /* 11/02/2022 SÓ CONSULTAR SE O SACADO É ELETRÔNICO NO PRÓPRIO BANCO; SE NÃO FOR, DEVOLVER RECORDSET VAZIO */ 
 
		/*---11/02/2022 - VERIFICANDO SE SACADO É ELETRÔNICO NO PRÓPRIO BANCO ---*/ 
		/*---16/03/2022 - ESTA TABELA #TITULOS É A AUXILIAR DAS CONSULTAS DE TÍTULOS POR SACELETRONICO. */ 
		/*---ELA AJUDA A POPULAR A TABELA FINAL QUE É A #TEMP_TITULOS_FILTRO. */ 
		/*---A CONSULTA PONTUAL DE UM TÍTULO NÃO SE RESTRINGE AO SACADO SER ELETRÔNICO!. */ 
 
		/*----------------------------------------------------------------------------------------------*/ 
		/* ESTE PRIMEIRO SELECT PEGA OS TÍTULOS DO CNPJ ESCOLHIDO COMO SACELETRONICO DO PRÓPRIO BANCO. */ 
		/*----------------------------------------------------------------------------------------------*/ 
		INSERT INTO #TITULOS_APOIO (
			NUMIDENTCDDA
		) 
		SELECT 
			NUMIDENTCDDA 
		FROM TITULOS WITH(NOLOCK) 
		WHERE CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO 
 
		/*----------------------------------------------------------------------------------------------*/ 
		/* ESTE SEGUNDO SELECT PEGA OS TÍTULOS DO CNPJ COMO TERCEIRO EM TÍTULOS DE OUTROS SACADOS. */ 
		/*----------------------------------------------------------------------------------------------*/ 
 
		INSERT INTO #TITULOS_APOIO (
			NUMIDENTCDDA
		) 
		SELECT 
			NUMIDENTCDDA 
		FROM TERCEIROS WITH(NOLOCK) 
		WHERE CNPJ_CPF_TERC = @CNPJ_CPF_SACADO /* É PRECISO TER UM ÍNDICE CNPJ_CPF_TERC */ 
 
		/*----------------------------------------------------------------------------------------------*/ 
		/* ESTE TERCEIRO SELECT PEGA OS TÍTULOS DO CNPJ COMO SACADO PRÓPRIO E ATIVO.(IDEM SELECT 1). */ 
		/*----------------------------------------------------------------------------------------------*/ 
 
		--INSERT INTO #TITULOS_APOIO (NUMIDENTCDDA) 
		--SELECT NUMIDENTCDDA 
		--FROM TITULOS WITH(NOLOCK) 
		--WHERE CNPJ_CPF_SACADO IN (SELECT S.CNPJ_CPF_SACADO FROM SACELETRONICO S WHERE S.CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO AND S.SITUACAOSACADO = 1) 
 
		/*----------------------------------------------------------------------------------------------*/ 
		/* ESTE QUARTO SELECT PEGA OS TÍTULOS DOS AGREGADOS ATIVOS DO SACADO PRINCIPAL. */ 
		/*----------------------------------------------------------------------------------------------*/ 
 
		INSERT INTO #TITULOS_APOIO (
			NUMIDENTCDDA
		) 
		SELECT 
			NUMIDENTCDDA 
		FROM TITULOS WITH(NOLOCK) 
		WHERE CNPJ_CPF_SACADO IN (SELECT A.CNPJ_CPF_AGREGADO 
									FROM AGREGADOS A 
									WHERE A.CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO 
									AND A.SITUACAOAGREGADO = '1'
								) 
 
		/*----------------------------------------------------------------------------------------------*/ 
		/* RETIRANDO AS MULTIPLICIDADES DE NUMIDENTCDDA... */ 
		/*----------------------------------------------------------------------------------------------*/ 
		INSERT INTO #TITULOS (
			NUMIDENTCDDA
		) 
		SELECT 
			NUMIDENTCDDA 
		FROM #TITULOS_APOIO 
		GROUP BY NUMIDENTCDDA 
 
	END /* 11/02/2022 SÓ CONSULTAR SE O SACADO É ELETRÔNICO NO PRÓPRIO BANCO; SE NÃO FOR, DEVOLVER RECORDSET VAZIO */ 
 
	IF (@TIPOPESQUISA = 'TITULO') 
	BEGIN
		INSERT INTO #TEMP_TITULOS_FILTRO (
			TIPOREGISTRO, NUMIDENTCDDA, CODIFSACADA, CODIFCEDENTE, 
			TIPOPESCEDENTE, CNPJ_CPF_CEDENTE, NOMECEDENTE, TIPOPESCEDENTEORI, CNPJ_CPF_CEDENTEORI, 
			NOMECEDENTEORI, ENDCEDENTEORI, CIDCEDENTEORI, UFCEDENTEORI, CEPCEDENTEORI, TIPOPESSACADO, 
			CNPJ_CPF_SACADO, NOMESACADO, ENDSACADO, CIDSACADO, UFSACADO, CEPSACADO, TIPOPESSACADOR, 
			CNPJ_CPF_SACADOR, 
			NOMESACADOR, CODCARTEIRA, CODMOEDACNAB, IDENTNOSSONUMERO, LINHADIGITAVEL, 
			DATAVENCIMENTO, VLRTITULO, SEUNUMERO, CODESPECIEDOC, DATAEMISSAO, QTDEDIASPROTESTO, 
			DATALIMPAGTO, TIPOPAGTO, INDTITULONEGOCIADO, VLRABATIMENTO, CODMORA, DATAMORA, VLRPERCMORA, 
			CODMULTA, DATAMULTA, VLRPERCMULTA, CODDESCONTO01, DATADESCONTO01, VLRPERCDESCONTO01, 
			CODDESCONTO02, DATADESCONTO02, VLRPERCDESCONTO02, CODDESCONTO03, DATADESCONTO03, 
			VLRPERCDESCONTO03, ACEITE, DATAACEITE, CODSITUACAO, TIPOBAIXA, SITPAGAMENTO, VLRMINTITULO, 
			VLRMAXTITULO, TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO, CODSISLEGADO, DTHRSITTITULO, 
			DATACALCULO, INDALTERAVALOR, TIPOCALCULO, NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI, NOMEFANTASIASACADO, NUMCODBARRAS, NUMPARCELA, 
			QTDPARCELA, INDBLOQUEIO, INDPARCIAL, QTDPAGTO, INDVALORPERC_MIN, INDVALORPERC_MAX, ISPBCEDENTE, TIPOAUTRECDIVERGENTE, 
			ISPBSACADA, CANALPAGTO, MEIOPAGTO, SITPAGAMENTOCIP, ULTNUMREFCADTIT, ULTNUMSEQCADTIT, ULTNUMREFBAIXAOPERAC, 
			ULTNUMSEQBAIXAOPERAC, ULTNUMREFBAIXAEFET, ULTNUMSEQBAIXAEFET, ULTNUMREFACEITE, ULTNUMSEQACEITE, ULTNUMREFTERC, ULTNUMSEQTERC
		) 
		SELECT 
			1, T.NUMIDENTCDDA, T.CODIFSACADA, T.CODIFCEDENTE, 
			T.TIPOPESCEDENTE, T.CNPJ_CPF_CEDENTE, T.NOMECEDENTE, T.TIPOPESCEDENTEORI, T.CNPJ_CPF_CEDENTEORI, 
			T.NOMECEDENTEORI, T.ENDCEDENTEORI, T.CIDCEDENTEORI, T.UFCEDENTEORI, T.CEPCEDENTEORI, T.TIPOPESSACADO, 
			T.CNPJ_CPF_SACADO, T.NOMESACADO, T.ENDSACADO, T.CIDSACADO, T.UFSACADO, T.CEPSACADO, T.TIPOPESSACADOR, 
			CASE 
				WHEN LEN(T.CNPJ_CPF_SACADOR)> 14 
					THEN SUBSTRING (T.CNPJ_CPF_SACADOR, 2, 14) 
				ELSE T.CNPJ_CPF_SACADOR 
				END, 
			T.NOMESACADOR, T.CODCARTEIRA, T.CODMOEDACNAB, T.IDENTNOSSONUMERO, T.LINHADIGITAVEL, 
			T.DATAVENCIMENTO, T.VLRTITULO, T.SEUNUMERO, T.CODESPECIEDOC, T.DATAEMISSAO, T.QTDEDIASPROTESTO, 
			T.DATALIMPAGTO, T.TIPOPAGTO, T.INDTITULONEGOCIADO, T.VLRABATIMENTO, T.CODMORA, T.DATAMORA, T.VLRPERCMORA, 
			T.CODMULTA, T.DATAMULTA, T.VLRPERCMULTA, T.CODDESCONTO01, T.DATADESCONTO01, T.VLRPERCDESCONTO01, 
			T.CODDESCONTO02, T.DATADESCONTO02, T.VLRPERCDESCONTO02, T.CODDESCONTO03, T.DATADESCONTO03, 
			T.VLRPERCDESCONTO03, T.ACEITE, T.DATAACEITE, T.CODSITUACAO, T.TIPOBAIXA, T.SITPAGAMENTO, T.VLRMINTITULO, 
			T.VLRMAXTITULO, T.TIPOPESTERCEIRO, T.CNPJ_CPF_TERCEIRO, T.CODSISLEGADO, T.DTHRSITTITULO, 
			T.DATACALCULO, T.INDALTERAVALOR, T.TIPOCALCULO, T.NOMEFANTASIACEDENTE, T.NOMEFANTASIACEDENTEORI, T.NOMEFANTASIASACADO, T.NUMCODBARRAS, T.NUMPARCELA, 
			T.QTDPARCELA, T.INDBLOQUEIO, T.INDPARCIAL, T.QTDPAGTO, T.INDVALORPERC_MIN, T.INDVALORPERC_MAX, T.ISPBCEDENTE, T.TIPOAUTRECDIVERGENTE, 
			T.ISPBSACADA, T.CANALPAGTO, T.MEIOPAGTO, T.SITPAGAMENTOCIP, T.ULTNUMREFCADTIT, T.ULTNUMSEQCADTIT, T.ULTNUMREFBAIXAOPERAC, 
			T.ULTNUMSEQBAIXAOPERAC, T.ULTNUMREFBAIXAEFET, T.ULTNUMSEQBAIXAEFET, T.ULTNUMREFACEITE, T.ULTNUMSEQACEITE, T.ULTNUMREFTERC, T.ULTNUMSEQTERC 
		FROM TITULOS T 
		WHERE T.NUMIDENTCDDA = @NUMIDENTCDDA 
	END
	ELSE IF (@CODCONDICAO IS NULL) 
	BEGIN
		INSERT INTO #TEMP_TITULOS_FILTRO (
			TIPOREGISTRO, NUMIDENTCDDA, CODIFSACADA, CODIFCEDENTE, 
			TIPOPESCEDENTE, CNPJ_CPF_CEDENTE, NOMECEDENTE, TIPOPESCEDENTEORI, CNPJ_CPF_CEDENTEORI, 
			NOMECEDENTEORI, ENDCEDENTEORI, CIDCEDENTEORI, UFCEDENTEORI, CEPCEDENTEORI, TIPOPESSACADO, 
			CNPJ_CPF_SACADO, NOMESACADO, ENDSACADO, CIDSACADO, UFSACADO, CEPSACADO, TIPOPESSACADOR, 
			CNPJ_CPF_SACADOR, 
			NOMESACADOR, CODCARTEIRA, CODMOEDACNAB, IDENTNOSSONUMERO, LINHADIGITAVEL, 
			DATAVENCIMENTO, VLRTITULO, SEUNUMERO, CODESPECIEDOC, DATAEMISSAO, QTDEDIASPROTESTO, 
			DATALIMPAGTO, TIPOPAGTO, INDTITULONEGOCIADO, VLRABATIMENTO, CODMORA, DATAMORA, VLRPERCMORA, 
			CODMULTA, DATAMULTA, VLRPERCMULTA, CODDESCONTO01, DATADESCONTO01, VLRPERCDESCONTO01, 
			CODDESCONTO02, DATADESCONTO02, VLRPERCDESCONTO02, CODDESCONTO03, DATADESCONTO03, 
			VLRPERCDESCONTO03, ACEITE, DATAACEITE, CODSITUACAO, TIPOBAIXA, SITPAGAMENTO, VLRMINTITULO, 
			VLRMAXTITULO, TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO, CODSISLEGADO, DTHRSITTITULO, 
			DATACALCULO, INDALTERAVALOR, TIPOCALCULO, NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI, NOMEFANTASIASACADO, NUMCODBARRAS, NUMPARCELA, 
			QTDPARCELA, INDBLOQUEIO, INDPARCIAL, QTDPAGTO, INDVALORPERC_MIN, INDVALORPERC_MAX, ISPBCEDENTE, TIPOAUTRECDIVERGENTE, 
			ISPBSACADA, CANALPAGTO, MEIOPAGTO, SITPAGAMENTOCIP, ULTNUMREFCADTIT, ULTNUMSEQCADTIT, ULTNUMREFBAIXAOPERAC, 
			ULTNUMSEQBAIXAOPERAC, ULTNUMREFBAIXAEFET, ULTNUMSEQBAIXAEFET, ULTNUMREFACEITE, ULTNUMSEQACEITE, ULTNUMREFTERC, ULTNUMSEQTERC
		) 
		SELECT 
			1, T.NUMIDENTCDDA, T.CODIFSACADA, T.CODIFCEDENTE, 
			T.TIPOPESCEDENTE, T.CNPJ_CPF_CEDENTE, T.NOMECEDENTE, T.TIPOPESCEDENTEORI, T.CNPJ_CPF_CEDENTEORI, 
			T.NOMECEDENTEORI, T.ENDCEDENTEORI, T.CIDCEDENTEORI, T.UFCEDENTEORI, T.CEPCEDENTEORI, T.TIPOPESSACADO, 
			T.CNPJ_CPF_SACADO, T.NOMESACADO, T.ENDSACADO, T.CIDSACADO, T.UFSACADO, T.CEPSACADO, T.TIPOPESSACADOR, 
			CASE 
				WHEN LEN(T.CNPJ_CPF_SACADOR)> 14 
					THEN SUBSTRING (T.CNPJ_CPF_SACADOR, 2, 14) 
				ELSE T.CNPJ_CPF_SACADOR 
				END, 
			T.NOMESACADOR, T.CODCARTEIRA, T.CODMOEDACNAB, T.IDENTNOSSONUMERO, T.LINHADIGITAVEL, 
			T.DATAVENCIMENTO, T.VLRTITULO, T.SEUNUMERO, T.CODESPECIEDOC, T.DATAEMISSAO, T.QTDEDIASPROTESTO, 
			T.DATALIMPAGTO, T.TIPOPAGTO, T.INDTITULONEGOCIADO, T.VLRABATIMENTO, T.CODMORA, T.DATAMORA, T.VLRPERCMORA, 
			T.CODMULTA, T.DATAMULTA, T.VLRPERCMULTA, T.CODDESCONTO01, T.DATADESCONTO01, T.VLRPERCDESCONTO01, 
			T.CODDESCONTO02, T.DATADESCONTO02, T.VLRPERCDESCONTO02, T.CODDESCONTO03, T.DATADESCONTO03, 
			T.VLRPERCDESCONTO03, T.ACEITE, T.DATAACEITE, T.CODSITUACAO, T.TIPOBAIXA, T.SITPAGAMENTO, T.VLRMINTITULO, 
			T.VLRMAXTITULO, T.TIPOPESTERCEIRO, T.CNPJ_CPF_TERCEIRO, T.CODSISLEGADO, T.DTHRSITTITULO, 
			T.DATACALCULO, T.INDALTERAVALOR, T.TIPOCALCULO, T.NOMEFANTASIACEDENTE, T.NOMEFANTASIACEDENTEORI, T.NOMEFANTASIASACADO, T.NUMCODBARRAS, T.NUMPARCELA, 
			T.QTDPARCELA, T.INDBLOQUEIO, T.INDPARCIAL, T.QTDPAGTO, T.INDVALORPERC_MIN, T.INDVALORPERC_MAX, T.ISPBCEDENTE, T.TIPOAUTRECDIVERGENTE, 
			T.ISPBSACADA, T.CANALPAGTO, T.MEIOPAGTO, T.SITPAGAMENTOCIP, T.ULTNUMREFCADTIT, T.ULTNUMSEQCADTIT, T.ULTNUMREFBAIXAOPERAC, 
			T.ULTNUMSEQBAIXAOPERAC, T.ULTNUMREFBAIXAEFET, T.ULTNUMSEQBAIXAEFET, T.ULTNUMREFACEITE, T.ULTNUMSEQACEITE, T.ULTNUMREFTERC, T.ULTNUMSEQTERC 
		FROM TITULOS T WITH (NOLOCK), #TITULOS TEMP_T 
		WHERE 
		/*((T.CNPJ_CPF_SACADO IN (SELECT S.CNPJ_CPF_SACADO FROM SACELETRONICO S WHERE S.CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO AND S.SITUACAOSACADO = 1)) 
		OR T.CNPJ_CPF_SACADO IN (SELECT A.CNPJ_CPF_AGREGADO FROM AGREGADOS A WHERE A.CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO AND A.SITUACAOAGREGADO = 1) 
		OR T.CNPJ_CPF_TERCEIRO = @CNPJ_CPF_SACADO) --19/06/2019 EDUARDOK -(PERFORMANCE) REMOVER OR DO SELECT - ALTERADO PARA UNION ALL*/ 
		T.NUMIDENTCDDA = TEMP_T.NUMIDENTCDDA 
		AND T.CNPJ_CPF_SACADO IN (SELECT S.CNPJ_CPF_SACADO 
									FROM SACELETRONICO S 
									WHERE S.CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO 
									AND S.SITUACAOSACADO = '1') 
		AND (@TIPOPESCEDENTE IS NULL 
			OR T.TIPOPESCEDENTE = @TIPOPESCEDENTE) 
		AND (@CNPJ_CPF_CEDENTE IS NULL 
			OR T.CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE) 
		AND (@DATAVENCIMENTOINI IS NULL 
			OR T.DATAVENCIMENTO > = @DATAVENCIMENTOINI) 
		AND (@DATAVENCIMENTOFIM IS NULL 
			OR T.DATAVENCIMENTO < = @DATAVENCIMENTOFIM) 
		UNION ALL 
		SELECT 
			1, T.NUMIDENTCDDA, T.CODIFSACADA, T.CODIFCEDENTE, 
			T.TIPOPESCEDENTE, T.CNPJ_CPF_CEDENTE, T.NOMECEDENTE, T.TIPOPESCEDENTEORI, T.CNPJ_CPF_CEDENTEORI, 
			T.NOMECEDENTEORI, T.ENDCEDENTEORI, T.CIDCEDENTEORI, T.UFCEDENTEORI, T.CEPCEDENTEORI, T.TIPOPESSACADO, 
			T.CNPJ_CPF_SACADO, T.NOMESACADO, T.ENDSACADO, T.CIDSACADO, T.UFSACADO, T.CEPSACADO, T.TIPOPESSACADOR, 
			CASE 
				WHEN LEN(T.CNPJ_CPF_SACADOR)> 14 
					THEN SUBSTRING (T.CNPJ_CPF_SACADOR, 2, 14) 
				ELSE T.CNPJ_CPF_SACADOR 
				END, 
			T.NOMESACADOR, T.CODCARTEIRA, T.CODMOEDACNAB, T.IDENTNOSSONUMERO, T.LINHADIGITAVEL, 
			T.DATAVENCIMENTO, T.VLRTITULO, T.SEUNUMERO, T.CODESPECIEDOC, T.DATAEMISSAO, T.QTDEDIASPROTESTO, 
			T.DATALIMPAGTO, T.TIPOPAGTO, T.INDTITULONEGOCIADO, T.VLRABATIMENTO, T.CODMORA, T.DATAMORA, T.VLRPERCMORA, 
			T.CODMULTA, T.DATAMULTA, T.VLRPERCMULTA, T.CODDESCONTO01, T.DATADESCONTO01, T.VLRPERCDESCONTO01, 
			T.CODDESCONTO02, T.DATADESCONTO02, T.VLRPERCDESCONTO02, T.CODDESCONTO03, T.DATADESCONTO03, 
			T.VLRPERCDESCONTO03, T.ACEITE, T.DATAACEITE, T.CODSITUACAO, T.TIPOBAIXA, T.SITPAGAMENTO, T.VLRMINTITULO, 
			T.VLRMAXTITULO, T.TIPOPESTERCEIRO, T.CNPJ_CPF_TERCEIRO, T.CODSISLEGADO, T.DTHRSITTITULO, 
			T.DATACALCULO, T.INDALTERAVALOR, T.TIPOCALCULO, T.NOMEFANTASIACEDENTE, T.NOMEFANTASIACEDENTEORI, T.NOMEFANTASIASACADO, T.NUMCODBARRAS, T.NUMPARCELA, 
			T.QTDPARCELA, T.INDBLOQUEIO, T.INDPARCIAL, T.QTDPAGTO, T.INDVALORPERC_MIN, T.INDVALORPERC_MAX, T.ISPBCEDENTE, T.TIPOAUTRECDIVERGENTE, 
			T.ISPBSACADA, T.CANALPAGTO, T.MEIOPAGTO, T.SITPAGAMENTOCIP, T.ULTNUMREFCADTIT, T.ULTNUMSEQCADTIT, T.ULTNUMREFBAIXAOPERAC, 
			T.ULTNUMSEQBAIXAOPERAC, T.ULTNUMREFBAIXAEFET, T.ULTNUMSEQBAIXAEFET, T.ULTNUMREFACEITE, T.ULTNUMSEQACEITE, T.ULTNUMREFTERC, T.ULTNUMSEQTERC 
		FROM TITULOS T WITH (NOLOCK)--NÃO PODE SER USADO A TEMP #TITULOS POIS A TEMP NÃO POSSUI TITULOS DO AGREGADO! 
		WHERE 
		--A CONDIÇÃO DE BUSCA POR AGREGADOS NÃO PERMITE UTILIZAR A TEMP! 
		T.CNPJ_CPF_SACADO IN (SELECT A.CNPJ_CPF_AGREGADO 
								FROM AGREGADOS A 
								WHERE A.CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO 
								AND A.SITUACAOAGREGADO = '1') 
		AND (@TIPOPESCEDENTE IS NULL
			OR T.TIPOPESCEDENTE = @TIPOPESCEDENTE) 
		AND (@CNPJ_CPF_CEDENTE IS NULL 
			OR T.CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE) 
		AND (@DATAVENCIMENTOINI IS NULL 
			OR T.DATAVENCIMENTO > = @DATAVENCIMENTOINI) 
		AND (@DATAVENCIMENTOFIM IS NULL 
			OR T.DATAVENCIMENTO < = @DATAVENCIMENTOFIM) 
		UNION ALL 
		SELECT 
			1, T.NUMIDENTCDDA, T.CODIFSACADA, T.CODIFCEDENTE, 
			T.TIPOPESCEDENTE, T.CNPJ_CPF_CEDENTE, T.NOMECEDENTE, T.TIPOPESCEDENTEORI, T.CNPJ_CPF_CEDENTEORI, 
			T.NOMECEDENTEORI, T.ENDCEDENTEORI, T.CIDCEDENTEORI, T.UFCEDENTEORI, T.CEPCEDENTEORI, T.TIPOPESSACADO, 
			T.CNPJ_CPF_SACADO, T.NOMESACADO, T.ENDSACADO, T.CIDSACADO, T.UFSACADO, T.CEPSACADO, T.TIPOPESSACADOR, 
			CASE 
				WHEN LEN(T.CNPJ_CPF_SACADOR)> 14 
					THEN SUBSTRING (T.CNPJ_CPF_SACADOR, 2, 14) 
				ELSE T.CNPJ_CPF_SACADOR 
				END, 
			T.NOMESACADOR, T.CODCARTEIRA, T.CODMOEDACNAB, T.IDENTNOSSONUMERO, T.LINHADIGITAVEL, 
			T.DATAVENCIMENTO, T.VLRTITULO, T.SEUNUMERO, T.CODESPECIEDOC, T.DATAEMISSAO, T.QTDEDIASPROTESTO, 
			T.DATALIMPAGTO, T.TIPOPAGTO, T.INDTITULONEGOCIADO, T.VLRABATIMENTO, T.CODMORA, T.DATAMORA, T.VLRPERCMORA, 
			T.CODMULTA, T.DATAMULTA, T.VLRPERCMULTA, T.CODDESCONTO01, T.DATADESCONTO01, T.VLRPERCDESCONTO01, 
			T.CODDESCONTO02, T.DATADESCONTO02, T.VLRPERCDESCONTO02, T.CODDESCONTO03, T.DATADESCONTO03, 
			T.VLRPERCDESCONTO03, T.ACEITE, T.DATAACEITE, T.CODSITUACAO, T.TIPOBAIXA, T.SITPAGAMENTO, T.VLRMINTITULO, 
			T.VLRMAXTITULO, T.TIPOPESTERCEIRO, T.CNPJ_CPF_TERCEIRO, T.CODSISLEGADO, T.DTHRSITTITULO, 
			T.DATACALCULO, T.INDALTERAVALOR, T.TIPOCALCULO, T.NOMEFANTASIACEDENTE, T.NOMEFANTASIACEDENTEORI, T.NOMEFANTASIASACADO, T.NUMCODBARRAS, T.NUMPARCELA, 
			T.QTDPARCELA, T.INDBLOQUEIO, T.INDPARCIAL, T.QTDPAGTO, T.INDVALORPERC_MIN, T.INDVALORPERC_MAX, T.ISPBCEDENTE, T.TIPOAUTRECDIVERGENTE, 
			T.ISPBSACADA, T.CANALPAGTO, T.MEIOPAGTO, T.SITPAGAMENTOCIP, T.ULTNUMREFCADTIT, T.ULTNUMSEQCADTIT, T.ULTNUMREFBAIXAOPERAC, 
			T.ULTNUMSEQBAIXAOPERAC, T.ULTNUMREFBAIXAEFET, T.ULTNUMSEQBAIXAEFET, T.ULTNUMREFACEITE, T.ULTNUMSEQACEITE, T.ULTNUMREFTERC, T.ULTNUMSEQTERC 
		FROM TITULOS T WITH (NOLOCK), #TITULOS TEMP_T 
		WHERE T.NUMIDENTCDDA = TEMP_T.NUMIDENTCDDA 
		AND T.CNPJ_CPF_TERCEIRO = @CNPJ_CPF_SACADO 
		AND (@TIPOPESCEDENTE IS NULL 
			OR T.TIPOPESCEDENTE = @TIPOPESCEDENTE) 
		AND (@CNPJ_CPF_CEDENTE IS NULL 
			OR T.CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE) 
		AND (@DATAVENCIMENTOINI IS NULL 
			OR T.DATAVENCIMENTO > = @DATAVENCIMENTOINI) 
		AND (@DATAVENCIMENTOFIM IS NULL 
			OR T.DATAVENCIMENTO < = @DATAVENCIMENTOFIM) 
	END
	ELSE IF @CODCONDICAO IN ('ABERTO', '1') 
 BEGIN
		/*---------------------------------------------*/ 
		/* PEGAR TÍTULOS EM ABERTO E CARTÕES EM ABERTO */ 
		/*---------------------------------------------*/ 
 
		INSERT INTO #TEMP_TITULOS_FILTRO (
			TIPOREGISTRO, NUMIDENTCDDA, CODIFSACADA, CODIFCEDENTE, 
			TIPOPESCEDENTE, CNPJ_CPF_CEDENTE, NOMECEDENTE, TIPOPESCEDENTEORI, CNPJ_CPF_CEDENTEORI, 
			NOMECEDENTEORI, ENDCEDENTEORI, CIDCEDENTEORI, UFCEDENTEORI, CEPCEDENTEORI, TIPOPESSACADO, 
			CNPJ_CPF_SACADO, NOMESACADO, ENDSACADO, CIDSACADO, UFSACADO, CEPSACADO, TIPOPESSACADOR, 
			CNPJ_CPF_SACADOR, 
			NOMESACADOR, CODCARTEIRA, CODMOEDACNAB, IDENTNOSSONUMERO, LINHADIGITAVEL, 
			DATAVENCIMENTO, VLRTITULO, SEUNUMERO, CODESPECIEDOC, DATAEMISSAO, QTDEDIASPROTESTO, 
			DATALIMPAGTO, TIPOPAGTO, INDTITULONEGOCIADO, VLRABATIMENTO, CODMORA, DATAMORA, VLRPERCMORA, 
			CODMULTA, DATAMULTA, VLRPERCMULTA, CODDESCONTO01, DATADESCONTO01, VLRPERCDESCONTO01, 
			CODDESCONTO02, DATADESCONTO02, VLRPERCDESCONTO02, CODDESCONTO03, DATADESCONTO03, 
			VLRPERCDESCONTO03, ACEITE, DATAACEITE, CODSITUACAO, TIPOBAIXA, SITPAGAMENTO, VLRMINTITULO, 
			VLRMAXTITULO, TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO, CODSISLEGADO, DTHRSITTITULO, 
			DATACALCULO, INDALTERAVALOR, TIPOCALCULO, NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI, NOMEFANTASIASACADO, NUMCODBARRAS, NUMPARCELA, 
			QTDPARCELA, INDBLOQUEIO, INDPARCIAL, QTDPAGTO, INDVALORPERC_MIN, INDVALORPERC_MAX, ISPBCEDENTE, TIPOAUTRECDIVERGENTE, 
			ISPBSACADA, CANALPAGTO, MEIOPAGTO, SITPAGAMENTOCIP, ULTNUMREFCADTIT, ULTNUMSEQCADTIT, ULTNUMREFBAIXAOPERAC, 
			ULTNUMSEQBAIXAOPERAC, ULTNUMREFBAIXAEFET, ULTNUMSEQBAIXAEFET, ULTNUMREFACEITE, ULTNUMSEQACEITE, ULTNUMREFTERC, ULTNUMSEQTERC
		) 
		SELECT 
			1, T.NUMIDENTCDDA, T.CODIFSACADA, T.CODIFCEDENTE, 
			T.TIPOPESCEDENTE, T.CNPJ_CPF_CEDENTE, T.NOMECEDENTE, T.TIPOPESCEDENTEORI, T.CNPJ_CPF_CEDENTEORI, 
			T.NOMECEDENTEORI, T.ENDCEDENTEORI, T.CIDCEDENTEORI, T.UFCEDENTEORI, T.CEPCEDENTEORI, T.TIPOPESSACADO, 
			T.CNPJ_CPF_SACADO, T.NOMESACADO, T.ENDSACADO, T.CIDSACADO, T.UFSACADO, T.CEPSACADO, T.TIPOPESSACADOR, 
			CASE 
				WHEN LEN(T.CNPJ_CPF_SACADOR)> 14 
					THEN SUBSTRING (T.CNPJ_CPF_SACADOR, 2, 14) 
				ELSE T.CNPJ_CPF_SACADOR 
				END, 
			T.NOMESACADOR, T.CODCARTEIRA, T.CODMOEDACNAB, T.IDENTNOSSONUMERO, T.LINHADIGITAVEL, 
			T.DATAVENCIMENTO, T.VLRTITULO, T.SEUNUMERO, T.CODESPECIEDOC, T.DATAEMISSAO, T.QTDEDIASPROTESTO, 
			T.DATALIMPAGTO, T.TIPOPAGTO, T.INDTITULONEGOCIADO, T.VLRABATIMENTO, T.CODMORA, T.DATAMORA, T.VLRPERCMORA, 
			T.CODMULTA, T.DATAMULTA, T.VLRPERCMULTA, T.CODDESCONTO01, T.DATADESCONTO01, T.VLRPERCDESCONTO01, 
			T.CODDESCONTO02, T.DATADESCONTO02, T.VLRPERCDESCONTO02, T.CODDESCONTO03, T.DATADESCONTO03, 
			T.VLRPERCDESCONTO03, T.ACEITE, T.DATAACEITE, T.CODSITUACAO, T.TIPOBAIXA, T.SITPAGAMENTO, T.VLRMINTITULO, 
			T.VLRMAXTITULO, T.TIPOPESTERCEIRO, T.CNPJ_CPF_TERCEIRO, T.CODSISLEGADO, T.DTHRSITTITULO, 
			T.DATACALCULO, T.INDALTERAVALOR, T.TIPOCALCULO, T.NOMEFANTASIACEDENTE, T.NOMEFANTASIACEDENTEORI, T.NOMEFANTASIASACADO, T.NUMCODBARRAS, T.NUMPARCELA, 
			T.QTDPARCELA, T.INDBLOQUEIO, T.INDPARCIAL, T.QTDPAGTO, T.INDVALORPERC_MIN, T.INDVALORPERC_MAX, T.ISPBCEDENTE, T.TIPOAUTRECDIVERGENTE, 
			T.ISPBSACADA, T.CANALPAGTO, T.MEIOPAGTO, T.SITPAGAMENTOCIP, T.ULTNUMREFCADTIT, T.ULTNUMSEQCADTIT, T.ULTNUMREFBAIXAOPERAC, 
			T.ULTNUMSEQBAIXAOPERAC, T.ULTNUMREFBAIXAEFET, T.ULTNUMSEQBAIXAEFET, T.ULTNUMREFACEITE, T.ULTNUMSEQACEITE, T.ULTNUMREFTERC, T.ULTNUMSEQTERC 
		FROM TITULOS T WITH (NOLOCK), #TITULOS TEMP_TIT 
		WHERE T.NUMIDENTCDDA = TEMP_TIT.NUMIDENTCDDA 
		AND (@TIPOPESCEDENTE IS NULL 
			OR T.TIPOPESCEDENTE = @TIPOPESCEDENTE) 
		AND (@CNPJ_CPF_CEDENTE IS NULL 
			OR T.CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE) 
		AND (@DATAVENCIMENTOINI IS NULL 
			OR T.DATAVENCIMENTO > = @DATAVENCIMENTOINI) 
		AND (@DATAVENCIMENTOFIM IS NULL 
			OR T.DATAVENCIMENTO < = @DATAVENCIMENTOFIM) 
		/*-----------------------------------------------------------------------------------------------------------*/ 
		/* 29/04/2019 - ELIANE - MUDANDO AS REGRAS DE SELEÇÃO DE TÍTULOS QUE NÃO SÃO CARTÃO E PARA TÍTULOS DE CARTÃO */ 
		/* 03/11/2021 - ELIANE - ENCONTRADO AMBIENTE ONDE CODSITUACAO ESTÁ COM 2 DÍGITOS E COM 1 DÍGITO. RA 10916. */ 
		/*-----------------------------------------------------------------------------------------------------------*/ 
		AND ((T.CODESPECIEDOC <> '31' 
				AND T.CODSITUACAO IN ('1', '01') 
				AND T.SITPAGAMENTO IS NULL 
				AND T.TIPOBAIXA IS NULL /*TITULO_SIT_ABERTO*/) 
			OR (T.CODESPECIEDOC <> '31' 
				AND T.CODSITUACAO IN ('1', '01') 
				AND T.SITPAGAMENTO = '3' 
				AND T.TIPOBAIXA IS NULL /*TITULO_SIT_ABERTO*/) 
			OR (T.CODESPECIEDOC = '31' 
				AND T.CODSITUACAO IN ('1', '01') /*CARTÃO DE CREDITO - TITULO_SIT_ABERTO*/)) 
		/*-----------------------------------------------------------------------------------------------------------*/ 
		/* 29/04/2019 - ELIANE - MUDANDO AS REGRAS DE SELEÇÃO DE TÍTULOS QUE NÃO SÃO CARTÃO E PARA TÍTULOS DE CARTÃO */ 
		/*-----------------------------------------------------------------------------------------------------------*/ 
	END
	ELSE IF @CODCONDICAO IN ('BLOQUEADO PARA PAGAMENTO', '3') 
	BEGIN
		INSERT INTO #TEMP_TITULOS_FILTRO (
			TIPOREGISTRO, NUMIDENTCDDA, CODIFSACADA, CODIFCEDENTE, 
			TIPOPESCEDENTE, CNPJ_CPF_CEDENTE, NOMECEDENTE, TIPOPESCEDENTEORI, CNPJ_CPF_CEDENTEORI, 
			NOMECEDENTEORI, ENDCEDENTEORI, CIDCEDENTEORI, UFCEDENTEORI, CEPCEDENTEORI, TIPOPESSACADO, 
			CNPJ_CPF_SACADO, NOMESACADO, ENDSACADO, CIDSACADO, UFSACADO, CEPSACADO, TIPOPESSACADOR, 
			CNPJ_CPF_SACADOR, 
			NOMESACADOR, CODCARTEIRA, CODMOEDACNAB, IDENTNOSSONUMERO, LINHADIGITAVEL, 
			DATAVENCIMENTO, VLRTITULO, SEUNUMERO, CODESPECIEDOC, DATAEMISSAO, QTDEDIASPROTESTO, 
			DATALIMPAGTO, TIPOPAGTO, INDTITULONEGOCIADO, VLRABATIMENTO, CODMORA, DATAMORA, VLRPERCMORA, 
			CODMULTA, DATAMULTA, VLRPERCMULTA, CODDESCONTO01, DATADESCONTO01, VLRPERCDESCONTO01, 
			CODDESCONTO02, DATADESCONTO02, VLRPERCDESCONTO02, CODDESCONTO03, DATADESCONTO03, 
			VLRPERCDESCONTO03, ACEITE, DATAACEITE, CODSITUACAO, TIPOBAIXA, SITPAGAMENTO, VLRMINTITULO, 
			VLRMAXTITULO, TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO, CODSISLEGADO, DTHRSITTITULO, 
			DATACALCULO, INDALTERAVALOR, TIPOCALCULO, NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI, NOMEFANTASIASACADO, NUMCODBARRAS, NUMPARCELA, 
			QTDPARCELA, INDBLOQUEIO, INDPARCIAL, QTDPAGTO, INDVALORPERC_MIN, INDVALORPERC_MAX, ISPBCEDENTE, TIPOAUTRECDIVERGENTE, 
			ISPBSACADA, CANALPAGTO, MEIOPAGTO, SITPAGAMENTOCIP, ULTNUMREFCADTIT, ULTNUMSEQCADTIT, ULTNUMREFBAIXAOPERAC, 
			ULTNUMSEQBAIXAOPERAC, ULTNUMREFBAIXAEFET, ULTNUMSEQBAIXAEFET, ULTNUMREFACEITE, ULTNUMSEQACEITE, ULTNUMREFTERC, ULTNUMSEQTERC) 
		SELECT 
			1, T.NUMIDENTCDDA, T.CODIFSACADA, T.CODIFCEDENTE, 
			T.TIPOPESCEDENTE, T.CNPJ_CPF_CEDENTE, T.NOMECEDENTE, T.TIPOPESCEDENTEORI, T.CNPJ_CPF_CEDENTEORI, 
			T.NOMECEDENTEORI, T.ENDCEDENTEORI, T.CIDCEDENTEORI, T.UFCEDENTEORI, T.CEPCEDENTEORI, T.TIPOPESSACADO, 
			T.CNPJ_CPF_SACADO, T.NOMESACADO, T.ENDSACADO, T.CIDSACADO, T.UFSACADO, T.CEPSACADO, T.TIPOPESSACADOR, 
			CASE 
				WHEN LEN(T.CNPJ_CPF_SACADOR)> 14 
					THEN SUBSTRING (T.CNPJ_CPF_SACADOR, 2, 14) 
				ELSE T.CNPJ_CPF_SACADOR 
				END, 
			T.NOMESACADOR, T.CODCARTEIRA, T.CODMOEDACNAB, T.IDENTNOSSONUMERO, T.LINHADIGITAVEL, 
			T.DATAVENCIMENTO, T.VLRTITULO, T.SEUNUMERO, T.CODESPECIEDOC, T.DATAEMISSAO, T.QTDEDIASPROTESTO, 
			T.DATALIMPAGTO, T.TIPOPAGTO, T.INDTITULONEGOCIADO, T.VLRABATIMENTO, T.CODMORA, T.DATAMORA, T.VLRPERCMORA, 
			T.CODMULTA, T.DATAMULTA, T.VLRPERCMULTA, T.CODDESCONTO01, T.DATADESCONTO01, T.VLRPERCDESCONTO01, 
			T.CODDESCONTO02, T.DATADESCONTO02, T.VLRPERCDESCONTO02, T.CODDESCONTO03, T.DATADESCONTO03, 
			T.VLRPERCDESCONTO03, T.ACEITE, T.DATAACEITE, T.CODSITUACAO, T.TIPOBAIXA, T.SITPAGAMENTO, T.VLRMINTITULO, 
			T.VLRMAXTITULO, T.TIPOPESTERCEIRO, T.CNPJ_CPF_TERCEIRO, T.CODSISLEGADO, T.DTHRSITTITULO, 
			T.DATACALCULO, T.INDALTERAVALOR, T.TIPOCALCULO, T.NOMEFANTASIACEDENTE, T.NOMEFANTASIACEDENTEORI, T.NOMEFANTASIASACADO, T.NUMCODBARRAS, T.NUMPARCELA, 
			T.QTDPARCELA, T.INDBLOQUEIO, T.INDPARCIAL, T.QTDPAGTO, T.INDVALORPERC_MIN, T.INDVALORPERC_MAX, T.ISPBCEDENTE, T.TIPOAUTRECDIVERGENTE, 
			T.ISPBSACADA, T.CANALPAGTO, T.MEIOPAGTO, T.SITPAGAMENTOCIP, T.ULTNUMREFCADTIT, T.ULTNUMSEQCADTIT, T.ULTNUMREFBAIXAOPERAC, 
			T.ULTNUMSEQBAIXAOPERAC, T.ULTNUMREFBAIXAEFET, T.ULTNUMSEQBAIXAEFET, T.ULTNUMREFACEITE, T.ULTNUMSEQACEITE, T.ULTNUMREFTERC, T.ULTNUMSEQTERC 
		FROM TITULOS T WITH (NOLOCK), #TITULOS TEMP_TIT 
		WHERE 
		/*((T.CNPJ_CPF_SACADO IN (SELECT S.CNPJ_CPF_SACADO FROM SACELETRONICO S WHERE S.CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO AND S.SITUACAOSACADO = 1)) 
		OR T.CNPJ_CPF_SACADO IN (SELECT A.CNPJ_CPF_AGREGADO FROM AGREGADOS A WHERE A.CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO AND A.SITUACAOAGREGADO = 1) 
		OR T.CNPJ_CPF_TERCEIRO = @CNPJ_CPF_SACADO) */ 
		T.NUMIDENTCDDA = TEMP_TIT.NUMIDENTCDDA 
		AND (@TIPOPESCEDENTE IS NULL 
			OR T.TIPOPESCEDENTE = @TIPOPESCEDENTE) 
		AND (@CNPJ_CPF_CEDENTE IS NULL 
			OR T.CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE) 
		AND (@DATAVENCIMENTOINI IS NULL 
			OR T.DATAVENCIMENTO > = @DATAVENCIMENTOINI) 
		AND (@DATAVENCIMENTOFIM IS NULL 
			OR T.DATAVENCIMENTO < = @DATAVENCIMENTOFIM) 
		AND T.CODSITUACAO = 1 
		AND T.SITPAGAMENTO = 1 
		AND T.TIPOBAIXA IS NULL 
		AND T.CODSISLEGADO = @CODSISLEGADO /*TITULO_SIT_BLOQUEADO*/ 
	END
	ELSE IF @CODCONDICAO IN ('BAIXADO', '2') 
	BEGIN
		INSERT INTO #TEMP_TITULOS_FILTRO (
			TIPOREGISTRO, NUMIDENTCDDA, CODIFSACADA, CODIFCEDENTE, 
			TIPOPESCEDENTE, CNPJ_CPF_CEDENTE, NOMECEDENTE, TIPOPESCEDENTEORI, CNPJ_CPF_CEDENTEORI, 
			NOMECEDENTEORI, ENDCEDENTEORI, CIDCEDENTEORI, UFCEDENTEORI, CEPCEDENTEORI, TIPOPESSACADO, 
			CNPJ_CPF_SACADO, NOMESACADO, ENDSACADO, CIDSACADO, UFSACADO, CEPSACADO, TIPOPESSACADOR, 
			CNPJ_CPF_SACADOR, 
			NOMESACADOR, CODCARTEIRA, CODMOEDACNAB, IDENTNOSSONUMERO, LINHADIGITAVEL, 
			DATAVENCIMENTO, VLRTITULO, SEUNUMERO, CODESPECIEDOC, DATAEMISSAO, QTDEDIASPROTESTO, 
			DATALIMPAGTO, TIPOPAGTO, INDTITULONEGOCIADO, VLRABATIMENTO, CODMORA, DATAMORA, VLRPERCMORA, 
			CODMULTA, DATAMULTA, VLRPERCMULTA, CODDESCONTO01, DATADESCONTO01, VLRPERCDESCONTO01, 
			CODDESCONTO02, DATADESCONTO02, VLRPERCDESCONTO02, CODDESCONTO03, DATADESCONTO03, 
			VLRPERCDESCONTO03, ACEITE, DATAACEITE, CODSITUACAO, TIPOBAIXA, SITPAGAMENTO, VLRMINTITULO, 
			VLRMAXTITULO, TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO, CODSISLEGADO, DTHRSITTITULO, 
			DATACALCULO, INDALTERAVALOR, TIPOCALCULO, NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI, NOMEFANTASIASACADO, NUMCODBARRAS, NUMPARCELA, 
			QTDPARCELA, INDBLOQUEIO, INDPARCIAL, QTDPAGTO, INDVALORPERC_MIN, INDVALORPERC_MAX, ISPBCEDENTE, TIPOAUTRECDIVERGENTE, 
			ISPBSACADA, CANALPAGTO, MEIOPAGTO, SITPAGAMENTOCIP, ULTNUMREFCADTIT, ULTNUMSEQCADTIT, ULTNUMREFBAIXAOPERAC, 
			ULTNUMSEQBAIXAOPERAC, ULTNUMREFBAIXAEFET, ULTNUMSEQBAIXAEFET, ULTNUMREFACEITE, ULTNUMSEQACEITE, ULTNUMREFTERC, ULTNUMSEQTERC
		) 
		SELECT 
			1, T.NUMIDENTCDDA, T.CODIFSACADA, T.CODIFCEDENTE, 
			T.TIPOPESCEDENTE, T.CNPJ_CPF_CEDENTE, T.NOMECEDENTE, T.TIPOPESCEDENTEORI, T.CNPJ_CPF_CEDENTEORI, 
			T.NOMECEDENTEORI, T.ENDCEDENTEORI, T.CIDCEDENTEORI, T.UFCEDENTEORI, T.CEPCEDENTEORI, T.TIPOPESSACADO, 
			T.CNPJ_CPF_SACADO, T.NOMESACADO, T.ENDSACADO, T.CIDSACADO, T.UFSACADO, T.CEPSACADO, T.TIPOPESSACADOR, 
			CASE 
				WHEN LEN(T.CNPJ_CPF_SACADOR)> 14 
					THEN SUBSTRING (T.CNPJ_CPF_SACADOR, 2, 14) 
				ELSE T.CNPJ_CPF_SACADOR 
				END, 
			T.NOMESACADOR, T.CODCARTEIRA, T.CODMOEDACNAB, T.IDENTNOSSONUMERO, T.LINHADIGITAVEL, 
			T.DATAVENCIMENTO, T.VLRTITULO, T.SEUNUMERO, T.CODESPECIEDOC, T.DATAEMISSAO, T.QTDEDIASPROTESTO, 
			T.DATALIMPAGTO, T.TIPOPAGTO, T.INDTITULONEGOCIADO, T.VLRABATIMENTO, T.CODMORA, T.DATAMORA, T.VLRPERCMORA, 
			T.CODMULTA, T.DATAMULTA, T.VLRPERCMULTA, T.CODDESCONTO01, T.DATADESCONTO01, T.VLRPERCDESCONTO01, 
			T.CODDESCONTO02, T.DATADESCONTO02, T.VLRPERCDESCONTO02, T.CODDESCONTO03, T.DATADESCONTO03, 
			T.VLRPERCDESCONTO03, T.ACEITE, T.DATAACEITE, T.CODSITUACAO, T.TIPOBAIXA, T.SITPAGAMENTO, T.VLRMINTITULO, 
			T.VLRMAXTITULO, T.TIPOPESTERCEIRO, T.CNPJ_CPF_TERCEIRO, T.CODSISLEGADO, T.DTHRSITTITULO, 
			T.DATACALCULO, T.INDALTERAVALOR, T.TIPOCALCULO, T.NOMEFANTASIACEDENTE, T.NOMEFANTASIACEDENTEORI, T.NOMEFANTASIASACADO, T.NUMCODBARRAS, T.NUMPARCELA, 
			T.QTDPARCELA, T.INDBLOQUEIO, T.INDPARCIAL, T.QTDPAGTO, T.INDVALORPERC_MIN, T.INDVALORPERC_MAX, T.ISPBCEDENTE, T.TIPOAUTRECDIVERGENTE, 
			T.ISPBSACADA, T.CANALPAGTO, T.MEIOPAGTO, T.SITPAGAMENTOCIP, T.ULTNUMREFCADTIT, T.ULTNUMSEQCADTIT, T.ULTNUMREFBAIXAOPERAC, 
			T.ULTNUMSEQBAIXAOPERAC, T.ULTNUMREFBAIXAEFET, T.ULTNUMSEQBAIXAEFET, T.ULTNUMREFACEITE, T.ULTNUMSEQACEITE, T.ULTNUMREFTERC, T.ULTNUMSEQTERC 
		FROM TITULOS T WITH (NOLOCK), #TITULOS TEMP_TIT 
		WHERE /*((T.CNPJ_CPF_SACADO IN (SELECT S.CNPJ_CPF_SACADO FROM SACELETRONICO S WHERE S.CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO AND S.SITUACAOSACADO = 1)) 
		OR T.CNPJ_CPF_SACADO IN (SELECT A.CNPJ_CPF_AGREGADO FROM AGREGADOS A WHERE A.CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO AND A.SITUACAOAGREGADO = 1) 
		OR T.CNPJ_CPF_TERCEIRO = @CNPJ_CPF_SACADO) */ 
		T.NUMIDENTCDDA = TEMP_TIT.NUMIDENTCDDA 
		AND (@TIPOPESCEDENTE IS NULL 
			OR T.TIPOPESCEDENTE = @TIPOPESCEDENTE) 
		AND (@CNPJ_CPF_CEDENTE IS NULL 
			OR T.CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE) 
		AND (@DATAVENCIMENTOINI IS NULL 
			OR T.DATAVENCIMENTO > = @DATAVENCIMENTOINI) 
		AND (@DATAVENCIMENTOFIM IS NULL 
		OR T.DATAVENCIMENTO < = @DATAVENCIMENTOFIM) 
		AND T.CODSITUACAO <> 1 
		AND T.TIPOBAIXA IS NOT NULL /* TITULO_SIT_BAIXADO */ 
	END
	ELSE
	BEGIN 
		INSERT INTO #TEMP_TITULOS_FILTRO (
			TIPOREGISTRO, NUMIDENTCDDA, CODIFSACADA, CODIFCEDENTE, 
			TIPOPESCEDENTE, CNPJ_CPF_CEDENTE, NOMECEDENTE, TIPOPESCEDENTEORI, CNPJ_CPF_CEDENTEORI, 
			NOMECEDENTEORI, ENDCEDENTEORI, CIDCEDENTEORI, UFCEDENTEORI, CEPCEDENTEORI, TIPOPESSACADO, 
			CNPJ_CPF_SACADO, NOMESACADO, ENDSACADO, CIDSACADO, UFSACADO, CEPSACADO, TIPOPESSACADOR, 
			CNPJ_CPF_SACADOR, 
			NOMESACADOR, CODCARTEIRA, CODMOEDACNAB, IDENTNOSSONUMERO, LINHADIGITAVEL, 
			DATAVENCIMENTO, VLRTITULO, SEUNUMERO, CODESPECIEDOC, DATAEMISSAO, QTDEDIASPROTESTO, 
			DATALIMPAGTO, TIPOPAGTO, INDTITULONEGOCIADO, VLRABATIMENTO, CODMORA, DATAMORA, VLRPERCMORA, 
			CODMULTA, DATAMULTA, VLRPERCMULTA, CODDESCONTO01, DATADESCONTO01, VLRPERCDESCONTO01, 
			CODDESCONTO02, DATADESCONTO02, VLRPERCDESCONTO02, CODDESCONTO03, DATADESCONTO03, 
			VLRPERCDESCONTO03, ACEITE, DATAACEITE, CODSITUACAO, TIPOBAIXA, SITPAGAMENTO, VLRMINTITULO, 
			VLRMAXTITULO, TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO, CODSISLEGADO, DTHRSITTITULO, 
			DATACALCULO, INDALTERAVALOR, TIPOCALCULO, NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI, NOMEFANTASIASACADO, NUMCODBARRAS, NUMPARCELA, 
			QTDPARCELA, INDBLOQUEIO, INDPARCIAL, QTDPAGTO, INDVALORPERC_MIN, INDVALORPERC_MAX, ISPBCEDENTE, TIPOAUTRECDIVERGENTE, 
			ISPBSACADA, CANALPAGTO, MEIOPAGTO, SITPAGAMENTOCIP, ULTNUMREFCADTIT, ULTNUMSEQCADTIT, ULTNUMREFBAIXAOPERAC, 
			ULTNUMSEQBAIXAOPERAC, ULTNUMREFBAIXAEFET, ULTNUMSEQBAIXAEFET, ULTNUMREFACEITE, ULTNUMSEQACEITE, ULTNUMREFTERC, ULTNUMSEQTERC
		) 	
		SELECT 
			1, T.NUMIDENTCDDA, T.CODIFSACADA, T.CODIFCEDENTE, 
			T.TIPOPESCEDENTE, T.CNPJ_CPF_CEDENTE, T.NOMECEDENTE, T.TIPOPESCEDENTEORI, T.CNPJ_CPF_CEDENTEORI, 
			T.NOMECEDENTEORI, T.ENDCEDENTEORI, T.CIDCEDENTEORI, T.UFCEDENTEORI, T.CEPCEDENTEORI, T.TIPOPESSACADO, 
			T.CNPJ_CPF_SACADO, T.NOMESACADO, T.ENDSACADO, T.CIDSACADO, T.UFSACADO, T.CEPSACADO, T.TIPOPESSACADOR, 
			CASE 
				WHEN LEN(T.CNPJ_CPF_SACADOR)> 14 
					THEN SUBSTRING (T.CNPJ_CPF_SACADOR, 2, 14) 
				ELSE T.CNPJ_CPF_SACADOR 
				END, 
			T.NOMESACADOR, T.CODCARTEIRA, T.CODMOEDACNAB, T.IDENTNOSSONUMERO, T.LINHADIGITAVEL, 
			T.DATAVENCIMENTO, T.VLRTITULO, T.SEUNUMERO, T.CODESPECIEDOC, T.DATAEMISSAO, T.QTDEDIASPROTESTO, 
			T.DATALIMPAGTO, T.TIPOPAGTO, T.INDTITULONEGOCIADO, T.VLRABATIMENTO, T.CODMORA, T.DATAMORA, T.VLRPERCMORA, 
			T.CODMULTA, T.DATAMULTA, T.VLRPERCMULTA, T.CODDESCONTO01, T.DATADESCONTO01, T.VLRPERCDESCONTO01, 
			T.CODDESCONTO02, T.DATADESCONTO02, T.VLRPERCDESCONTO02, T.CODDESCONTO03, T.DATADESCONTO03, 
			T.VLRPERCDESCONTO03, T.ACEITE, T.DATAACEITE, T.CODSITUACAO, T.TIPOBAIXA, T.SITPAGAMENTO, T.VLRMINTITULO, 
			T.VLRMAXTITULO, T.TIPOPESTERCEIRO, T.CNPJ_CPF_TERCEIRO, T.CODSISLEGADO, T.DTHRSITTITULO, 
			T.DATACALCULO, T.INDALTERAVALOR, T.TIPOCALCULO, T.NOMEFANTASIACEDENTE, T.NOMEFANTASIACEDENTEORI, T.NOMEFANTASIASACADO, T.NUMCODBARRAS, T.NUMPARCELA, 
			T.QTDPARCELA, T.INDBLOQUEIO, T.INDPARCIAL, T.QTDPAGTO, T.INDVALORPERC_MIN, T.INDVALORPERC_MAX, T.ISPBCEDENTE, T.TIPOAUTRECDIVERGENTE, 
			T.ISPBSACADA, T.CANALPAGTO, T.MEIOPAGTO, T.SITPAGAMENTOCIP, T.ULTNUMREFCADTIT, T.ULTNUMSEQCADTIT, T.ULTNUMREFBAIXAOPERAC, 
			T.ULTNUMSEQBAIXAOPERAC, T.ULTNUMREFBAIXAEFET, T.ULTNUMSEQBAIXAEFET, T.ULTNUMREFACEITE, T.ULTNUMSEQACEITE, T.ULTNUMREFTERC, T.ULTNUMSEQTERC 
		FROM TITULOS T WITH (NOLOCK), #TITULOS TEMP_TIT 
		WHERE /*((T.CNPJ_CPF_SACADO IN (SELECT S.CNPJ_CPF_SACADO FROM SACELETRONICO S WHERE S.CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO AND S.SITUACAOSACADO = 1)) 
		OR T.CNPJ_CPF_SACADO IN (SELECT A.CNPJ_CPF_AGREGADO FROM AGREGADOS A WHERE A.CNPJ_CPF_SACADO = @CNPJ_CPF_SACADO AND A.SITUACAOAGREGADO = 1) 
		OR T.CNPJ_CPF_TERCEIRO = @CNPJ_CPF_SACADO) */ 
		T.NUMIDENTCDDA = TEMP_TIT.NUMIDENTCDDA 
		AND (@TIPOPESCEDENTE IS NULL 
			OR T.TIPOPESCEDENTE = @TIPOPESCEDENTE) 
		AND (@CNPJ_CPF_CEDENTE IS NULL 
			OR T.CNPJ_CPF_CEDENTE = @CNPJ_CPF_CEDENTE) 
		AND (@DATAVENCIMENTOINI IS NULL 
			OR T.DATAVENCIMENTO > = @DATAVENCIMENTOINI) 
		AND (@DATAVENCIMENTOFIM IS NULL 
			OR T.DATAVENCIMENTO < = @DATAVENCIMENTOFIM) 
		AND (T.SITPAGAMENTO IS NULL 
			OR (T.SITPAGAMENTO IS NOT NULL 
			AND T.CODSISLEGADO = @CODSISLEGADO)) 
	END 

	CREATE NONCLUSTERED INDEX IX_01 ON #TEMP_TITULOS_FILTRO (TIPOREGISTRO) INCLUDE (NUMIDENTCDDA, CNPJ_CPF_SACADO, SEQFATURA) 
 
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		--MENSAGEM 
		SEQMENSAGEM, TEXTO
	) 
	SELECT 
		T.NUMIDENTCDDA, 2, T.CNPJ_CPF_SACADO, 
		M.SEQMENSAGEM, M.TEXTO 
	FROM #TEMP_TITULOS_FILTRO T 
	INNER JOIN MENSAGENS M (NOLOCK) 
		ON (T.NUMIDENTCDDA = M.NUMIDENTCDDA) 
	WHERE T.TIPOREGISTRO = 1 

	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		--NOTA FISCAL 
		NUMNOTAFISCAL, DATAEMISSAONOTA, VLRNOTAFISCAL
	) 
	SELECT 
		T.NUMIDENTCDDA, 4, T.CNPJ_CPF_SACADO, 
		N.NUMNOTAFISCAL, N.DATAEMISSAO, N.VLRNOTAFISCAL 
	FROM #TEMP_TITULOS_FILTRO T 
	INNER JOIN NOTAS_FISCAIS N (NOLOCK) 
		ON (T.NUMIDENTCDDA = N.NUMIDENTCDDA) 
	WHERE T.TIPOREGISTRO = 1 
 
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		--ANEXO FATURA 
		SEQFATURA, CODMODELO
	) 
	SELECT 
		T.NUMIDENTCDDA, 5, T.CNPJ_CPF_SACADO, 
		A.SEQFATURA, A.CODMODELO 
	FROM #TEMP_TITULOS_FILTRO T 
	INNER JOIN ANEXO_FATURA A (NOLOCK) 
		ON (T.NUMIDENTCDDA = A.NUMIDENTCDDA) 
	WHERE T.TIPOREGISTRO = 1 
 
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		--MODELO (ANEXO FATURA) 
		SEQFATURA, SEQMODELO, CABECALHO, TPDADOS
	) 
	SELECT 
		T.NUMIDENTCDDA, 6, T.CNPJ_CPF_SACADO, 
		M.SEQFATURA, M.SEQMODELO, M.CABECALHO, M.TPDADOS 
	FROM #TEMP_TITULOS_FILTRO T 
	INNER JOIN MODELO M (NOLOCK) 
		ON (T.NUMIDENTCDDA = M.NUMIDENTCDDA 
		AND T.SEQFATURA = M.SEQFATURA) 
	WHERE T.TIPOREGISTRO = 5 
 
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		--DETALHE ANTES DO CABECALHO (ANEXO FATURA) 
		SEQFATURA, SEQDETANTES, TEXTO
	) 
	SELECT 
		T.NUMIDENTCDDA, 7, T.CNPJ_CPF_SACADO, 
		D.SEQFATURA, D.SEQDETANTES, D.TEXTO 
	FROM #TEMP_TITULOS_FILTRO T 
	INNER JOIN DET_ANTES_CABEC D (NOLOCK) 
		ON (T.NUMIDENTCDDA = D.NUMIDENTCDDA 
		AND T.SEQFATURA = D.SEQFATURA) 
	WHERE T.TIPOREGISTRO = 5 
 
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		--DETALHE APOS CABECALHO (ANEXO FATURA) 
		SEQFATURA, SEQDETDEPOIS, TEXTO
	) 
	SELECT 
		T.NUMIDENTCDDA, 8, T.CNPJ_CPF_SACADO, 
		D.SEQFATURA, D.SEQDETAPOS, D.TEXTO 
	FROM #TEMP_TITULOS_FILTRO T 
	INNER JOIN DET_APOS_CABEC D (NOLOCK) 
		ON (T.NUMIDENTCDDA = D.NUMIDENTCDDA 
		AND T.SEQFATURA = D.SEQFATURA) 
	WHERE T.TIPOREGISTRO = 5 
 
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		--BAIXA OPERACIONAL 
		NUMIDENTCBAIXAOPERAC, NUMREFBAIXAOPERAC, TIPOBAIXAOPERACIONAL, DATABAIXAOPERACIONAL, 
		--13/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOMEPORTADOR E DATAHORARECBTTITULO (CATÁLOGO 5.03 E 5.04)
		VLRBAIXAOPERACIONAL, TIPOPESPORTADOR, CNPJ_CPF_PORTADOR, NOME_PORTADOR,
		--29/03/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
		TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO,
		AGENCIARECEBEDORA, DATAHORARECBTTITULO, DATAHORACANCEL, INDCONTINGENCIA, 
		ORIGEMCANCELAMENTO
	) 
	SELECT 
		#TEMP_TITULOS_FILTRO.NUMIDENTCDDA, 9, #TEMP_TITULOS_FILTRO.CNPJ_CPF_SACADO, 
		BAIXAS_OPERACIONAIS.NUMIDENTCBAIXAOPERAC, BAIXAS_OPERACIONAIS.NUMREFBAIXAOPERAC, BAIXAS_OPERACIONAIS.TIPOBAIXA, BAIXAS_OPERACIONAIS.DATABAIXA, 
		--13/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOMEPORTADOR E DATAHORARECBTTITULO (CATÁLOGO 5.03 E 5.04)
		BAIXAS_OPERACIONAIS.VLRBAIXA, BAIXAS_OPERACIONAIS.TIPOPESPORTADOR, BAIXAS_OPERACIONAIS.CNPJ_CPF_PORTADOR, BAIXAS_OPERACIONAIS.NOME_PORTADOR,
		--29/03/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
		BAIXAS_OPERACIONAIS.TIPOPESAGREGADOR, BAIXAS_OPERACIONAIS.CNPJ_CPF_AGREGADOR, BAIXAS_OPERACIONAIS.NOMEAGREGADOR, BAIXAS_OPERACIONAIS.ISPBINICIADORPAGTO,
		BAIXAS_OPERACIONAIS.AGENCIARECEBEDORA, BAIXAS_OPERACIONAIS.DATAHORARECBTTITULO, BAIXAS_OPERACIONAIS.DATAHORACANCEL, BAIXAS_OPERACIONAIS.INDCONTINGENCIA, 
		BAIXAS_OPERACIONAIS.ORIGEMCANCELAMENTO 
	FROM #TEMP_TITULOS_FILTRO 
	INNER JOIN BAIXAS_OPERACIONAIS (NOLOCK) 
		ON (#TEMP_TITULOS_FILTRO.NUMIDENTCDDA = BAIXAS_OPERACIONAIS.NUMIDENTCDDA) 
	WHERE #TEMP_TITULOS_FILTRO.TIPOREGISTRO = 1 
 
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		--BAIXA EFETIVA 
		NUMIDENTCBAIXAEFET, NUMREFBAIXAEFET, DATABAIXAEFETIVA, VLRBAIXAEFETIVA, TIPOBAIXAEFETIVA
	) 
	SELECT 
		T.NUMIDENTCDDA, 10, T.CNPJ_CPF_SACADO, 
		BAIXAS.NUMIDENTCBAIXAEFET, BAIXAS.NUMREFBAIXAEFET, BAIXAS.DATABAIXA, BAIXAS.VLRBAIXA, BAIXAS.TIPOBAIXA 
	FROM #TEMP_TITULOS_FILTRO T 
	INNER JOIN BAIXAS_EFETIVAS BAIXAS (NOLOCK) 
		ON (T.NUMIDENTCDDA = BAIXAS.NUMIDENTCDDA) 
	WHERE T.TIPOREGISTRO = 1 
 
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		--CALCULOS 
		DATACALCULO, VLRMORA, VLRMULTA, VLRDESCONTO, VLRCOBRAR) 
	SELECT 
		T.NUMIDENTCDDA, 11, T.CNPJ_CPF_SACADO, 
		CALCULOS.DATACALCULO, CALCULOS.VLRMORA, CALCULOS.VLRMULTA, CALCULOS.VLRDESCONTO, CALCULOS.VLRCOBRAR 
	FROM #TEMP_TITULOS_FILTRO T 
	INNER JOIN CALCULOS (NOLOCK) 
		ON (T.NUMIDENTCDDA = CALCULOS.NUMIDENTCDDA) 
	WHERE T.TIPOREGISTRO = 1 
 
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		--TERCEIROS 
		TIPOPESTERC, CNPJ_CPF_TERC, NUMIDENTCTERC, NUMREFTERC, 
		TIPOPESAUTORIZADOR, CNPJ_CPF_AUTORIZADOR
	) 
	SELECT 
		T.NUMIDENTCDDA, 12, T.CNPJ_CPF_SACADO, 
		--TERCEIROS 
		TERCEIROS.TIPOPESTERC, TERCEIROS.CNPJ_CPF_TERC, TERCEIROS.NUMIDENTCTERC, TERCEIROS.NUMREFTERC, 
		TERCEIROS.TIPOPESAUTORIZADOR, TERCEIROS.CNPJ_CPF_AUTORIZADOR 
	FROM #TEMP_TITULOS_FILTRO T 
	INNER JOIN TERCEIROS (NOLOCK) 
		ON (T.NUMIDENTCDDA = TERCEIROS.NUMIDENTCDDA) 
	WHERE T.TIPOREGISTRO = 1 
 
	IF @P_ORDEM = 'C' 
	BEGIN
		SELECT 
			TIPOREGISTRO, NUMIDENTCDDA, CODIFSACADA, CODIFCEDENTE, 
			TIPOPESCEDENTE, CNPJ_CPF_CEDENTE, NOMECEDENTE, TIPOPESCEDENTEORI, 
			CNPJ_CPF_CEDENTEORI, NOMECEDENTEORI, ENDCEDENTEORI, CIDCEDENTEORI, 
			UFCEDENTEORI, CEPCEDENTEORI, TIPOPESSACADO, CNPJ_CPF_SACADO, 
			NOMESACADO, ENDSACADO, CIDSACADO, UFSACADO, 
			CEPSACADO, TIPOPESSACADOR, CNPJ_CPF_SACADOR, NOMESACADOR, 
			CODCARTEIRA, CODMOEDACNAB, IDENTNOSSONUMERO, LINHADIGITAVEL, 
			DATAVENCIMENTO, VLRTITULO, SEUNUMERO, CODESPECIEDOC, 
			DATAEMISSAO, QTDEDIASPROTESTO, DATALIMPAGTO, TIPOPAGTO, 
			INDTITULONEGOCIADO, VLRABATIMENTO, CODMORA, DATAMORA, 
			VLRPERCMORA, CODMULTA, DATAMULTA, VLRPERCMULTA, 
			CODDESCONTO01, DATADESCONTO01, VLRPERCDESCONTO01, CODDESCONTO02, 
			DATADESCONTO02, VLRPERCDESCONTO02, CODDESCONTO03, DATADESCONTO03, 
			VLRPERCDESCONTO03, ACEITE, DATAACEITE, CODSITUACAO, 
			TIPOBAIXA, SITPAGAMENTO, VLRMINTITULO, VLRMAXTITULO, 
			TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO, CODSISLEGADO, DTHRSITTITULO, 
			INDALTERAVALOR, TIPOCALCULO, NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI, 
			NOMEFANTASIASACADO, NUMCODBARRAS, NUMPARCELA, QTDPARCELA, 
			INDBLOQUEIO, INDPARCIAL, QTDPAGTO, INDVALORPERC_MIN, 
			INDVALORPERC_MAX, ISPBCEDENTE, TIPOAUTRECDIVERGENTE, ISPBSACADA, 
			CANALPAGTO, MEIOPAGTO, SITPAGAMENTOCIP, ULTNUMREFCADTIT, 
			ULTNUMSEQCADTIT, ULTNUMREFBAIXAOPERAC, ULTNUMSEQBAIXAOPERAC, ULTNUMREFBAIXAEFET, 
			ULTNUMSEQBAIXAEFET, ULTNUMREFACEITE, ULTNUMSEQACEITE, ULTNUMREFTERC, 
			ULTNUMSEQTERC, SEQMENSAGEM, TEXTO, SEQFATURA, 
			CODMODELO, SEQDETANTES, SEQDETDEPOIS, CABECALHO, 
			TPDADOS, SEQMODELO, NUMNOTAFISCAL, VLRNOTAFISCAL, 
			DATAEMISSAONOTA, NUMIDENTCBAIXAOPERAC, NUMREFBAIXAOPERAC, TIPOBAIXAOPERACIONAL, 
			DATABAIXAOPERACIONAL, VLRBAIXAOPERACIONAL, TIPOPESPORTADOR, CNPJ_CPF_PORTADOR, 
			--13/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOMEPORTADOR E DATAHORARECBTTITULO (CATÁLOGO 5.03 E 5.04)
			NOME_PORTADOR, 
			--29/03/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
			TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO,
			AGENCIARECEBEDORA, 
			DATAHORARECBTTITULO, DATAHORACANCEL, INDCONTINGENCIA, 
			ORIGEMCANCELAMENTO, NUMIDENTCBAIXAEFET, NUMREFBAIXAEFET, DATABAIXAEFETIVA, 
			VLRBAIXAEFETIVA, TIPOBAIXAEFETIVA, DATACALCULO, VLRMORA, 
			VLRMULTA, VLRDESCONTO, VLRCOBRAR, TIPOPESTERC, 
			CNPJ_CPF_TERC, NUMIDENTCTERC, NUMREFTERC, TIPOPESAUTORIZADOR, 
			CNPJ_CPF_AUTORIZADOR 
		FROM #TEMP_TITULOS_FILTRO 
		ORDER BY CNPJ_CPF_SACADO, NUMIDENTCDDA, TIPOREGISTRO, SEQFATURA, SEQMENSAGEM, SEQDETANTES, SEQDETDEPOIS, NUMNOTAFISCAL, DATACALCULO 
	END
	ELSE
	BEGIN 
		SELECT 
			TIPOREGISTRO, NUMIDENTCDDA, CODIFSACADA, CODIFCEDENTE, 
			TIPOPESCEDENTE, CNPJ_CPF_CEDENTE, NOMECEDENTE, TIPOPESCEDENTEORI, 
			CNPJ_CPF_CEDENTEORI, NOMECEDENTEORI, ENDCEDENTEORI, CIDCEDENTEORI, 
			UFCEDENTEORI, CEPCEDENTEORI, TIPOPESSACADO, CNPJ_CPF_SACADO, 
			NOMESACADO, ENDSACADO, CIDSACADO, UFSACADO, 
			CEPSACADO, TIPOPESSACADOR, CNPJ_CPF_SACADOR, NOMESACADOR, 
			CODCARTEIRA, CODMOEDACNAB, IDENTNOSSONUMERO, LINHADIGITAVEL, 
			DATAVENCIMENTO, VLRTITULO, SEUNUMERO, CODESPECIEDOC, 
			DATAEMISSAO, QTDEDIASPROTESTO, DATALIMPAGTO, TIPOPAGTO, 
			INDTITULONEGOCIADO, VLRABATIMENTO, CODMORA, DATAMORA, 
			VLRPERCMORA, CODMULTA, DATAMULTA, VLRPERCMULTA, 
			CODDESCONTO01, DATADESCONTO01, VLRPERCDESCONTO01, CODDESCONTO02, 
			DATADESCONTO02, VLRPERCDESCONTO02, CODDESCONTO03, DATADESCONTO03, 
			VLRPERCDESCONTO03, ACEITE, DATAACEITE, CODSITUACAO, 
			TIPOBAIXA, SITPAGAMENTO, VLRMINTITULO, VLRMAXTITULO, 
			TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO, CODSISLEGADO, DTHRSITTITULO, 
			INDALTERAVALOR, TIPOCALCULO, NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI, 
			NOMEFANTASIASACADO, NUMCODBARRAS, NUMPARCELA, QTDPARCELA, 
			INDBLOQUEIO, INDPARCIAL, QTDPAGTO, INDVALORPERC_MIN, 
			INDVALORPERC_MAX, ISPBCEDENTE, TIPOAUTRECDIVERGENTE, ISPBSACADA, 
			CANALPAGTO, MEIOPAGTO, SITPAGAMENTOCIP, ULTNUMREFCADTIT, 
			ULTNUMSEQCADTIT, ULTNUMREFBAIXAOPERAC, ULTNUMSEQBAIXAOPERAC, ULTNUMREFBAIXAEFET, 
			ULTNUMSEQBAIXAEFET, ULTNUMREFACEITE, ULTNUMSEQACEITE, ULTNUMREFTERC, 
			ULTNUMSEQTERC, SEQMENSAGEM, TEXTO, SEQFATURA, 
			CODMODELO, SEQDETANTES, SEQDETDEPOIS, CABECALHO, 
			TPDADOS, SEQMODELO, NUMNOTAFISCAL, VLRNOTAFISCAL, 
			DATAEMISSAONOTA, NUMIDENTCBAIXAOPERAC, NUMREFBAIXAOPERAC, TIPOBAIXAOPERACIONAL, 
			DATABAIXAOPERACIONAL, VLRBAIXAOPERACIONAL, TIPOPESPORTADOR, CNPJ_CPF_PORTADOR, 
			--13/07/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DOS CAMPOS NOMEPORTADOR E DATAHORARECBTTITULO (CATÁLOGO 5.03 E 5.04)
			NOME_PORTADOR, 
			--29/03/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
			TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO,
			AGENCIARECEBEDORA, 
			DATAHORARECBTTITULO, DATAHORACANCEL, INDCONTINGENCIA, 
			ORIGEMCANCELAMENTO, NUMIDENTCBAIXAEFET, NUMREFBAIXAEFET, DATABAIXAEFETIVA, 
			VLRBAIXAEFETIVA, TIPOBAIXAEFETIVA, DATACALCULO, VLRMORA, 
			VLRMULTA, VLRDESCONTO, VLRCOBRAR, TIPOPESTERC, 
			CNPJ_CPF_TERC, NUMIDENTCTERC, NUMREFTERC, TIPOPESAUTORIZADOR, 
			CNPJ_CPF_AUTORIZADOR 
		FROM #TEMP_TITULOS_FILTRO 
		ORDER BY CNPJ_CPF_SACADO, NUMIDENTCDDA, TIPOREGISTRO DESC, SEQFATURA, SEQMENSAGEM, SEQDETANTES, SEQDETDEPOIS, NUMNOTAFISCAL, DATACALCULO 
	END
END 
GO

INSERT INTO VERSAO_SISTEMA 
(
	[VERSAO], 
	[NOMESCRIPT], 
	[CODUSUARIO], 
	[DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_PESQUISA_TITULO_POR_SACADO', 
	SYSTEM_USER, 
	GETDATE() 
GO
