USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME = 'SP_PESQUISA_TITULO_POR_NUMCODBARRAS')
BEGIN
	EXEC ('CREATE PROCEDURE DBO.SP_PESQUISA_TITULO_POR_NUMCODBARRAS AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE DBO.SP_PESQUISA_TITULO_POR_NUMCODBARRAS (
	@P_NUMCODBARRAS VARCHAR (44) = NULL
)
AS
BEGIN
	/*
		09/08/2021 - RFAQUINI - CRIAÇÃO DA PROCEDURE - ITM - SOL. 77377
		
		LASILVA 15-12-2022 - ACRESCENTADO COLUNAS NOME_PORTADOR E DATAHORARECBTTITULO. AO REALIZAR A CONSULTA DO TÍTULO ESTAVAM DANDO INVÁLIDAS.   
		
		28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)
		
		#TEMP_TITULOS_FILTRO.TIPOREGISTRO
		1 - TITULOS
		2 - MENSAGEM
		3 - (NÃO EXISTE)
		4 - NOTA FISCAL
		5 - ANEXO FATURA
		6 - MODELO (ANEXO FATURA)
		7 - DETALHE ANTES DO CABEÇALHO (ANEXO FATURA)
		8 - DETALHE APÓS CABEÇALHO (ANEXO FATURA) 
		9 - BAIXA OPERACIONAL
		10 - BAIXA EFETIVA
		11 - CALCULOS
		12 - TERCEIROS

		EXEC SP_PESQUISA_TITULO_POR_NUMCODBARRAS '07793753100002839150001112000000500028547547' --9; N TIPOREGISTRO = 1
		EXEC SP_PESQUISA_TITULO_POR_NUMCODBARRAS '39999100000251000991805254612100320006700001'	--62; N TIPOREGISTROS
	*/

	IF (SELECT OBJECT_ID('TEMPDB..#TEMP_TITULOS_FILTRO')) IS NOT NULL 
	BEGIN
		DROP TABLE #TEMP_TITULOS_FILTRO
	END
	
	IF (SELECT OBJECT_ID('TEMPDB..#TITULOS')) IS NOT NULL 
	BEGIN
		DROP TABLE #TITULOS
	END

	DECLARE	@NUMCODBARRAS VARCHAR (44)

	SELECT  @P_NUMCODBARRAS = CASE 
								WHEN @P_NUMCODBARRAS = '' 
									THEN NULL 
								ELSE @P_NUMCODBARRAS 
								END

	SELECT  @NUMCODBARRAS = RTRIM (@P_NUMCODBARRAS)

	SELECT 99 	
		TIPOREGISTRO, 
		CONVERT(NUMERIC(19, 0), NULL) NUMIDENTCDDA, 
		CONVERT (CHAR(3), NULL) CODIFSACADA, 
		CONVERT (CHAR(3), NULL) CODIFCEDENTE, 
		CONVERT (CHAR(1), NULL) TIPOPESCEDENTE, 
		CONVERT (VARCHAR(14), NULL) CNPJ_CPF_CEDENTE, 
		CONVERT (VARCHAR(50), NULL) NOMECEDENTE, 
		CONVERT (CHAR(1), NULL) TIPOPESCEDENTEORI, 
		CONVERT (VARCHAR(14), NULL) CNPJ_CPF_CEDENTEORI, 
		CONVERT (VARCHAR(50), NULL) NOMECEDENTEORI, 
		CONVERT (VARCHAR(50), NULL) ENDCEDENTEORI, 
		CONVERT (VARCHAR(50), NULL) CIDCEDENTEORI, 
		CONVERT (CHAR(2), NULL) UFCEDENTEORI, 
		CONVERT (CHAR(8), NULL) CEPCEDENTEORI, 
		CONVERT (CHAR(1), NULL) TIPOPESSACADO, 
		CONVERT (VARCHAR(14), NULL) CNPJ_CPF_SACADO, 
		CONVERT (VARCHAR(50), NULL) NOMESACADO, 
		CONVERT (VARCHAR(50), NULL) ENDSACADO, 
		CONVERT (VARCHAR(50), NULL) CIDSACADO, 
		CONVERT (CHAR(2), NULL) UFSACADO, 
		CONVERT (CHAR(8), NULL) CEPSACADO, 
		CONVERT (CHAR(1), NULL) TIPOPESSACADOR, 
		CONVERT (VARCHAR(14), NULL) CNPJ_CPF_SACADOR, 
		CONVERT (VARCHAR(50), NULL) NOMESACADOR, 
		CONVERT (CHAR(1), NULL) CODCARTEIRA, 
		CONVERT (CHAR(2), NULL) CODMOEDACNAB, 
		CONVERT (VARCHAR(20), NULL) IDENTNOSSONUMERO, 
		CONVERT (VARCHAR(47), NULL) LINHADIGITAVEL, 
		CONVERT (DATETIME, NULL) DATAVENCIMENTO, 
		CONVERT (NUMERIC(19, 5), NULL) VLRTITULO, 
		CONVERT (VARCHAR(15), NULL) SEUNUMERO, 
		CONVERT (CHAR(2), NULL) CODESPECIEDOC, 
		CONVERT (DATETIME, NULL) DATAEMISSAO, 
		CONVERT (INT, NULL) QTDEDIASPROTESTO, 
		CONVERT (DATETIME, NULL) DATALIMPAGTO, 
		CONVERT (INT, NULL) TIPOPAGTO, 
		CONVERT (CHAR(1), NULL) INDTITULONEGOCIADO, 
		CONVERT (NUMERIC(19, 5), NULL) VLRABATIMENTO, 
		CONVERT (CHAR(1), NULL) CODMORA, 
		CONVERT (DATETIME, NULL) DATAMORA, 
		CONVERT (NUMERIC(19, 5), NULL) VLRPERCMORA, 
		CONVERT (CHAR(1), NULL) CODMULTA, 
		CONVERT (DATETIME, NULL) DATAMULTA, 
		CONVERT (NUMERIC(19, 5), NULL) VLRPERCMULTA, 
		CONVERT (CHAR(1), NULL) CODDESCONTO01, 
		CONVERT (DATETIME, NULL) DATADESCONTO01, 
		CONVERT (NUMERIC(19, 5), NULL) VLRPERCDESCONTO01, 
		CONVERT (CHAR(1), NULL) CODDESCONTO02, 
		CONVERT (DATETIME, NULL) DATADESCONTO02, 
		CONVERT (NUMERIC(19, 5), NULL) VLRPERCDESCONTO02, 
		CONVERT (CHAR(1), NULL) CODDESCONTO03, 
		CONVERT (DATETIME, NULL) DATADESCONTO03, 
		CONVERT (NUMERIC(19, 5), NULL) VLRPERCDESCONTO03, 
		CONVERT (CHAR(1), NULL) ACEITE, 
		CONVERT (DATETIME, NULL) DATAACEITE, 
		CONVERT (CHAR(2), NULL) CODSITUACAO, 
		--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)
		CONVERT (VARCHAR(2), NULL) TIPOBAIXA, 
		CONVERT (CHAR(1), NULL) SITPAGAMENTO, 
		CONVERT (NUMERIC(19, 5), NULL) VLRMINTITULO, 
		CONVERT (NUMERIC(19, 5), NULL) VLRMAXTITULO, 
		CONVERT (CHAR(1), NULL) TIPOPESTERCEIRO, 
		CONVERT (VARCHAR(14), NULL) CNPJ_CPF_TERCEIRO, 
		CONVERT (VARCHAR(10), NULL) CODSISLEGADO, 
		CONVERT (DATETIME, NULL) DTHRSITTITULO, 
		CONVERT (CHAR(1), NULL) INDALTERAVALOR, 
		CONVERT (CHAR(2), NULL) TIPOCALCULO, 
		CONVERT (VARCHAR(80), NULL) NOMEFANTASIACEDENTE, 
		CONVERT (VARCHAR(80), NULL) NOMEFANTASIACEDENTEORI, 
		CONVERT (VARCHAR(80), NULL) NOMEFANTASIASACADO, 
		CONVERT (VARCHAR(44), NULL) NUMCODBARRAS, 
		CONVERT (INT, NULL) NUMPARCELA, 
		CONVERT (INT, NULL) QTDPARCELA, 
		CONVERT (CHAR(1), NULL) INDBLOQUEIO, 
		CONVERT (CHAR(1), NULL) INDPARCIAL, 
		CONVERT (INT, NULL)  QTDPAGTO, 
		CONVERT (CHAR(1), NULL) INDVALORPERC_MIN, 
		CONVERT (CHAR(1), NULL) INDVALORPERC_MAX, 
		CONVERT (VARCHAR(8), NULL) ISPBCEDENTE, 
		CONVERT (CHAR(1), NULL) TIPOAUTRECDIVERGENTE, 
		CONVERT (VARCHAR(8), NULL) ISPBSACADA, 
		CONVERT (CHAR(1), NULL) CANALPAGTO, 
		CONVERT (CHAR(1), NULL) MEIOPAGTO, 
		CONVERT (CHAR(2), NULL) SITPAGAMENTOCIP, 
		CONVERT (NUMERIC(19, 0), NULL) ULTNUMREFCADTIT, 
		CONVERT (NUMERIC(19, 0), NULL) ULTNUMSEQCADTIT, 
		CONVERT (NUMERIC(19, 0), NULL) ULTNUMREFBAIXAOPERAC, 
		CONVERT (NUMERIC(19, 0), NULL) ULTNUMSEQBAIXAOPERAC, 
		CONVERT (NUMERIC(19, 0), NULL) ULTNUMREFBAIXAEFET, 
		CONVERT (NUMERIC(19, 0), NULL) ULTNUMSEQBAIXAEFET, 
		CONVERT (NUMERIC(19, 0), NULL) ULTNUMREFACEITE, 
		CONVERT (NUMERIC(19, 0), NULL) ULTNUMSEQACEITE, 
		CONVERT (NUMERIC(19, 0), NULL) ULTNUMREFTERC, 
		CONVERT (NUMERIC(19, 0), NULL) ULTNUMSEQTERC, 
		-- MENSAGENS
		CONVERT (INTEGER, NULL) SEQMENSAGEM, 
		CONVERT (VARCHAR(100), NULL) TEXTO, 
		-- ANEXO FATURA
		CONVERT (NUMERIC(17, 0), NULL) SEQFATURA, 
		CONVERT (INTEGER, NULL) CODMODELO, 
		CONVERT (NUMERIC(17, 0), NULL) SEQDETANTES, 
		CONVERT (NUMERIC(17, 0), NULL) SEQDETDEPOIS, 
		CONVERT (VARCHAR(255), NULL) CABECALHO, 
		CONVERT (VARCHAR(2), NULL) TPDADOS, 
		CONVERT (NUMERIC(17, 0), NULL) SEQMODELO, 
		-- NOTAS FISCAIS
		CONVERT (VARCHAR(15), NULL) NUMNOTAFISCAL, 
		CONVERT (NUMERIC(19, 5), NULL) VLRNOTAFISCAL, 
		CONVERT (DATETIME, NULL) DATAEMISSAONOTA, 
		-- BAIXAS OPERACIONAIS
		CONVERT(NUMERIC(19, 0), NULL) NUMIDENTCBAIXAOPERAC, 
		CONVERT(NUMERIC(19, 0), NULL) NUMREFBAIXAOPERAC, 
		--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)
		CONVERT(VARCHAR(2), NULL) TIPOBAIXAOPERACIONAL, 
		CONVERT(DATETIME, NULL) DATABAIXAOPERACIONAL, 
		CONVERT(NUMERIC(19, 5), NULL) VLRBAIXAOPERACIONAL, 
		CONVERT(CHAR(1), NULL) TIPOPESPORTADOR, 
		CONVERT(VARCHAR(14), NULL) CNPJ_CPF_PORTADOR, 
		-- LASILVA 15-12-2022 - ACRESCENTADO COLUNAS NOME_PORTADOR E DATAHORARECBTTITULO. AO REALIZAR A CONSULTA DO TÍTULO ESTAVAM DANDO INVÁLIDAS.   
		CONVERT(VARCHAR(80), NULL) NOME_PORTADOR,  
		CONVERT(DATETIME, NULL) DATAHORARECBTTITULO,   
		CONVERT(DATETIME, NULL) DATAHORACANCEL, 
		CONVERT(CHAR(1), NULL) INDCONTINGENCIA, 
		CONVERT(CHAR(1), NULL) ORIGEMCANCELAMENTO, 
		-- BAIXAS EFETIVAS
		CONVERT(NUMERIC(19, 0), NULL) NUMIDENTCBAIXAEFET, 
		CONVERT(NUMERIC(19, 0), NULL) NUMREFBAIXAEFET, 
		CONVERT(DATETIME, NULL) DATABAIXAEFETIVA, 
		CONVERT(NUMERIC(19, 5), NULL) VLRBAIXAEFETIVA, 
		--28/03/2023 - RFAQUINI - ALTERAÇÃO TIPOBAIXA (CATÁLOGO 5.06 - Modernização da Cobrança)
		CONVERT(VARCHAR(2), NULL) TIPOBAIXAEFETIVA, 
		-- CALCULOS
		CONVERT(DATETIME, NULL) DATACALCULO, 
		CONVERT(NUMERIC(19, 5), NULL) VLRMORA, 
		CONVERT(NUMERIC(19, 5), NULL) VLRMULTA, 
		CONVERT(NUMERIC(19, 5), NULL) VLRDESCONTO, 
		CONVERT(NUMERIC(19, 5), NULL) VLRCOBRAR, 
		-- TERCEIROS
		CONVERT(CHAR(1), NULL) TIPOPESTERC, 
		CONVERT(VARCHAR(14), NULL) CNPJ_CPF_TERC, 
		CONVERT(NUMERIC(19, 0), NULL) NUMIDENTCTERC, 
		CONVERT(NUMERIC(19, 0), NULL) NUMREFTERC, 
		CONVERT(CHAR(1), NULL) TIPOPESAUTORIZADOR, 
		CONVERT(VARCHAR(14), NULL) CNPJ_CPF_AUTORIZADOR				
		
		INTO #TEMP_TITULOS_FILTRO 
	FROM TITULOS 
	WHERE 1 = 2

	CREATE TABLE #TITULOS (
		NUMIDENTCDDA NUMERIC (19, 0)
	)
	
	INSERT INTO #TITULOS (
		NUMIDENTCDDA
	)
	SELECT 
		NUMIDENTCDDA
	FROM TITULOS WITH (NOLOCK)
	WHERE NUMCODBARRAS = @NUMCODBARRAS
	
	CREATE NONCLUSTERED INDEX IDX_TEMP_TITULOS ON #TITULOS (NUMIDENTCDDA)
	 
	INSERT INTO #TEMP_TITULOS_FILTRO (
		TIPOREGISTRO, NUMIDENTCDDA, CODIFSACADA, CODIFCEDENTE, 
		TIPOPESCEDENTE, CNPJ_CPF_CEDENTE, NOMECEDENTE, TIPOPESCEDENTEORI, CNPJ_CPF_CEDENTEORI, 
		NOMECEDENTEORI, ENDCEDENTEORI, CIDCEDENTEORI, UFCEDENTEORI, CEPCEDENTEORI, TIPOPESSACADO, 
		CNPJ_CPF_SACADO, NOMESACADO, ENDSACADO, CIDSACADO, UFSACADO, CEPSACADO, TIPOPESSACADOR, 
		CNPJ_CPF_SACADOR, 
		NOMESACADOR, CODCARTEIRA, CODMOEDACNAB, IDENTNOSSONUMERO, LINHADIGITAVEL, 
		DATAVENCIMENTO, VLRTITULO, SEUNUMERO, CODESPECIEDOC, DATAEMISSAO, QTDEDIASPROTESTO, 
		DATALIMPAGTO, TIPOPAGTO, INDTITULONEGOCIADO, VLRABATIMENTO, CODMORA, DATAMORA, VLRPERCMORA, 
		CODMULTA, DATAMULTA, VLRPERCMULTA, CODDESCONTO01, DATADESCONTO01, VLRPERCDESCONTO01, 
		CODDESCONTO02, DATADESCONTO02, VLRPERCDESCONTO02, CODDESCONTO03, DATADESCONTO03, 
		VLRPERCDESCONTO03, ACEITE, DATAACEITE, CODSITUACAO, TIPOBAIXA, SITPAGAMENTO, VLRMINTITULO, 
		VLRMAXTITULO, TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO, CODSISLEGADO, DTHRSITTITULO, 
		DATACALCULO, INDALTERAVALOR, TIPOCALCULO, NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI, NOMEFANTASIASACADO, NUMCODBARRAS, NUMPARCELA, 
		QTDPARCELA, INDBLOQUEIO, INDPARCIAL, QTDPAGTO, INDVALORPERC_MIN, INDVALORPERC_MAX, ISPBCEDENTE, TIPOAUTRECDIVERGENTE, 
		ISPBSACADA, CANALPAGTO, MEIOPAGTO, SITPAGAMENTOCIP, ULTNUMREFCADTIT, ULTNUMSEQCADTIT, ULTNUMREFBAIXAOPERAC, 
		ULTNUMSEQBAIXAOPERAC, ULTNUMREFBAIXAEFET, ULTNUMSEQBAIXAEFET, ULTNUMREFACEITE, ULTNUMSEQACEITE, ULTNUMREFTERC, ULTNUMSEQTERC)
	SELECT 
		1, TITULOS.NUMIDENTCDDA, TITULOS.CODIFSACADA, TITULOS.CODIFCEDENTE, 
		TITULOS.TIPOPESCEDENTE, TITULOS.CNPJ_CPF_CEDENTE, TITULOS.NOMECEDENTE, TITULOS.TIPOPESCEDENTEORI, TITULOS.CNPJ_CPF_CEDENTEORI, 
		TITULOS.NOMECEDENTEORI, TITULOS.ENDCEDENTEORI, TITULOS.CIDCEDENTEORI, TITULOS.UFCEDENTEORI, TITULOS.CEPCEDENTEORI, TITULOS.TIPOPESSACADO, 
		TITULOS.CNPJ_CPF_SACADO, TITULOS.NOMESACADO, TITULOS.ENDSACADO, TITULOS.CIDSACADO, TITULOS.UFSACADO, TITULOS.CEPSACADO, TITULOS.TIPOPESSACADOR, 
		CASE 
			WHEN LEN(TITULOS.CNPJ_CPF_SACADOR) > 14 
				THEN SUBSTRING (TITULOS.CNPJ_CPF_SACADOR, 2, 14) 
			ELSE TITULOS.CNPJ_CPF_SACADOR 
			END, 
		TITULOS.NOMESACADOR, TITULOS.CODCARTEIRA, TITULOS.CODMOEDACNAB, TITULOS.IDENTNOSSONUMERO, TITULOS.LINHADIGITAVEL, 
		TITULOS.DATAVENCIMENTO, TITULOS.VLRTITULO, TITULOS.SEUNUMERO, TITULOS.CODESPECIEDOC, TITULOS.DATAEMISSAO, TITULOS.QTDEDIASPROTESTO, 
		TITULOS.DATALIMPAGTO, TITULOS.TIPOPAGTO, TITULOS.INDTITULONEGOCIADO, TITULOS.VLRABATIMENTO, TITULOS.CODMORA, TITULOS.DATAMORA, TITULOS.VLRPERCMORA, 
		TITULOS.CODMULTA, TITULOS.DATAMULTA, TITULOS.VLRPERCMULTA, TITULOS.CODDESCONTO01, TITULOS.DATADESCONTO01, TITULOS.VLRPERCDESCONTO01, 
		TITULOS.CODDESCONTO02, TITULOS.DATADESCONTO02, TITULOS.VLRPERCDESCONTO02, TITULOS.CODDESCONTO03, TITULOS.DATADESCONTO03, 
		TITULOS.VLRPERCDESCONTO03, TITULOS.ACEITE, TITULOS.DATAACEITE, TITULOS.CODSITUACAO, TITULOS.TIPOBAIXA, TITULOS.SITPAGAMENTO, TITULOS.VLRMINTITULO, 
		TITULOS.VLRMAXTITULO, TITULOS.TIPOPESTERCEIRO, TITULOS.CNPJ_CPF_TERCEIRO, TITULOS.CODSISLEGADO, TITULOS.DTHRSITTITULO, 
		TITULOS.DATACALCULO, TITULOS.INDALTERAVALOR, TITULOS.TIPOCALCULO, TITULOS.NOMEFANTASIACEDENTE, TITULOS.NOMEFANTASIACEDENTEORI, TITULOS.NOMEFANTASIASACADO, TITULOS.NUMCODBARRAS, TITULOS.NUMPARCELA, 
		TITULOS.QTDPARCELA, TITULOS.INDBLOQUEIO, TITULOS.INDPARCIAL, TITULOS.QTDPAGTO, TITULOS.INDVALORPERC_MIN, TITULOS.INDVALORPERC_MAX, TITULOS.ISPBCEDENTE, TITULOS.TIPOAUTRECDIVERGENTE, 
		TITULOS.ISPBSACADA, TITULOS.CANALPAGTO, TITULOS.MEIOPAGTO, TITULOS.SITPAGAMENTOCIP, TITULOS.ULTNUMREFCADTIT, TITULOS.ULTNUMSEQCADTIT, TITULOS.ULTNUMREFBAIXAOPERAC, 
		TITULOS.ULTNUMSEQBAIXAOPERAC, TITULOS.ULTNUMREFBAIXAEFET, TITULOS.ULTNUMSEQBAIXAEFET, TITULOS.ULTNUMREFACEITE, TITULOS.ULTNUMSEQACEITE, TITULOS.ULTNUMREFTERC, TITULOS.ULTNUMSEQTERC
	FROM TITULOS 
	INNER JOIN #TITULOS
		ON (TITULOS.NUMIDENTCDDA = #TITULOS.NUMIDENTCDDA)

	CREATE NONCLUSTERED INDEX IX_01 ON #TEMP_TITULOS_FILTRO (TIPOREGISTRO) INCLUDE (NUMIDENTCDDA, CNPJ_CPF_SACADO, SEQFATURA)
	-------------------------------------------------------------------------------------------------------
	-- MENSAGEM
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, 
		SEQMENSAGEM, TEXTO
	)
	SELECT 
		#TITULOS.NUMIDENTCDDA, 2,
		MENSAGENS.SEQMENSAGEM, MENSAGENS.TEXTO
	FROM #TITULOS  
	INNER JOIN MENSAGENS (NOLOCK)
		ON (#TITULOS.NUMIDENTCDDA = MENSAGENS.NUMIDENTCDDA)
	-------------------------------------------------------------------------------------------------------
	-- NOTA FISCAL
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO,
		NUMNOTAFISCAL, DATAEMISSAONOTA, VLRNOTAFISCAL
	)
	SELECT 
		#TITULOS.NUMIDENTCDDA, 4, 
		NOTAS_FISCAIS.NUMNOTAFISCAL, NOTAS_FISCAIS.DATAEMISSAO, NOTAS_FISCAIS.VLRNOTAFISCAL
	FROM #TITULOS 
	INNER JOIN NOTAS_FISCAIS (NOLOCK)
		ON (#TITULOS.NUMIDENTCDDA = NOTAS_FISCAIS.NUMIDENTCDDA)
	-------------------------------------------------------------------------------------------------------	
	-- ANEXO FATURA
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO,
		SEQFATURA, CODMODELO
	)
	SELECT 
		#TITULOS.NUMIDENTCDDA, 5, 
		ANEXO_FATURA.SEQFATURA, ANEXO_FATURA.CODMODELO
	FROM #TITULOS  
	INNER JOIN ANEXO_FATURA (NOLOCK)
		ON (#TITULOS.NUMIDENTCDDA = ANEXO_FATURA.NUMIDENTCDDA)
	-------------------------------------------------------------------------------------------------------	
	-- MODELO (ANEXO FATURA)
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		SEQFATURA, SEQMODELO, CABECALHO, TPDADOS
	)
	SELECT 
		#TEMP_TITULOS_FILTRO.NUMIDENTCDDA, 6, #TEMP_TITULOS_FILTRO.CNPJ_CPF_SACADO, 
		MODELO.SEQFATURA, MODELO.SEQMODELO, MODELO.CABECALHO, MODELO.TPDADOS
	FROM #TEMP_TITULOS_FILTRO  
	INNER JOIN MODELO (NOLOCK)
		ON (#TEMP_TITULOS_FILTRO.NUMIDENTCDDA = MODELO.NUMIDENTCDDA
		AND #TEMP_TITULOS_FILTRO.SEQFATURA = MODELO.SEQFATURA)
	WHERE #TEMP_TITULOS_FILTRO.TIPOREGISTRO = 5
	-------------------------------------------------------------------------------------------------------	
	-- DETALHE ANTES DO CABEÇALHO (ANEXO FATURA)
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		SEQFATURA, SEQDETANTES, TEXTO
	)
	SELECT 
		#TEMP_TITULOS_FILTRO.NUMIDENTCDDA, 7, #TEMP_TITULOS_FILTRO.CNPJ_CPF_SACADO, 
		DET_ANTES_CABEC.SEQFATURA, DET_ANTES_CABEC.SEQDETANTES, DET_ANTES_CABEC.TEXTO
	FROM #TEMP_TITULOS_FILTRO  
	INNER JOIN DET_ANTES_CABEC (NOLOCK)
		ON (#TEMP_TITULOS_FILTRO.NUMIDENTCDDA = DET_ANTES_CABEC.NUMIDENTCDDA
		AND #TEMP_TITULOS_FILTRO.SEQFATURA = DET_ANTES_CABEC.SEQFATURA)
	WHERE #TEMP_TITULOS_FILTRO.TIPOREGISTRO = 5
	-------------------------------------------------------------------------------------------------------	
	-- DETALHE APÓS CABEÇALHO (ANEXO FATURA)
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, 
		SEQFATURA, SEQDETDEPOIS, TEXTO
		)
	SELECT 
		#TEMP_TITULOS_FILTRO.NUMIDENTCDDA, 8, #TEMP_TITULOS_FILTRO.CNPJ_CPF_SACADO, 
		DET_APOS_CABEC.SEQFATURA, DET_APOS_CABEC.SEQDETAPOS, DET_APOS_CABEC.TEXTO
	FROM #TEMP_TITULOS_FILTRO  
	INNER JOIN DET_APOS_CABEC (NOLOCK)
		ON (#TEMP_TITULOS_FILTRO.NUMIDENTCDDA = DET_APOS_CABEC.NUMIDENTCDDA
		AND #TEMP_TITULOS_FILTRO.SEQFATURA = DET_APOS_CABEC.SEQFATURA)
	WHERE #TEMP_TITULOS_FILTRO.TIPOREGISTRO = 5
	-------------------------------------------------------------------------------------------------------
	-- BAIXA OPERACIONAL  
	INSERT INTO #TEMP_TITULOS_FILTRO (  
		NUMIDENTCDDA, TIPOREGISTRO,   
		NUMIDENTCBAIXAOPERAC, NUMREFBAIXAOPERAC, TIPOBAIXAOPERACIONAL, DATABAIXAOPERACIONAL, VLRBAIXAOPERACIONAL,   
		TIPOPESPORTADOR, CNPJ_CPF_PORTADOR, NOME_PORTADOR, DATAHORARECBTTITULO, DATAHORACANCEL, INDCONTINGENCIA, ORIGEMCANCELAMENTO  
	) 
	SELECT   
		#TITULOS.NUMIDENTCDDA, 9,   
		BAIXAS_OPERACIONAIS.NUMIDENTCBAIXAOPERAC, BAIXAS_OPERACIONAIS.NUMREFBAIXAOPERAC, BAIXAS_OPERACIONAIS.TIPOBAIXA, BAIXAS_OPERACIONAIS.DATABAIXA, BAIXAS_OPERACIONAIS.VLRBAIXA,   
		BAIXAS_OPERACIONAIS.TIPOPESPORTADOR, BAIXAS_OPERACIONAIS.CNPJ_CPF_PORTADOR, BAIXAS_OPERACIONAIS.NOME_PORTADOR, BAIXAS_OPERACIONAIS.DATAHORARECBTTITULO, BAIXAS_OPERACIONAIS.DATAHORACANCEL, BAIXAS_OPERACIONAIS.INDCONTINGENCIA, 
		BAIXAS_OPERACIONAIS.ORIGEMCANCELAMENTO  
	FROM #TITULOS   
	INNER JOIN BAIXAS_OPERACIONAIS (NOLOCK)  
		ON (#TITULOS.NUMIDENTCDDA = BAIXAS_OPERACIONAIS.NUMIDENTCDDA)  
	-------------------------------------------------------------------------------------------------------
	-- BAIXA EFETIVA
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, 
		NUMIDENTCBAIXAEFET, NUMREFBAIXAEFET, DATABAIXAEFETIVA, VLRBAIXAEFETIVA, TIPOBAIXAEFETIVA
	)
	SELECT 
		#TITULOS.NUMIDENTCDDA, 10, 
		BAIXAS_EFETIVAS.NUMIDENTCBAIXAEFET, BAIXAS_EFETIVAS.NUMREFBAIXAEFET, BAIXAS_EFETIVAS.DATABAIXA, BAIXAS_EFETIVAS.VLRBAIXA, BAIXAS_EFETIVAS.TIPOBAIXA
	FROM #TITULOS   
	INNER JOIN BAIXAS_EFETIVAS (NOLOCK)
		ON (#TITULOS.NUMIDENTCDDA = BAIXAS_EFETIVAS.NUMIDENTCDDA)
	-------------------------------------------------------------------------------------------------------
	-- CALCULOS
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, 
		DATACALCULO, VLRMORA, VLRMULTA, VLRDESCONTO, VLRCOBRAR
	)
	SELECT 
		#TITULOS.NUMIDENTCDDA, 11, 
		CALCULOS.DATACALCULO, CALCULOS.VLRMORA, CALCULOS.VLRMULTA, CALCULOS.VLRDESCONTO, CALCULOS.VLRCOBRAR
	FROM #TITULOS  
	INNER JOIN CALCULOS (NOLOCK)
		ON (#TITULOS.NUMIDENTCDDA = CALCULOS.NUMIDENTCDDA)
	-------------------------------------------------------------------------------------------------------	
	-- TERCEIROS
	INSERT INTO #TEMP_TITULOS_FILTRO (
		NUMIDENTCDDA, TIPOREGISTRO, 
		TIPOPESTERC, CNPJ_CPF_TERC, NUMIDENTCTERC, NUMREFTERC, 
		TIPOPESAUTORIZADOR, CNPJ_CPF_AUTORIZADOR
	)
	SELECT 
		#TITULOS.NUMIDENTCDDA, 12,
		TERCEIROS.TIPOPESTERC, TERCEIROS.CNPJ_CPF_TERC, TERCEIROS.NUMIDENTCTERC, TERCEIROS.NUMREFTERC, 
		TERCEIROS.TIPOPESAUTORIZADOR, TERCEIROS.CNPJ_CPF_AUTORIZADOR
	FROM #TITULOS 
	INNER JOIN TERCEIROS (NOLOCK)
		ON (#TITULOS.NUMIDENTCDDA = TERCEIROS.NUMIDENTCDDA)
	-------------------------------------------------------------------------------------------------------
	SELECT TIPOREGISTRO, NUMIDENTCDDA, CODIFSACADA, CODIFCEDENTE, TIPOPESCEDENTE, CNPJ_CPF_CEDENTE, NOMECEDENTE, TIPOPESCEDENTEORI, 
		CNPJ_CPF_CEDENTEORI, NOMECEDENTEORI, ENDCEDENTEORI, CIDCEDENTEORI, UFCEDENTEORI, CEPCEDENTEORI, TIPOPESSACADO, CNPJ_CPF_SACADO, 
		NOMESACADO, ENDSACADO, CIDSACADO, UFSACADO, CEPSACADO, TIPOPESSACADOR, CNPJ_CPF_SACADOR, NOMESACADOR, CODCARTEIRA, CODMOEDACNAB, 
		IDENTNOSSONUMERO, LINHADIGITAVEL, DATAVENCIMENTO, VLRTITULO, SEUNUMERO, CODESPECIEDOC, DATAEMISSAO, QTDEDIASPROTESTO, DATALIMPAGTO, 
		TIPOPAGTO, INDTITULONEGOCIADO, VLRABATIMENTO, CODMORA, DATAMORA, VLRPERCMORA, CODMULTA, DATAMULTA, VLRPERCMULTA, CODDESCONTO01, 
		DATADESCONTO01, VLRPERCDESCONTO01, CODDESCONTO02, DATADESCONTO02, VLRPERCDESCONTO02, CODDESCONTO03, DATADESCONTO03, VLRPERCDESCONTO03, 
		ACEITE, DATAACEITE, CODSITUACAO, TIPOBAIXA, SITPAGAMENTO, VLRMINTITULO, VLRMAXTITULO, TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO, CODSISLEGADO, 
		DTHRSITTITULO, INDALTERAVALOR, TIPOCALCULO, NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI, NOMEFANTASIASACADO, NUMCODBARRAS, NUMPARCELA, 
		QTDPARCELA, INDBLOQUEIO, INDPARCIAL, QTDPAGTO, INDVALORPERC_MIN, INDVALORPERC_MAX, ISPBCEDENTE, TIPOAUTRECDIVERGENTE, ISPBSACADA, 
		CANALPAGTO, MEIOPAGTO, SITPAGAMENTOCIP, ULTNUMREFCADTIT, ULTNUMSEQCADTIT, ULTNUMREFBAIXAOPERAC, ULTNUMSEQBAIXAOPERAC, ULTNUMREFBAIXAEFET, 
		ULTNUMSEQBAIXAEFET, ULTNUMREFACEITE, ULTNUMSEQACEITE, ULTNUMREFTERC, ULTNUMSEQTERC, SEQMENSAGEM, TEXTO, SEQFATURA, CODMODELO, SEQDETANTES, 
		SEQDETDEPOIS, CABECALHO, TPDADOS, SEQMODELO, NUMNOTAFISCAL, VLRNOTAFISCAL, DATAEMISSAONOTA, NUMIDENTCBAIXAOPERAC, NUMREFBAIXAOPERAC, 
		TIPOBAIXAOPERACIONAL, DATABAIXAOPERACIONAL, VLRBAIXAOPERACIONAL, TIPOPESPORTADOR, CNPJ_CPF_PORTADOR, NOME_PORTADOR, DATAHORARECBTTITULO,  
  DATAHORACANCEL, INDCONTINGENCIA, ORIGEMCANCELAMENTO, NUMIDENTCBAIXAEFET, NUMREFBAIXAEFET, DATABAIXAEFETIVA, VLRBAIXAEFETIVA, TIPOBAIXAEFETIVA,  
  DATACALCULO, VLRMORA, VLRMULTA, VLRDESCONTO, VLRCOBRAR, TIPOPESTERC, CNPJ_CPF_TERC, NUMIDENTCTERC, NUMREFTERC, TIPOPESAUTORIZADOR, CNPJ_CPF_AUTORIZADOR  
	FROM #TEMP_TITULOS_FILTRO
	ORDER BY NUMIDENTCDDA, TIPOREGISTRO, CNPJ_CPF_SACADO, SEQFATURA, SEQMENSAGEM, SEQDETANTES, SEQDETDEPOIS, NUMNOTAFISCAL, DATACALCULO
	
END
GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO], 
    [NOMESCRIPT], 
    [CODUSUARIO], 
    [DATAATU]
)
SELECT
	'V15_01_1_01B', 
	'SP_PESQUISA_TITULO_POR_NUMCODBARRAS', 
	SYSTEM_USER, 
	GETDATE() 
GO