USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_PROCESSA_DDA0114_ADDA114_RR2')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_PROCESSA_DDA0114_ADDA114_RR2 AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE SP_PROCESSA_DDA0114_ADDA114_RR2(
			@P_TIMEOUT INT, 
			@P_SQLERRO INT OUT
) AS BEGIN

	/*
		03/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
								REMOÇÃO DE ALIAS
								
		25/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
		24/02/2023 - Eliane - Alterações para a MODERNIZAÇÃO.
		08/03/2023 - Eliane   - O acerto final deve setar CODPROCESSA = 2 E NÃO 1 !!!         
	*/
	
	/*
		MARCACOES DIFERENCIADAS (CODPROCESSA)

		"4" - DUPLICIDADE DE AVISO (APENAS O MAIS RECENTE GERA ATUALIZACAO NA BASE)

		DOMINIOS DE REJEICOES (CODREJEICAO)

		"01" - TITULO NAO ENCONTRADO
		"26" - BAIXA JA CADASTRADA

	*/

	DECLARE
		@DATAULTPROCESSAMENTO DATETIME, 
		@DATAPROCESSAMENTO DATETIME, 
		@SQLERRO INTEGER, 
		@TIMESTAMP DATETIME, 
		@ISPB CHAR(8),
		@VRSMANUAL VARCHAR (07) /* 24/02/2023 */
		


	SELECT 
		@DATAULTPROCESSAMENTO = DATAULTPROCESSAMENTO, 
		@DATAPROCESSAMENTO = DATAPROCESSAMENTO, 
		@TIMESTAMP = GETDATE(), 
		@ISPB = ISPB
   	FROM PARAMETROS 
	WHERE CODSISTEMA = 'DDA-AUTK'  
  	
	SELECT @VRSMANUAL = VRSMANUAL FROM VWIB_VRSMANUAL WITH (NOLOCK)  /* 24/02/2023 */
  	
   	-- TIMEOUT DAS TABELAS DE RESERVA
   	DELETE 
	FROM TEMP_RECEBE_ADDA114_RR2 
	WHERE DATEADD(MINUTE, @P_TIMEOUT, DATAHORAPROC) < @TIMESTAMP

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	-- TRATAMENTO DE RECEBES ACEITAS
	-- SELECIONA TUDO PENDENTE
	SELECT * 
		INTO #TEMP_RR2 
	FROM RECEBE_ADDA114_RR2
	WHERE DATAMOVTO >= @DATAULTPROCESSAMENTO 
	AND DATAMOVTO <= @DATAPROCESSAMENTO 
	AND CODPROCESSA = '0' 
	AND INDIMPORTACAOVALIDA = 'S'

	-- DELETA TUDO QUE ESTA RESERVADO
	DELETE #TEMP_RR2 
	FROM #TEMP_RR2 
	INNER JOIN TEMP_RECEBE_ADDA114_RR2  
		ON (TEMP_RECEBE_ADDA114_RR2.SEQ_RECEBE = #TEMP_RR2.SEQ_RECEBE 
		AND TEMP_RECEBE_ADDA114_RR2.NUMIDENTCDDA = #TEMP_RR2.NUMIDENTCDDA 
		AND TEMP_RECEBE_ADDA114_RR2.DATAMOVTO = #TEMP_RR2.DATAMOVTO)

	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	-- RESERVA O QUE ESTA LIVRE
	INSERT INTO TEMP_RECEBE_ADDA114_RR2(
		SEQ_RECEBE, NUMIDENTCDDA, DATAMOVTO, DATAHORAPROC
	)
	SELECT 
		SEQ_RECEBE, NUMIDENTCDDA, DATAMOVTO, @TIMESTAMP 
	FROM #TEMP_RR2

	-- PK DUPLICADA, PROCESSOS SIMULTANEOS?
	SELECT @SQLERRO = @@ERROR		 
	IF @SQLERRO <> 0 GOTO TRATAERRO

	IF(EXISTS(SELECT 1 FROM #TEMP_RR2))
	BEGIN

		/** REJEICOES **/
		-- COD REJEICAO "01" - TITULO NAO EXISTE
		UPDATE #TEMP_RR2 SET 
			CODPROCESSA = '2', 
			CODREJEICAO = '01' 
		FROM #TEMP_RR2 
		WHERE CODPROCESSA = '0' 
		AND CODREJEICAO IS NULL
		AND NOT EXISTS (SELECT 1 
					FROM TITULOS 
					WHERE NUMIDENTCDDA = #TEMP_RR2.NUMIDENTCDDA)

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERRO

		-- COD REJEICAO "26" - BAIXA JA CADASTRADA
		UPDATE #TEMP_RR2 SET 
			CODPROCESSA = '2', 
			CODREJEICAO = '26' 
		FROM #TEMP_RR2 
		WHERE CODPROCESSA = '0' 
		AND CODREJEICAO IS NULL
		AND EXISTS (SELECT 1 
				FROM BAIXAS_OPERACIONAIS 
				WHERE NUMIDENTCDDA = #TEMP_RR2.NUMIDENTCDDA 
				AND NUMIDENTCBAIXAOPERAC = #TEMP_RR2.NUMIDENTCBAIXAOPERAC)

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERRO

		/** MARCACOES DIFERENCIADAS **/
		-- MOVIMENTOS SERAO SEPARADOS DOS DEMAIS PARA SOMENTE RECEBEREM A MARCACAO DE PROCESSADOS AO FINAL DA PROCEDURE

		
		-- NAO CONSISTIR MAIS ESTA SITUACAO !!!
		-- CODPROCESSA "5": BAIXA JA RECEBIDA EM UMA ADDA/DDA0114R1
		--UPDATE #TEMP_RR2 SET 
		--	CODPROCESSA = '5' 
		--FROM #TEMP_RR2 
		--WHERE CODPROCESSA = '0' 
		--AND CODREJEICAO IS NULL
		--AND ((ISPBIFSACADA IS NOT NULL 
		--	AND ISPBIFSACADA = @ISPB) -- R1 A SER RECEBIDA: A PROPRIA INSTITUICAO GEROU O TITULO (ISPBIFSACADA EH ENVIADA SOMENTE PARA IF DESTINATARIA) E ACONTECE DE SER A IF ONDE A BAIXA FOI FEITA
		--	OR EXISTS (SELECT 1 
		--			FROM RECEBE_ADDA114_RET_ACEITOS 
		--			WHERE DATAMOVTO >= @DATAULTPROCESSAMENTO 
		--			AND DATAMOVTO <= @DATAPROCESSAMENTO 
		--			AND NUMCTRLDDA = #TEMP_RR2.NUMCTRLDDA)) -- R1 RECEBIDA
		--
		--SELECT @SQLERRO = @@ERROR		 
		--IF @SQLERRO <> 0 GOTO TRATAERRO



		-- CODPROCESSA "4": DUPLICIDADE DE AVISOS
		-- SE HOUVER DUPLICIDADE NO AVISO, MESMA BAIXA, OS RECEBIMENTOS COM DATAHORADDA OU SEQ_RECEBE MENOR SAO SEPARADAS PARA SEREM SOMENTE MARCADAS COMO PROCESSADAS AO FINAL
		SELECT MAX(DATAHORADDA) MAX_DATAHORADDA, NUMIDENTCBAIXAOPERAC 
			INTO #TEMP_MAX_DATAHORADDA 
		FROM #TEMP_RR2
		WHERE CODPROCESSA = '0' 
		AND CODREJEICAO IS NULL
		GROUP BY NUMIDENTCBAIXAOPERAC

		UPDATE #TEMP_RR2 SET CODPROCESSA = '4' 
		FROM #TEMP_RR2 
		WHERE #TEMP_RR2.CODPROCESSA = '0' 
		AND #TEMP_RR2.CODREJEICAO IS NULL 
		AND #TEMP_RR2.DATAHORADDA < (SELECT MAX_DATAHORADDA 
						FROM #TEMP_MAX_DATAHORADDA  
						WHERE #TEMP_MAX_DATAHORADDA.NUMIDENTCBAIXAOPERAC = #TEMP_RR2.NUMIDENTCBAIXAOPERAC)

		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERRO

		SELECT MAX(SEQ_RECEBE) MAX_SEQ_RECEBE, NUMIDENTCBAIXAOPERAC 
			INTO #TEMP_MAX_SEQ_RECEBE 
		FROM #TEMP_RR2
		WHERE CODPROCESSA = '0' 
		AND CODREJEICAO IS NULL 
		GROUP BY NUMIDENTCBAIXAOPERAC

		UPDATE #TEMP_RR2 SET 
			CODPROCESSA = '4' 
		FROM #TEMP_RR2 
		WHERE #TEMP_RR2.CODPROCESSA = '0' 
		AND #TEMP_RR2.CODREJEICAO IS NULL 
		AND #TEMP_RR2.SEQ_RECEBE < (SELECT MAX_SEQ_RECEBE 
						FROM #TEMP_MAX_SEQ_RECEBE  
						WHERE #TEMP_MAX_SEQ_RECEBE.NUMIDENTCBAIXAOPERAC = #TEMP_RR2.NUMIDENTCBAIXAOPERAC)
	
		SELECT @SQLERRO = @@ERROR		 
		IF @SQLERRO <> 0 GOTO TRATAERRO

		-- O RESTO PODE SER DADO COMO ACEITO E PROCESSADO
		UPDATE #TEMP_RR2 SET 
			CODPROCESSA = '1' 
		WHERE CODPROCESSA = '0' 
		AND CODREJEICAO IS NULL


		/*----------------------------------------------------------------------------*/
                /* 24/02/2023 - Neste ponto podemos chegar com N baixas para o mesmo título ! */
                /* Decidir com qual delas faremos o UPDATE em TÍTULOS !                       */
                /*----------------------------------------------------------------------------------------------*/
                /* 24/02/2023 - Eliane.  Selecionando a mais recente baixa do título.                           */
                /* INICIO DO TRECHO.                                                                            */
                /*----------------------------------------------------------------------------------------------*/
                
		--MAX_NUMIDENTCBAIXA POR TÍTULO - MODERNIZAÇÃO
		--14/02/2023 - ELIANE - TRATAMENTO DO CAMPO NUMIDENTBAIXAOPERAC (CATÁLOGO MODERNIZAÇÃO)
		SELECT MAX(#TEMP_RR2.NUMIDENTCBAIXAOPERAC) NUMIDENTCBAIXAOPERAC, #TEMP_RR2.NUMIDENTCDDA NUMIDENTCDDA
			INTO #TEMP_MAX_NUMIDENTCBAIXAOPERAC
		FROM #TEMP_RR2 
		WHERE #TEMP_RR2.CODPROCESSA = '1'
		AND #TEMP_RR2.CODREJEICAO IS NULL
		GROUP BY #TEMP_RR2.NUMIDENTCDDA
		
                /*----------------------------------------------------------------------------------------------*/
                /* 24/02/2023 - Eliane.  Selecionando a mais recente baixa do título.                           */
                /* FIM DO TRECHO.                                                                               */
                /*----------------------------------------------------------------------------------------------*/

		BEGIN TRANSACTION

        	IF @VRSMANUAL <= '5.05'  
            
           	BEGIN /* 24/02/2023 - Catalogo anterior à MODERNIZAÇÃO - SOMENTE AVISO DE LIQUIDAÇÃO */

			--ATUALIZACAO DAS INFORMACOES DO TITULO, DESDE QUE A SEQUENCIA DA BAIXA ESTEJA ATUALIZADA EM RELACAO A SEQUENCIA DO TITULO
			UPDATE TITULOS SET 
				TITULOS.SITPAGAMENTO = '2', /* SITUACAO "BAIXA ENVIADA" */
				TITULOS.SITPAGAMENTOCIP = #TEMP_RR2.CODSITUACAOTIT, 
				TITULOS.TIPOBAIXA = #TEMP_RR2.TIPOBAIXATIT, 
				TITULOS.DATAPAGTOBAIXA = ISNULL(#TEMP_RR2.DATABAIXAOPERAC, TITULOS.DATAPAGTOBAIXA), 
				TITULOS.VLRPAGTOBAIXA = ISNULL(#TEMP_RR2.VLRBAIXAOPERAC, TITULOS.VLRPAGTOBAIXA), 
				TITULOS.ULTNUMREFBAIXAOPERAC = #TEMP_RR2.NUMREFBAIXAOPERAC, 
				TITULOS.ULTNUMSEQBAIXAOPERAC = #TEMP_RR2.NUMSEQBAIXAOPERAC, 
				TITULOS.INDCONTINGENCIA = ISNULL(#TEMP_RR2.INDCONTINGENCIA, TITULOS.INDCONTINGENCIA), 
				TITULOS.TIPOPESPORTADOR	= ISNULL(#TEMP_RR2.TIPOPESPORTADOR, TITULOS.TIPOPESPORTADOR), 
				TITULOS.CNPJ_CPF_PORTADOR = ISNULL(#TEMP_RR2.CNPJ_CPF_PORTADOR, TITULOS.CNPJ_CPF_PORTADOR), 
				TITULOS.QTDPAGTOREG =  ISNULL(#TEMP_RR2.QTDPAGTOREGTD, TITULOS.QTDPAGTOREG), 
				TITULOS.VLRSALDOATUAL = ISNULL(#TEMP_RR2.VLRSALDOATUAL, TITULOS.VLRSALDOATUAL)
					
			FROM TITULOS 
			INNER JOIN #TEMP_RR2  
				ON(#TEMP_RR2.CODPROCESSA = '1' 
				AND TITULOS.NUMIDENTCDDA = #TEMP_RR2.NUMIDENTCDDA
				AND #TEMP_RR2.NUMSEQBAIXAOPERAC > ISNULL(TITULOS.ULTNUMSEQBAIXAOPERAC, -1))
	
			SELECT @SQLERRO = @@ERROR		 
			IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS
	
           	END   /* 24/02/2023 - Catalogo anterior à MODERNIZAÇÃO - SOMENTE AVISO DE LIQUIDAÇÃO */
    	        ELSE 
           	BEGIN /* 24/02/2023 - Catalogo MODERNIZAÇÃO */

			--ATUALIZACAO DAS INFORMACOES DO TITULO, DESDE QUE A SEQUENCIA DA BAIXA ESTEJA ATUALIZADA EM RELACAO A SEQUENCIA DO TITULO
			UPDATE TITULOS SET 
			TITULOS.SITPAGAMENTO = '2', /* SITUACAO "BAIXA ENVIADA" */
			TITULOS.SITPAGAMENTOCIP = #TEMP_RR2.CODSITUACAOTIT, 
			TITULOS.ULTNUMREFBAIXAOPERAC = #TEMP_RR2.NUMREFBAIXAOPERAC, 
			TITULOS.ULTNUMSEQBAIXAOPERAC = ISNULL (#TEMP_RR2.NUMSEQBAIXAOPERAC, 0), 
			TITULOS.INDCONTINGENCIA = ISNULL(#TEMP_RR2.INDCONTINGENCIA, TITULOS.INDCONTINGENCIA), 
			TITULOS.TIPOPESPORTADOR	= ISNULL(#TEMP_RR2.TIPOPESPORTADOR, TITULOS.TIPOPESPORTADOR), 
			TITULOS.CNPJ_CPF_PORTADOR = ISNULL(#TEMP_RR2.CNPJ_CPF_PORTADOR, TITULOS.CNPJ_CPF_PORTADOR), 
			TITULOS.QTDPAGTOREG =  ISNULL(#TEMP_RR2.QTDPAGTOREGTD, TITULOS.QTDPAGTOREG), 
			TITULOS.VLRSALDOATUAL = ISNULL(#TEMP_RR2.VLRSALDOATUAL, TITULOS.VLRSALDOATUAL),
/*---------------------------------------------------------------*/				
/* dados que serão atualizados a partir da MODERNIZAÇÃO - inicio */

		CODSITUACAO = CASE WHEN #TEMP_RR2.TIPOBAIXATIT IN ('0', '9', '11') /* Baixa Operacional Integral Interbancária */
		                   THEN '4' /* título liquidado - LIQ INTERBANCÁRIA */
		                   WHEN #TEMP_RR2.TIPOBAIXATIT = '1' /* Baixa Operacional Integral Intrabancária */
		                   THEN '3' /* título liquidado - LIQ INTRABANCÁRIA */
		                   WHEN #TEMP_RR2.TIPOBAIXATIT IN ('5', '8') /* Baixa por solicitação do Cedente/Destinatária */
				   THEN '2' /* título baixado por solicitação do cedente */
		                   WHEN #TEMP_RR2.TIPOBAIXATIT = '6' /* Baixa integral por envio para protesto   */
				   THEN '6' /* título baixado por envio para protesto */
		                   WHEN #TEMP_RR2.TIPOBAIXATIT = '7' /* Baixa integral por decurso de prazo      */
				   THEN '5' /* título baixado por decurso de prazo */
		                   
		                   WHEN #TEMP_RR2.TIPOBAIXATIT = '4' /* Pago via PIX - NÃO TENHO COMO DISTINGUIR IF REC  */
				   THEN '4' /* título baixado por decurso de prazo */
		                   
		                   ELSE TITULOS.CODSITUACAO /* Continua como está. Baixas Parciais não alteram situação do título. */
		              END,

			TITULOS.TIPOBAIXA 	= #TEMP_RR2.TIPOBAIXATIT, 
			TITULOS.DATAPAGTOBAIXA 	= ISNULL(#TEMP_RR2.DATABAIXAOPERAC, TITULOS.DATAPAGTOBAIXA), 
			TITULOS.VLRPAGTOBAIXA 	= ISNULL(#TEMP_RR2.VLRBAIXAOPERAC, TITULOS.VLRPAGTOBAIXA) 

/* dados que serão atualizados a partir da MODERNIZAÇÃO - fim    */
/*---------------------------------------------------------------*/				
					
	     		FROM TITULOS  
	     		INNER JOIN #TEMP_RR2 
	     			ON (TITULOS.NUMIDENTCDDA    = #TEMP_RR2.NUMIDENTCDDA)
	     		INNER JOIN #TEMP_MAX_NUMIDENTCBAIXAOPERAC
	       			ON (#TEMP_MAX_NUMIDENTCBAIXAOPERAC.NUMIDENTCDDA = #TEMP_RR2.NUMIDENTCDDA AND
	            	#TEMP_MAX_NUMIDENTCBAIXAOPERAC.NUMIDENTCBAIXAOPERAC 	= #TEMP_RR2.NUMIDENTCBAIXAOPERAC)

	     		WHERE #TEMP_RR2.CODPROCESSA = '1'   

			SELECT @SQLERRO = @@ERROR		 
			IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS
	
           	END   /* 24/02/2023 - Catalogo MODERNIZAÇÃO */


			INSERT INTO BAIXAS_OPERACIONAIS
			(
				NUMIDENTCDDA, NUMIDENTCBAIXAOPERAC, NUMCTRLDDA, NUMREFBAIXAOPERAC, 
				NUMSEQBAIXAOPERAC, NUMREFCADTIT, NUMSEQCADTIT, DATAMOVTO, 
				DATAHORADDA, TIPOBAIXA, DATABAIXA, DATAHORABAIXA, 
				VLRBAIXA, NUMCODBARRAS, SITBAIXA, DATAHORASITUACAO, 
				ISPBSACADA, CODIFSACADA, NUMCTRLDDACANCEL, DATAHORACANCEL, 
				SITPAGTO, SITUACAOTIT, CANALPAGTO, MEIOPAGTO, 
				--03/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
				INDCONTINGENCIA, TIPOPESPORTADOR, CNPJ_CPF_PORTADOR, NOME_PORTADOR,
				--25/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
				DATAHORARECBTTITULO, QTDPAGTOREG, VLRSALDOATUAL,
				
				TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO. AGENCIARECEBEDORA /* CAT MODERNIZAÇÃO */
			) 
			SELECT
				#TEMP_RR2.NUMIDENTCDDA, #TEMP_RR2.NUMIDENTCBAIXAOPERAC, #TEMP_RR2.NUMCTRLDDA, #TEMP_RR2.NUMREFBAIXAOPERAC, 
				ISNULL (#TEMP_RR2.NUMSEQBAIXAOPERAC, 0), #TEMP_RR2.NUMREFALTCADTIT, NULL, #TEMP_RR2.DATAMOVTO, 
				#TEMP_RR2.DATAHORADDA, #TEMP_RR2.TIPOBAIXATIT, #TEMP_RR2.DATABAIXAOPERAC, #TEMP_RR2.DATAHORABAIXAOPERAC, 
				#TEMP_RR2.VLRBAIXAOPERAC, #TEMP_RR2.NUMCODBARRASBAIXAOPE, 'A', /* BAIXA ATIVA */ #TEMP_RR2.DATAHORASITUACAOBAIXAOPERAC, 
				#TEMP_RR2.ISPBIFSACADA, #TEMP_RR2.CODIFSACADA, NULL, NULL, 
				NULL, #TEMP_RR2.CODSITUACAOTIT, #TEMP_RR2.CANALPAGTO, #TEMP_RR2.MEIOPAGTO, 
				--03/11/2021 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
				#TEMP_RR2.INDCONTINGENCIA, #TEMP_RR2.TIPOPESPORTADOR, #TEMP_RR2.CNPJ_CPF_PORTADOR, #TEMP_RR2.NOME_PORTADOR,
				--25/05/2022 - RFAQUINI - INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
				#TEMP_RR2.DATAHORARECBTTITULO, #TEMP_RR2.QTDPAGTOREGTD, #TEMP_RR2.VLRSALDOATUAL,
				
				#TEMP_RR2.TIPOPESAGREGADOR, #TEMP_RR2.CNPJ_CPF_AGREGADOR, #TEMP_RR2.NOMEAGREGADOR, 	/* CAT MODERNIZAÇÃO */
				#TEMP_RR2.AGENCIARECEBEDORA 								/* CAT MODERNIZAÇÃO */
				

			FROM #TEMP_RR2 
			WHERE #TEMP_RR2.CODPROCESSA = '1' 
			AND #TEMP_RR2.CODREJEICAO IS NULL
			
			SELECT @SQLERRO = @@ERROR		 
			IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS

			-- RESTABELECENDO OS RECEBIMENTOS COM MARCACOES DIFERENCIADAS PARA O ESTADO DE PROCESSADO
			UPDATE #TEMP_RR2 SET 
				CODPROCESSA = '2',    /* 08/03/2023 ESTAVA = 1 */ 
				CODREJEICAO = '36'    /* 24/02/2023 */
			WHERE CODPROCESSA IN ('4', '5')

			SELECT @SQLERRO = @@ERROR		 
			IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS

			-- RECEBES PROCESSADAS
			UPDATE RECEBE_ADDA114_RR2 SET 
				CODPROCESSA = #TEMP_RR2.CODPROCESSA, 
				CODREJEICAO = #TEMP_RR2.CODREJEICAO, 
				DATAMANUTENCAO = @TIMESTAMP
			FROM RECEBE_ADDA114_RR2 
			INNER JOIN #TEMP_RR2  
				ON (RECEBE_ADDA114_RR2.SEQ_RECEBE = #TEMP_RR2.SEQ_RECEBE)

			SELECT @SQLERRO = @@ERROR		 
			IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS

		COMMIT TRANSACTION
	
	END

	RETURN
	TRATAERRO_TRANS:
		ROLLBACK TRANSACTION
		GOTO TRATAERRO
	TRATAERRO:
		SELECT @P_SQLERRO = @SQLERRO
		RETURN
END
GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO], 
    [NOMESCRIPT], 
    [CODUSUARIO], 
    [DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_PROCESSA_DDA0114_ADDA114_RR2', 
	SYSTEM_USER, 
	GETDATE() 
GO