USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_PROCESSA_DDA0501R1_ADDA501RET')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_PROCESSA_DDA0501R1_ADDA501RET AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE [dbo].[SP_PROCESSA_DDA0501R1_ADDA501RET]
AS
BEGIN
  
 DECLARE @DATAULTPROCESSAMENTO DATETIME,   
  @DATAPROCESSAMENTO DATETIME,  
  @SQLERRO INTEGER  
    
 SELECT @DATAULTPROCESSAMENTO=DATAULTPROCESSAMENTO, @DATAPROCESSAMENTO = DATAPROCESSAMENTO    
 FROM PARAMETROS   
 WHERE CODSISTEMA = 'DDA-AUTK'  
  
 ----------------------------------------------------------------  
 -- TRATAMENTO DE PEDIDOS RECUSADOS  
 IF((SELECT COUNT(CODPROCESSA)   
   FROM RECEBE_DDA0501_ADDA501_RECUSADOS   
   WHERE CODPROCESSA = '0'   
   AND DATAMOVTO >= @DATAULTPROCESSAMENTO   
   AND DATAMOVTO <= @DATAPROCESSAMENTO   
   AND INDIMPORTACAOVALIDA = 'S'  
  ) > 0  
 )  
 BEGIN  
  
  BEGIN TRANSACTION  
  
  UPDATE RECEBE_DDA0501_ADDA501_RECUSADOS SET   
   CODPROCESSA = '4'   
  WHERE CODPROCESSA = '0'   
  AND DATAMOVTO >= @DATAULTPROCESSAMENTO   
  AND DATAMOVTO <= @DATAPROCESSAMENTO   
  AND INDIMPORTACAOVALIDA = 'S'  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  UPDATE MANUT_BENEFICIARIO SET   
   SITUACAOPEDIDO = '5',   
   CODRETORNO = '1'   
  FROM MANUT_BENEFICIARIO B,   
   RECEBE_DDA0501_ADDA501_RECUSADOS R  
  WHERE B.NUMPEDIDO = R.NUMPEDIDO   
  AND R.CODPROCESSA = '4'   
  AND R.DATAMOVTO >= @DATAULTPROCESSAMENTO   
  AND R.DATAMOVTO <= @DATAPROCESSAMENTO  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  UPDATE RECEBE_DDA0501_ADDA501_RECUSADOS SET   
   CODPROCESSA = '1'   
  FROM RECEBE_DDA0501_ADDA501_RECUSADOS R  
  INNER JOIN MANUT_BENEFICIARIO M   
   ON (M.NUMPEDIDO = R.NUMPEDIDO)  
  WHERE R.CODPROCESSA = '4'   
  AND R.DATAMOVTO >= @DATAULTPROCESSAMENTO   
  AND R.DATAMOVTO <= @DATAPROCESSAMENTO  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  UPDATE RECEBE_DDA0501_ADDA501_RECUSADOS SET   
   CODPROCESSA = '2'  
  WHERE CODPROCESSA = '4'   
  AND DATAMOVTO >= @DATAULTPROCESSAMENTO   
  AND DATAMOVTO <= @DATAPROCESSAMENTO   
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  COMMIT TRANSACTION  
  
 END  
  
 ----------------------------------------------------------------  
 -- TRATAMENTO DE PEDIDOS ACEITOS  
 IF((SELECT COUNT(CODPROCESSA)   
   FROM RECEBE_DDA0501_ADDA501_ACEITOS   
   WHERE CODPROCESSA = '0'   
   AND DATAMOVTO >= @DATAULTPROCESSAMENTO   
   AND DATAMOVTO <= @DATAPROCESSAMENTO   
   AND INDIMPORTACAOVALIDA = 'S'  
  ) > 0  
 )  
 BEGIN  
  
  BEGIN TRANSACTION  
  
  UPDATE RECEBE_DDA0501_ADDA501_ACEITOS SET   
   CODPROCESSA = '4'   
  WHERE CODPROCESSA = '0'   
  AND DATAMOVTO >= @DATAULTPROCESSAMENTO   
  AND DATAMOVTO <= @DATAPROCESSAMENTO   
  AND INDIMPORTACAOVALIDA = 'S'  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  SELECT R.*, M.CNPJ_CPF_BENEFICIARIO, M.CODSISLEGADO, M.DATALEGADO, M.DATAPEDIDO, M.NUMCTRLLEGADO  
   INTO #TEMP_ACEITOS   
  FROM RECEBE_DDA0501_ADDA501_ACEITOS R,   
   MANUT_BENEFICIARIO M  
  WHERE R.CODPROCESSA = '4'   
  AND R.NUMPEDIDO = M.NUMPEDIDO  
  AND DATAMOVTO >= @DATAULTPROCESSAMENTO   
  AND DATAMOVTO <= @DATAPROCESSAMENTO   
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  SELECT MAX(DATAHORADDA) DATAHORADDA, CNPJ_CPF_BENEFICIARIO   
   INTO #TEMP_MAX_DATA_BENEF   
  FROM #TEMP_ACEITOS  
  GROUP BY CNPJ_CPF_BENEFICIARIO  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  SELECT MAX(T.SEQ_RECEBE) SEQ_RECEBE   
   INTO #TEMP_MAX_SEQ_BENEF   
  FROM #TEMP_MAX_DATA_BENEF M  
  INNER JOIN #TEMP_ACEITOS T   
   ON (T.CNPJ_CPF_BENEFICIARIO = M.CNPJ_CPF_BENEFICIARIO   
    AND T.DATAHORADDA = M.DATAHORADDA)  
  GROUP BY M.CNPJ_CPF_BENEFICIARIO  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
    
  -- VALIDACAO DE RECEBES DESATUALIZADAS (CODREJEICAO = '19' PARA PEDIDOS MAIS ANTIGOS QUANDO EXISTE MAIS DE UMA MANUTENCAO PARA SER PROCESSADA PARA O MESMO CPF/CNPJ)  
  UPDATE #TEMP_ACEITOS SET   
   CODREJEICAO = '19'   
  FROM #TEMP_ACEITOS  
  WHERE SEQ_RECEBE NOT IN (SELECT SEQ_RECEBE   
         FROM #TEMP_MAX_SEQ_BENEF  
        )  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  -- VALIDAÇÃO DE BENEFICIARIO JA INCLUIDO  
  UPDATE #TEMP_ACEITOS SET   
   CODREJEICAO = '18'   
  FROM #TEMP_ACEITOS T, BENEFICIARIO B  
  WHERE T.ISPBADM = B.ISPBADM   
  AND T.CNPJ_CPF_BENEFICIARIO = B.CNPJ_CPF_BENEFICIARIO  
  AND T.CODREJEICAO IS NULL  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  -- INSERT DOS NOVOS BENEFICIARIOS  
  INSERT INTO BENEFICIARIO(  
   ISPBADM, CNPJ_CPF_BENEFICIARIO, TIPOPESSOABENEFICIARIO, NUMIDENTCBENEFICIARIO, NOMEBENEFICIARIO,  
   NOMEFANTASIABENEFICIARIO, SITUACAO_IF, DTHRSITBENEFICIARIO_IF, DATAINIBENEFICIARIO, SITUACAORELACIONAMENTO,  
   DTHRINIBENEFICIARIO, DTHRBENEFICIARIO, NUMREFCADBENEFICIARIO, NUMSEQCADBENEFICIARIO  
  )  
  SELECT   
   T.ISPBADM, T.CNPJ_CPF_BENEFICIARIO, M.TIPOPESSOABENEFICIARIO, T.NUMIDENTCBENEFICIARIO, M.NOMEBENEFICIARIO, M.NOMEFANTASIABENEFICIARIO,  
   M.SITUACAOBENEFICIARIO, M.DTHRSITBENEFICIARIO, M.DATAINIBENEFICIARIO, M.SITUACAORELACIONAMENTO,  
   M.DTHRINIBENEFICIARIO, T.DATAHORADDA, T.NUMREFCADBENEFICIARIO, T.NUMSEQCADBENEFICIARIO  
  FROM MANUT_BENEFICIARIO M, #TEMP_ACEITOS T  
  WHERE T.CODREJEICAO IS NULL   
  AND T.NUMPEDIDO = M.NUMPEDIDO  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  INSERT INTO CONVENIOS(  
   ISPBADM, CNPJ_CPF_BENEFICIARIO, ISPBINCORPORADO, TIPOPRODCONVENIO, TIPOAGENCIA, CODAGENCIA, TIPOCARTEIRACOBRANCA,  
   TIPOCONTA, NUMCONTA, SITUACAOCONVENIO, DATAINICONVENIO, CODCLIENTECONV  
  )  
  SELECT   
   T.ISPBADM, T.CNPJ_CPF_BENEFICIARIO, R.ISPBINCORPORADO, R.TIPOPRODCONVENIO, R.TIPOAGENCIA, R.CODAGENCIA, R.TIPOCARTEIRACOBRANCA,  
   R.TIPOCONTA, R.NUMCONTA, R.SITUACAOCONVENIO, R.DATAINICONVENIO, R.CODCLIENTECONV  
  FROM MANUT_CONVENIOS R, #TEMP_ACEITOS T  
  WHERE T.CODREJEICAO IS NULL   
  AND R.CODSISLEGADO = T.CODSISLEGADO   
  AND R.DATALEGADO = T.DATALEGADO  
  AND R.DATAPEDIDO = T.DATAPEDIDO   
  AND R.NUMCTRLLEGADO = T.NUMCTRLLEGADO  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  INSERT INTO REPRESENTANTES(ISPBADM, CNPJ_CPF_BENEFICIARIO, CNPJ_CPF_REPRESENTANTE, TIPOPESSOAREPRESENTANTE)  
  SELECT T.ISPBADM, T.CNPJ_CPF_BENEFICIARIO, R.CNPJ_CPF_REPRESENTANTE, R.TIPOPESSOAREPRESENTANTE  
  FROM MANUT_REPRESENTANTES R, #TEMP_ACEITOS T  
  WHERE T.CODREJEICAO IS NULL   
  AND T.CODSISLEGADO = R.CODSISLEGADO   
  AND T.DATALEGADO = R.DATALEGADO  
  AND T.DATAPEDIDO = R.DATAPEDIDO   
  AND T.NUMCTRLLEGADO = R.NUMCTRLLEGADO  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  -- UPDATE DA SITUACAO CIP DO BENEFICIARIO SE ELE JA ERA TERCEIRO  
  UPDATE BENEFICIARIO SET   
  SITUACAO_CIP = BT.SITUACAO   
  FROM BENEFICIARIO B  
  INNER JOIN #TEMP_ACEITOS T   
   ON (B.CNPJ_CPF_BENEFICIARIO = T.CNPJ_CPF_BENEFICIARIO)  
  INNER JOIN BENEFICIARIO_TERC BT   
   ON (B.CNPJ_CPF_BENEFICIARIO = BT.CNPJ_CPF_BENEFICIARIO)  
  WHERE T.CODREJEICAO IS NULL  
    
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
    
  -- UPDATE DA SITUACAO CIP SE ELA VEIO COMO SEM CADASTRO (SITUACAO "S"):   
  -- ADQUIRE A SITUACAO DA PROPRIA IF, A PRIMEIRA CADASTRANDO O BENEFICIARIO  
  UPDATE BENEFICIARIO SET   
   SITUACAO_CIP = SITUACAO_IF   
  FROM BENEFICIARIO B  
  INNER JOIN #TEMP_ACEITOS T   
   ON (ISNULL(B.SITUACAO_CIP, '') = 'S'   
  AND B.CNPJ_CPF_BENEFICIARIO = T.CNPJ_CPF_BENEFICIARIO)  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  
  -- 27/02/2023 - INICIO DELETE DO BENEFICIARIO EM TERCEIROS, SE HOUVER, MAS ANTES, DELETANDO SEUS REPRESENTANTES...
  
  DELETE RT 
  FROM REPRESENTANTES_TERC RT
  INNER JOIN #TEMP_ACEITOS T 
  	ON (RT.CNPJ_CPF_BENEFICIARIO = T.CNPJ_CPF_BENEFICIARIO)
  WHERE T.CODREJEICAO IS NULL
  
  SELECT @SQLERRO = @@ERROR	
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS
  
  -- 27/02/2023 - FIM    DELETE DO BENEFICIARIO EM TERCEIROS, SE HOUVER, MAS ANTES, DELETANDO SEUS REPRESENTANTES...

  
  -- DELETE DO BENEFICIARIO EM TERCEIROS, SE HOUVER  
  DELETE B   
  FROM BENEFICIARIO_TERC B  
  INNER JOIN #TEMP_ACEITOS T   
   ON (B.CNPJ_CPF_BENEFICIARIO = T.CNPJ_CPF_BENEFICIARIO)  
  WHERE T.CODREJEICAO IS NULL  
    
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  -- ATUALIZACAO DE RECEBES E MANUTS  
  UPDATE RECEBE_DDA0501_ADDA501_ACEITOS SET   
   CODPROCESSA = '1'   
  FROM RECEBE_DDA0501_ADDA501_ACEITOS R,   
   #TEMP_ACEITOS T  
  WHERE R.CODPROCESSA = '4'   
  AND R.SEQ_RECEBE = T.SEQ_RECEBE   
  AND T.CODREJEICAO IS NULL  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  UPDATE RECEBE_DDA0501_ADDA501_ACEITOS SET   
   CODPROCESSA = '2',   
   CODREJEICAO = T.CODREJEICAO   
  FROM RECEBE_DDA0501_ADDA501_ACEITOS R,   
   #TEMP_ACEITOS T  
  WHERE R.CODPROCESSA = '4'   
  AND R.SEQ_RECEBE = T.SEQ_RECEBE   
  AND T.CODREJEICAO IS NOT NULL   
  AND R.DATAMOVTO >= @DATAULTPROCESSAMENTO   
  AND R.DATAMOVTO <= @DATAPROCESSAMENTO  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  -- SE UMA RECEBE AINDA ESTA COM CODPROCESSA = '4', ELA NAO POSSUI UM PEDIDO CORRESPONDENTE  
  UPDATE RECEBE_DDA0501_ADDA501_ACEITOS SET   
   CODPROCESSA = '2'   
  WHERE CODPROCESSA = '4'   
  AND DATAMOVTO >= @DATAULTPROCESSAMENTO   
  AND DATAMOVTO <= @DATAPROCESSAMENTO  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  UPDATE MANUT_BENEFICIARIO SET   
   SITUACAOPEDIDO = '5',   
   CODRETORNO = CASE  
       WHEN T.CODREJEICAO IS NULL   
        THEN '0'  
       ELSE '1'  
      END,   
   NUMREFCADBENEFICIARIO_RET = T.NUMREFCADBENEFICIARIO,   
   NUMSEQCADBENEFICIARIO = T.NUMSEQCADBENEFICIARIO  
  FROM MANUT_BENEFICIARIO M, #TEMP_ACEITOS T  
  WHERE M.NUMPEDIDO = T.NUMPEDIDO  
  
  SELECT @SQLERRO = @@ERROR   
  IF @SQLERRO <> 0 GOTO TRATAERRO_TRANS  
  
  COMMIT TRANSACTION  
  
 END  
  
 RETURN  
   
 TRATAERRO_TRANS:  
  ROLLBACK TRANSACTION  
  DECLARE @RETORNO VARCHAR(10)  
  SELECT @RETORNO = CONVERT(VARCHAR(10),@SQLERRO)  
  RAISERROR(@RETORNO,15,1)  
 RETURN  
  
END  
GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO], 
    [NOMESCRIPT], 
    [CODUSUARIO], 
    [DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_PROCESSA_DDA0501R1_ADDA501RET', 
	SYSTEM_USER, 
	GETDATE() 
GO