USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_RESERVAR_BAIXA_EFETIVA_TITULO_GERACAO_ARQUIVO')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_RESERVAR_BAIXA_EFETIVA_TITULO_GERACAO_ARQUIVO AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE SP_RESERVAR_BAIXA_EFETIVA_TITULO_GERACAO_ARQUIVO(    
	@P_NOMEARQREM  VARCHAR(255),    
	@P_QTD INT    
) AS     
BEGIN    
	/*  
		03/11/2022 - RFAQUINI - ITM - ALTERAÇÃO PARA QUE SEJA ENVIADA NUMIDENTCBAIXAOPERAC DE BAIXAS_OPERACIONAIS   
										QUANDO O CLIENTE FOR CODIF '077'   
										EM CASOS DE CODEVENTO '0120'  
										ALTERAÇÃO TEMPORÁRIA ENQUANTO PROJETO-MODERNIZAÇÃO NÃO ENTRA EM PRODUÇÃO, QUANDO A DDA0118 SERÁ ELIMINADA  
	*/  
	DECLARE   
		@DATAHORAREM DATETIME,   
		@DATAULTPROCESSAMENTO DATETIME    

	SELECT   
		@DATAHORAREM = GETDATE()    

	SELECT   
		@DATAULTPROCESSAMENTO = DATAULTPROCESSAMENTO   
	FROM PARAMETROS    

	--SELECIONANDO TODAS AS MANUTENCOES PREPARADAS PARA ENVIO NO TIPO DE MANUTENCAO VISADO    
	DECLARE   
		@DATAPROCESSAMENTO DATETIME,  
		@CODIF VARCHAR(4)  

	SELECT   
		@DATAPROCESSAMENTO = DATAPROCESSAMENTO,  
		@CODIF = CODIF  
	FROM PARAMETROS  

	SELECT TOP(@P_QTD) MANUT_TITULOS.*, NULL AS ERRO   
		INTO #TEMP   
	FROM MANUT_TITULOS     
	WHERE MANUT_TITULOS.TIPOMANUTENCAOTIT = 'B'   
	AND MANUT_TITULOS.TIPOENVIO = 'X'   
	AND MANUT_TITULOS.FORMAENVIO = 'R'     
	AND MANUT_TITULOS.CODEVENTO NOT IN ('8108', '8114', '8115')   
	AND MANUT_TITULOS.SITUACAOPEDIDO = '4'   

	--03/11/2022 - RFAQUINI - ITM - ALTERAÇÃO PARA QUE SEJA ENVIADA NUMIDENTCBAIXAOPERAC DE BAIXAS_OPERACIONAIS   
	--ALTERAÇÃO TEMPORÁRIA ENQUANTO PROJETO-MODERNIZAÇÃO NÃO ENTRA EM PRODUÇÃO, QUANDO A DDA0118 SERÁ ELIMINADA  
	IF (@CODIF = '637')  
	BEGIN  
		UPDATE #TEMP SET  
			NUMIDENTCBAIXAOPERAC = (  
										SELECT MAX(BAIXAS_OPERACIONAIS.NUMIDENTCBAIXAOPERAC)   
										FROM BAIXAS_OPERACIONAIS WITH (NOLOCK)  
										WHERE BAIXAS_OPERACIONAIS.NUMIDENTCDDA = #TEMP.NUMIDENTCDDA  
									)  
		WHERE CODEVENTO = '0120'  
	END  


	/* INCLUINDO A CHAVE DE TODAS AS MANUTENCOES QUE JA NAO ESTIVEREM NA TABELA QUE AUXILIA O WORKFLOW DE ARQUIVOS,     
	JUNTO A MARCACAO DO ARQUIVO QUE ESTA SENDO PROCESSADO E O TIMESTAMP DESSA EXECUCAO */    

	DELETE #TEMP   
	FROM
		#TEMP,   
		TEMP_BAIXA_EFETIVA_TITULO_GERACAO_ARQUIVO     
	WHERE #TEMP.DATAPEDIDO = TEMP_BAIXA_EFETIVA_TITULO_GERACAO_ARQUIVO.DATAPEDIDO   
	AND #TEMP.DATALEGADO = TEMP_BAIXA_EFETIVA_TITULO_GERACAO_ARQUIVO.DATALEGADO    
	AND #TEMP.NUMCTRLLEGADO = TEMP_BAIXA_EFETIVA_TITULO_GERACAO_ARQUIVO.NUMCTRLLEGADO   
	AND #TEMP.CODSISLEGADO = TEMP_BAIXA_EFETIVA_TITULO_GERACAO_ARQUIVO.CODSISLEGADO    

	INSERT INTO TEMP_BAIXA_EFETIVA_TITULO_GERACAO_ARQUIVO (   
		DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO, NOMEARQREM, DATAHORAREM  
	)    
	SELECT   
		DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO, @P_NOMEARQREM, @DATAHORAREM   
	FROM #TEMP    

	/* PROVAVELMENTE ESSA MESMA PROCEDURE SENDO EXECUTADA QUASE SIMULTANEAMENTE, GERANDO PK DUPLICADA...     
	O WORKFLOW DEVE SER SUSPENSO COM O RETORNO DE UM ERRO */    
	IF @@ERROR != 0    
	BEGIN    
		SELECT 'S' ERRO    
	RETURN    
	END    

	-- ESSA TEMP EH UM ESPELHO DESSAS MANUTENCOES QUE ACABARAM DE SER RESERVADAS. RETORNAR PARA QUE SEJAM UTILIZADAS NA GERACAO DO ARQUIVO    
	SELECT *   
	FROM #TEMP    
END    
GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO], 
	[NOMESCRIPT], 
	[CODUSUARIO], 
	[DATAATU]
)
SELECT 
	'V15_01_1_01B', 
	'SP_RESERVAR_BAIXA_EFETIVA_TITULO_GERACAO_ARQUIVO', 
	SYSTEM_USER, 
	GETDATE() 
GO