USE AB_DDA
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'SP_RESERVAR_MANUTENCAO_TITULO_GERACAO_ARQUIVO')
BEGIN
	EXEC ('CREATE PROCEDURE dbo.SP_RESERVAR_MANUTENCAO_TITULO_GERACAO_ARQUIVO AS BEGIN RETURN END')
END
GO

ALTER PROCEDURE dbo.SP_RESERVAR_MANUTENCAO_TITULO_GERACAO_ARQUIVO(
	@P_NOMEARQREM VARCHAR(255), 
	@P_TIPOMANUTENCAO CHAR(1), 
	@P_QTD INT
) AS 
BEGIN

	/*
		19/11/2021 - RFAQUINI, UAFERREIRA - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
											REMOÇÃO DE ALIAS
											
		09/08/2022 - RFAQUINI- INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)

		23/01/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
								DOS CAMPOS 
									TIPOPESAGREGADOR, 
									CNPJ_CPF_AGREGADOR,
									NOMEAGREGADOR,
									ISPBINICIADORPAGTO,
									AGENCIARECEBEDORA
		
		02/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
								DO CAMPO 
									CODMOTIVO

											
	*/
	DECLARE 
		@DATAHORAREM DATETIME, 
		@DATAULTPROCESSAMENTO DATETIME, 
		@FILTRO_QTD INT
	
	SELECT @DATAHORAREM = GETDATE()
	
	SELECT @FILTRO_QTD = 3 * @P_QTD
	
	SELECT @DATAULTPROCESSAMENTO = DATAULTPROCESSAMENTO 
	FROM PARAMETROS

	-- SELECIONANDO TODAS AS MANUTENCOES PREPARADAS PARA ENVIO NO TIPO DE MANUTENCAO VISADO ("I", OU "A" DESDE QUE NAO ACOMPANHADO DE UMA MANUT_COMPLEMENTOS E NAO SEJA CODEVENTO 8300 - MANUT. ANEXO DE FATURA)

	SELECT 
		DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO, 
		NUMPEDIDO, NUMIDENTCDDA, CODEVENTO, CODIFSACADA, 
		TIPOMANUTENCAOTIT, CODIFCEDENTE, TIPOPESCEDENTE, CNPJ_CPF_CEDENTE, 
		NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI, NOMEFANTASIASACADO, NUMIDENTCBAIXAOPERAC, 
		
		NUMREFBAIXAOPERAC,NUMSEQBAIXAOPERAC, NUMIDENTCBAIXAEFET, NUMREFBAIXAEFET, 
		NUMSEQBAIXAEFET, ISPBCEDENTE, ISPBSACADA, CANALPAGTO, 
		MEIOPAGTO, NUMREFBAIXAOPERAC_RET, NUMREFBAIXAEFET_RET, NOMECEDENTE, 
		TIPOPESCEDENTEORI, CNPJ_CPF_CEDENTEORI, NOMECEDENTEORI, ENDCEDENTEORI, 
		
		CIDCEDENTEORI, UFCEDENTEORI, CEPCEDENTEORI, TIPOPESSACADO, 
		CNPJ_CPF_SACADO, NOMESACADO, ENDSACADO, CIDSACADO, 
		UFSACADO, CEPSACADO, TIPOPESSACADOR, CNPJ_CPF_SACADOR, 
		NOMESACADOR, CODCARTEIRA, CODMOEDACNAB, IDENTNOSSONUMERO, 
		
		NUMCODBARRAS, DATAVENCIMENTO, VLRTITULO, SEUNUMERO, 
		CODESPECIEDOC, DATAEMISSAO, QTDEDIASPROTESTO, DATALIMPAGTO, 
		TIPOPAGTO, INDTITULONEGOCIADO, VLRABATIMENTO, CODMORA, 
		DATAMORA, VLRPERCMORA, CODMULTA, DATAMULTA, 
		
		VLRPERCMULTA, CODDESCONTO01, DATADESCONTO01, VLRPERCDESCONTO01, 
		CODDESCONTO02, DATADESCONTO02, VLRPERCDESCONTO02, CODDESCONTO03, 
		DATADESCONTO03, VLRPERCDESCONTO03, VLRMINTITULO, VLRMAXTITULO, 
		TIPOBAIXA, DATAPAGTOBAIXA, VLRPAGTOBAIXA, ACEITE, 
		
		NUMCTRLDDA, DATAHORADDA, TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO, 
		NUMIDENTCDDA2, DATAVENCTOINI, DATAVENCTOFIM, DATACADASTINI, 
		DATACADASTFIM, TIPOCONSULTA, CNPJBASE, BUSCABASESACADO, 
		CODSITUACAO, TIPORETORNO, SITUACAOPEDIDO, CODRETORNO, 
		
		NOMEARQRET, NOMEARQREM, TIPOCALCULO, INDALTERAVALOR, 
		DATACALCULO, VLRCALCULADODESC, VLRCALCULADOMORA, VLRCALCULADOMULTA, 
		VLRCOBRAR, TIPOENVIO, FORMAENVIO, LINHADIGITAVEL, 
		NUMPARCELA, QTDPARCELA, TIPOAUTRECDIVERGENTE, INDBLOQUEIO, 
		
		INDPARCIAL, QTDPAGTO, INDVALORPERC_MIN, INDVALORPERC_MAX, 
		NUMREFCADTIT, NUMSEQCADTIT, NUMREFACEITE, NUMSEQACEITE, 
		NUMREFTERC, NUMSEQTERC, NUMIDENTCTERC, NUMREFACEITE_RET, 
		NUMREFTERC_RET, TIPOPESAUTORIZADOR, CNPJ_CPF_AUTORIZADOR, TIPOPESPORTADOR, 
		
		CNPJ_CPF_PORTADOR, 

		--19/11/2021 - RFAQUINI, UAFERREIRA - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
		NOME_PORTADOR, 
		
		--09/08/2022 - RFAQUINI- INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)
		DATAHORARECBTTITULO, 
		
		--23/01/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
		TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO,
		AGENCIARECEBEDORA, 
		
		--02/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
		CODMOTIVO,
		
		INDCONTINGENCIA, SPID, DATAHORAPROCESSO, NUMPEDIDOPEND, 
		DATAHORACANCELAMENTOBAIXAOPERAC,
		CONVERT (CHAR, NULL) AS ERRO

		INTO #TEMP_MANUT_TITULOS 
	FROM MANUT_TITULOS 
	WHERE 1 = 2

	SELECT * 
		INTO #TEMP_MANUT_TITULOS_INICIO 
	FROM #TEMP_MANUT_TITULOS 


	IF (@P_TIPOMANUTENCAO IS NOT NULL AND @P_TIPOMANUTENCAO = 'I') 
	BEGIN
		INSERT INTO #TEMP_MANUT_TITULOS_INICIO
		(
			DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO, 
			NUMPEDIDO, NUMIDENTCDDA, CODEVENTO, CODIFSACADA, 
			TIPOMANUTENCAOTIT, CODIFCEDENTE, TIPOPESCEDENTE, CNPJ_CPF_CEDENTE, 
			NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI, NOMEFANTASIASACADO, NUMIDENTCBAIXAOPERAC, 
			
			NUMREFBAIXAOPERAC, NUMSEQBAIXAOPERAC, NUMIDENTCBAIXAEFET, NUMREFBAIXAEFET, 
			NUMSEQBAIXAEFET, ISPBCEDENTE, ISPBSACADA, CANALPAGTO, 
			MEIOPAGTO, NUMREFBAIXAOPERAC_RET, NUMREFBAIXAEFET_RET, NOMECEDENTE, 
			TIPOPESCEDENTEORI, CNPJ_CPF_CEDENTEORI, NOMECEDENTEORI, ENDCEDENTEORI, 
			
			CIDCEDENTEORI, UFCEDENTEORI, CEPCEDENTEORI, TIPOPESSACADO, 
			CNPJ_CPF_SACADO, NOMESACADO, ENDSACADO, CIDSACADO, 
			UFSACADO, CEPSACADO, TIPOPESSACADOR, CNPJ_CPF_SACADOR, 
			NOMESACADOR, CODCARTEIRA, CODMOEDACNAB, IDENTNOSSONUMERO, 
			
			NUMCODBARRAS, DATAVENCIMENTO, VLRTITULO, SEUNUMERO, 
			CODESPECIEDOC, DATAEMISSAO, QTDEDIASPROTESTO, DATALIMPAGTO, 
			TIPOPAGTO, INDTITULONEGOCIADO, VLRABATIMENTO, CODMORA, 
			DATAMORA, VLRPERCMORA, CODMULTA, DATAMULTA, 
			
			VLRPERCMULTA, CODDESCONTO01, DATADESCONTO01, VLRPERCDESCONTO01, 
			CODDESCONTO02, DATADESCONTO02, VLRPERCDESCONTO02, CODDESCONTO03, 
			DATADESCONTO03, VLRPERCDESCONTO03, VLRMINTITULO, VLRMAXTITULO, 
			TIPOBAIXA, DATAPAGTOBAIXA, VLRPAGTOBAIXA, ACEITE, 
			
			NUMCTRLDDA, DATAHORADDA, TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO, 
			NUMIDENTCDDA2, DATAVENCTOINI, DATAVENCTOFIM, DATACADASTINI, 
			DATACADASTFIM, TIPOCONSULTA, CNPJBASE, BUSCABASESACADO, 
			CODSITUACAO, TIPORETORNO, SITUACAOPEDIDO, CODRETORNO, 
			
			NOMEARQRET, NOMEARQREM, TIPOCALCULO, INDALTERAVALOR, 
			DATACALCULO, VLRCALCULADODESC, VLRCALCULADOMORA, VLRCALCULADOMULTA, 
			VLRCOBRAR, TIPOENVIO, FORMAENVIO, LINHADIGITAVEL, 
			NUMPARCELA, QTDPARCELA, TIPOAUTRECDIVERGENTE, INDBLOQUEIO, 
			
			INDPARCIAL, QTDPAGTO, INDVALORPERC_MIN, INDVALORPERC_MAX, 
			NUMREFCADTIT, NUMSEQCADTIT, NUMREFACEITE, NUMSEQACEITE, 
			NUMREFTERC, NUMSEQTERC, NUMIDENTCTERC, NUMREFACEITE_RET, 
			NUMREFTERC_RET, TIPOPESAUTORIZADOR, CNPJ_CPF_AUTORIZADOR, TIPOPESPORTADOR, 
			
			CNPJ_CPF_PORTADOR, 

			--19/11/2021 - RFAQUINI, UAFERREIRA - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
			NOME_PORTADOR, 
			
			--09/08/2022 - RFAQUINI- INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)	
			DATAHORARECBTTITULO, 
			
			--23/01/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
			TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO,
			AGENCIARECEBEDORA,
			--02/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
			CODMOTIVO,
			
			INDCONTINGENCIA, SPID, DATAHORAPROCESSO, NUMPEDIDOPEND, 
			DATAHORACANCELAMENTOBAIXAOPERAC,
			ERRO
		) 
		SELECT TOP(@FILTRO_QTD) 
			DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO, 
			NUMPEDIDO, NUMIDENTCDDA, CODEVENTO, CODIFSACADA, 
			TIPOMANUTENCAOTIT, CODIFCEDENTE, TIPOPESCEDENTE, CNPJ_CPF_CEDENTE, 
			NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI, NOMEFANTASIASACADO, NUMIDENTCBAIXAOPERAC, 
			
			NUMREFBAIXAOPERAC, NUMSEQBAIXAOPERAC, NUMIDENTCBAIXAEFET, NUMREFBAIXAEFET, 
			NUMSEQBAIXAEFET, ISPBCEDENTE, ISPBSACADA, CANALPAGTO, 
			MEIOPAGTO, NUMREFBAIXAOPERAC_RET, NUMREFBAIXAEFET_RET, NOMECEDENTE, 
			TIPOPESCEDENTEORI, CNPJ_CPF_CEDENTEORI, NOMECEDENTEORI, ENDCEDENTEORI, 
			
			CIDCEDENTEORI, UFCEDENTEORI, CEPCEDENTEORI, TIPOPESSACADO, 
			CNPJ_CPF_SACADO, NOMESACADO, ENDSACADO, CIDSACADO, 
			UFSACADO, CEPSACADO, TIPOPESSACADOR, CNPJ_CPF_SACADOR, 
			NOMESACADOR, CODCARTEIRA, CODMOEDACNAB, IDENTNOSSONUMERO, 
			
			NUMCODBARRAS, DATAVENCIMENTO, VLRTITULO, SEUNUMERO, 
			CODESPECIEDOC, DATAEMISSAO, QTDEDIASPROTESTO, DATALIMPAGTO, 
			TIPOPAGTO, INDTITULONEGOCIADO, VLRABATIMENTO, CODMORA, 
			DATAMORA, VLRPERCMORA, CODMULTA, DATAMULTA, 
			
			VLRPERCMULTA, CODDESCONTO01, DATADESCONTO01, VLRPERCDESCONTO01, 
			CODDESCONTO02, DATADESCONTO02, VLRPERCDESCONTO02, CODDESCONTO03, 
			DATADESCONTO03, VLRPERCDESCONTO03, VLRMINTITULO, VLRMAXTITULO, 
			TIPOBAIXA, DATAPAGTOBAIXA, VLRPAGTOBAIXA, ACEITE, 
			
			NUMCTRLDDA, DATAHORADDA, TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO, 
			NUMIDENTCDDA2, DATAVENCTOINI, DATAVENCTOFIM, DATACADASTINI, 
			DATACADASTFIM, TIPOCONSULTA, CNPJBASE, BUSCABASESACADO, 
			CODSITUACAO, TIPORETORNO, SITUACAOPEDIDO, CODRETORNO, 
			
			NOMEARQRET, NOMEARQREM, TIPOCALCULO, INDALTERAVALOR, 
			DATACALCULO, VLRCALCULADODESC, VLRCALCULADOMORA, VLRCALCULADOMULTA, 
			VLRCOBRAR, TIPOENVIO, FORMAENVIO, LINHADIGITAVEL, 
			NUMPARCELA, QTDPARCELA, TIPOAUTRECDIVERGENTE, INDBLOQUEIO, 
			
			INDPARCIAL, QTDPAGTO, INDVALORPERC_MIN, INDVALORPERC_MAX, 
			NUMREFCADTIT, NUMSEQCADTIT, NUMREFACEITE, NUMSEQACEITE, 
			NUMREFTERC, NUMSEQTERC, NUMIDENTCTERC, NUMREFACEITE_RET, 
			NUMREFTERC_RET, TIPOPESAUTORIZADOR, CNPJ_CPF_AUTORIZADOR, TIPOPESPORTADOR, 
			
			CNPJ_CPF_PORTADOR, 
			
			--19/11/2021 - RFAQUINI, UAFERREIRA - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
			NOME_PORTADOR, 
			
			--09/08/2022 - RFAQUINI- INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)	
			DATAHORARECBTTITULO, 
			
			--23/01/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
			TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO,
			AGENCIARECEBEDORA,
			
			--02/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
			CODMOTIVO,
			
			INDCONTINGENCIA, SPID, DATAHORAPROCESSO, NUMPEDIDOPEND, 
			DATAHORACANCELAMENTOBAIXAOPERAC,
			CONVERT (CHAR, NULL) AS ERRO
		FROM MANUT_TITULOS 
		WHERE DATAPEDIDO >= @DATAULTPROCESSAMENTO 
		AND SITUACAOPEDIDO = '4' 
		AND TIPOMANUTENCAOTIT = 'I'
		AND TIPOENVIO = 'X'
		ORDER BY DATAVENCIMENTO

	END 
	ELSE
	IF (@P_TIPOMANUTENCAO IS NOT NULL AND @P_TIPOMANUTENCAO = 'A') 
	BEGIN
		INSERT INTO #TEMP_MANUT_TITULOS_INICIO 
		(
			DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO, 
			NUMPEDIDO, NUMIDENTCDDA, CODEVENTO, CODIFSACADA, 
			TIPOMANUTENCAOTIT, CODIFCEDENTE, TIPOPESCEDENTE, CNPJ_CPF_CEDENTE, 
			NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI, NOMEFANTASIASACADO, NUMIDENTCBAIXAOPERAC, 
			
			NUMREFBAIXAOPERAC, NUMSEQBAIXAOPERAC, NUMIDENTCBAIXAEFET, NUMREFBAIXAEFET, 
			NUMSEQBAIXAEFET, ISPBCEDENTE, ISPBSACADA, CANALPAGTO, 
			MEIOPAGTO, NUMREFBAIXAOPERAC_RET, NUMREFBAIXAEFET_RET, NOMECEDENTE, 
			TIPOPESCEDENTEORI, CNPJ_CPF_CEDENTEORI, NOMECEDENTEORI, ENDCEDENTEORI, 
			
			CIDCEDENTEORI, UFCEDENTEORI, CEPCEDENTEORI, TIPOPESSACADO, 
			CNPJ_CPF_SACADO, NOMESACADO, ENDSACADO, CIDSACADO, 
			UFSACADO, CEPSACADO, TIPOPESSACADOR, CNPJ_CPF_SACADOR, 
			NOMESACADOR, CODCARTEIRA, CODMOEDACNAB, IDENTNOSSONUMERO, 
			
			NUMCODBARRAS, DATAVENCIMENTO, VLRTITULO, SEUNUMERO, 
			CODESPECIEDOC, DATAEMISSAO, QTDEDIASPROTESTO, DATALIMPAGTO, 
			TIPOPAGTO, INDTITULONEGOCIADO, VLRABATIMENTO, CODMORA, 
			DATAMORA, VLRPERCMORA, CODMULTA, DATAMULTA, 
			
			VLRPERCMULTA, CODDESCONTO01, DATADESCONTO01, VLRPERCDESCONTO01, 
			CODDESCONTO02, DATADESCONTO02, VLRPERCDESCONTO02, CODDESCONTO03, 
			DATADESCONTO03, VLRPERCDESCONTO03, VLRMINTITULO, VLRMAXTITULO, 
			TIPOBAIXA, DATAPAGTOBAIXA, VLRPAGTOBAIXA, ACEITE, 
			
			NUMCTRLDDA, DATAHORADDA, TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO, 
			NUMIDENTCDDA2, DATAVENCTOINI, DATAVENCTOFIM, DATACADASTINI, 
			DATACADASTFIM, TIPOCONSULTA, CNPJBASE, BUSCABASESACADO, 
			CODSITUACAO, TIPORETORNO, SITUACAOPEDIDO, CODRETORNO, 
			
			NOMEARQRET, NOMEARQREM, TIPOCALCULO, INDALTERAVALOR, 
			DATACALCULO, VLRCALCULADODESC, VLRCALCULADOMORA, VLRCALCULADOMULTA, 
			VLRCOBRAR, TIPOENVIO, FORMAENVIO, LINHADIGITAVEL, 
			NUMPARCELA, QTDPARCELA, TIPOAUTRECDIVERGENTE, INDBLOQUEIO, 
			
			INDPARCIAL, QTDPAGTO, INDVALORPERC_MIN, INDVALORPERC_MAX, 
			NUMREFCADTIT, NUMSEQCADTIT, NUMREFACEITE, NUMSEQACEITE, 
			NUMREFTERC, NUMSEQTERC, NUMIDENTCTERC, NUMREFACEITE_RET, 
			NUMREFTERC_RET, TIPOPESAUTORIZADOR, CNPJ_CPF_AUTORIZADOR, TIPOPESPORTADOR, 
			
			CNPJ_CPF_PORTADOR, 

			--19/11/2021 - RFAQUINI, UAFERREIRA - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
			NOME_PORTADOR, 
			
			--09/08/2022 - RFAQUINI- INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)	
			DATAHORARECBTTITULO, 
			
			--23/01/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
			TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO,
			AGENCIARECEBEDORA,
			
			--02/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
			CODMOTIVO,
			
			INDCONTINGENCIA, SPID, DATAHORAPROCESSO, NUMPEDIDOPEND, 
			DATAHORACANCELAMENTOBAIXAOPERAC,
			ERRO
		)
		SELECT TOP(@FILTRO_QTD) 
			DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO, 
			NUMPEDIDO, NUMIDENTCDDA, CODEVENTO, CODIFSACADA, 
			TIPOMANUTENCAOTIT, CODIFCEDENTE, TIPOPESCEDENTE, CNPJ_CPF_CEDENTE, 
			NOMEFANTASIACEDENTE, NOMEFANTASIACEDENTEORI, NOMEFANTASIASACADO, NUMIDENTCBAIXAOPERAC, 
			
			NUMREFBAIXAOPERAC, NUMSEQBAIXAOPERAC, NUMIDENTCBAIXAEFET, NUMREFBAIXAEFET, 
			NUMSEQBAIXAEFET, ISPBCEDENTE, ISPBSACADA, CANALPAGTO, 
			MEIOPAGTO, NUMREFBAIXAOPERAC_RET, NUMREFBAIXAEFET_RET, NOMECEDENTE, 
			TIPOPESCEDENTEORI, CNPJ_CPF_CEDENTEORI, NOMECEDENTEORI, ENDCEDENTEORI, 
			
			CIDCEDENTEORI, UFCEDENTEORI, CEPCEDENTEORI, TIPOPESSACADO, 
			CNPJ_CPF_SACADO, NOMESACADO, ENDSACADO, CIDSACADO, 
			UFSACADO, CEPSACADO, TIPOPESSACADOR, CNPJ_CPF_SACADOR, 
			NOMESACADOR, CODCARTEIRA, CODMOEDACNAB, IDENTNOSSONUMERO, 
			
			NUMCODBARRAS, DATAVENCIMENTO, VLRTITULO, SEUNUMERO, 
			CODESPECIEDOC, DATAEMISSAO, QTDEDIASPROTESTO, DATALIMPAGTO, 
			TIPOPAGTO, INDTITULONEGOCIADO, VLRABATIMENTO, CODMORA, 
			DATAMORA, VLRPERCMORA, CODMULTA, DATAMULTA, 
			
			VLRPERCMULTA, CODDESCONTO01, DATADESCONTO01, VLRPERCDESCONTO01, 
			CODDESCONTO02, DATADESCONTO02, VLRPERCDESCONTO02, CODDESCONTO03, 
			DATADESCONTO03, VLRPERCDESCONTO03, VLRMINTITULO, VLRMAXTITULO, 
			TIPOBAIXA, DATAPAGTOBAIXA, VLRPAGTOBAIXA, ACEITE, 
			
			NUMCTRLDDA, DATAHORADDA, TIPOPESTERCEIRO, CNPJ_CPF_TERCEIRO, 
			NUMIDENTCDDA2, DATAVENCTOINI, DATAVENCTOFIM, DATACADASTINI, 
			DATACADASTFIM, TIPOCONSULTA, CNPJBASE, BUSCABASESACADO, 
			CODSITUACAO, TIPORETORNO, SITUACAOPEDIDO, CODRETORNO, 
			
			NOMEARQRET, NOMEARQREM, TIPOCALCULO, INDALTERAVALOR, 
			DATACALCULO, VLRCALCULADODESC, VLRCALCULADOMORA, VLRCALCULADOMULTA, 
			VLRCOBRAR, TIPOENVIO, FORMAENVIO, LINHADIGITAVEL, 
			NUMPARCELA, QTDPARCELA, TIPOAUTRECDIVERGENTE, INDBLOQUEIO, 
			
			INDPARCIAL, QTDPAGTO, INDVALORPERC_MIN, INDVALORPERC_MAX, 
			NUMREFCADTIT, NUMSEQCADTIT, NUMREFACEITE, NUMSEQACEITE, 
			NUMREFTERC, NUMSEQTERC, NUMIDENTCTERC, NUMREFACEITE_RET, 
			NUMREFTERC_RET, TIPOPESAUTORIZADOR, CNPJ_CPF_AUTORIZADOR, TIPOPESPORTADOR, 
			
			CNPJ_CPF_PORTADOR, 
			
			--19/11/2021 - RFAQUINI, UAFERREIRA - INCLUSÃO E TRATAMENTO DO CAMPO NOME_PORTADOR (CATÁLOGO 5.03)
			NOME_PORTADOR, 
			
			--09/08/2022 - RFAQUINI- INCLUSÃO E TRATAMENTO DO CAMPO DATAHORARECBTTITULO (CATÁLOGO 5.04)	
			DATAHORARECBTTITULO, 
			
			--23/01/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
			TIPOPESAGREGADOR, CNPJ_CPF_AGREGADOR, NOMEAGREGADOR, ISPBINICIADORPAGTO,
			AGENCIARECEBEDORA,
			
			--02/02/2023 - RFAQUINI - INCLUSÃO E TRATAMENTO (CATÁLOGO 5.06 - Modernização da Cobrança)
			CODMOTIVO,
			
			INDCONTINGENCIA, SPID, DATAHORAPROCESSO, NUMPEDIDOPEND, 
			DATAHORACANCELAMENTOBAIXAOPERAC,
			CONVERT (CHAR, NULL) AS ERRO
		FROM MANUT_TITULOS 
		WHERE DATAPEDIDO >= @DATAULTPROCESSAMENTO 
		AND SITUACAOPEDIDO = '4' 
		AND TIPOMANUTENCAOTIT = 'A'
		AND CODEVENTO NOT IN ('8300', '8121', '8122', '8104')
		AND TIPOENVIO = 'X'

		DELETE #TEMP_MANUT_TITULOS_INICIO
		FROM #TEMP_MANUT_TITULOS_INICIO 
		INNER JOIN MANUT_COMPLEMENTOS 
			ON (#TEMP_MANUT_TITULOS_INICIO.DATAPEDIDO = MANUT_COMPLEMENTOS.DATAPEDIDO 
			AND #TEMP_MANUT_TITULOS_INICIO.DATALEGADO = MANUT_COMPLEMENTOS.DATALEGADO
			AND #TEMP_MANUT_TITULOS_INICIO.NUMCTRLLEGADO = MANUT_COMPLEMENTOS.NUMCTRLLEGADO 
			AND #TEMP_MANUT_TITULOS_INICIO.CODSISLEGADO = MANUT_COMPLEMENTOS.CODSISLEGADO)
	END 

	/* INCLUINDO A CHAVE DE TODAS AS MANUTENCOES QUE JA NAO ESTIVEREM NA TABELA QUE AUXILIA O WORKFLOW DE ARQUIVOS, 
	JUNTO A MARCACAO DO ARQUIVO QUE ESTA SENDO PROCESSADO E O TIMESTAMP DESSA EXECUCAO */

	DELETE #TEMP_MANUT_TITULOS_INICIO 
	FROM #TEMP_MANUT_TITULOS_INICIO  
	INNER JOIN TEMP_MANUTENCAO_TITULO_GERACAO_ARQUIVO 
		ON (#TEMP_MANUT_TITULOS_INICIO.DATAPEDIDO = TEMP_MANUTENCAO_TITULO_GERACAO_ARQUIVO.DATAPEDIDO 
		AND #TEMP_MANUT_TITULOS_INICIO.DATALEGADO = TEMP_MANUTENCAO_TITULO_GERACAO_ARQUIVO.DATALEGADO
		AND #TEMP_MANUT_TITULOS_INICIO.NUMCTRLLEGADO = TEMP_MANUTENCAO_TITULO_GERACAO_ARQUIVO.NUMCTRLLEGADO 
		AND #TEMP_MANUT_TITULOS_INICIO.CODSISLEGADO = TEMP_MANUTENCAO_TITULO_GERACAO_ARQUIVO.CODSISLEGADO)

	INSERT INTO #TEMP_MANUT_TITULOS 
	SELECT TOP(@P_QTD) * 
	FROM #TEMP_MANUT_TITULOS_INICIO 

	INSERT INTO TEMP_MANUTENCAO_TITULO_GERACAO_ARQUIVO (
		DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO, NOMEARQREM, DATAHORAREM
	)
	SELECT 
		DATAPEDIDO, DATALEGADO, CODSISLEGADO, NUMCTRLLEGADO, @P_NOMEARQREM, @DATAHORAREM 
	FROM #TEMP_MANUT_TITULOS

	/* PROVAVELMENTE ESSA MESMA PROCEDURE SENDO EXECUTADA QUASE SIMULTANEAMENTE, GERANDO PK DUPLICADA... 
	O WORKFLOW DEVE SER SUSPENSO COM O RETORNO DE UM ERRO */
	IF @@ERROR != 0
	BEGIN
		SELECT 'S' ERRO
	RETURN
	END

	-- ESSA TEMP EH UM ESPELHO DESSAS MANUTENCOES QUE ACABARAM DE SER RESERVADAS. RETORNAR PARA QUE SEJAM UTILIZADAS NA GERACAO DO ARQUIVO
	SELECT * 
	FROM #TEMP_MANUT_TITULOS

END
GO

INSERT INTO VERSAO_SISTEMA (
	[VERSAO],
	[NOMESCRIPT],
	[CODUSUARIO],
	[DATAATU])
SELECT 
	'V15_01_1_01B', 
	'SP_RESERVAR_MANUTENCAO_TITULO_GERACAO_ARQUIVO', 
	SYSTEM_USER, 
	GETDATE() 
GO