name: Run 

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: [self-hosted, tomcat]
    steps:

      - name: Checkout
        uses: actions/checkout@v3.0.0

      # - name: Backup file .war
      #   run: |
      #     chmod +x ./scripts/backup.sh
      #     ./scripts/backup.sh

      - name: Undeploy file .war
        run: |
          ./scripts/undeploy.sh

      # - name: Add file .war
      #   run: |
      #     chmod +x ./scripts/add.sh
      #     ./scripts/add.sh