name: Run 

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: [self-hosted, tomcat]
    steps:

      - name: Checkout
        uses: actions/checkout@v3.0.0

      
      - name: Add file .war
        run: |
          chmod +x ./scripts/add.sh
          ./scripts/add.sh