name: Run 

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: [self-hosted, tomcat]
    steps:

      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Backup file .war
        run: |
          chmod +x ./scripts/backup.sh
          ./scripts/backup.sh

      - name: Undeploy file .war
        run: |
          chmod +x ./scripts/undeploy.py
          ./scripts/undeploy.py

      - name: Change file context.xml
        run: |
          chmod +x ./scripts/unzip.sh
          ./scripts/unzip.sh

      - name: Change file context.xml
        run: |
          chmod +x ./scripts/add.sh
          ./scripts/add.sh